### ISSUE TITLE
PrestoS3FileSystem breaks read-after-write strict S3 consistency

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#103]
Method: `com.facebook.presto.hive.s3.PrestoS3FileSystem#create`
will check for file existence when `overwrite==false`. File existence check will break read-after-write strict S3 consistency per S3 doc:
```
Amazon S3 provides read-after-write consistency for PUTS of new objects in
your S3 bucket in all regions with one caveat. The caveat is that if you make a
HEAD or GET request to the key name (to find if the object exists) before
creating the object, Amazon S3 provides eventual consistency for read-after-write. 
```

The existence check itself is weak as the file might be created while data is gathered in staging directory for upload.

I propose to remove the check of use `LIST` S3 request instead that does not break `read-after-write` consistency.

FYI: @findepi

**Comment by sopel39** [comment]
This seems to be related to: https://github.com/prestodb/presto/issues/11587
as record parquet writer will create files with `override=false` mode.

**Comment by electrum** [comment]
Since this only affects Parquet, and we know that our file names are unique, we might be able to fix this for Parquet by changing the flag when opening the file. Or perhaps we could change the S3 FS to ignore the exists check (since it is only for Presto and is not a general purpose FS).
