### ISSUE TITLE
Add array functions: any_match(x, boolean lambda), all_match(x, boolean lambda) and none_match(x, boolean lambda)

### ISSUE THREAD

**Issue by linxingyuan1102** [prestosql/presto#1036]
cc: @wagnermarkd 

Consider the following table
```
presto:u_xinlin> describe order_dates;
      Column      |    Type     | Extra | Comment 
------------------+-------------+-------+---------
 productid        | integer     |       |         
 order_date_array | array(date) |       |         
(2 rows)
```
The `any_match` function will simplify a query
```
select * from order_dates where contains(transform(order_date_array, x -> x = date('2019-06-24')), true);
```
to
```
select * from order_dates where any_match(order_date_array, x -> x = date('2019-06-24'));
```
The `all_match` function will simplify
```
select * from order_dates where not contains(transform(order_date_array, x -> x > date('2019-06-24')), false);
```
to
```
select * from order_dates where all_match(order_date_array, x -> x > date('2019-06-24'));
```

An additional benefit is that this approach opens the possibility to short-circuit, whereas `contains(transform(arrary, lambda))` will transform the whole array.

Does anyone have comments?

**Comment by martint** [comment]
This sounds like a good addition!

**Comment by linxingyuan1102** [comment]
@martint Thanks for the comment. I'll start the work.

**Comment by electrum** [comment]
Should we have a `none_match` variant as well? Or does `NOT any_match(...)` suffice?

**Comment by linxingyuan1102** [comment]
@electrum I think `none_match` sounds good.

**Comment by findepi** [comment]
Done in https://github.com/prestosql/presto/pull/1045
