### ISSUE TITLE
Add support for renaming views

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#1037]
We can use a similar syntax as for renaming tables (also same as PostgreSQL):
```
ALTER VIEW name RENAME TO new_name
```
While it's tempting to make the existing table syntax work for this, the specification already differentiates between `DROP TABLE` and `DROP VIEW`, so it makes sense for rename to be separate as well.

**Comment by Praveen2112** [comment]
@electrum Can I take this ?

**Comment by martint** [comment]
The proposed syntax seems reasonable.
