### ISSUE TITLE
Cannot create empty Hive partition for non-bucketed table

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#104]
The `system.create_empty_partition` procedure fails because the source directory does not exist (no files were written) and thus the rename fails. `SemiTransactionalHiveMetastore.Committer#prepareAddPartition` should probably unconditionally create `currentPath` before checking if it is equal to `targetPath`.

**Comment by findepi** [comment]
related @wenleix's comment: https://github.com/prestosql/presto/pull/99#issuecomment-459013716

> I believe the first commit ("Fix creating non-bucketed empty partition") should be replaced by prestodb/presto#12204 . cc @electrum
