### ISSUE TITLE
Enable the Information Schema Connector to load data lazily

### ISSUE THREAD

**Issue by linxingyuan1102** [prestosql/presto#1046]
cc: @wagnermarkd @findepi @electrum 

The current implementation of the Information Schema Connector preloads all the data from underlying connectors and then builds a `ConnectorPageSource`.

A better approach is to make it lazily build `Page`s on the fly.
1. This approach benefits queries with a limit clause, e.g., `select * from hive.information_schema.columns limit 1`.
2. In addition, it decreases latency of the first query result.
3. Finally, for queries touching a lot of tables (e.g., `select * from hive.information_schema.columns`), it's possible that some (Hive) tables have invalid metadata, which eventually fails the query. The new approach passes `Page`s to downstream operators as soon as they are ready. In this way, failures can be detected sooner.

This issue is a follow-up of #998

**Comment by linxingyuan1102** [comment]
I implemented a basic version of "lazy" `InformationSchemaPageSource` and `InformationSchemaPageSourceProvider` but found the benefits mentioned above didn't show up.

It turns out `InformationSchemaMetadata::getPrefixes` is also a bottleneck which prevents the first query result to be returned in a low latency.

Please LMK if anyone has a comment.

**Comment by Praveen2112** [comment]
I was waiting for this patch so that we could modify it to solve this issue too (https://github.com/prestosql/presto/issues/631#issuecomment-486621503)
