### ISSUE TITLE
Benchmark Driver docs very unfriendly

### ISSUE THREAD

**Issue by archongum** [prestosql/presto#1052]
It's almost impossible to run a benchmark against Presto by reading this article: [Benchmark Driver](https://prestosql.io/docs/current/installation/benchmark-driver.html)

Furthermore, digging into `presto-benchmark-driver` source code
![Snipaste_2019-06-27_18-04-00](https://user-images.githubusercontent.com/20929338/60258170-308eda80-9907-11e9-8eaa-3c34902fbc81.jpg)

But can't get it work either
![Snipaste_2019-06-27_18-04-44](https://user-images.githubusercontent.com/20929338/60258239-53b98a00-9907-11e9-88c6-0bcf21d8a017.jpg)

**So it needs an enhancement maybe?**

**Comment by l0yu** [comment]
@archongum I once run into similar issue
my case is benchmark app could ping all nodes in cluster (ex: workers)
after network connection fixed, benchmark works. or you can run in standalone mode first and test

**Comment by archongum** [comment]
@l0yu I already run in standalone mode but didn't work.
How to play with the `suite.json` and `sql/*.sql` files? Could you give me a demo for `tpch connector` please?

**Comment by l0yu** [comment]
@archongum 
you can run with ` --debug ` option for details
and ` --help ` show how to customized other options

**Comment by sopel39** [comment]
@archongum What use case do you try to benchmark?

**Comment by archongum** [comment]
@sopel39 Thanks for your attention.
We built our Data Warehouse upon Hive(HDFS, ORC) and Presto do the ETLs and analytical queries which resource-sensitive but low concurrence.
But now, we're going to use Presto to publish DM(Data Mark) to our Web/App using which require high concurrence - for us, a small company, maybe not that high - hence, we want to find out how does Presto behave in concurrent aspect. 
(Why Presto but MySQL? Because it's about data consistency between)

I noticed that Benchmark Driver run queries in serial. It's not suitable in this case.

**Comment by sopel39** [comment]
@archongum You could also try using https://github.com/prestosql/benchto. It does support running queries concurrently and various other scenarios. However, it requires more setup as it consists of various components (e.g benchmark server, benchmark runner, benchmark RDBMS).

Alternatively maybe it's possible to add concurrency support to Benchmark Driver.
