### ISSUE TITLE
prestosql pre-build rpm file should be available in maven

### ISSUE THREAD

**Issue by bb786112** [prestosql/presto#1066]
Hi,

We always need to create a rpm from source to install on linux using Apache Ambari. Can we always add a rpm file on maven so, user can directly use rpm without building it.

We have rpm available for prestodb in maven.

Thanks
Bharat

**Comment by findepi** [comment]
@bb786112 I think it's already there.
please check
https://search.maven.org/artifact/io.prestosql/presto-server-rpm/
and eg https://search.maven.org/remotecontent?filepath=io/prestosql/presto-server-rpm/315/presto-server-rpm-315.rpm

**Comment by electrum** [comment]
We should link to it on the website, however: https://github.com/prestosql/prestosql.io/pull/33
