### ISSUE TITLE
How to use Presto Configuration parameters dynamically 

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestosql/presto#1068]
Hi team,

I am writing one application to optimize the Presto, and show the recommendations after running each query based on cluster stats. I want to use
Presto config properties dynamically from my Java program. I know I can place Presto configuration properties inside “etc/config.properties” file, but in order to take advantage of properties I need to restart the presto server. What I want I should be able to pass these properties dynamically with Presto Query and there should be no need to restart the presto server.

Please do let me know how can I pass the configuration properties dynamically without restarting the Presto server.
I used to do these kind of task with Apache IMPALA and APACHE HIVE but I am not getting any clue for Presto.

I am referring to below configuration properties -

https://prestosql.io/docs/current/admin/properties.html

**Comment by dain** [comment]
Properties contained in the configuration properties files can not be changed after the process has started.  There simply is no facility to change these, and there isn’t even a permanent linkage between the initial properties and the services that consume them, so even if we wanted to change them we couldn't.  Additionally, many of those properties are things like ports and thread pools that are difficult or impossible to change after starting the process.

The properties that can be controlled at runtime are typically exposed via query session.  The defaults session properties are normally specified in configuration files, but the defaults can be overridden with a SessionPropertyConfigurationManager plugin:

  https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/Plugin.java#L78

This plugin eventually provides:

  https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/session/SessionPropertyConfigurationManager.java

Which will be called for any query to override the default session properties.

Finally, there are some limited properties that can be controlled via JMX.  These are mostly from third part libraries, and Presto itself has very few (if any) mutable JMX attributes.

**Comment by PranayMunshi1982** [comment]
Thanks @dain . This was really helping.
