### ISSUE TITLE
There are 5.5 GB more LocalDispatchQuery objects In coordinator's GC stack after a lone time pressure test.

### ISSUE THREAD

**Issue by Crossoverrr** [prestosql/presto#1083]
There are more and more LocalDispatchQuery object in coordinator's GC stack after a long time pressure test(6 more hours).
Then the performance of presto will be very low.
So I dumped the hprof file of jvm and I found that there are 5.5 GB more LocalDispatchQuery object.
I am using a presto-hbase connector to fetch data from HBase.
What should I do? Is this a bug of presto?
![image](https://user-images.githubusercontent.com/33892550/60651088-0b0a4f80-9e78-11e9-88d6-f012121d25f9.png)
![image](https://user-images.githubusercontent.com/33892550/60651117-1a899880-9e78-11e9-87f3-b0ea4141ebb3.png)

**Comment by Crossoverrr** [comment]
My presto version is prestosql-312.

**Comment by findepi** [comment]
@Crossoverrr there was a know memory leak in 312. Could you please redo your test in 315?

**Comment by Crossoverrr** [comment]
Do you mean the #843 "Fix leak in operator peak memory computations" in prestosql-313?
![image](https://user-images.githubusercontent.com/33892550/60652968-b36de300-9e7b-11e9-96a1-b9307dd47bbe.png)
Thank you very much @findepi , I will try that 315.

**Comment by findepi** [comment]
@Crossoverrr no, not this one. I don't remember which exactly, but you should be good with 315 anyway.
Let me close the issue for now. If you still experience _the same_ memory leak in 315, please reopen. 
If you experience some other problem, please create a new issue.

Also, I recommend you join the `#troubleshooting` channel on Presto Slack (https://prestosql.io/community.html) if you haven't yet joined.
Thanks!

**Comment by Crossoverrr** [comment]
Thanks again!
According to our pressure test results, most of the query scenarios showed a 10% to 20% improvement in performance, which made us very excited!

**Comment by findepi** [comment]
@Crossoverrr glad to hear that! This is huge!  If you consider blogging about this, let us know (eg link here). We can tweet it further.

Also, I see you joined our slack. Welcome to the community! :)

**Comment by Crossoverrr** [comment]
It's my pleasure to join the presto community ! :)
Yes, if the result is good I will spend some time to write a blog, hahaha.

**Comment by electrum** [comment]
If you don’t have your own blog or would like to contribute the Presto community blog, its easy, just write some markdown for the post and send a pull request.

https://prestosql.io/blog/
https://github.com/prestosql/prestosql.io

**Comment by Crossoverrr** [comment]
OK. I got it. I will try that as soon as I finished my test on prestosql-315. :)

**Comment by Crossoverrr** [comment]
We didn't found this problem in prestosql-315, and the performance is as good as prestosql-312, thank you all. You are GREAT!     lol
