### ISSUE TITLE
CREATE TABLE AS SELECT does not work for external tables

### ISSUE THREAD

**Issue by anoopj** [prestosql/presto#1089]
Sounds like CTAS does not work with external tables.  Any reasons why this should not be supported? We can contribute a patch if there is agreement.

```
presto> create table anoopj3.customer WITH (format = 'ORC', external_location='s3://anoopj-bucket/customer/') as select * from tpcds.sf100.customer;
Query 20190705_175533_00057_txqsu failed: External tables cannot be created using CREATE TABLE AS
```

The above error is coming from [here](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java#L1085-L1086). 

Expected result: The above table should be created successfully with the location and format specified in the CTAS statement.

**Comment by anoopj** [comment]
cc @dain @electrum

**Comment by findepi** [comment]
The only reason that I see not to implement this is that subsequent `DROP TABLE` will leave data behind.
Maybe what we actually want is the ability to create non-external (managed) tables with specified location?
E.g. `WITH (format = 'ORC', location=....)`

Today, a workaround is to `CREATE SCHEMA somewhere_else WITH (location=....)` and create tables within that schema.
This works, but is verbose a and doesn't allow to use arbitrary locations (path's last component must be equal to the table name).

**Comment by anoopj** [comment]
Agree that both approaches (allowing CTAS with external tables or allowing managed tables to have arbitrary locations) can work.

**Comment by electrum** [comment]
Both seem fine. These restrictions were put in place because allowing users to do them seemed like a bad idea (files in random places), but we could allow them with config flags so that administrators can disable the behavior.

**Comment by electrum** [comment]
We should allow creating external tables using `CREATE TABLE AS` if `hive.non-managed-table-writes-enabled`, just as we allow inserts.

**Comment by kfirt** [comment]
Actually we would like to "leave data behind", as we would like to "export" a query result-set to a specific location.

**Comment by findepi** [comment]
Fixed in https://github.com/prestosql/presto/pull/2669
