### ISSUE TITLE
Type of StringLiteral related issue

### ISSUE THREAD

**Issue by hustnn** [prestosql/presto#1130]
I have some issues on the varchar type in creating table:

1. Create table will fail for the result of query like `SELECT ''` as the inferred type is `VARCHAR(0) `which is not allowed in creating table;

2. The common super type of varchar is the max length column, then the column type of table created with the result of `SELECT * FROM (VALUES 'a','ab','') ` is `VARCHAR(2)`.

For issue 1, does it make sense to change the inferred type for empty to `VARCHAR` to avoid the issue in creating table?

For issue 2, does it make sense to change the common super type to `VARCHAR` to make the created table less strict?

If make sense, I can submit the PR.

**Comment by kokosing** [comment]
Is using `cast` an option to you?

- `SELECT cast('' as varchar(10) a)`
- `SELECT * FROM (VALUES 'a','ab', cast('' as varchar(10))`

**Comment by hustnn** [comment]
@kokosing 
For case 1, sometimes users creates the new column with a custom expression which may generate empty column, then save a table will fail. They may not explicitly call `cast`.

For case 2, what I mean is the column type if decided at the time of creating the table, its type is the largest value with the data so far, after that he may continue insert some more longer strings.

**Comment by electrum** [comment]
Is `varchar(0)` even legal? Need to check the specification. For the other use case, I agree a cast is appropriate.

**Comment by hustnn** [comment]
@electrum @kokosing Thanks. 

Close this issue. These issues should be solved by adding cast in user side.

**Comment by electrum** [comment]
I filed #1136 to fix the empty varchar issue. It seems to not be legal per the standard, so we shouldn't produce such a type.
