### ISSUE TITLE
I need a full list of config property options

### ISSUE THREAD

**Issue by byungnam** [prestosql/presto#1150]
I'm looking for a full list of the properties that can be used for `config.properties` or `session-property-config.properties`. 

In fact, I'm currently looking for the guide to `session-property-config.properties`. [The official manual page](https://prestosql.io/docs/current/admin/session-property-managers.html) only made me confused about the naming format (should I replace every dot (`.`) and dash (`-`) to underscore (`_`)? ) with the lack of the list of property options that I can use.

So I first decided to find the full list of properties. I already knew [this manual](https://prestosql.io/docs/current/admin/properties.html), but it seems it does not contain some properties like `query.max-run-time` or `query.max-execution-time` which can be found at [the code](https://github.com/prestodb/presto/blob/2e6cafcf20dd69f8f739d9fb886cf0c9a0593232/presto-main/src/main/java/com/facebook/presto/execution/QueryManagerConfig.java#L61-L62) or the document of the session property config.

So.. where are they? Any information?

**Comment by findepi** [comment]
@byungnam Probably the best place is to get possible config options for `config.properties` is to check `server.log`.
Config options are printed at startup (name, default value, configured value, optional description).

Note that some config options are dependent on other configs (e.g. you can configure Kerberos principal only when you enable Kerberos).
Dependent config options will not be printed in `server.log`.

For session property config options, take a look at `SystemSessionProperties`. This lists all engine-provided session properties.
Connectors can provide session properties that are catalog-specific. Do you need them too?

I invite you to join our Slack (https://prestosql.io/community.html)
Slack is a better place to ask this type of questions and often much faster.
See you there!
