### ISSUE TITLE
does presto have any plan about support implicit conversion (from number to varchar )

### ISSUE THREAD

**Issue by zhangxin0112** [prestosql/presto#116]
May be all the Hive users want this features . It take huge cost changes for rewrite Hive scripts. Hive‘s market is so huge(ETL). Why not consider fully supporting Hive? This is more conducive to the development of Presto. Presto can increase the indication that opening this feature will reduce performance.

Some ln: https://github.com/prestodb/presto/issues/10888

**Comment by sopel39** [comment]
I don't think implicit `number -> string` cast is part of SQL standard:
```
A number is assignable only to sites of numeric type. If an assignment of some number would result in a loss of its most significant digit, an exception condition is raised. If least significant digits are lost, implementation- defined rounding or truncating occurs, with no exception condition being raised. The rules for arithmetic are specified in Subclause 6.26, “<numeric value expression>”.
``` 

Maybe we could have a compatibility toggle for such feature? @martint ?

**Comment by zhangxin0112** [comment]
Ye. Good idea. It is good for both.

**Comment by aniruddha-pe** [comment]
Hey, is this being taken up anytime soon ? If not as a default, probably can be provided as an option to user to set true before running a query like hive.groupby.orderby.position.alias=true
