### ISSUE TITLE
How to choose Presto Session Properties and its values

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestosql/presto#1166]
Hi Team,
I want to optimize the Presto, I have to perform optimization at run time means without restarting the Presto Server so for this reason I am using Presto Session Properties. I can set session properties when I am firing the query. 

I've couple of questions below
**I've come across 91 session properties, out of that I want to use some of them but
(1) I don't know how to choose their values, whether it should be 'true' or 'false' for particular query, or value of session property should be 10 or 100. 
(2) How to decide these values looking at 'query'?**
(3) I want some detail description of below session properties. Where can I found detail about below properties. 

 
following are session properties with current and default values which I want to use for optimization - 

- dictionary_aggregation                                                     | false                    | false                

distributed_index_join                                                           | false                  | false                
distributed_join                                                                     |                          |                      
distributed_sort                                                                     | true                  | true                 

enable_intermediate_aggregations                                       | false                 | false                
execution_policy                                                                    | all-at-once       | all-at-once          
initial_splits_per_node                                                            | 8                      | 8                    
join_distribution_type                                                         | PARTITIONED      | PARTITIONED          
join_reordering_strategy                     | ELIMINATE_CROSS_JOINS | ELIMINATE_CROSS_JOINS
max_drivers_per_task                                                             |                          |                      
max_reordered_joins                                                              | 9                       | 9                    
optimize_hash_generation                                                     | true                  | true                 
push_aggregation_through_join                                            | true                  | true                 
push_partial_aggregation_through_join                                | false                 | false                
push_table_write_through_union                                           | true                 | true                 
query_priority                                                                         | 1                     | 1                    
redistribute_writes                                                                  | true                | true                 

spill_enabled                                                                           | false                 | false                
split_concurrency_adjustment_interval                                   | 100.00ms              | 100.00ms             

task_concurrency                                                                     | 16                    | 16                   
task_share_index_loading                                                        | false                 | false                
task_writer_count                                                                    | 1                     | 1                    
writer_min_size                                                                       | 32MB                  | 32MB                 

hive.bucket_execution_enabled                                             | true                  | true                 
hive.force_local_scheduling                                                   | false                 | false                
hive.hive_storage_format                                                       | ORC                   | ORC                  
hive.insert_existing_partitions_behavior                                 | APPEND                | APPEND               

hive.orc_bloom_filters_enabled                                              | false                 | false                
hive.orc_max_buffer_size                                                       | 8MB                   | 8MB                  
hive.s3_select_pushdown_enabled                                         | false                 | false                

 
@dain

**Comment by PranayMunshi1982** [comment]
@dain I've checked description of each session properties in "SHOW SESSION" but it is one liner. I am looking for detail description in order to make decision.

**Comment by dain** [comment]
@PranayMunshi1982 I have a bit of a back log on issues and pull requests right now, so it might take me a couple of days to get to this one.  Sorry for the delay.

**Comment by PranayMunshi1982** [comment]
Thank you @dain. I can understand your situation. :)

**Comment by dain** [comment]
Sorry this one fell off my radar.  `SHOW SESSION` prints the documentation we have for the session properties.  In general we don't suggest that people mess with session properties unless they are having an issue.  If you have specific questions about properties, or are trying to solve a problem, I suggest you ask on Slack: https://prestosql.io/slack.html
