### ISSUE TITLE
Max Planning Time Control

### ISSUE THREAD

**Issue by infearOnTheWay** [prestosql/presto#1177]
I wonder whether there exists a kind of solution to control the planning time of single query, since such query would occupy large amounts of resource and affect other following query.
Is there any configs can do this?Or can I do this by limit the total query time through other configs?
My presto version is 0.202.

**Comment by kokosing** [comment]
There is `experimental.iterative-optimizer-timeout` config property and matching `iterative_optimizer_timeout` session property. This control only optimizer execution. This was 

One option (workaround) would be to periodically do `select * from system.runtime.queries` and `call system.kill_query()` which exceeds threshold.

**Comment by infearATbaidu** [comment]
@kokosing Thanks for quick reply!
As I know,  `iterative-optimizer-timeout` only works within "single iterativeOptomizer". Is there any global control on all optimizers?
BTW, is it better that presto supports a kind of automcatic strategy to control such high-cost query?

**Comment by infearOnTheWay** [comment]
@kokosing In our situation，there exists some query involve about 100 thousands columns. These query cost long time such as 20 minutes on planning. So we try to control the planning time of such query in order not to affect following query.
On the other hand, if we can know the most time-consumed procedure within the planning of such query, it would also be helpful. Can we analyze the time cost of each planning procedure?
Thanks for your attention.

**Comment by kokosing** [comment]
@infearOnTheWay Have you fixed your issue? What was the resolution?

> On the other hand, if we can know the most time-consumed procedure within the planning of such query, it would also be helpful. Can we analyze the time cost of each planning procedure?

There are JMX statistics exposed for planner which tells which optimizer rules takes how much of time.

> there exists some query involve about 100 thousands columns. These query cost long time such as 20 minutes on planning.

Maybe there are places where we can improve planning, can you try attach a profiller during a planing of that query?

> So we try to control the planning time of such query in order not to affect following query.

I don't get it. Do you try to kill queries which take huge amount of time for planing? Notice that `system.runtime.queries` exposes information about planning time and analysis time. That could be used for external system to control such queries.
