### ISSUE TITLE
Failed to initialize connection pool: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unrecognized connection property

### ISSUE THREAD

**Issue by qinzl1** [prestosql/presto#1258]
HikariPool seem can not init presto jdbc
I use sreamsets JDBC Query Consumer (https://streamsets.com/documentation/datacollector/3.9.x/help/datacollector/UserGuide/Origins/JDBCConsumer.html#concept_qhf_hjr_bs)
Has anyone used this tool

**Comment by findepi** [comment]
> Failed to initialize pool: Unrecognized connection property

what's the offending connection property?

**Comment by qinzl1** [comment]
@findepi 
No special configuration
![image](https://user-images.githubusercontent.com/20242930/62597387-74b6c700-b918-11e9-9470-866aeef9c66a.png)
It doesn't seem to support presto
![image](https://user-images.githubusercontent.com/20242930/62597353-56e96200-b918-11e9-832a-d9e99b4eef46.png)

**Comment by kokosing** [comment]
Please try to open an issue in https://github.com/brettwooldridge/HikariCP. From information you sent it is hard to say anything.

What is the UI tool that you are using? Have you tried to use HikariCP with Presto directly from java code. That way it will be easier to debug the actual issue.

**Comment by qinzl1** [comment]
@kokosing 
the UI tool is streamsets 
https://streamsets.com/

**Comment by kokosing** [comment]
What was the resolution?

**Comment by harshadwaj** [comment]
@qinzl1
I am facing the same issue. Can you please post the resolution?

**Comment by shangshao** [comment]
@qinzl1
I am facing the same issue. Can you please post the resolution?
