### ISSUE TITLE
OutOfMemoryError occurred in presto-client

### ISSUE THREAD

**Issue by wyukawa** [prestosql/presto#1259]
Hi,

I develop presto web ui https://github.com/yanagishima/yanagishima depends on presto-client

OutOfMemoryError occurred in yanagishima and then we analyzed yanagishiam heap dump with Eclipse Memory Analyzer

Here is the yanagishima command line argument and Eclipse Memory Analyzer result
```
/opt/jdk-11.0.3+7/bin/java -Xmx10G -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError ... yanagishima.server.YanagishimaServer ...
```

![](https://i.gyazo.com/d450b34fa23aa77d3fc5006116080a30.gif)
![](https://i.gyazo.com/507add051c06e3bede902752bb10822d.gif)

It seems that there is the memory pressure in FixJsonDataUtils.
https://github.com/prestodb/presto/blob/0.215/presto-client/src/main/java/com/facebook/presto/client/FixJsonDataUtils.java#L78

yanagishiam has new/old presto-client to handle new/old presto server.

The above code is prestodb but I guess OOME may occur in prestosql.

As a workaround, I will increase java heap in yanagishima.

But it would be great if this is the presto issue and it will be improved in the future.

Thanks

**Comment by afilipchik** [comment]
+1. I guess it is caused by some query handling change. After a bit of debugging I noticed that StatementClientV1 in advance method tries to load ```/v1/statement/executing/[QUERY_ID]/xb3cafccb6fc94e6882d227f590aacf79/0``` which in our case (structs) returns 150 Mb of data which mostly full with:
```"typeSignature":{"rawType":"row","typeArguments":[{"rawType":``` json.

That makes query slow (even when select limit 1) and OOMs both java and python clients.

**Comment by electrum** [comment]
This doesn't look like a leak. Rather, the JSON response appears too large to be processed using a reasonable amount of memory.

By default, the server tries to produce a JSON result size of 1MB, which is much smaller than what you appear to be seeing. Two questions:

1. Do you have any client modifications to set `targetResultSize` to a larger value, or server modifications to increase `MAX_TARGET_RESULT_SIZE`?
2. What version of the server are you using for the client that hits this error? There was a change 84a3d0b65bf27867edeb1617498726558ce73062 in 0.213 to prevent large responses for dictionary blocks.

**Comment by wyukawa** [comment]
1. We don't have any client modifications
2. version of the server is 0.197

It would be resolved if we upgrade the presto server.
Thanks!
