### ISSUE TITLE
Use iceberg plugin classloader inside PartitionTable getTableMetadata method

### ISSUE THREAD

**Issue by vrozov** [prestosql/presto#1281]
To avoid class/resource loading issues, it is necessary to switch thread context class loader to the iceberg plugin class loader inside `getTableMetadata` method.

**Comment by electrum** [comment]
I looked into this and this should be working correctly, as `IcebergConnector.getMetadata()` is wrapping the `IcebergMetadata` instance in `ClassLoaderSafeConnectorMetadata`, which ensures the correct class loader is set for `getTableMetadata` and all the other calls.

**Comment by vrozov** [comment]
The issue is not with `IcebergConnector.getTableMetadata()` that is working correctly, it is with `PartitionTable.getTableMetadata()`. Note that the affected query is `select * from "table$partitions"`.

**Comment by electrum** [comment]
Ah, this is for `SystemTable`. We could add a `ClassLoaderSafeSystemTable` (ugh).

**Comment by electrum** [comment]
Sorry for the confusion, I missed the `PartitionTable` part when reading the description.

**Comment by vrozov** [comment]
@electrum I'll look into the issue, please assign it to me.

**Comment by electrum** [comment]
@vrozov great, assigned to you. Note that after you sign the CLA (required for contributions), you’ll have the GitHub “triage” permission so that you can assign and manage issues yourself. https://github.com/prestosql/cla
