### ISSUE TITLE
Can't start the server in Intellij after the Google Sheet Plugin commit

### ISSUE THREAD

**Issue by linxingyuan1102** [prestosql/presto#1288]
It gives an error
```
Error injecting constructor, io.prestosql.spi.PrestoException: /usr/local/presto/credentials/google-sheets-credentials.json (No such file or directory)
```

I understand that this can be fixed by adding such a file. But is there a simpler way to fix this? Given that I don't intend to use the Google Sheets Connector for now.

**Comment by electrum** [comment]
We should probably just delete this file for now. Developers who want to use it can create their own. The existing file also seems to be broken since `metadata-sheet-id` is invalid. Do you want to send a PR to delete the file?

**Comment by linxingyuan1102** [comment]
Thanks @electrum !

I've opened the PR.
