### ISSUE TITLE
GEO functions doc problem

### ISSUE THREAD

**Issue by infearOnTheWay** [prestosql/presto#1314]
Hi 

https://prestosql.io/docs/current/functions/geospatial.html.
Above doc explain ST_Contains function as:
ST_Contains(Geometry, Geometry) → boolean
Returns true if and only if no points of the second geometry lie in the exterior of the first geometry, and at least one point of the interior of the **first geometry** lies in the interior of the **second geometry**.

In my opinion, the second half defination should be：
and at least one point of the interior of the **second geometry** lies in the interior of the **first geometry**.

Is it a mistake or I misunderstand the function meaning? I refered from:
https://postgis.net/docs/ST_Contains.html

**Comment by martint** [comment]
They are both equivalent. Basically it’s saying that the second geometry is fully contained in the first geometry and it’s not an empty geometry. I do agree that the description is too convoluted and could be improved.

**Comment by infearOnTheWay** [comment]
@martint Thanks for your explaination. Now I understand and it may be better to improve this discription.
