### ISSUE TITLE
Show Join distribution type in the Live Plan

### ISSUE THREAD

**Issue by anjalinorwood** [prestosql/presto#1323]
Live Plans in Presto UI currently do not show the name of the table being scanned. It also does not show the type of join (distributed/replicated). These pieces of information are crucial in debugging queries. This issue is to add these pieces of information to the plan.

**Comment by findepi** [comment]
> Live Plans in Presto UI currently do not show the name of the table being scanned.

I see this being shown:

![image](https://user-images.githubusercontent.com/144328/63295009-f5d46d80-c2cb-11e9-9589-76a6eb544882.png)

What version are you using?

**Comment by anjalinorwood** [comment]
I was on 212. I see the table name in the latest (master). Thanks for changing the issue title.

**Comment by findepi** [comment]
I am concerned that showing distribution type is actually redundant information.
When join is broadcast, it's left source is within same stage.
When join is partitioned, both sources are connected with an exchange, separate stages.

**Comment by dain** [comment]
@findepi with a co-located join the source is in the same stage also
