### ISSUE TITLE
(A basic question!) why we should set catalogs on each presto workers?

### ISSUE THREAD

**Issue by blcksrx** [prestosql/presto#1325]
Why we should create the catalog directory and copy and pates the catalog directory of old worker(or coordinator) on the new worker?
for example in the situation of the using HA Hadoop, you should edit the hive connector on each presto node and append this on them:
```
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
```
It's repetitive and boring:D way! And what I want to say is that it's not better to set the catalog directory only on the coordinator and the coordinator tell it to the other nodes?

**Comment by findepi** [comment]
> It's repetitive and boring:D way!

It is! :)

And there are tools to help you with that!
Either you use some automated deployment specific to your environment, or you can use `presto-admin` (https://github.com/prestosql/presto-admin).
On AWS, Azure, GCloud or Kubernetes, you can use Starburst integrations instead.

> it's not better to set the catalog directory only on the coordinator and the coordinator tell it to the other nodes?

The potential downside is that a worker could need slightly different configuration than the coordinator.
Admittedly it would be useful in certain situation, but automation around your deployment (as mentioned above) is the recommended way.

HTH.

BTW
Presto Slack (https://prestosql.io/community.html) is the best place for asking questions for the community to answer.

**Comment by blcksrx** [comment]
Hi, thanks for that, I know about presto-admin and the deployment tools(i use ansible and k8s!) and I just wanted the reason that why we should use other tools.
I will join the slack:D

**Comment by findepi** [comment]
> I just wanted the reason that why we should use other tools.

I think the short explanation is -- because what we have is simpler & plays nicely with automation.
(Each worker is immediately ready, doesn't need to wait until configuration propagated, etc.)
And no-one wanted the more dynamic method so much as to implement this yet.
Still, i agree that having this would nicely complement current feature set.

> I will join the slack

welcome!
