### ISSUE TITLE
Presto throws error when there is datatype mis-match between parquet schema and hive metastore

### ISSUE THREAD

**Issue by anirbanch** [prestosql/presto#136]
test

**Comment by findepi** [comment]
replaced with https://github.com/prestosql/presto/issues/137

**Comment by DBZshahin** [comment]
Is this issue been resolved  ?? 
We are still facing issues with the  **Mismatched Domain types: smallint vs integer** when trying to compare a smallint type with integer

**Comment by findepi** [comment]
@DBZshahin which Presto version are you using?

**Comment by DBZshahin** [comment]
@findepi  it is Presto on AWS EMR, version 0.214

**Comment by findepi** [comment]
@DBZshahin the error you're quoting
> Mismatched Domain types: smallint vs integer

is fixed in Presto 302. See https://prestosql.io/docs/current/release/release-302.html

**Comment by DBZshahin** [comment]
Ohh ok, we are using Presto on AWS EMR and its latest EMR version and presto available is version 0.214. Thanks for the info, we are checking with AWS when Presto version would be updated.
