### ISSUE TITLE
Integer division default to double, is consistent with spark sql?

### ISSUE THREAD

**Issue by melin** [prestosql/presto#1381]
Integer division default to double, is consistent with spark sql?
Can you add a parameter to turn it on?
![image](https://user-images.githubusercontent.com/1145830/63744101-ea3b0500-c8d0-11e9-8bcf-5612f8050f9b.png)

**Comment by martint** [comment]
Presto implements division using standard SQL semantics. Division between two exact numeric values (e.g., integers) is expected to return an exact numeric value. `double` is considered an "approximate numeric type". If you want to achieve the same semantics as Spark, you can cast one of the terms in your expression to `double` or use the scientific notation form:

```
CAST(6 as double) /  2
```

or 

```
6e0 / 2
```
