### ISSUE TITLE
IS DISTINCT FROM bug with ObjectIdFunctions

### ISSUE THREAD

**Issue by dickson-conde** [prestosql/presto#139]
This is a copy of the issue from the original prestodb repo: https://github.com/prestodb/presto/issues/11869

I'm getting the error:

`com.facebook.presto.metadata.OperatorNotFoundException: 'IS DISTINCT FROM' cannot be applied to ObjectId, ObjectId`

when trying to select from a view that pulls data from a MongoDB connector despite 'IS DISTINCT FROM' not being used in the view. I'm assuming there's some background logic that happens with joins/aggregations that uses the 'IS DISTINCT FROM' command.

The select works in presto version .188 but does not work in version .203 when testing a presto upgrade.

**Comment by electrum** [comment]
Thanks for reporting. This will be fixed in the upcoming `203` release.

**Comment by electrum** [comment]
Thanks for reporting. This will be fixed in the upcoming `303` release.
