### ISSUE TITLE
Make EffectivePredicateExtractor.Visitor#visitTableScan use metadata.getTableProperties()

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#1399]
`getTableProperties()` produces detailed predicate from connector that involves partition values. Such predicate can then be forwarded to other side of join, etc so it's really useful in partition pruning.

Using of `getTableProperties()` was removed by https://github.com/prestosql/presto/pull/621.

We should think how to restore this behavior.
The problem with connectors is that at beginning of planning there might be little predicates
to constraint partition enumeration (e.g. in Hive) and we don't want to query too many partitions at that stage.
We could:
1. Cache partitions query
2. Bailout when too many partitions are queries.
3. Bailout on too simple filter predicates

Some other ideas?

FYI: @martint @findepi

**Comment by findepi** [comment]
We should not go to Metastore until all derivable predicates are pushed down to TS level.
I've witnessed that even _asking_ Metastore for partitions (with or without bailing out when there are too many) can take very long time, especially where there are not enough predicates pushed down.

I think that we should not change `EffectivePredicateExtractor`, as it's used in many places. Instead we should have clearly defined phases in query planning:

1. pushdown as much as possible without talking to external systems
2. ask for table properties (partitions in Hive case)
   - in fact this doesn't need to be "ask all at once". It's conceivable that we do this in the loop:
     1. ask for table properties for one TS
     2. derived as much as possible
     3. repeat for next TS
3. pushdown as much as possible

**Comment by sopel39** [comment]
> Instead we should have clearly defined phases in query planning:

That's a good idea. We still need to ask for table properties eventually as it might lead to new predicates which could be used in join graph.

> in fact this doesn't need to be "ask all at once". It's conceivable that we do this in the loop: 

Unfortunately it might still be an issue that new predicates in one join branch would trigger narrowing predicates from other join branch TS. This could be repeated for other join branches. I guess we should implement caching in connectors for such cases.

**Comment by findepi** [comment]
> I guess we should implement caching in connectors for such cases.

TableHandle is effectively a cache.
For example in Hive connector -- once we load partitions list, we don't need to go to Metastore the second time, we just narrow down this list.

**Comment by sopel39** [comment]
This issue also means that `getTableProperties()` is not really used anywhere apart from explains. This could lead to invalid implementations in connectors.

**Comment by sopel39** [comment]
This is now fixed in master
