### ISSUE TITLE
s3 api compatible storage

### ISSUE THREAD

**Issue by l0yu** [prestosql/presto#1416]
some cloud vendor like
https://www.alibabacloud.com/help/doc-detail/64919.htm
https://intl.cloud.tencent.com/product/cos

provide s3 api compatible object storage, with minor difference
does presto provide s3 filesystem 'spi' for hive connector, so that developer could customize implementation ?

https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ConfigurationInitializer.java#L127
^^
for example
```
config.set("fs.mys3.impl", S3FileSystemProvider);
```

**Comment by l0yu** [comment]
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html
https://gosspublic.alicdn.com/AliyunJavaSDK/latest/javadoc/index.html
https://intl.cloud.tencent.com/document/product/436/31534
^^ and java sdk looks similar

**Comment by findepi** [comment]
@l0yu the "spi" for hive connector is the hadoop file system API.
https://github.com/prestosql/presto/pull/1397 is going to allow you to use custom implementations.

**Comment by l0yu** [comment]
ok, very cool ! Thanks

**Comment by l0yu** [comment]
https://youtu.be/iTI-UHBl7ik
I made a customization and it works, demo ^^

**Comment by apc999** [comment]
@l0yu  the video is private. mind opening it to the public?

**Comment by l0yu** [comment]
> @l0yu the video is private. mind opening it to the public?

try again @apc999

**Comment by tooptoop4** [comment]
@51yu what customisation did u make?
