### ISSUE TITLE
Pseudocolumn for "last modified" date

### ISSUE THREAD

**Issue by cstuart1** [prestosql/presto#1423]
The $path pseudo column is very helpful; Thank you for providing this.
Could the metadata for the "last modified" date be added as well?

This would allow me to:
- Selectively pull 'new' data from an object path (IE ETL processed up to X date, get 'new' data )
- Summarize S3 details directly in a query without relying on external processes 

My current usage of Presto is with Athena.
Thank you!

**Comment by findepi** [comment]
Other pseudo-column recently request was `file size`.

**Comment by findepi** [comment]
@Praveen2112 am i correct you're working on this? (if yes, please assign yourself)
