### ISSUE TITLE
what's  the different between  prestodb  with  prestosql?

### ISSUE THREAD

**Issue by newluhuibiao** [prestosql/presto#1434]
prestodb project website is https://prestodb.github.io/

**Comment by kokosing** [comment]
Duplicate of https://github.com/prestosql/presto/issues/380

**Comment by kokosing** [comment]
@newluhuibiao please see #380. It gives high overview of the differences.
If you have further questions, please join Presto Slack (https://prestosql.io/community.html) where you can learn more. See you there!
