### ISSUE TITLE
version318  when  execute  command:mvnw clean install -DskipTests  then  error  is below

### ISSUE THREAD

**Issue by newluhuibiao** [prestosql/presto#1438]
Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (default) on project presto-spi: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml

**Comment by martint** [comment]
How did you get the source code for Presto? Make sure to get it by cloning the github repo instead of the tgz file.

**Comment by newluhuibiao** [comment]
@martint  thks!
when  i Running Presto in Idea by README.md ,but  it well occurs  SqlBaseParser ,SqlBaseLexer,SqlBaseBaseListener  in  presto-parser   module.

**Comment by findepi** [comment]
@newluhuibiao you need to build Presto from command line first. IntelliJ isn't configured to do certain build steps.

Run this:
```
./mvnw clean install -DskipTests
```

if you're still having problems, make sure you have cloned git repository:
```
$ git describe
318-95-g4440b965e6
```

**Comment by newluhuibiao** [comment]
ok ,thks!
