### ISSUE TITLE
GPL-2.0-with-classpath-exception license text at presto-jdbc/src/main/resources/META-INF/license/LICENSE.jol.txt

### ISSUE THREAD

**Issue by ajorg-aws** [prestosql/presto#1461]
I'm trying to figure out why there is a GPL-2.0-with-classpath-exception license text at [`presto-jdbc/src/main/resources/META-INF/license/LICENSE.jol.txt`](https://github.com/prestosql/presto/blob/318/presto-jdbc/src/main/resources/META-INF/license/LICENSE.jol.txt). It was added in 7ec30b9e44ea1f917ae34e0ef6a23749855a71c1 which also includes a relocation of the `org.openjdk.jol` namespace for the JDBC driver, but when I look at the [JDBC .jar](https://repo1.maven.org/maven2/io/prestosql/presto-jdbc/318/presto-jdbc-318.jar) file I don't find anything at `io/prestosql/jdbc/$internal/jol`.

```xml
                                <relocation>
                                    <pattern>org.openjdk.jol</pattern>
                                    <shadedPattern>${shadeBase}.jol</shadedPattern>
                                </relocation>
```

I do see that `presto-server-rpm` includes `jol-core-0.2.jar` (though it does not specify "and GPLv2 with exceptions" in the `License:` header). I also see `org/openjdk/jol/` in `presto-cli`.

If the JOL code is not actually included in presto-jdbc, would it be appropriate to remove the GPL license text from the JDBC sources to avoid any confusion?

Or have I missed something and JOL *is* actually included in the JDBC driver?

**Comment by electrum** [comment]
It’s no longer included. Would you like to send PR to remove it?

**Comment by ajorg-aws** [comment]
Yep. I'll have to sign the iCLA and send that in, so expect the PR later today or tomorrow. Thanks!
