### ISSUE TITLE
Incorrect comparisson of parquet binary statistics for accented characters

### ISSUE THREAD

**Issue by thoralf-gutierrez** [prestosql/presto#1462]
Original Issue from the old repo: https://github.com/prestodb/presto/issues/12338 by @igorcalabria

> On version 0.216 presto incorrectly assumes that a binary column statistic is corrupt due to wrong ordering of accented values. The root cause is probably the naive comparison made by the slice library here:
https://github.com/prestodb/presto/blob/master/presto-parquet/src/main/java/com/facebook/presto/parquet/predicate/TupleDomainParquetPredicate.java#L201
>
> I have added a simple test case on TupleDomainParquetPredicateTest that should not fail
> ```
>    @Test
>    public void testAccentedString() throws ParquetCorruptionException {
>        String column = "StringColumn";
>
>        assertEquals(getDomain(createUnboundedVarcharType(), 10, stringColumnStats("Áncash", "china"), ID, column,
>                true), create(ValueSet.ofRanges(range(createUnboundedVarcharType(), > utf8Slice("Áncash"), true, utf8Slice("china"), true)), false));
>    }
> ```
> but it fails with
> ```
> com.facebook.presto.parquet.ParquetCorruptionException: Corrupted statistics for column "StringColumn" in Parquet file "testFile": [min: Áncash, max: china, num_nulls: 0]
> ```
> Áncash comes before China, but presto flags the statistics as corrupt since it does not use natural ordering to sort binary statistics.
> As additional information, the files that led me to this error were generated by spark

It seems ordering can be different between different systems and this leads to one system encoding certain statistics (min/max) with an ordering that is different from Presto's.

In the best case, Presto notices that something is wrong with statistics and throws an exception (this is what happened to @igorcalabria) but in the worst case Presto does not notice the problem and can serve incorrect results. See my last comment:

> Say we have strings A, B, C. If the order for Parquet is A, B, C but for Presto is A, C, B.
(I don't mean to imply that Parquet's order is correct, while Presto's isn't -- this is just an example)
> 
> In the best case, say we have a Parquet page of Bs and Cs, the stats will show min=B and max=C and Presto will raise the corrupt stats exception.
> 
> In the worst case, say we have a Parquet page of As, Bs, and Cs, the stats will show min=A, max=C. Presto will not raise an exception as it also finds that A < C. But if Presto is looking for Bs, it will completely skip the page because it believes that B > C. No exception will be raised and Presto will return the wrong result.

**Comment by thoralf-gutierrez** [comment]
We are discussing this issue in the Presto Community Slack (https://prestosql.io/community.html), [#parquet-stats](https://app.slack.com/client/TFKPX15NC/CN55NH3PY/details/info)

**Comment by findepi** [comment]
This hasn't been updated for a while and i suspect one of the upgrades (Hive 3 or Parquet lib update) could have solved the problem.
There may be no point in keeping the issue open, so let me close this. We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).

**Comment by tooptoop4** [comment]
so hive 2 isn't supported by presto anymore? its still an issue

**Comment by ConnorJBeck** [comment]
Can confirm, we are still having this issue. In particular, it's corrupting when trying to generate a Parquet table where a column has currency symbols ($, €, etc.). We are using 0.232, and [patch notes from last year](https://prestosql.io/docs/current/release/release-327.html) suggest that the `hive.parquet.fail-on-corrupted-statistics` configuration is being deprecated. I would have thought this implied that this issue was fixed.

**Comment by findepi** [comment]
> We are using 0.232

@ConnorJBeck can you please try again with the latest release (currently 348, https://prestosql.io/download.html)?
if you have any questions, you can always ping me on [our slack](https://prestosql.io/slack.html)
