### ISSUE TITLE
show create table is not checked with accessControl

### ISSUE THREAD

**Issue by dpolonsky** [prestosql/presto#1482]
show columns from <table_name>;
and show create table <table_name>;
are both showing a common base data related to columns (column name and type)

but when executing show create table <table_name>, accessControl.checkCanShowColumnsMetadata is not called
as a result, a user is granted access to information that should have been filtered by the same permissions defined on columns

**Comment by dpolonsky** [comment]
@kokosing I have a one-line fix for that fix it is just I need to sort out CLA first

**Comment by kokosing** [comment]
> I have a one-line fix for that

Awesome! That was really quick. Does it work for both cases? Do you have tests for that?

**Comment by dpolonsky** [comment]
should be covered, I will need to add more tests though

**Comment by ebyhr** [comment]
I'm closing this issue because the related PR was already merged.
