### ISSUE TITLE
Hive not caching metadata when using Amazon Glue metastore

### ISSUE THREAD

**Issue by gs-asrivastav** [prestosql/presto#1487]
Hi, 
We've noticed that the caching mechanism is not working for hive metadata when we use Amazon Gluestore. We tried debugging the source code and even though it seems that there is some caching implementation in: 

```
public static CachingHiveMetastore memoizeMetastore(HiveMetastore delegate, long maximumSize)
    {
        return new CachingHiveMetastore(
                delegate,
                newDirectExecutorService(),
                OptionalLong.empty(),
                OptionalLong.empty(),
                maximumSize);
    }
```

But this essentially returns a new instance everytime it's fetched. 

We also placed debug points on: 
```
io.prestosql.plugin.hive.metastore.glue.GlueHiveMetastore#getTable
```
But it looks like this method is always called whenever we use Gluestore. If the caching mechanism was working, it shouldn't have reached the methods. 

Can you please help me understand this behavior? 

**hive.properties**
```
connector.name=hive-hadoop2
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.non-managed-table-writes-enabled = true
hive.s3-file-system-type = PRESTO
hive.metastore=glue
hive.hdfs.impersonation.enabled = true
hive.s3.use-instance-credentials=true
hive.s3.signer-type=AWSS3V4SignerType
hive.parquet.use-column-names=true
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.compression-codec=SNAPPY
hive.recursive-directories=true
```

**Comment by electrum** [comment]
The cache is not currently wired up for the Glue metastore, but that should be easy to add. Are you seeing performance issues with Glue that would be helped by caching?

**Comment by gs-asrivastav** [comment]
We're seeing a lag of 200ms-300ms which we'd like to avoid. It impacts the query time, if we use hive metastore the time spent in query analysis is less.

**Comment by gs-asrivastav** [comment]
We looked at HiveMetadataFactory

```
SemiTransactionalHiveMetastore metastore = new SemiTransactionalHiveMetastore(
                hdfsEnvironment,
                this.metastore,
                CachingHiveMetastore.memoizeMetastore(this.metastore, perTransactionCacheMaximumSize), // per-transaction cache
                renameExecution,
                skipDeletionForAlter,
                skipTargetCleanupOnRollback);
```

The memoizeMetastore method however returns a new instance everytime by creating new instances of cache maps through io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore#newCacheBuilder

Is this the correct behavior?

**Comment by gs-asrivastav** [comment]
@electrum would presto continue to work directly with glue or is would this be part of caching too?

**Comment by electrum** [comment]
The per-transaction cache works with all metastore implementations. To cache across transactions, you’ll need a change similar to the one you made to bind the caching metastore. Would you like to submit a PR?

**Comment by sopel39** [comment]
Closed via https://github.com/prestosql/presto/pull/1625
