### ISSUE TITLE
Hive procedures do not validate user access to objects

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#1489]
It is required for user to have:
 - insert privilege in order to create partitions.
 - delete privilege to drop partitions

**Comment by electrum** [comment]
I think we should restrict this to table owners.

**Comment by kokosing** [comment]
> I think we should restrict this to table owners.

I am not sure about it. Why not to use same privileges when partitions are dropped or created in regular way (during `INSERT` or `DELETE`)?

**Comment by electrum** [comment]
It seems different because it’s referencing existing data on the file system. I can see going either way.

**Comment by guyco33** [comment]
Same issue  for ```system.register_partition``` and for ```system.unregister_partition```
