### ISSUE TITLE
Too many dots in table name error

### ISSUE THREAD

**Issue by blcksrx** [prestosql/presto#1490]
I use Kafka-connect and Debezium connector to read Oplog from MongoDB and send it to Kafka
the connectors. On the connector config there's a key that name is **mongodb.name** and with the value of this key, the connector will create the topic on Kafka base on the database and collection.
For example, assume these configs:
```
mongodb.name = mongodb
database = company
collection = test
```
with these configs, the connector will create a topic with name **mongodb.company.test**. In case of connecting the presto with the **connector.name=kafka** to read the topic from the Kafka with presto, the query would be this:
```
SELECT * FROM kafka.default."mongodb.company.test";
```
And this query will return the **Too many dots in table name error**.
Also, I read the code that generates this error, it happens on **MetadataUtil.java** on this method:
```
 public static QualifiedObjectName createQualifiedObjectName(Session session, Node node, QualifiedName name)
    {
        requireNonNull(session, "session is null");
        requireNonNull(name, "name is null");
        if (name.getParts().size() > 3) {
            throw new PrestoException(SYNTAX_ERROR, format("Too many dots in table name: %s", name));
        }

        List<String> parts = Lists.reverse(name.getParts());
        String objectName = parts.get(0);
        String schemaName = (parts.size() > 1) ? parts.get(1) : session.getSchema().orElseThrow(() ->
                semanticException(MISSING_SCHEMA_NAME, node, "Schema must be specified when session schema is not set"));
        String catalogName = (parts.size() > 2) ? parts.get(2) : session.getCatalog().orElseThrow(() ->
                semanticException(MISSING_CATALOG_NAME, node, "Catalog must be specified when session catalog is not set"));

        return new QualifiedObjectName(catalogName, schemaName, objectName);
    }
```
And this is absolutely wrong! It should be a policy on splitting that not breaks the **"** character and skip it! in this case, the **QualifiedName name** will be like this:
```
catalogName = kafka
schemaName = default
objectName = "mongodb.comapny.test"
```

**Comment by findepi** [comment]
> In case of connecting the presto with the **connector.name=kafka** to read the topic from the Kafka with presto, the query would be this:
> 
> ```
> SELECT * FROM kafka.default."mongodb.company.test";
> ```
> 
> And this query will return the **Too many dots in table name error**.

Are you executing the query form command line via Presto CLI?

**Comment by blcksrx** [comment]
> Are you executing the query form command line via Presto CLI?

yes.

**Comment by findepi** [comment]
Bash/shell is stripping out `"` (actually: it interprets them), so you need to escape them:
```
presto-cli --execute "
SELECT * FROM kafka.default.\"mongodb.company.test\";
"
```

**Comment by blcksrx** [comment]
It returns this now:
```
Cannot list splits for table 'mongodb.comapny.test' reading topic ''mongodb.comapny.tes' java.nio.channels.ClosedChannelException
```

**Comment by findepi** [comment]
@blcksrx you're clearly past your original problem, so let me close this issue.
I encourage you to join Presto Slack (https://prestosql.io/community.html) and ask on the `#troubleshooting` channel
