### ISSUE TITLE
presto build failing

### ISSUE THREAD

**Issue by MichaelChirico** [prestosql/presto#1528]
I'm trying to set myself up a Docker environment in order to contribute more effectively to Presto when possible. e.g. I was a bit stymied here by relying on cla-bot to check commits:

https://github.com/prestosql/presto/pull/765

However, building Presto from source is not working for me with this `Dockerfile`:

```
FROM ubuntu:18.04

ARG PRESTO_GIT=https://github.com/prestosql/presto.git
ENV PRESTO_GIT=${PRESTO_GIT:-https://github.com/prestosql/presto.git}

ARG PRESTO_BRANCH=master
ENV PRESTO_BRANCH=${PRESTO_BRANCH:-master}

RUN apt-get update && \
    apt-get install -y \
      openjdk-11-jdk \
      git

RUN git clone $PRESTO_GIT presto && cd presto && \
    git config --global user.email "my@email.com" && \
    git config --global user.name "Michael Chirico" && \
    git checkout -B $PRESTO_BRANCH && \
    git pull origin $PRESTO_BRANCH

RUN cd /presto && ./mvnw clean install
```

Have run it a few times and it dies in different places, e.g.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-geospatial-toolkit 319-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ presto-geospatial-toolkit ---
[INFO] Deleting /presto/presto-geospatial-toolkit/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (default) @ presto-geospatial-toolkit ---
[INFO] 
[INFO] --- dependency-scope-maven-plugin:0.8:check (default) @ presto-geospatial-toolkit ---
[INFO] No test dependency scope issues found
[INFO] 
[INFO] --- license-maven-plugin:2.3:check (default) @ presto-geospatial-toolkit ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ presto-geospatial-toolkit ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ presto-geospatial-toolkit ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] argLine set to empty
[INFO] 
[INFO] --- git-commit-id-plugin:2.1.13:revision (default) @ presto-geospatial-toolkit ---
Killed
```

or

```
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-main 319-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ presto-main ---
[INFO] Deleting /presto/presto-main/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (default) @ presto-main ---
[INFO] Ignoring requireUpperBoundDeps in org.codehaus.plexus:plexus-utils
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[WARNING] Invalid bytecodeVersion for module-info.class: expected 52, but was 53
[INFO] 
[INFO] --- dependency-scope-maven-plugin:0.8:check (default) @ presto-main ---
[INFO] No test dependency scope issues found
[INFO] 
[INFO] --- license-maven-plugin:2.3:check (default) @ presto-main ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ presto-main ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ presto-main ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] argLine set to empty
[INFO] 
[INFO] --- git-commit-id-plugin:2.1.13:revision (default) @ presto-main ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ presto-main ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 85 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ presto-main ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1679 source files to /presto/presto-main/target/classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] /presto/presto-main/src/main/java/io/prestosql/execution/buffer/PagesSerde.java:[39,23] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[INFO] /presto/presto-main/src/main/java/io/prestosql/metadata/TableHandle.java: Some input files use or override a deprecated API.
[INFO] /presto/presto-main/src/main/java/io/prestosql/metadata/TableHandle.java: Recompile with -Xlint:deprecation for details.
[INFO] /presto/presto-main/src/main/java/io/prestosql/cost/ComposableStatsCalculator.java: Some input files use unchecked or unsafe operations.
[INFO] /presto/presto-main/src/main/java/io/prestosql/cost/ComposableStatsCalculator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ presto-main ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ presto-main ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 811 source files to /presto/presto-main/target/test-classes
Killed
```

Unfortunately `Killed` isn't very helpful for debugging... is there something wrong with my image setup?

I had the same trouble with Piotr's suggested command:

```
./mvnw -pl '!presto-server-rpm,!presto-docs,!presto-proxy,!presto-testing-server-launcher' clean install -TC2 -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dair.check.skip-all=true
```

---

Just noticed there's some ambiguity on the `README` re:Java depenency:

> Java 8 Update 161 or higher (8u161+), 64-bit.

Does this mean any java version >= Java 8 u 161? Or does it mean Java 8 specifically, with any version of Java 8 above Update 161?

Anyway, using `openjdk-8-jdk` instead of 11 had a similar failure.

**Comment by findepi** [comment]
> Unfortunately `Killed` isn't very helpful for debugging... is there something wrong with my image setup?

I'd guess OOM killer (OS of Docker host) decided to kill maven.

Are you on Win/Mac/Linux?

**Comment by electrum** [comment]
Presto likely requires JDK 8 to build. Running Maven with a newer JDK means that all the plugins need to be compatible. I did a bunch of work previously to get it working with JDK 9, but it may have regressed, and there might be issues with newer JDKs. So use the latest version of JDK 8.

However, you can and should run the Presto server on JDK 11. There were substantial improvements to the G1 garbage collector since JDK 8.

The "Killed" from the compiler plugin is not a compatibility issue (you'd see a stack trace or other specific failure). This likely means the JVM is getting killed by the OS for running out of memory.

Rather than trying to do a full Presto build as part of a Docker image build, I'd just run a Docker instance interactively, and run the build from there. It should be much easier to debug, tweak, etc. Basically, treat the Docker instance as you would any other virtual machine used for development.

**Comment by MichaelChirico** [comment]
>Rather than trying to do a full Presto build as part of a Docker image build, I'd just run a Docker instance interactively, and run the build from there.

Well, that's exactly what I am doing in practice at the moment, in order to test the Dockerfile is working correctly.

Earlier, I was doing some other stuff in the background, but after clearing almost everything on my machine, the same error obtains.

> Are you on Win/Mac/Linux?

My machine is Mac and the Docker is built on minimal Ubuntu `ubuntu:18.04` image

**Comment by electrum** [comment]
Almost all of the Presto developers use Mac. You can run the build natively on Mac, no need to use Docker (except for product tests which use Docker internally). You’ll also want to setup the code in IntelliJ.

**Comment by MichaelChirico** [comment]
My Mac is using Java 11... not comfortable enough with Java to go messing with that. Docker serves to isolate my machine's setup from that used to build+test Presto

**Comment by electrum** [comment]
You can install both. It’s designed to allow that. Each JDK lives in a single directory so you can haven any number of them without conflict.

By default it will use the latest version, but set the older version to be first in your `PATH` for the terminal used for Presto development.

**Comment by findepi** [comment]
> My machine is Mac and the Docker is built on minimal Ubuntu `ubuntu:18.04` image

I too would recommend building directly, without Docker.
Besides reason already mentioned, it should be waaay faster, because of the docker overlay filesystem performance hit. (mileage vary)

If you still want to go docker route, make sure you give the Docker host enough memory (Docker > Preferences ...)  and reduce swap to minimum.
My Docker on Mac has 8g memory limit, but I'm running product tests, not a build. 
For build 2-3g should be sufficient, but you may need to manually tell maven JVM not to use more (eg 3g docker limit and -Xmx2g may work).
(Latest Java 8 is smart enough to autoconfigure -Xmx based on available memory, but I don't know if you have recent enough Java version for this to work.)

**Comment by MichaelChirico** [comment]
Thanks both. I'm quite apprehensive to mess around with my local Java installation since the last times I've done so it's taken a full day to recover but I guess if I'm serious about contributing to a Java project I'll have to figure it out sooner or later.
