### ISSUE TITLE
Remote page is too large

### ISSUE THREAD

**Issue by xingnailu** [prestosql/presto#1547]
Running Presto v.317 on hive 1.1.0

Getting the following exception when querying data :

`io.prestosql.operator.PageTooLargeException: Remote page is too large
	at io.prestosql.operator.HttpPageBufferClient.rewriteException(HttpPageBufferClient.java:534)
	at io.prestosql.operator.HttpPageBufferClient.access$1800(HttpPageBufferClient.java:88)
	at io.prestosql.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:403)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
But I can query the results. 

my query is: 

> SELECT
  t1.user_id
, t1.app_id
, t1.distribution_channel
, t1.platform
, "flatten"("array_sort"("array_agg"(ARRAY["date_diff"('day', "from_iso8601_timestamp"(t1.p_day), "from_iso8601_timestamp"(t2.p_day)),
      IF((t2.session_launch IS NULL), 0, t2.session_launch),
      IF((t2.view_doc_list_feeds IS NULL), 0, t2.view_doc_list_feeds),
      IF((t2.click_doc IS NULL), 0, t2.click_doc)]))
      ) l
FROM
  (dw.fact_user_device_app_sketch t2
INNER JOIN dw.dim_new_user t1 ON (((t2.user_id = CAST(t1.user_id AS varchar(20)))
    AND (t2.platform = t1.platform))
    AND (t2.app_id = t1.app_id)))
WHERE (((((t1.p_type = 'app')
    AND (t1.p_day = '2018-08-01'))
    AND (t2.p_type = 'client'))
    AND (t2.p_day >= '2018-08-01'))
    AND (t2.p_day <= '2018-08-08'))
GROUP BY t1.user_id, t1.app_id, t1.distribution_channel, t1.platform
LIMIT 350000

explain the query:

> Output[user_id, app_id, distribution_channel, platform, l]
 │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, flatten:array(bigint)]
 │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
 │   user_id := user_id_0
 │   app_id := app_id_2
 │   platform := platform_3
 │   l := flatten
 └─ Project[]
    │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, flatten:array(bigint)]
    │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
    │   flatten := "flatten"("array_sort"("array_agg"))
    └─ LocalExchange[ROUND_ROBIN] ()
       │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
       │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
       └─ Limit[350000]
          │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
          │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
          └─ LocalExchange[SINGLE] ()
             │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
             │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
             └─ RemoteExchange[GATHER]
                │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
                │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
                └─ LimitPartial[350000]
                   │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
                   │   Estimates: {rows: 350000 (76.44MB), cpu: ?, memory: ?, network: ?}
                   └─ Project[]
                      │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg:array(array(bigint))]
                      │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                      └─ Aggregate(FINAL)[user_id_0, app_id_2, distribution_channel, platform_3][$hashvalue]
                         │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, $hashvalue:bigint, array_agg:array(array(bigint))]
                         │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                         │   array_agg := array_agg("array_agg_40")
                         └─ LocalExchange[HASH][$hashvalue] ("user_id_0", "app_id_2", "distribution_channel", "platform_3")
                            │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg_40:array(array(bigint)), $hashvalue:bigint]
                            │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                            └─ RemoteExchange[REPARTITION][$hashvalue_41]
                               │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, array_agg_40:array(array(bigint)), $hashvalue_41:bigint]
                               │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                               └─ Aggregate(PARTIAL)[user_id_0, app_id_2, distribution_channel, platform_3][$hashvalue_47]
                                  │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, $hashvalue_47:bigint, array_agg_40:array(array(bigint))]
                                  │   array_agg_40 := array_agg("expr_17")
                                  └─ Project[]
                                     │   Layout: [user_id_0:bigint, app_id_2:varchar, distribution_channel:varchar, platform_3:varchar, expr_17:array(bigint), $hashvalue_47:bigint]
                                     │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                                     │   expr_17 := "array_constructor"("date_diff"('day', "from_iso8601_timestamp"("p_day_5"), "from_iso8601_timestamp"("p_day")), CAST((CASE WHEN ("session_launch" IS NULL) THEN 0 ELSE "session_launch" END
                                     │   $hashvalue_47 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("user_id_0"), 0)), COALESCE("$operator$hash_code"("app_id_2"), 0)), COALESCE("
                                     └─ InnerJoin[("user_id" = "expr_10") AND ("platform" = "platform_3") AND ("app_id" = "app_id_2")][$hashvalue_42, $hashvalue_44]
                                        │   Layout: [click_doc:integer, session_launch:integer, view_doc_list_feeds:integer, p_day:varchar, user_id_0:bigint, app_id_2:varchar, platform_3:varchar, distribution_channel:varchar, p_day_5:varch
                                        │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                                        │   Distribution: PARTITIONED
                                        ├─ RemoteExchange[REPARTITION][$hashvalue_42]
                                        │  │   Layout: [user_id:varchar, app_id:varchar, click_doc:integer, session_launch:integer, platform:varchar, view_doc_list_feeds:integer, p_day:varchar, $hashvalue_42:bigint]
                                        │  │   Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
                                        │  └─ ScanProject[table = hive:dw:fact_user_device_app_sketch]
                                        │         Layout: [user_id:varchar, app_id:varchar, click_doc:integer, session_launch:integer, platform:varchar, view_doc_list_feeds:integer, p_day:varchar, $hashvalue_43:bigint]
                                        │         Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}
                                        │         $hashvalue_43 := "combine_hash"("combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("user_id"), 0)), COALESCE("$operator$hash_code"("platform"), 0)), COALESCE("$operato
                                        │         click_doc := click_doc:int:4:REGULAR
                                        │         user_id := user_id:string:0:REGULAR
                                        │         view_doc_list_feeds := view_doc_list_feeds:int:40:REGULAR
                                        │         p_day := p_day:string:-1:PARTITION_KEY
                                        │             :: [[2018-08-01], [2018-08-02], [2018-08-03], [2018-08-04], [2018-08-05], [2018-08-06], [2018-08-07], [2018-08-08]]
                                        │         app_id := app_id:string:2:REGULAR
                                        │         platform := platform:string:18:REGULAR
                                        │         session_launch := session_launch:int:16:REGULAR
                                        │         p_rate:string:-1:PARTITION_KEY
                                        │             :: [[daily]]
                                        │         p_type:string:-1:PARTITION_KEY
                                        │             :: [[client]]
                                        └─ LocalExchange[HASH][$hashvalue_44] ("expr_10", "platform_3", "app_id_2")
                                           │   Layout: [user_id_0:bigint, app_id_2:varchar, platform_3:varchar, distribution_channel:varchar, p_day_5:varchar, expr_10:varchar, $hashvalue_44:bigint]
                                           │   Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
                                           └─ RemoteExchange[REPARTITION][$hashvalue_45]
                                              │   Layout: [user_id_0:bigint, app_id_2:varchar, platform_3:varchar, distribution_channel:varchar, p_day_5:varchar, expr_10:varchar, $hashvalue_45:bigint]
                                              │   Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
                                              └─ Project[]
                                                 │   Layout: [user_id_0:bigint, app_id_2:varchar, platform_3:varchar, distribution_channel:varchar, p_day_5:varchar, expr_10:varchar, $hashvalue_46:bigint]
                                                 │   Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}
                                                 │   $hashvalue_46 := "combine_hash"("combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("expr_10"), 0)), COALESCE("$operator$hash_code"("platform_3"), 0)), COALESCE("$op
                                                 └─ ScanProject[table = hive:dw:dim_new_user]
                                                        Layout: [user_id_0:bigint, app_id_2:varchar, platform_3:varchar, distribution_channel:varchar, p_day_5:varchar, expr_10:varchar]
                                                        Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}
                                                        expr_10 := CAST(CAST("user_id_0" AS varchar(20)) AS varchar)
                                                        platform_3 := platform:string:3:REGULAR
                                                        p_day_5 := p_day:string:-1:PARTITION_KEY
                                                            :: [[2018-08-01]]
                                                        distribution_channel := distribution_channel:string:8:REGULAR
                                                        user_id_0 := user_id:bigint:0:REGULAR
                                                        app_id_2 := app_id:string:2:REGULAR
                                                        p_type:string:-1:PARTITION_KEY
                                                            :: [[app]]

And What went wrong? Is there any configuration that can affect the repair?

**Comment by xingnailu** [comment]
![remotePageLarge](https://user-images.githubusercontent.com/24468606/65040432-f9b8e580-d986-11e9-8259-0ec8011a253e.jpg)

**Comment by xingnailu** [comment]
The result of the query is 330486 rows.  So is the result of this query correct?

**Comment by dain** [comment]
Normally, this is caused by having one row that is larger than `32MB`.  You can increase this limit, but be careful, as at some point you can cause GC issues, or OOM the process.  The property is `exchange.http-client.max-content-length`

**Comment by xingnailu** [comment]
@dain 
Thanks Reply.  
 I changed the  exchange.http-client.max-content-length from 32MB to 64MB, but I still got same error.  Should I check my data in tables? Or because the calculation process produced a very large line？
 And I noticed that many configuration values are 32MB in presto， Is this related to g1 garbage collection?

**Comment by luohao** [comment]
> And I noticed that many configuration values are 32MB in presto， Is this related to g1 garbage collection?

32MB is usually the region size in JVM. Actually I think 16MB might be a better config value for max object size. Anything larger than half region size(e.g., 32/2=16MB) is going to occupy the whole region which causes heap fragmentations. G1 doesn't handle this kind of humongous object very well(no compaction during GC) and it may lead to frequent major GC and subsequent OOM.

**Comment by xingnailu** [comment]
@luohao  Thanks.
The problem is that a lot of test data is aggregated together in group by.
