### ISSUE TITLE
presto315 hive.information_schema.columns is empty

### ISSUE THREAD

**Issue by gaojun2048** [prestosql/presto#1607]
hi
today I upgrade my presto cluster version from 0.201 to 315. 
Then I found the table hive.information_schema.columns is empty . 
Now,I run the SQL "show tables from xxx" it return 0 rows.

![image](https://user-images.githubusercontent.com/32193458/65831336-1b9d5b00-e2eb-11e9-9c62-69795b2bc331.png)

So, what is the change about it?

Thank you!

**Comment by findepi** [comment]
@gaojun2048  Is `db_benchmarktest` a schema in `hive` catalog?

Do I understand correctly that
- `SELECT * FROM hive.db_benchmarktest.event` returns data,
- but `SHOW TABLES FROM hive.db_benchmarktest` does not show "event" table?

What's the value of `hive.security`?
Do you have system access control configured?

**Comment by jiangzhx** [comment]
> @gaojun2048 Is `db_benchmarktest` a schema in `hive` catalog?
> 
> Do I understand correctly that
> 
> * `SELECT * FROM hive.db_benchmarktest.event` returns data,
> * but `SHOW TABLES FROM hive.db_benchmarktest` does not show "event" table?
> 
> What's the value of `hive.security`?
> Do you have system access control configured?

it's not show table from db.

it's
`show columns from table;`
return empty result.

**Comment by findepi** [comment]
@jiangzhx thanks for clarification. I got mislead by this:

> Now,I run the SQL "show tables from xxx" it return 0 rows.

Anyway...
What's the value of hive.security?
Do you have system access control configured?

**Comment by jiangzhx** [comment]
> @jiangzhx thanks for clarification. I got mislead by this:
> 
> > Now,I run the SQL "show tables from xxx" it return 0 rows.
> 
> Anyway...
> What's the value of hive.security?
> Do you have system access control configured?

we upgrade from 0.201 to 315. also  implement SystemAccessControl by ouself.

the hive config:

> connector.name=hive-hadoop2
> hive.metastore-cache-ttl=120s
> hive.metastore-refresh-interval=5s
> hive.metastore.uri=thrift://localhost:9083
> hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml



![image](https://user-images.githubusercontent.com/494507/65862352-a42a0300-e3a0-11e9-8200-d7530e5963a6.png)

**Comment by kokosing** [comment]
> implement SystemAccessControl by ouself.

Did you implement `filterColumns` method there? Can you share its code?

**Comment by kokosing** [comment]
`filterColumns` were added in `308`

**Comment by jiangzhx** [comment]
> `filterColumns` were added in `308`
thks. 
we just return
` return Collections.emptyList();
` 
i made a mistake;

**Comment by findepi** [comment]
@jiangzhx i am glad you found the source of the problem.

Assuming you're from the same team as @gaojun2048 , let me close the issue.

(Also, if you haven't yet, be sure to join Presto Slack https://prestosql.io/slack.html. See you there!)

**Comment by jiangzhx** [comment]
> @jiangzhx i am glad you found the source of the problem.
> 
> Assuming you're from the same team as @gaojun2048 , let me close the issue.
> 
> (Also, if you haven't yet, be sure to join Presto Slack https://prestosql.io/slack.html. See you there!)

yes,we work together。thks,please help close the issues.
