### ISSUE TITLE
JDBC Driver - low performance of getColumns method

### ISSUE THREAD

**Issue by bohyn** [prestosql/presto#1620]
Reading columns metadata by using Presto JDBC driver's method PrestoDatabaseMetaData.getColumns() method is very slow.

We have Presto (319) connected to Hive catalog with hundreds of tables. This particular problem was observed with Spotfire as a JDBC client. By looking at the driver source, calling getColumns() method for one table results in executing following query over "system.jdbc.columns" view:

`SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE, TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX, NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB, CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE, SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE, SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN FROM system.jdbc.columns WHERE TABLE_SCHEM LIKE 'test_schema' ESCAPE '\' AND TABLE_NAME LIKE 'test_table' ESCAPE '\' ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION`

According to my observations, the query actually goes over all tables in meta catalog, even when there is a filter for TABLE_NAME. When I execute this query manually from CLI, it usually fails on some complete unrelated problem with metadata of other table (which is ok, as that other table has incorrect reference to external Avro schema, but I'd expect it shouldn't be examined at all as it should be filtered out by TABLE_NAME param) after quite a long time (~30 minutes).

When I change that query to use "=" operators instead of "LIKE" for comparison of TABLE_NAME and TABLE_SCHEM, the performance increases rapidly. Isn't this more a problem of query optimizer?

I believe filtering on TABLE_NAME and TABLE_SCHEM using "LIKE" operator should prevent touching metadata discovery of tables, that are excluded by this filter, but I have an impression the behaviour is opposite.

**Comment by findepi** [comment]
> `TABLE_SCHEM LIKE 'test_schema' ESCAPE '\'`

The `_` is a special character for LIKE and needs to be escaped. Otherwise Presto cannot execute the query as optimally as it does with `=` predicate.
It should actually be `TABLE_SCHEM LIKE 'test\_schema' ESCAPE '\'`.

We recently made certain improvements for such bogus queries in `information_schema`. They are not yet applied to `system.jdbc.columns` though.
While we will likely apply more such improvements, making the client issue the _right queries_ remains an important factor.

Can you please report this as a problem to Spotfire?

**Comment by bohyn** [comment]
Tho problem is the client (Spotfire) is not executing the query by itself. It just calls API method PrestoDatabaseMetaData.getColumns() of Presto JDBC driver. Is there any more performance-optimal alternative within the driver?

**Comment by findepi** [comment]
@bohyn sorry, i should be more precise.

See https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String- 
It takes `tableNamePattern` -- a _pattern_.
If you want to list columns of `some_table`, you need to escape the `_` with "search string escape"
https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getSearchStringEscape--

**Comment by bohyn** [comment]
@findepi, I understand, I added few more notes into more previous comment regarding this, let me just repeat it here:

I understand Spotfire could potentially escape underscores, but still - if the getColumns API provides possibility of looking for columns by pattern matching, it should also ensure, that the queries using patterns are handled is an optimal way.
This particular problem is, that the column lookup times out by spending too much time on loading schema details for some table, that does not even match the input pattern.

**Comment by findepi** [comment]
@bohyn of course, we should make it as optimal as it can be.
It is said we are working around client deficiencies, but we this doesn't mean we won't do it.

Still, if a client uses `getColumns` API without escaping, this is **a bug** in the client.
Performance aside -- you want columns from `some_table`, but you will get columns from `some1table`, `some2table`, ... _as well_.
Does this example help?

**Comment by bohyn** [comment]
@findepi, ok I try to contact Spotfire support and ask them about fix.

But again, my biggest concern is, that when I pass e.g. `some_table ` to the `getColumns` method, it eventually fails on problem with schema discovery for table `my_other_tbl`.

**Comment by findepi** [comment]
> when I pass e.g. `some_table` to the `getColumns` method, it eventually fails on problem with schema discovery for table `my_other_tbl`.

I agree, it shouldn't be so. There is definitely room for improvement.

**Comment by tooptoop4** [comment]
same as https://github.com/prestodb/presto/issues/11442

**Comment by tooptoop4** [comment]
https://github.com/troels/nz-presto/blob/master/presto-main/src/main/java/com/facebook/presto/execution/SqlQueryManager.java#L451-L576
