### ISSUE TITLE
[base-jdbc-connector] projection pushdown

### ISSUE THREAD

**Issue by l0yu** [prestosql/presto#1635]
Seems like ` applyProjection ` is not impl in ` presto-base-jdbc `
Will ` applyProjection ` help reduce IO if user just select few columns on "wide" table ?

**Comment by findepi** [comment]
It's not needed for this case. Column selection is passed here:
https://github.com/prestosql/presto/blob/c6c1feb85f87701d07b04e334e8e99fb0306d41e/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java#L337

HTH

**Comment by l0yu** [comment]
> It's not needed for this case. Column selection is passed here:
> 
> https://github.com/prestosql/presto/blob/c6c1feb85f87701d07b04e334e8e99fb0306d41e/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java#L337
> 
> HTH

ok thanks !
