### ISSUE TITLE
ThriftHiveMetastore#getPartitionStatistics is leaking getPartitionsByNames calls within transaction cache

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#1657]
`ThriftHiveMetastore#getPartitionStatistics` calls `getPartitionsByNames` underneath in order to obtain partition stats. However, partitions are normally cached by `CachingHiveMetastore` per transaction. This doubles Metastore partition queries when number of partitions is below 100. The overhead might be significant when there are many concurrent queries (e.g. 20).

**Comment by sopel39** [comment]
Similarly `ThriftHiveMetastore#getPartitionStatistics` calls `ThriftHiveMetastore#getTable`, but tables should also be cached per transaction, thus saving one metastore call.

Similarly `BridgingHiveMetastore#getPartitionsByNames` calls `ThriftHiveMetastore#getTable` and `ThriftHiveMetastore#getFields`

**Comment by sopel39** [comment]
I think we might want to move caching lower, e.g. thrift level. That would require some explicit transaction cleanup, but we already pass `HiveIdentity` down to `ThriftHiveMetastore` so we could also pass transaction id.

Alternatively we could recreate entire metastore onion for each transaction, keeping only basic thrift client plus global thrift cache. `CachingHiveMetastore` would still be needed for Glue.

I think the latter approach is better.

**Comment by electrum** [comment]
The problem is that the Presto metastore interfaces split up table/partition from statistics, but these are combined at the Thrift metastore. Rather than changing how all the caching works, we can simply change the API to better match the Thrift metastore API.

Combining these seems fine since Glue doesn't have stats, and is likely to model them like Hive when they do. And even if they don't, it's easy to have the Glue implementation do separate calls to merge them together.

**Comment by sopel39** [comment]
> Rather than changing how all the caching works, we can simply change the API to better match the Thrift metastore API.

Isn't that the same as moving cache lower? We probably still need some translation (e.g `BridgingHiveMetastore`) in order to simplify more complex classes (e.g. `SemiTransactionalHiveMetastore`) so that they don't bother with low level thrift details

**Comment by electrum** [comment]
No, we would still have the `io.prestosql.plugin.hive.metastore` classes for everything, but `PartitionStatistics` would be contained in `Partition` rather than being fetched separately.

**Comment by sopel39** [comment]
This is already fixed in master
