### ISSUE TITLE
Add support for Cassandra cluster using SSL

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#1680]
https://groups.google.com/forum/#!topic/presto-users/zkcbheqKpDk
https://github.com/prestodb/presto/pull/7326
https://github.com/prestodb/presto/pull/6745

**Comment by martint** [comment]
I added something like this for the elasticsearch connector, so we could model it after that.

**Comment by ebyhr** [comment]
Thanks for sharing the information. It's very helpful.
