### ISSUE TITLE
Should information_schema.columns.COMMENT be renamed to COLUMN_COMMENT?

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#170]
Mysql `information_schema.columns` table exposes `column_comment` column, while Presto exposes `comment` column, see https://dev.mysql.com/doc/refman/5.7/en/columns-table.html

I couldn't find this column in ANSI SQL, nor in Oracle, Teradata, MSSQL.

It looks like Hue depends on this column: https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L213

This column was added to Presto about 5 years ago (with https://github.com/prestodb/presto/pull/1214). In origin PR I do not see any discussion about compliance with existing database system or ANSI SQL.

**Comment by kokosing** [comment]
To me it looks like a bug in Hue.

**Comment by ebyhr** [comment]
By the way, `information_schema.tables` doesn't have a column for comment. Is it not implemented intentionally? 

```
presto:default> select *, table_comment from hive.information_schema.tables where table_name = 'test_comment';
 table_catalog | table_schema |  table_name  | table_type | table_comment 
---------------+--------------+--------------+------------+---------------
 hive          | default      | test_comment | BASE TABLE | NULL          
```

Although hidden `table_comment` column exists, it always returns `NULL`.

**Comment by findepi** [comment]
@ebyhr this was added in https://github.com/prestosql/presto/commit/9c9ac4e685ca108bbb6b535f2083300e58413cb9
In order to show real table comments, we would need to modify `io.prestosql.metadata.MetadataListing#listTables` so that it returns table names  + comments.

**Comment by ebyhr** [comment]
I see, thank you for providing the information!

**Comment by findepi** [comment]
> Should information_schema.columns.COMMENT be renamed to COLUMN_COMMENT? 

both exist now. let me close this

**Comment by jhjiang0** [comment]
which version could get this change, I download the newest(0.240) source, but 
`select * from mysql_test.information_schema.columns`
there only 
` table_catalog |   table_schema   |     table_name      | column_name  | ordinal_position | column_default | is_nullable |  data_type   | comment | extra_info`
no one column named `COLUMN_COMMENT` ,
still need we change the source code ?

**Comment by findepi** [comment]
@jhjiang0  The `COLUMN_COMMENT` column in `.information_schema.columns` table is available at least since Presto 320.
Note that it won't show up in `SELECT *` -- it is hidden, because it is non standard column (the schema of `information_schema` is governed by the spec).
You need explicitly select it: `SELECT COLUMN_COMMENT FROM mysql_test.information_schema.columns`.
Please make sure you run the latest Presto from https://prestosql.io/download.html

**Comment by jhjiang0** [comment]
@findepi  thank you for providing the information!  I'm download from the chinese website, maybe then don't update to latest, I will try download your latest code test this problem. thanks!
