### ISSUE TITLE
Support Hive bucketing v2 for timestamp

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1706]
Follow up to https://github.com/prestosql/presto/issues/538

https://github.com/prestosql/presto/pull/1697 adds support for Hive bucketing v2, except for timestamp data type.

Per @electrum [comment](https://issues.apache.org/jira/browse/HIVE-21376?focusedCommentId=16783706&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16783706) under https://issues.apache.org/jira/browse/HIVE-21376, Hive bucketing v2 for `timestamp` was changed between 3.0 and 3.1 as part of https://issues.apache.org/jira/browse/HIVE-20007.

We should add support for Hive bucketing v2 for `timestamp` once we make sure Hive 3.0 has been generally superseded with 3.1 in the wild.

**Comment by electrum** [comment]
Another option is to remove support for bucketing on timestamp: https://github.com/prestosql/presto/pull/4759
