### ISSUE TITLE
Move Connector#getSystemTables to ConnectorMetadata

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1715]
Move `io.prestosql.spi.connector.Connector#getSystemTables` to `io.prestosql.spi.connector.ConnectorMetadata`.
`io.prestosql.spi.connector.ConnectorMetadata#getSystemTable` is in `ConnectorMetadata`.
Maintain backward compatibility.

**Comment by sopel39** [comment]
Could you describe the purpose of the change?

**Comment by findepi** [comment]
Making the APIs more coherent.

**Comment by electrum** [comment]
The APIs are intentional. One is a static list, unrelated to transaction, and the other is dynamic. If you move the method, you’d also need to change the behavior to be transactional.
