### ISSUE TITLE
Add examples in date_add(), date_diff() documentation

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1717]
Today the `date_diff()` docs are a bit vague.

- provide some examples (2-3 examples)
- same for `date_add()`

**Comment by Anurag870** [comment]
@findepi  Possible values of 'unit' are defined in the documentation https://prestodb.github.io/docs/current/functions/datetime.html, just above **date_add** function under **"Interval Functions"** heading

Is that what you are asking or something else?

**Comment by findepi** [comment]
@Anurag870 thanks for checking this!
When you start reading docs from a link like https://prestodb.github.io/docs/current/functions/datetime.html#date_diff it's not that obvious, because unit description is not initially visible.

Still would be good to add some examples, I will edit this issue.
