### ISSUE TITLE
Adding a short-term solution for pushing down partial aggregation into the connector

### ISSUE THREAD

**Issue by rzeyde-varada** [prestosql/presto#172]
Greetings,

Following #18, we have created a simple partial aggregation push-down prototype, by a creating a new PlanOptimizer. It was added at the end of the optimizers' list ([here](https://github.com/prestosql/presto/blob/7567baf65ee3d9356d6371b7112b04bf23a75b62/presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java#L511)), matching the partial AggregationNode - and passing down the aggregations (specified by their [FunctionCall](https://github.com/prestosql/presto/blob/57051c9a9616eee4f8713f58b84c07a8041767cb/presto-parser/src/main/java/io/prestosql/sql/tree/FunctionCall.java) quailified name and the relevant column handles) into ConnectorTableLayoutHandle (as it's currently done for predicate pushdown by the PickLayouts optimizer) of the underlying ScanNode.

Currently, we keep the original partial aggregation node in the query plan, since we don't support all aggregations in our connector and would like to fall back to Presto implementation for unsupported aggregations.
In order to keep the implementation generic, we have added a new API for Metadata interface for optionally adding aggregation into existing TableLayoutHandle by the new optimizer.

We would like to ask whether our approach makes sense?
If so, we would like to help the effort adding this feature (partial aggregation pushdown API) to mainline Presto.

Also, we were not sure whether we are adding the new optimizer at the correct stage of PlanOptimizers. Maybe we should put it as a part of PickLayouts?

**Comment by pgagnon** [comment]
@rzeyde-varada I think it would be best to either submit a short design proposal or a WIP PR to gather some comments.

**Comment by rzeyde-varada** [comment]
@pgagnon Thanks!
The design for [Pushdown of complex operations](https://github.com/prestosql/presto/wiki/Pushdown-of-complex-operations) answers most of our questions, so I'll close this issue for now.

**Comment by cwang9208** [comment]
@rzeyde-varada Hi, do you have a repo that implements this pushdown? This is a really nice feature.
