### ISSUE TITLE
Add Hive procedure to recover (discover) partitions

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#174]
This would provide the same functionality as Hive's [MSCK REPAIR TABLE](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-RecoverPartitions(MSCKREPAIRTABLE)).

**Comment by luohao** [comment]
Is there anyone working on `msck` feature? If not, I can take it.

**Comment by martint** [comment]
No one is. Go for it!
