### ISSUE TITLE
Log test @DataProvider values in product tests

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1759]
This is actually Tempto issue (https://github.com/prestosql/tempto/issues/19):

> Tempto logs test class, method name, groups.
> It should log `@DataProvider`-provided values too.
> 
> Example log:
> 
> ```
> 2019-10-15 19:14:23 INFO: [6 of 13] io.prestosql.tests.hive.TestHiveBucketedTables.testBucketingVersion (Groups: )
> 2019-10-15 19:14:46 INFO: SUCCESS     /    io.prestosql.tests.hive.TestHiveBucketedTables.testBucketingVersion (Groups: ) took 22.3 seconds
> 2019-10-15 19:14:46 INFO: [7 of 13] io.prestosql.tests.hive.TestHiveBucketedTables.testBucketingVersion (Groups: )
> 2019-10-15 19:14:51 INFO: SUCCESS     /    io.prestosql.tests.hive.TestHiveBucketedTables.testBucketingVersion (Groups: ) took 5.2 seconds
> ```
> 
> -- test runs are not distinguishable.

Copying here for visibility.

**Comment by rsarawgi** [comment]
@findepi Can I pick this one?

**Comment by findepi** [comment]
@rsarawgi sure, appreciated! I assigned you in the main (tempto) issue.
