### ISSUE TITLE
Broken RPM generation

### ISSUE THREAD

**Issue by realknorke** [prestosql/presto#1767]
From v321 onwards the module `presto-server-rpm` is broken. Version v320 is fine. Installation of Presto using the RPM file results in broken installation.

**Analysis**
In the RPM are multiple empty files, that is, JAR dependencies with a size of 0 bytes. As a result several (all?) plugins cannot be loaded because of missing class files. The server won't start.

**Cause**
The RPM is built from fragments from the `presto-server` target (e.g. `presto-server-322-SNAPSHOT.tar.gz`). This TGZ is created by the maven plugin `ca.vanzyl.maven.plugins:provisio-maven-plugin:1.0.2` which claims to be able to use hardlinks for duplicate files in (generated) tar.gz files. In older versions (<v321) the plugin was `io.takari.maven.plugins:provisio-maven-plugin:0.1.140` which is NOT using hardlinks.

The difference in size between the two .tar.gz is 345mb (hardlinks) vs. ~950mb (duplicates in archive).

See also https://github.com/prestosql/presto-maven-plugin/commit/a3b790263bd2dc29eb63ec8a4d1365247fd471a3

Please keep in mind that hardlinks are allowed in tar files.

**Possible Fix**
While the original `maven-dependency-plugin` may not be able to deal with hardlinks in archives it should be better to either
 - unpack the .tar.gz target from `presto-server` using shell commands (tar+gzip) or
 - disable usage of hardlinks (this will double the size of the official .tar.gz) or
 - fix the `maven-dependency-plugin` to be 100% compatible to (GNU) tar

**Comment by realknorke** [comment]
To safe some time: compare the content of the .tar.gz with the unpacked "version" in presto-server-rpm/target/

**Comment by jvanzyl** [comment]
I've submitted a PR for review to fix the issue: https://github.com/prestosql/presto/pull/1769

**Comment by kokosing** [comment]
Thanks for the fix. Anyway it looks we need to add tests for RPM so this does not happen in future: https://github.com/prestosql/presto/issues/1771
