### ISSUE TITLE
Support pivot

### ISSUE THREAD

**Issue by RosterIn** [prestosql/presto#1772]
Check this https://stackoverflow.com/questions/52226242/sql-server-pivot-table-to-one-column-per-date
exactly what I need to do with presto

Convert:
```
Customer  |   BalDate   | Balance
----------+-------------+--------
Customer1 |  1/01/2017  | 0.00
Customer1 |  1/02/2017  | 0.00
Customer1 |  1/03/2017  | 0.00
Customer1 |  1/04/2017  | 0.00
....      |  ....       | ....

```
into:

```
|   Customer   |   01/01/2017  |   01/02/2017  |    01/03/2017  |   01/04/2017  |    01/05/2017  |   01/06/2017  |    01/07/2017  |   01/08/2017  |    01/09/2017  |    01/10/2017  | ....
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|    Customer1 |     0.00      |      0.00     |      0.00      |     0.00      |      0.00      |     0.00      |      0.00      |      0.00     |      0.00      |      0.00      | ....
|    Customer2 |     0.00      |      0.00     |      0.00      |     0.00      |      0.00      |     0.00      |      0.00      |      0.00     |      0.00      |      0.00      | ....
|    Customer3 |     0.00      |      0.00     |      0.00      |     0.00      |      0.00      |     0.00      |      0.00      |      0.00     |      0.00      |      0.00      | ....

```
 
 In this case the columns (dates) are taken from the date in the BalDate  column there can be 1000+ dates
There is no way to do that in Presto.
The only way to pivot in presto is to hard coded the columns like shown here:
https://support.treasuredata.com/hc/en-us/articles/360001451248-Hive-Presto-Standard-SQL-Tips
Note the hard coding of the columns in the query `c1,c2,c3` you need to write a case for each one. it isn't dynamic pivot based on data.

Now see the answers in StackOverflow how simple it is to solve this problem in MS SQL.

Can presto find a proper way to address pivot issues?

**Comment by ebyhr** [comment]
Presto currently doesn't have a good way to support it. Please see  https://github.com/prestosql/presto/issues/1206. 

Also, I would recommend to join our Slack from https://prestosql.io/slack.html
I think this is the best place to ask questions.

**Comment by findepi** [comment]
@RosterIn you can use similar approach as the one suggested on the SO question you linked to (https://stackoverflow.com/a/52226623/65458), ie to build your SQL dynamically.
This assumes you'd need to fire two queries, not one. Second query would need to be generated based on column information fetched with the first query.

As @ebyhr suggested, let's move the discussion to our slack. Thanks
