### ISSUE TITLE
Cluster not performing under load

### ISSUE THREAD

**Issue by ayush-chauhan** [prestosql/presto#1776]
I am using open-source presto v3.20. My queries are not performing under load. Queries wait a long time to even start. Row/sec field is normally 1/10 of the query without load. Query was in the execution state for 10m under load still no computation was not done and without load it executed completely in 18secs

Resource utilization underload
<img width="1417" alt="resource summary under load" src="https://user-images.githubusercontent.com/40881979/66984246-f88aed80-f0d7-11e9-8276-bab9ac0937af.png">

Resource utilization without load
<img width="1402" alt="resource summary without load" src="https://user-images.githubusercontent.com/40881979/66984247-f88aed80-f0d7-11e9-8c34-772ad214efa3.png">

rows per sec under load
<img width="1434" alt="rows per sec under load" src="https://user-images.githubusercontent.com/40881979/66984249-f88aed80-f0d7-11e9-8d87-a2069d3c1298.png">

rows per sec without load
<img width="1430" alt="rows per sec without load" src="https://user-images.githubusercontent.com/40881979/66984250-f9238400-f0d7-11e9-8f6f-7eafd3cd93af.png">

**hive.properties**
```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hive-metastore-datapl:80

hive.s3.connect-timeout=1m
hive.s3.max-connections=1500

hive.table-statistics-enabled=true
hive.parquet.fail-on-corrupted-statistics=false
hive.ignore-corrupted-statistics=false

hive.storage-format=PARQUET
hive.parquet.use-column-names=true

hive.max-outstanding-splits=30000
hive.max-initial-splits=2000
hive.max-initial-split-size=256MB
hive.max-split-size=256MB

hive.non-managed-table-writes-enabled=true
hive.recursive-directories=true
```

**config.properties on coordinator**
```
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=3TB
query.max-memory-per-node=45890MB
discovery-server.enabled=true
discovery.uri=http://presto-2:8080
query.max-length=100000000
query.max-run-time=20m
query.max-stage-count=500
query.max-total-memory-per-node=45890MB
experimental.reserved-pool-enabled=false
query.low-memory-killer.policy=total-reservation-on-blocked-nodes
scheduler.http-client.max-requests-queued-per-destination=5000
scheduler.http-client.max-connections-per-server=10000
exchange.http-client.request-timeout=120s
exchange.http-client.max-requests-queued-per-destination=5000
exchange.http-client.max-connections-per-server=10000
exchange.client-threads=40
join-distribution-type=AUTOMATIC
optimizer.join-reordering-strategy=AUTOMATIC
```

**config.properties on worker**
```
coordinator=false
http-server.http.port=8080
query.max-memory=3TB
query.max-memory-per-node=45890MB
discovery.uri=http://presto-2:8080
query.max-length=100000000
query.max-run-time=20m
query.max-stage-count=500
query.max-total-memory-per-node=45890MB
experimental.reserved-pool-enabled=false
query.low-memory-killer.policy=total-reservation-on-blocked-nodes
exchange.http-client.request-timeout=120s
exchange.http-client.max-requests-queued-per-destination=5000
exchange.http-client.max-connections-per-server=10000
exchange.client-threads=40
join-distribution-type=AUTOMATIC
optimizer.join-reordering-strategy=AUTOMATIC
```

**Comment by findepi** [comment]
@ayush-chauhan I see you need help with tuning your Presto or troubleshooting a specific problem.
Could we please move the question to our slack (https://prestosql.io/slack.html), the `#troubleshooting` channel?
Thanks

(I'm closing the issue; you can still link to it without need to copy everything into Slack)
