### ISSUE TITLE
Test that server is compatible with older versions of the JDBC driver

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#1787]
We need to start the server and run a few queries against it using previous JDBC driver release versions.

**Comment by findepi** [comment]
For previous JDBC versions, we could pull them from maven central and load in separate classloader.
Similar to what we do in `io.prestosql.server.PluginManager#buildClassLoaderFromPom`.

This would allow us to have "unit test" (precisely: a test runnable from IDE) for this, while still covering more than 1 JDBC version.

**Comment by martint** [comment]
We should add tests for PARAMETRIC_DATETIME capability. Specifically, queries that involve the following types:
* timestamp(3)
* timestamp(p) with p < 3
* timestamp(p) with p > 3
* All the above, when nested in another type such as array, map or row.

**Comment by findepi** [comment]
Having this could prevent a regression in https://github.com/prestosql/presto/pull/4141.
