### ISSUE TITLE
Ignore Parquet binary statistics corrupted before PARQUET-251

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1798]
Before https://issues.apache.org/jira/browse/PARQUET-251 Parquet files could have their binary statistics corrupted: all row groups can have stats mirrored from the last group.
parquet-mr's reader recognizes such stats and ignores them.

**Comment by martint** [comment]
How does parquet-mr recognize them?

**Comment by martint** [comment]
Found it: https://github.com/apache/parquet-mr/blob/68e0eae9fb375d9b586ab3899828968f2a6d711e/parquet-column/src/main/java/org/apache/parquet/CorruptStatistics.java

**Comment by sanchitkashyap** [comment]
Looks like this is already fixed as part of https://github.com/prestosql/presto/commit/d408b6c85d0a1e49adab4ea91ca17606471b3058 
https://github.com/prestosql/presto/commit/f8899cc7236402ea4fed3997e6d61b5e9d02842e, so we can close this.
