### ISSUE TITLE
AssertFunctions assumes a Slice is a VARCHAR

### ISSUE THREAD

**Issue by enaggar** [prestosql/presto#1801]
While creating a unit test for one of the UDFs with VARBINARY return type, `assertFunction` fails with a mismatched error, although parsing the Slice into hexdecimal output it matches the returned result.
Tracing back how assrtFunction works, looks like there is an assumption Slice is always a VARCHAR? (Slice is converted into a string)
https://github.com/prestosql/presto/blob/master/presto-main/src/test/java/io/prestosql/operator/scalar/FunctionAssertions.java#L250 
```
    public void assertFunction(String projection, Type expectedType, Object expected)
    {
        if (expected instanceof Slice) {
            expected = ((Slice) expected).toStringUtf8();
        }

        Object actual = selectSingleValue(projection, expectedType, compiler);
        assertEquals(actual, expected);
    }
```

**Comment by electrum** [comment]
This is legacy behavior from before `expectedType` was added as a parameter to this method. It should be comparing that as well before making this transformation.

However, it works in practice, because for `VARBINARY`, the expected value passed in should be an instance of `SqlVarbinary`, not `Slice`. Take a look at `TestVarbinaryFunctions` for an example.

We could change this to also check for `isVarcharType(type)`, or perhaps remove this conversion entirely, and rely on the caller to pass a `String`.

**Comment by enaggar** [comment]
Hmmm I'm confused, I thought for Varbinary a Slice is used (like here https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java#L74) both as an input and as an output.
Also I tried to pass in a String instead, and it still failed although there were no literal differences between the expected and output values.

**Comment by enaggar** [comment]
Just checked the Test file, this looks useful let me try that.

**Comment by enaggar** [comment]
It worked, thanks!

**Comment by findepi** [comment]
> We could change this to also check for `isVarcharType(type)`, or perhaps remove this conversion entirely, and rely on the caller to pass a `String`.

@electrum please create an issue

**Comment by electrum** [comment]
`VARBINARY` uses `Slice` as the "Java type" during execution, but the assertion framework converts the result to `SqlVarBinary` before comparison. Note that `SqlVarBinary` is also the class that's used to return `VARBINARY` results to the client.
