### ISSUE TITLE
Use tempto QueryAssert in presto-jdbc test

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1809]
Tests of `presto-jdbc` would benefit from using `tempto` there. 
(`tempto` is the library used in product tests)

For example:
```
Set<List<Object>> rows = ImmutableSet.copyOf(readRows(rs));
assertTrue(rows.contains(getTablesRow("information_schema", "tables")));
```

can be replaced with
```
assertThat(QueryResult.forResultSet(rs))                                // io.prestosql.tempto.assertions.QueryAssert#assertThat(QueryResult)
        .contains(getTablesRow("information_schema", "tables"));
```

and `readRows` becomes obsolete.

**Comment by priyankalakhe** [comment]
Hi @findepi - I can work on this, if this is still open.

**Comment by findepi** [comment]
@priyankalakhe thanks, go ahead!

I recommend to start small (e.g. change only few places first), put up a PR to get the feedback early.

**Comment by priyankalakhe** [comment]
Will do - thanks @findepi 

Will get started in the next day or two and send something out early.

**Comment by findepi** [comment]
Superseded by https://github.com/prestosql/presto/issues/4098
