### ISSUE TITLE
Allow configuring HDFS replication factor

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1829]
https://github.com/prestosql/presto/issues/456#issuecomment-472282528

> As for the replication count, I believe you can change this by using the Hive connector `hive.config.resources` property to point at an `hdfs-site.xml` that contains the following property:
> 
> ```xml
> <property> 
>   <name>dfs.replication<name> 
>   <value>2<value> 
> <property>
> ```
> 
> Let us know if this works and we can add a first-class Hive connector configuration property for this (normally users should not need to specify a Hadoop config file).

- Allow configuring HDFS replication factor directly in hive.properties
- Add short documentation entry for the new configuration property

**Comment by sopel39** [comment]
Will HDFS rebalanced data on it's only?

**Comment by rohangarg** [comment]
> Will HDFS rebalanced data on it's own?

From the docs (https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsUserGuide.html#Balancer), it doesn't seem like the HDFS block balancer (across datanodes) is triggered automatically - the user can trigger it via a command line though.
is the concern regarding hotspotting of datanodes?

**Comment by sopel39** [comment]
> is the concern regarding hotspotting of datanodes?

It's also concert about data persistence. No replication means the data might be lost once the node dies.

**Comment by rohangarg** [comment]
> > is the concern regarding hotspotting of datanodes?
> 
> It's also concert about data persistence. No replication means the data might be lost once the node dies.

Yes, if the datanode wasn't decommissioned before shutdown or it is a node failure. Also, the hotspotting of a datanode could maybe increase the chance of failure. A scenario in presto where hotspotting might occur is with colocated HDFS cluster with file replication factor as 1 and a single writer task for large results.

**Comment by agrawalreetika** [comment]
I would like to work on this task.
As per I tried replication factor property works fine when we place it in hive.config.resources file as below:
<property>
      <name>dfs.replication</name>
      <value>2</value>
</property>

As per the given info, we want to make this is as a property in the hive catalog file? Please correct me or add if my understanding is correct?
