### ISSUE TITLE
Is dynamic_filtering not available in the view?

### ISSUE THREAD

**Issue by gaojun2048** [prestosql/presto#1836]
This is  my test case:
table event and table test3 is  hive table.
event_vd is a view with create sql : create view event_vd as select col1 ,col2 from tab1 union all select col1,col2 from tab2.

![image](https://user-images.githubusercontent.com/32193458/67383451-c25ed980-f5c1-11e9-85ee-d353f2cc32d1.png)

**Comment by raunaqmorarka** [comment]
Right now you would see dynamic filtering only if the join in your query is a broadcast join, is that the case here ?

**Comment by findepi** [comment]
You can force broadcast join with `SET SESSION join_distribution_type = 'BROADCAST';`

**Comment by gaojun2048** [comment]
> Right now you would see dynamic filtering only if the join in your query is a broadcast join, is that the case here ?
> You might also want to take a look at the explain plan for your query to verify that dynamic filters are added by optimizer.

Thank you.
I am sure the join type is broadcast.
![image](https://user-images.githubusercontent.com/32193458/67447935-101e2500-f648-11e9-9ead-dc1a6bf03e60.png)

the sql to create view event_hive_vd is like this:
` CREATE VIEW hive.db_benchmarktest.event_hive_vd AS 
 SELECT                                        
   "distinct_id"                               
 , "xwho"                                      
 , "xwhen"                                     
 , "xwhat"                                     
 , "$os"                                       
 , "$utm_campaign_id"                          
 , "$utm_campaign"                             
 , "$utm_medium"                               
 , "$utm_source"                               
 , "$utm_content"                              
 , "$utm_term"                                 
 , "$channel"                                  
 , "$referrer"                                 
 , "$referrer_domain"                          
 , "$traffic_source_type"                      
 , "$search_engine"                            
 , "$search_keyword"                           
 , "$social"                                   
 , "$social_share_from"                        
 , "$scene"                                    
 , "$scene_type"                               
 , "$platform"                                 
 , "$session_id"                               
 , "$url"                                      
 , "$social_media"                             
 , "$url_domain"                               
 , "$track_xwhen"                              
 , "$fingerprint"                              
 , "$campaign_shortlink"                       
 , "$prop_0"                                   
 , "$prop_1"                                   
 , "$prop_2"                                   
 , "$prop_3"                                   
 , "$prop_4"                                   
 , "hrk"                                       
 , "$manufacturer"                             
 , "$os_version"                               
 , "$producttype"                              
 , "$title"                                    
 , "price"                                     
 , "$lib_version"                              
 , "$screen_height"                            
 , "flag"                                      
 , "$screen_width"                             
 , "counts"                                    
 , "$if_first_day"                             
 , "$lib"                                      
 , "$user_agent"                               
 , "$model"                                    
 , "$device_type"                              
 , "$brand"                                    
 , "time"                                      
 , "$app_version"                              
 , "$browser"                                  
 , "$is_login"                                 
 , "$ip"                                       
 , "$network"                                  
 , "$browser_version"                          
 , "$country"                                  
 , "$province"                                 
 , "$city"                                     
 , "sleepreporthotstart_custom2"               
 , "$appclick_custom2"                         
 , "snaillogoad_custom2"                       
 , "ad_info_custom2"                           
 , "sleepadvise_custom2"                       
 , "$append_custom2"                           
 , "challenge_sign_success_custom2"            
 , "$appstart_custom2"                         
 , "tab_dreamtalk_custom2"                     
 , "interstitialad_custom2"                    
 , "bs_custom2"                                
 , "play_custom2"                              
 , "reportpagead_custom2"                      
 , "ad_type_custom2"                           
 , "showreportpage_custom2"                    
 , "httpdns_custom2"                           
 , "app_operation_custom2"                     
 , "showmainpage_custom2"                      
 , "game_register_custom2"                     
 , "appinstall_custom2"                        
 , "es_custom2"                                
 , "challenge_official_d_custom2"              
 , "splash_ad_custom2"                         
 , "enterchallengepage_custom2"                
 , "showreport_custom2"                        
 , "example_dream_play_number_custom2"         
 , "share_custom2"                             
 , "staycommunity_custom2"                     
 , "clickjoinnowbutton_custom2"                
 , "clickreleasebutton_custom2"                
 , "app_crash_custom2"                         
 , "report_custom2"                            
 , "my_info_custom2"                           
 , "report_check_custom2"                      
 , "sendemoji_custom2"                         
 , "showcommunity_custom2"                     
 , "app_start_background_custom2"              
 , "stayshopping_custom2"                      
 , "$signup_custom2"                           
 , "challenge_home_page_custom2"               
 , "challenge_rankinglist_custom2"             
 , "mainpageclick_custom2"                     
 , "challengerecordpage_custom2"               
 , "ring_star_custom2"                         
 , "tab_find_custom2"                          
 , "login_custom2"                             
 , "challengehomepage_custom2"                 
 , "tab_shopping_custom2"                      
 , "mypagerad_custom2"                         
 , "groomclick_custom2"                        
 , "appreceivednotification_custom2"           
 , "my_mywallet_custom2"                       
 , "showminepage_custom2"                      
 , "my_makemoney_custom2"                      
 , "officialshowoff_custom2"                   
 , "delete_talk_custom2"                       
 , "joined_challenge_with_coupon_custom2"      
 , "challenge_page_custom2"                    
 , "sleep_ranklist_custom2"                    
 , "communityad_custom2"                       
 , "healthy_list_custom2"                      
 , "txsms_custom2"                             
 , "createpostsuccess_custom2"                 
 , "example_check_number_custom2"              
 , "buy_custom2"                               
 , "challenge_sign_custom2"                    
 , "click_logo_11_11_number_custom2"           
 , "showcommunitystyle_custom2"                
 , "challenge_custom_join_custom2"             
 , "showshopping_custom2"                      
 , "clockring_custom2"                         
 , "startnighttalkmatch_custom2"               
 , "s2_alarm_setting_custom2"                  
 , "challengepagead_custom2"                   
 , "natural_music_play_custom2"                
 , "challenge_official_u_custom2"              
 , "logoutaccount_custom2"                     
 , "$appchannelmatching_custom2"               
 , "pillow_custom2"                            
 , "sharereport_custom2"                       
 , "s2_a2dp_connection_custom2"                
 , "challenge_custom_custom2"                  
 , "coupon_immediate_use_custom2"              
 , "lullaby_custom2"                           
 , "release_dream_talk_success_custom2"        
 , "join_brand_challenge_custom2"              
 , "get_dadge_custom2"                         
 , "shownighttalkhome_custom2"                 
 , "leavenighttalkpage_custom2"                
 , "dreamtalk_share_custom2"                   
 , "homepagead_custom2"                        
 , "news_custom2"                              
 , "sign_notify_custom2"                       
 , "challenge_vip_cvip_custom2"                
 , "challenge_sleep_custom2"                   
 , "challenge_pay_custom2"                     
 , "challenge_phone_custom2"                   
 , "sleep_remind_shop_custom2"                 
 , "brandchallenge_custom2"                    
 , "inmobi_custom2"                            
 , "add_care_custom2"                          
 , "click_member_custom2"                      
 , "withdraw_bind_phone_number_custom2"        
 , "challenage_share_custom2"                  
 , "apptheme_custom2"                          
 , "battery_describe_custom2"                  
 , "s2_a2dp_ble_connection_custom2"            
 , "sendvoice_custom2"                         
 , "showdetermination_custom2"                 
 , "s2_upgrade_custom2"                        
 , "challenge_invite_custom2"                  
 , "buy_shopping_custom2"                      
 , "challenge_withdraw_custom2"                
 , "pillow_c_custom2"                          
 , "challenge_cvip_custom2"                    
 , "s2_bind_setting_custom2"                   
 , "challenge_plan_custom2"                    
 , "wallet_vip_custom2"                        
 , "add_friend_custom2"                        
 , "nighttalkmatch_custom2"                    
 , "nighttalkduration_custom2"                 
 , "my_info_dreamtalk_custom2"                 
 , "health_article_click_custom2"              
 , "other_app_recommend_custom2"               
 , "nighttalkreport_custom2"                   
 , "tobevip_custom2"                           
 , "banner_click_custom2"                      
 , "challenge_home_cvip_custom2"               
 , "operate_custom2"                           
 , "challenge_result_custom2"                  
 , "challenge_home_custom2"                    
 , "enternighttalk_custom2"                    
 , "s2_setting_switch_custom2"                 
 , "sleep_not_detection_custom2"               
 , "signsuccessshare_custom2"                  
 , "submit_payment_with_coupon_custom2"        
 , "make_custom_challenge_custom2"             
 , "release_dream_talk_custom2"                
 , "appnobackground_custom2"                   
 , "$appviewscreen_custom2"                    
 , "s2_receive_sleep_record_custom2"           
 , "ad_click_custom2"                          
 , "topiccard_custom2"                         
 , "ds"                                        
 FROM                                          
   hive.db_benchmarktest.event                 
 UNION ALL SELECT                              
   "distinct_id"                               
 , "xwho"                                      
 , "xwhen"                                     
 , "xwhat"                                     
 , "$os"                                       
 , "$utm_campaign_id"                          
 , "$utm_campaign"                             
 , "$utm_medium"                               
 , "$utm_source"                               
 , "$utm_content"                              
 , "$utm_term"                                 
 , "$channel"                                  
 , "$referrer"                                 
 , "$referrer_domain"                          
 , "$traffic_source_type"                      
 , "$search_engine"                            
 , "$search_keyword"                           
 , "$social"                                   
 , "$social_share_from"                        
 , "$scene"                                    
 , "$scene_type"                               
 , "$platform"                                 
 , "$session_id"                               
 , "$url"                                      
 , "$social_media"                             
 , "$url_domain"                               
 , "$track_xwhen"                              
 , "$fingerprint"                              
 , "$campaign_shortlink"                       
 , "$prop_0"                                   
 , "$prop_1"                                   
 , "$prop_2"                                   
 , "$prop_3"                                   
 , "$prop_4"                                   
 , "hrk"                                       
 , "$manufacturer"                             
 , "$os_version"                               
 , "$producttype"                              
 , "$title"                                    
 , "price"                                     
 , "$lib_version"                              
 , "$screen_height"                            
 , "flag"                                      
 , "$screen_width"                             
 , "counts"                                    
 , "$if_first_day"                             
 , "$lib"                                      
 , "$user_agent"                               
 , "$model"                                    
 , "$device_type"                              
 , "$brand"                                    
 , "time"                                      
 , "$app_version"                              
 , "$browser"                                  
 , "$is_login"                                 
 , "$ip"                                       
 , "$network"                                  
 , "$browser_version"                          
 , "$country"                                  
 , "$province"                                 
 , "$city"                                     
 , "sleepreporthotstart_custom2"               
 , "$appclick_custom2"                         
 , "snaillogoad_custom2"                       
 , "ad_info_custom2"                           
 , "sleepadvise_custom2"                       
 , "$append_custom2"                           
 , "challenge_sign_success_custom2"            
 , "$appstart_custom2"                         
 , "tab_dreamtalk_custom2"                     
 , "interstitialad_custom2"                    
 , "bs_custom2"                                
 , "play_custom2"                              
 , "reportpagead_custom2"                      
 , "ad_type_custom2"                           
 , "showreportpage_custom2"                    
 , "httpdns_custom2"                           
 , "app_operation_custom2"                     
 , "showmainpage_custom2"                      
 , "game_register_custom2"                     
 , "appinstall_custom2"                        
 , "es_custom2"                                
 , "challenge_official_d_custom2"              
 , "splash_ad_custom2"                         
 , "enterchallengepage_custom2"                
 , "showreport_custom2"                        
 , "example_dream_play_number_custom2"         
 , "share_custom2"                             
 , "staycommunity_custom2"                     
 , "clickjoinnowbutton_custom2"                
 , "clickreleasebutton_custom2"                
 , "app_crash_custom2"                         
 , "report_custom2"                            
 , "my_info_custom2"                           
 , "report_check_custom2"                      
 , "sendemoji_custom2"                         
 , "showcommunity_custom2"                     
 , "app_start_background_custom2"              
 , "stayshopping_custom2"                      
 , "$signup_custom2"                           
 , "challenge_home_page_custom2"               
 , "challenge_rankinglist_custom2"             
 , "mainpageclick_custom2"                     
 , "challengerecordpage_custom2"               
 , "ring_star_custom2"                         
 , "tab_find_custom2"                          
 , "login_custom2"                             
 , "challengehomepage_custom2"                 
 , "tab_shopping_custom2"                      
 , "mypagerad_custom2"                         
 , "groomclick_custom2"                        
 , "appreceivednotification_custom2"           
 , "my_mywallet_custom2"                       
 , "showminepage_custom2"                      
 , "my_makemoney_custom2"                      
 , "officialshowoff_custom2"                   
 , "delete_talk_custom2"                       
 , "joined_challenge_with_coupon_custom2"      
 , "challenge_page_custom2"                    
 , "sleep_ranklist_custom2"                    
 , "communityad_custom2"                       
 , "healthy_list_custom2"                      
 , "txsms_custom2"                             
 , "createpostsuccess_custom2"                 
 , "example_check_number_custom2"              
 , "buy_custom2"                               
 , "challenge_sign_custom2"                    
 , "click_logo_11_11_number_custom2"           
 , "showcommunitystyle_custom2"                
 , "challenge_custom_join_custom2"             
 , "showshopping_custom2"                      
 , "clockring_custom2"                         
 , "startnighttalkmatch_custom2"               
 , "s2_alarm_setting_custom2"                  
 , "challengepagead_custom2"                   
 , "natural_music_play_custom2"                
 , "challenge_official_u_custom2"              
 , "logoutaccount_custom2"                     
 , "$appchannelmatching_custom2"               
 , "pillow_custom2"                            
 , "sharereport_custom2"                       
 , "s2_a2dp_connection_custom2"                
 , "challenge_custom_custom2"                  
 , "coupon_immediate_use_custom2"              
 , "lullaby_custom2"                           
 , "release_dream_talk_success_custom2"        
 , "join_brand_challenge_custom2"              
 , "get_dadge_custom2"                         
 , "shownighttalkhome_custom2"                 
 , "leavenighttalkpage_custom2"                
 , "dreamtalk_share_custom2"                   
 , "homepagead_custom2"                        
 , "news_custom2"                              
 , "sign_notify_custom2"                       
 , "challenge_vip_cvip_custom2"                
 , "challenge_sleep_custom2"                   
 , "challenge_pay_custom2"                     
 , "challenge_phone_custom2"                   
 , "sleep_remind_shop_custom2"                 
 , "brandchallenge_custom2"                    
 , "inmobi_custom2"                            
 , "add_care_custom2"                          
 , "click_member_custom2"                      
 , "withdraw_bind_phone_number_custom2"        
 , "challenage_share_custom2"                  
 , "apptheme_custom2"                          
 , "battery_describe_custom2"                  
 , "s2_a2dp_ble_connection_custom2"            
 , "sendvoice_custom2"                         
 , "showdetermination_custom2"                 
 , "s2_upgrade_custom2"                        
 , "challenge_invite_custom2"                  
 , "buy_shopping_custom2"                      
 , "challenge_withdraw_custom2"                
 , "pillow_c_custom2"                          
 , "challenge_cvip_custom2"                    
 , "s2_bind_setting_custom2"                   
 , "challenge_plan_custom2"                    
 , "wallet_vip_custom2"                        
 , "add_friend_custom2"                        
 , "nighttalkmatch_custom2"                    
 , "nighttalkduration_custom2"                 
 , "my_info_dreamtalk_custom2"                 
 , "health_article_click_custom2"              
 , "other_app_recommend_custom2"               
 , "nighttalkreport_custom2"                   
 , "tobevip_custom2"                           
 , "banner_click_custom2"                      
 , "challenge_home_cvip_custom2"               
 , "operate_custom2"                           
 , "challenge_result_custom2"                  
 , "challenge_home_custom2"                    
 , "enternighttalk_custom2"                    
 , "s2_setting_switch_custom2"                 
 , "sleep_not_detection_custom2"               
 , "signsuccessshare_custom2"                  
 , "submit_payment_with_coupon_custom2"        
 , "make_custom_challenge_custom2"             
 , "release_dream_talk_custom2"                
 , "appnobackground_custom2"                   
 , "$appviewscreen_custom2"                    
 , "s2_receive_sleep_record_custom2"           
 , "ad_click_custom2"                          
 , "topiccard_custom2"                         
 , "ds"                                        
 FROM                                          
   hive.db_benchmarktest.event_empty`

table hive.db_benchmarktest.event_empty is an empty table.

the explain plan for the table query is :
SQL: explain analyze select count(1) from event a inner join test_3 b on a.distinct_id=b.distinct_id where ds='20190501'

explain plan:
![image](https://user-images.githubusercontent.com/32193458/67449540-119e1c00-f64d-11e9-8a24-168177542bdf.png)

the explain plan for the view query is:
SQL:explain analyze select count(1) from event_hive_vd a inner join test_3 b on a.distinct_id=b.distinct_id where ds='20190501'

explain plan:
![image](https://user-images.githubusercontent.com/32193458/67449599-46aa6e80-f64d-11e9-80b4-142caf8e9339.png)
![image](https://user-images.githubusercontent.com/32193458/67449611-5033d680-f64d-11e9-86b8-d4d3b4483d7b.png)

It seems that if you use view, dynamicFilterAssignments does not work in the source fragment.

**Comment by raunaqmorarka** [comment]
I believe the optimizer part of adding dynamic filters to the query plan has worked correctly. In the second case, dynamic filter function is present in the ScanFilterProject on table db_benchmarktest.event in Fragment 2.
My understanding is that in the current node local implementation, the table scan on the probe side needs to be part of the same fragment or stage as the inner join for dynamic filtering to kick in. That doesn't seem to be the case here.
@vromanv @sopel39 wdyt ?

**Comment by gaojun2048** [comment]
I guess the problem caused by union all. I create a view hive.db_benchmarktest.event_hive_vd_not_unionall ,  event_hive_vd_not_unionall is not use union all and the create sql is:
` CREATE VIEW hive.db_benchmarktest.event_hive_vd_not_unionall AS 
 SELECT                                        
   "distinct_id"                               
 , "xwho"                                      
 , "xwhen"                                     
 , "xwhat"                                     
 , "$os"                                       
 , "$utm_campaign_id"                          
 , "$utm_campaign"                             
 , "$utm_medium"                               
 , "$utm_source"                               
 , "$utm_content"                              
 , "$utm_term"                                 
 , "$channel"                                  
 , "$referrer"                                 
 , "$referrer_domain"                          
 , "$traffic_source_type"                      
 , "$search_engine"                            
 , "$search_keyword"                           
 , "$social"                                   
 , "$social_share_from"                        
 , "$scene"                                    
 , "$scene_type"                               
 , "$platform"                                 
 , "$session_id"                               
 , "$url"                                      
 , "$social_media"                             
 , "$url_domain"                               
 , "$track_xwhen"                              
 , "$fingerprint"                              
 , "$campaign_shortlink"                       
 , "$prop_0"                                   
 , "$prop_1"                                   
 , "$prop_2"                                   
 , "$prop_3"                                   
 , "$prop_4"                                   
 , "hrk"                                       
 , "$manufacturer"                             
 , "$os_version"                               
 , "$producttype"                              
 , "$title"                                    
 , "price"                                     
 , "$lib_version"                              
 , "$screen_height"                            
 , "flag"                                      
 , "$screen_width"                             
 , "counts"                                    
 , "$if_first_day"                             
 , "$lib"                                      
 , "$user_agent"                               
 , "$model"                                    
 , "$device_type"                              
 , "$brand"                                    
 , "time"                                      
 , "$app_version"                              
 , "$browser"                                  
 , "$is_login"                                 
 , "$ip"                                       
 , "$network"                                  
 , "$browser_version"                          
 , "$country"                                  
 , "$province"                                 
 , "$city"                                     
 , "sleepreporthotstart_custom2"               
 , "$appclick_custom2"                         
 , "snaillogoad_custom2"                       
 , "ad_info_custom2"                           
 , "sleepadvise_custom2"                       
 , "$append_custom2"                           
 , "challenge_sign_success_custom2"            
 , "$appstart_custom2"                         
 , "tab_dreamtalk_custom2"                     
 , "interstitialad_custom2"                    
 , "bs_custom2"                                
 , "play_custom2"                              
 , "reportpagead_custom2"                      
 , "ad_type_custom2"                           
 , "showreportpage_custom2"                    
 , "httpdns_custom2"                           
 , "app_operation_custom2"                     
 , "showmainpage_custom2"                      
 , "game_register_custom2"                     
 , "appinstall_custom2"                        
 , "es_custom2"                                
 , "challenge_official_d_custom2"              
 , "splash_ad_custom2"                         
 , "enterchallengepage_custom2"                
 , "showreport_custom2"                        
 , "example_dream_play_number_custom2"         
 , "share_custom2"                             
 , "staycommunity_custom2"                     
 , "clickjoinnowbutton_custom2"                
 , "clickreleasebutton_custom2"                
 , "app_crash_custom2"                         
 , "report_custom2"                            
 , "my_info_custom2"                           
 , "report_check_custom2"                      
 , "sendemoji_custom2"                         
 , "showcommunity_custom2"                     
 , "app_start_background_custom2"              
 , "stayshopping_custom2"                      
 , "$signup_custom2"                           
 , "challenge_home_page_custom2"               
 , "challenge_rankinglist_custom2"             
 , "mainpageclick_custom2"                     
 , "challengerecordpage_custom2"               
 , "ring_star_custom2"                         
 , "tab_find_custom2"                          
 , "login_custom2"                             
 , "challengehomepage_custom2"                 
 , "tab_shopping_custom2"                      
 , "mypagerad_custom2"                         
 , "groomclick_custom2"                        
 , "appreceivednotification_custom2"           
 , "my_mywallet_custom2"                       
 , "showminepage_custom2"                      
 , "my_makemoney_custom2"                      
 , "officialshowoff_custom2"                   
 , "delete_talk_custom2"                       
 , "joined_challenge_with_coupon_custom2"      
 , "challenge_page_custom2"                    
 , "sleep_ranklist_custom2"                    
 , "communityad_custom2"                       
 , "healthy_list_custom2"                      
 , "txsms_custom2"                             
 , "createpostsuccess_custom2"                 
 , "example_check_number_custom2"              
 , "buy_custom2"                               
 , "challenge_sign_custom2"                    
 , "click_logo_11_11_number_custom2"           
 , "showcommunitystyle_custom2"                
 , "challenge_custom_join_custom2"             
 , "showshopping_custom2"                      
 , "clockring_custom2"                         
 , "startnighttalkmatch_custom2"               
 , "s2_alarm_setting_custom2"                  
 , "challengepagead_custom2"                   
 , "natural_music_play_custom2"                
 , "challenge_official_u_custom2"              
 , "logoutaccount_custom2"                     
 , "$appchannelmatching_custom2"               
 , "pillow_custom2"                            
 , "sharereport_custom2"                       
 , "s2_a2dp_connection_custom2"                
 , "challenge_custom_custom2"                  
 , "coupon_immediate_use_custom2"              
 , "lullaby_custom2"                           
 , "release_dream_talk_success_custom2"        
 , "join_brand_challenge_custom2"              
 , "get_dadge_custom2"                         
 , "shownighttalkhome_custom2"                 
 , "leavenighttalkpage_custom2"                
 , "dreamtalk_share_custom2"                   
 , "homepagead_custom2"                        
 , "news_custom2"                              
 , "sign_notify_custom2"                       
 , "challenge_vip_cvip_custom2"                
 , "challenge_sleep_custom2"                   
 , "challenge_pay_custom2"                     
 , "challenge_phone_custom2"                   
 , "sleep_remind_shop_custom2"                 
 , "brandchallenge_custom2"                    
 , "inmobi_custom2"                            
 , "add_care_custom2"                          
 , "click_member_custom2"                      
 , "withdraw_bind_phone_number_custom2"        
 , "challenage_share_custom2"                  
 , "apptheme_custom2"                          
 , "battery_describe_custom2"                  
 , "s2_a2dp_ble_connection_custom2"            
 , "sendvoice_custom2"                         
 , "showdetermination_custom2"                 
 , "s2_upgrade_custom2"                        
 , "challenge_invite_custom2"                  
 , "buy_shopping_custom2"                      
 , "challenge_withdraw_custom2"                
 , "pillow_c_custom2"                          
 , "challenge_cvip_custom2"                    
 , "s2_bind_setting_custom2"                   
 , "challenge_plan_custom2"                    
 , "wallet_vip_custom2"                        
 , "add_friend_custom2"                        
 , "nighttalkmatch_custom2"                    
 , "nighttalkduration_custom2"                 
 , "my_info_dreamtalk_custom2"                 
 , "health_article_click_custom2"              
 , "other_app_recommend_custom2"               
 , "nighttalkreport_custom2"                   
 , "tobevip_custom2"                           
 , "banner_click_custom2"                      
 , "challenge_home_cvip_custom2"               
 , "operate_custom2"                           
 , "challenge_result_custom2"                  
 , "challenge_home_custom2"                    
 , "enternighttalk_custom2"                    
 , "s2_setting_switch_custom2"                 
 , "sleep_not_detection_custom2"               
 , "signsuccessshare_custom2"                  
 , "submit_payment_with_coupon_custom2"        
 , "make_custom_challenge_custom2"             
 , "release_dream_talk_custom2"                
 , "appnobackground_custom2"                   
 , "$appviewscreen_custom2"                    
 , "s2_receive_sleep_record_custom2"           
 , "ad_click_custom2"                          
 , "topiccard_custom2"                         
 , "ds"                                        
 FROM                                          
   hive.db_benchmarktest.event                 
 `

I run the query sql:
`explain analyze select count(1) from event_hive_vd_not_unionall a inner join test_3 b on a.distinct_id=b.distinct_id where ds='20190501';
`

I found the explain plan is same as two table inner join.
the explain plan is:
![image](https://user-images.githubusercontent.com/32193458/67457265-cc3a1880-f665-11e9-8859-d76578b073de.png)
![image](https://user-images.githubusercontent.com/32193458/67457288-df4ce880-f665-11e9-97a6-0dc1f5cbd331.png)

**Comment by sopel39** [comment]
> My understanding is that in the current node local implementation, the table scan on the probe side needs to be part of the same fragment or stage as the inner join for dynamic filtering to kick in. That doesn't seem to be the case here.

Yes, join must be in same stage as table scan. Also there are limits to how big the build side can be. Additionally, applying dynamic filter might not always help, because it does filter on stripes (in ORC case). If stripe contains at least on row that matches dynamic filter, then the whole stripe will be read.
