### ISSUE TITLE
Add support for columns property to ANALYZE statement

### ISSUE THREAD

**Issue by ptkool** [prestosql/presto#1884]
The ability to specify the columns for which statistics should be collected in an ANALYZE statement would be extremely beneficial in reducing overall processing time and resources.

The suggested syntax is given below.

`ANALYZE schema.table WITH (columns = ARRAY['column1', 'column2', ...])`

**Comment by ptkool** [comment]
https://github.com/prestosql/presto/compare/master...Shopify:analyze_with_columns?expand=1

**Comment by findepi** [comment]
@ptkool let's talk on #dev (https://prestosql.io/slack.html) about this.
