### ISSUE TITLE
Unit test for end-to-end delivery of extra credentials

### ISSUE THREAD

**Issue by luohao** [prestosql/presto#189]
Need to add unit tests to verify the end-to-end delivery of extra credentials (from client to connector) in case there are future changes that break the path (e.g., changes to `Session`, `Identity`, `ConnectorIdentity` or `TaskUpdateRequest`).

**Comment by electrum** [comment]
I was thinking we could add a test-only system table that would return the credentials as an easy way to test this.

**Comment by luohao** [comment]
I am working on a `TestHiveExtraCredential` that creates a `DistributedQueryRunner` with a special `DynamicConfigurationProvider` that verifies the extra credential in `hdfsContext.connectoIdentity.extraCredentials`. `DistributedQueryRunner::execute` takes a `Session` object with the credentials in `Identity` and sends it to the testing Presto cluster. This makes sure the credentials are delivered all the way to Hive connector, which has a bit more coverage.

**Comment by luohao** [comment]
Explored both ways of verifying `extraCredentials` at connector level:
- verify extra credentials in `HdfsContext` (99f112c7e12f00cd8fc3f1dcfdfdc01fbe37b00d): need fair amount of changes to `HivePlugin` and `HiveConnectorFactory`, and it looks nasty which I don't like.
- verify extra credentials through a testing `SystemTable`(#199): it looks cleaner and more elegant. But it does not cover code inside Hive connector.

I pick the second approach and submitted #199.
