### ISSUE TITLE
A bot to notify pull request author when tests fail

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1900]
Currently when a PR fails on Travis, the author of PR is not notified and needs to check status of their PRs manually.

**Comment by findepi** [comment]
According to https://github.com/travis-ci/travis-ci/issues/8661 there is no build-in solution. (cc @BanzaiMan)
And there is @bluzi's app for this https://github.com/bluzi/travis-buddy

**Comment by findepi** [comment]
travis-buddy seems to work for `travis-ci.org` only https://github.com/bluzi/travis-buddy/issues/146
(i didn't test this, but the source suggests so)

**Comment by bluzi** [comment]
@findepi That makes a lot of sense, unfortunately I'm on vacation at the moment and it will be a while until I'll be able to have a look.

**Comment by findepi** [comment]
Covered by Github actions.
