### ISSUE TITLE
Add Slack badge to documentation

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#1944]
As we talked offline, let's add Slack badge to documentation so that everyone can join the community easily. I created some samples. 

1. [![Join Slack](https://img.shields.io/badge/slack-ask%20for%20help-blue.svg?logo=slack)](https://prestosql.io/slack.html)
2. [![Join Slack](https://img.shields.io/badge/slack-ask%20for%20help-blueviolet.svg?logo=slack)](https://prestosql.io/slack.html)
3. [![Join Slack](https://img.shields.io/badge/slack-ask%20for%20help-brightgreen.svg?logo=slack)](https://prestosql.io/slack.html)
4. [![Join Slack](https://img.shields.io/badge/slack-ask%20for%20help-blue.svg?logo=slack&color=5a92f5)](https://prestosql.io/slack.html)
4. [![Join Slack](https://img.shields.io/badge/slack-ask%20for%20help-blue.svg?logo=slack&color=1FE3FF)](https://prestosql.io/slack.html)

References
- https://shields.io/
- https://github.com/prestosql/presto/blob/master/presto-docs/src/main/sphinx/themes/presto/static/presto.css_t

**Comment by electrum** [comment]
Thanks for creating these examples. Done in [`presto-docs.sh`](https://github.com/prestosql/release-scripts/blob/master/presto-docs.sh)
