### ISSUE TITLE
TestDistributedSpilledQueries tests are flaky

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#1951]
Tests hang forever, some old build: https://travis-ci.com/prestosql/presto/jobs/249267817

**Comment by sopel39** [comment]
duplicate of https://github.com/prestosql/presto/issues/1951

**Comment by sopel39** [comment]
Similar to https://github.com/prestosql/presto/issues/1337

**Comment by findepi** [comment]
It hasn't been observed for a while. Please reopen with a new link & output transcript if you see this again.
