### ISSUE TITLE
Please add release date to release log

### ISSUE THREAD

**Issue by OmerJog** [prestosql/presto#1960]
Example:
https://prestosql.io/docs/current/release/release-322.html

it's impossible to know when 322 was released

**Comment by tooptoop4** [comment]
https://repo1.maven.org/maven2/io/prestosql/presto-server/ shows release dates

**Comment by findepi** [comment]
Also GH knows that -- https://github.com/prestosql/presto/releases/tag/322

But i agree that having date on the release notes page directly would be much nicer.
Challenge is that the RNs are a static markdown page, so we need to figure out how to inject a date there.

**Comment by OmerJog** [comment]
Thanks.. I think it should be added in the docs..
Most people read the docs not the repo itself

**Comment by martint** [comment]
Done! We've started adding dates: https://prestosql.io/docs/current/release.html
