### ISSUE TITLE
Allow product test debugging with a command line flag

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1990]
This line is quite frequently edited (locally).
https://github.com/prestosql/presto/blob/46354be811db9a61dbc338df983297c6c0285535/presto-product-tests/conf/presto/etc/jvm.config#L23

provide a command line option (switch or env variable) providing same effect without making the workspace dirty.

The flag could additionally control 
https://github.com/prestosql/presto/blob/2166560fcec39ae05c644a8bcdc04acd7e67730c/presto-product-tests/conf/docker/files/run-tempto.sh#L22

but that's not as important.

**Comment by wendigo** [comment]
I believe that this is already implemented @findepi

**Comment by findepi** [comment]
Mostly -- yes. Let me close this.
