### ISSUE TITLE
filterNode with predicate value of "False" in the logical plan

### ISSUE THREAD

**Issue by RahelehK** [prestosql/presto#2000]
Execution of TPCDS q04 will result in a filterNode in the logical plan which has a predicate value of "false" as seen in below snapshot: (mysql connector) 
![image](https://user-images.githubusercontent.com/45022919/68603511-6bd51480-0476-11ea-8417-863e28d6e3c8.png)

Please note that this issue is also reproducible with builtin tpcds connector as well. 
Furthermore, the predicate is also retained in the final plan as can be seen below:
![image](https://user-images.githubusercontent.com/45022919/68603559-8909e300-0476-11ea-8f7a-83fafcd8e92a.png)

**Comment by findepi** [comment]
@RahelehK thanks for reporting this.
Obviously, such a predicate should be "eliminated" (replaced with empty `ValuesNode`).

**Comment by findepi** [comment]
Fixed, thanks.
