### ISSUE TITLE
Cannot query a hive avro table with nested levels Presto

### ISSUE THREAD

**Issue by spachari** [prestosql/presto#2021]
When I try to query the table I get this exception.

```
Caused by: org.apache.hadoop.hive.serde2.SerDeException
Number of levels of nesting supported for LazySimpleSerde is 7 Unable to work with level 11. Use hive.serialization.extend.nesting.levels serde property for tables using LazySimpleSerde.
org.apache.hadoop.hive.serde2.lazy.LazyUtils.getSeparator(LazyUtils.java:388)
org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:352)
org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:349)
org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:349)
org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:349)
org.apache.hadoop.hive.serde2.lazy.LazyFactory.createLazyObjectInspector(LazyFactory.java:349)
```
I understand this error and we do

```
set hive.serialization.extend.nesting.levels=true;
```
for hive.

 Please tell me what is the equivalent of the above statement in presto to read the nested avro table data?

**Comment by findepi** [comment]
@spachari thanks for your report.
I couldn't reproduce the problem in [Presto 325](https://prestosql.io/download.html). Can you try to reproduce it on your side?

**Comment by findepi** [comment]
@spachari is your table Avro table or something else?

**Comment by spachari** [comment]
@findepi , it is avro table and the nesting levels are 11. I will try with version 325.

**Comment by spachari** [comment]
this is in presto version 0.193

**Comment by findepi** [comment]
I couldn't reproduce this for Avro in 325, but i could for sequencefile.

**Comment by findepi** [comment]
@spachari can you add `hive.serialization.extend.nesting.levels=true` and `hive.serialization.extend.additional.nesting.levels=true` as TBLPROPERTIES (in Hive) to your table and check whether it solves your problem?

**Comment by spachari** [comment]
@findepi - thanks for your help. We can close this issue. You are correct. The version we are using was older one. I created an EMR with a later version of presto and the query works fine

**Comment by spachari** [comment]
I am closing this issue.

**Comment by spachari** [comment]
I was using an older version of presto
