### ISSUE TITLE
Kudu connector cannot delete rows by non-key columns!

### ISSUE THREAD

**Issue by Crossoverrr** [prestosql/presto#2025]
I found a question that I cannot delete rows by non-key columns,
My sql is like :
`delete from event_v1 where xwho='xxxxx';`
xwho is not a key column in kudu, then this SQL can delete nothing.
but if we change SQL to :
`delete from event_v1 where xwhen=xxxxxxx;`
xwhen is a key column in this kudu table, then this SQL can delete rows successful.
![image](https://user-images.githubusercontent.com/33892550/68933329-6279de00-07cf-11ea-80cf-b65a39af82d6.png)
And I checked the code, I found where the problem is. If I change these codes below in KuduRecordSet: line 72 and 73 to line 74, the problem will be resolved. So why kudu connector need to change the index in fieldMapping from ordinalPosition to its index in columns?
![image](https://user-images.githubusercontent.com/33892550/68933892-90abed80-07d0-11ea-8f9c-fb66480b0443.png)

**Comment by kokosing** [comment]
@MartinWeindel Do you have a context about this?

**Comment by Crossoverrr** [comment]
I'm using prestosql-322.
When I commit a delete sql, kudu connector will get all the columns' value of a row, but the columns object here at line 65 of KuduRecordSet.java only contains columns the SQL desired, so there will be a mismatch when KuduRecordCursorWithVirtualRowId using this fieldMapping object to get the index of a column. The connector will get the wrong column value, so it cannot delete the rows we specified by where clause.  I have debugged the code, I think this is the problem.

**Comment by MartinWeindel** [comment]
I think this was necessary to exclude the VirtualRowId field from the result.
If you apply the suggested change, I would expect that some test fails.

**Comment by MartinWeindel** [comment]
@Crossoverrr You are probably right.

**Comment by Crossoverrr** [comment]
> I think this was necessary to exclude the VirtualRowId field from the result.
> If you apply the suggested change, I would expect that some test fails.

Totolly agree with you !
I just don't know why they do it like this.  :)

**Comment by Crossoverrr** [comment]
I have test some simple select and delete operation, they are good. 
Let me do some further test later. 
thank you for your help, thank you very much!

**Comment by ebyhr** [comment]
@Crossoverrr Thanks for reporting this issue. This should be fixed by https://github.com/prestosql/presto/pull/2263. If you face the same issue with the next version 327 that will be released this week, please reopen this issue.

**Comment by Crossoverrr** [comment]
Glad to see this issue has been resolved! :)
