### ISSUE TITLE
Kudu connector create schema error

### ISSUE THREAD

**Issue by Crossoverrr** [prestosql/presto#2070]
When I create a schema using sql below:
`CREATE SCHEMA IF NOT EXISTS ckudu.db_wupengtest_v2;`
It shows error like:
`Query 20191120_080918_00027_6cfg8 failed: Primary key column schema is not set`
So I checked "$schemas" table, It has 2 columns which are all primary key column, 
but the code only upsert one column, I think this may be a problem of kudu connector, 
just need help!
here are some pictures:
![image](https://user-images.githubusercontent.com/33892550/69221164-98dda180-0bb1-11ea-928d-7ee3c658add3.png)
![image](https://user-images.githubusercontent.com/33892550/69221197-aa26ae00-0bb1-11ea-869a-cc270c5a1b80.png)

**Comment by Crossoverrr** [comment]
I checked the code how you create a kudu "$schemas" table, actually there is only one schema column created.
So, where is column tenant  coming from ? Table "$schemas" was not created by me.

**Comment by kokosing** [comment]
CC @MartinWeindel

**Comment by MartinWeindel** [comment]
the tenant column is legacy from the original connector, which allows to use one kudu database with multiple presto installations.

**Comment by Crossoverrr** [comment]
So is that means column tenant is truly exist in table "$schemas"?
If that's true I have to set its value when creating schema using kudu connector.

**Comment by Crossoverrr** [comment]
Thank you for your help! Let me do some further test, then I will close this issue.
