### ISSUE TITLE
Document unicode varchar literals

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2113]
Document `U&'...'` varchar literals.

* https://github.com/prestosql/presto/blob/7441e0d54cf797e5f312975fc254562284efe40c/presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4#L748-L749
* https://github.com/prestosql/presto/blob/7441e0d54cf797e5f312975fc254562284efe40c/presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java#L1766
* spec

**Comment by mosabua** [comment]
I think this should go somewhere in https://prestosql.io/docs/current/language.html 

We probably need some sort of introductory section about SQL there and then go into the details and there we could add the info about unicode usage. Wdyt @findepi

**Comment by electrum** [comment]
Agreed. For now, we can add it to the string section on that page, since that’s where we put the input syntax for other data types.

**Comment by electrum** [comment]
We also need to document binary literals.

**Comment by mosabua** [comment]
Got some info about binary literals I can look at while I am working on this ?

**Comment by electrum** [comment]
The syntax for binary literals looks like
```sql
X'abcdef1234567890ABCDEF'
```
That's `X'...'` where the value is a even number of hexadecimal digits.

**Comment by mosabua** [comment]
Created https://github.com/prestosql/presto/pull/2139 and https://github.com/prestosql/presto/pull/2140 for SQL chapetrs .. now will do these docs to tie it up.

**Comment by mosabua** [comment]
https://github.com/prestosql/presto/pull/2142

**Comment by mosabua** [comment]
Ready for review
