### ISSUE TITLE
Presto can't filter bigint/smallint/tinyint type in tables created by impala with parquet format

### ISSUE THREAD

**Issue by heyfly0** [prestosql/presto#2166]
Hello , I am a new presto user.
Presto can't filter bigint/smallint/tinyint (but int type is work.) type in tables created by impala with parquet format.
But When i create same parquet table using hive , it works fine.

My Versions is this.
- Presto version 320
- Impala(CDH) version 2.11.0-cdh5.14.2
- Hive(CDH) hive-1.1.0-cdh5.14.2
- Parquet compression format: SNAPPY

Ways to reproduce:
**Step 1**
``` code
Create a table in Impala with parquet format, insert some values : 
create table tmp.impala_table(
uid bigint
)
stored as parquet;
insert into tmp.impala_table values (1),(2),(3);
```

**Step 2**
Query the table with presto:
Select all , return all rows:
```code
presto:hive> select * from tmp.impala_table;
    uid
-----------
         1
         2
         3
(3 rows)

```
I can't get result when i  Run select with condition ( '=' , '>' ):
```code
presto:hive> select * from tmp.impala_table where uid = 2;
 uid
-----
(0 rows)
presto:hive> select * from tmp.impala_table where uid > 2;
 uid
-----
(0 rows)
```
but running select with '<' condition is work.:
```code
presto:hive> select * from tmp.impala_table where uid  < 2;
    uid
-----------
         1
(1 rows)
```

hive connector configuration:
```code
connector.name=hive-hadoop2
hive.metastore.uri=thrift://host1:9083,thrift://host2:9083
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/_HOST@FDS.HADOOP
hive.metastore.client.principal=myprinc@MY.HADOOP
hive.metastore.client.keytab=/presto/etc/myprinc.keytab
hive.hdfs.impersonation.enabled=true
hive.non-managed-table-writes-enabled=true
hive.config.resources=/presto/etc/hadoop/hdfs-site.xml
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.principal=myprinc@MY.HADOOP
hive.hdfs.presto.keytab=/presto/etc/myprinc.keytab
```

**Comment by electrum** [comment]
Thanks for reporting this issue and providing reproduction steps. It’s probably an issue with the statistics in the file. Would you be able to attach the Parquet file from the reproduction to this issue?

Please also join us on Slack: https://prestosql.io/slack.html

**Comment by heyfly0** [comment]
@electrum Thank you for your quick answer.
This is the parquet file.

[8e4f4c31b41524fe-250332f300000000_350635556_data.0.parq.zip](https://github.com/prestosql/presto/files/3909917/8e4f4c31b41524fe-250332f300000000_350635556_data.0.parq.zip)

**Comment by ryanrupp** [comment]
This looks to be indirectly fixed by the change here - https://github.com/prestosql/presto/commit/9492f60bd1ac7e69e5836779ecaac750095db5ee#diff-d291244bef4e95142198b095d80bde5aR211 - going through `ParquetMetadataConverter` it handles v2 min/max stats correctly. Before this change, what was happening was handling the min/max stats got in a bad state where it thought the stats were set but internally it was just defaulting longs to 0 so min = 0, max = 0 that's why `<` queries were working.

The stats in the file themselves look correct though, just using the v2 format I believe:

```
creator:     impala version 2.11.0-cdh5.14.2 (build ed85dce709da9557aeb28be89e8044947708876c) 

file schema: schema 
--------------------------------------------------------------------------------
uid:         OPTIONAL INT64 R:0 D:1

row group 1: RC:3 TS:65 OFFSET:4 
--------------------------------------------------------------------------------
uid:          INT64 SNAPPY DO:4 FPO:40 SZ:65/64/0.98 VC:3 ENC:PLAIN_DICTIONARY,RLE ST:[min: 1, max: 3, num_nulls: 0]
```

Try the latest version of PrestoSQL 326 which should have this fix

**Comment by heyfly0** [comment]
@ryanrupp Hello.
I upgraded presto to 326 version. And Then this bug was solved.
Thank you for your answer.
