### ISSUE TITLE
Make stats update concurrent

### ISSUE THREAD

**Issue by JamesRTaylor** [prestosql/presto#2170]
Setting hive.collect-column-statistics-on-write = false causes queries to be stuck in the finishing state due to synchronization in updatePartitionStatistics. Setting this property is necessary with large number of concurrent queries (10+) and large number of partitions (1500 + ). 

Stats update could be improve by:
- making it concurrent of possible
- avoid fetching/updating column stats if these are not being updated

An alternate stop-gap approach would be to introduce a property that disables stats update completely.

For more detail, see https://prestosql.slack.com/archives/CGB0QHWSW/p1574880608345400

**Comment by findepi** [comment]
> causes queries to be stuck in the finishing state due to synchronization in updatePartitionStatistics

@JamesRTaylor did you see https://github.com/prestosql/presto/pull/2154?

**Comment by JamesRTaylor** [comment]
Thanks, @findepi. I’ll close this one as a duplicate.
