### ISSUE TITLE
Terminal Colors for CLI

### ISSUE THREAD

**Issue by AntoniosHadji** [prestosql/presto#2187]
On cli version 325, the prompt color conflicts with the solarized dark color scheme.  This results in an invisible prompt.  

This does not happen with latest version from prestodb 0.229.    

It would be nice to have the colors configurable versus having to change the terminal color.

**Comment by findepi** [comment]
I think we should start with an option to disable highlighting as an escape valve.

**Comment by ebyhr** [comment]
Let's continue in #6190
