### ISSUE TITLE
Why outer join not working as expected

### ISSUE THREAD

**Issue by groobyming** [prestosql/presto#2197]
Presto version : 308
When I perform an outer join, the results are not as expected, here is my SQL and LIVE PLAN

SQL：
SELECT *
FROM tableA a
	FULL JOIN TableB b ON a.id = b.id
WHERE a.thedate = '20191201'
	AND b.thedate = '20191201'
LIMIT 1000

Stage：
![image](https://user-images.githubusercontent.com/34335395/70137497-ffda7a80-16c8-11ea-9daf-0a8c81f3ed18.png)

**Comment by Praveen2112** [comment]
Hi, Can you share the details about connector you are using and entire live plan or explain query ?

Please join the #troubleshooting channel on our slack https://prestosql.io/slack.html.
See you there!!!

**Comment by Praveen2112** [comment]
But I think this is an expected plan structure we get when we apply a filter condition which is involved on the columns which are not a part of Join criteria but if they are involving columns from both the left and right tables. 

When we apply this filter `a.thedate = '20191201' AND b.thedate = '20191201'` on top of a full join we would remove the null rows which gets added if a corresponding match are not found (on proble or build side)  so which would be equivalent to applying an `INNER JOIN` which would be way faster than applying a `FULL JOIN` and running that filter on top of it.

If we apply a filter condition which selects the null value then `FULL JOIN` is retained (filter will be applied on top of it).
If we apply a filter condition which spans on only one table then it will converted to a `LEFT JOIN`.


> the results are not as expected
Is this statement is wrt to other query engine like Hive ?

**Comment by groobyming** [comment]
> Hi, Can you share the details about connector you are using and entire live plan or explain query ?
> 
> Please join the #troubleshooting channel on our slack https://prestosql.io/slack.html.
> See you there!!!

Thanks, I will share this question on Slack https://prestosql.io/slack.html

**Comment by groobyming** [comment]
And here is the connector and detail LIVE PLAN
connector：HIVE 
explain：
"- Output[thedate, dteventtime, dteventtimestamp, localtime, displayname, accessdatabusiness, bk_biz_id, dt_par_unit, thedate, dteventtime, dteventtimestamp, localtime, displayname, bk_biz_id, query_num, dt_par_unit] => [thedate:integer, dteventtime:varchar, dteventtimestamp:bigint, localtime:varchar, displayname:varchar, accessdatabusiness:bigint, bk_biz_id:bigint, dt_par_unit:integer, thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer]
        Estimates: {rows: 1000 (390.63kB), cpu: ?, memory: ?, network: ?}
        thedate := thedate_0
        dteventtime := dteventtime_1
        dteventtimestamp := dteventtimestamp_2
        localtime := localtime_3
        displayname := displayname_4
        bk_biz_id := bk_biz_id_5
        dt_par_unit := dt_par_unit_6
    - Limit[1000] => [localtime:varchar, bk_biz_id:bigint, thedate:integer, displayname:varchar, accessdatabusiness:bigint, dteventtimestamp:bigint, dt_par_unit:integer, dteventtime:varchar, bk_biz_id_5:integer, thedate_0:integer, localtime_3:varchar, displayname_4:varchar, dteventtime_1:varchar, dteventtimestamp_2:bigint, query_num:bigint, dt_par_unit_6:integer]
            Estimates: {rows: 1000 (390.63kB), cpu: ?, memory: ?, network: ?}
        - LocalExchange[SINGLE] () => [localtime:varchar, bk_biz_id:bigint, thedate:integer, displayname:varchar, accessdatabusiness:bigint, dteventtimestamp:bigint, dt_par_unit:integer, dteventtime:varchar, bk_biz_id_5:integer, thedate_0:integer, localtime_3:varchar, displayname_4:varchar, dteventtime_1:varchar, dteventtimestamp_2:bigint, query_num:bigint, dt_par_unit_6:integer]
                Estimates: {rows: 1000 (390.63kB), cpu: ?, memory: ?, network: ?}
            - RemoteExchange[GATHER] => [localtime:varchar, bk_biz_id:bigint, thedate:integer, displayname:varchar, accessdatabusiness:bigint, dteventtimestamp:bigint, dt_par_unit:integer, dteventtime:varchar, bk_biz_id_5:integer, thedate_0:integer, localtime_3:varchar, displayname_4:varchar, dteventtime_1:varchar, dteventtimestamp_2:bigint, query_num:bigint, dt_par_unit_6:integer]
                    Estimates: {rows: 1000 (390.63kB), cpu: ?, memory: ?, network: ?}
                - LimitPartial[1000] => [thedate:integer, dteventtime:varchar, dteventtimestamp:bigint, localtime:varchar, displayname:varchar, accessdatabusiness:bigint, bk_biz_id:bigint, dt_par_unit:integer, thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer]
                        Estimates: {rows: 1000 (390.63kB), cpu: ?, memory: ?, network: ?}
                    - InnerJoin[(""bk_biz_id"" = ""expr_8"")][$hashvalue, $hashvalue_74] => [thedate:integer, dteventtime:varchar, dteventtimestamp:bigint, localtime:varchar, displayname:varchar, accessdatabusiness:bigint, bk_biz_id:bigint, dt_par_unit:integer, thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer]
                            Distribution: PARTITIONED
                        - RemoteExchange[REPARTITION][$hashvalue] => [thedate:integer, dteventtime:varchar, dteventtimestamp:bigint, localtime:varchar, displayname:varchar, accessdatabusiness:bigint, bk_biz_id:bigint, dt_par_unit:integer, $hashvalue:bigint]
                                Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                            - ScanProject[table = hive:test:tableA] => [thedate:integer, dteventtime:varchar, dteventtimestamp:bigint, localtime:varchar, displayname:varchar, accessdatabusiness:bigint, bk_biz_id:bigint, dt_par_unit:integer, $hashvalue_73:bigint]
                                    Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                    $hashvalue_73 := ""combine_hash""(bigint '0', COALESCE(""$operator$hash_code""(""bk_biz_id""), 0))
                                    localtime := localtime:string:3:REGULAR
                                    bk_biz_id := bk_biz_id:bigint:6:REGULAR
                                    thedate := thedate:int:0:REGULAR
                                    displayname := displayname:string:4:REGULAR
                                    accessdatabusiness := accessdatabusiness:bigint:5:REGULAR
                                    dteventtimestamp := dteventtimestamp:bigint:2:REGULAR
                                    dt_par_unit := dt_par_unit:int:-1:PARTITION_KEY
                                        :: [[2019120100], [2019120101], [2019120102], [2019120103], [2019120104], [2019120105], [2019120106], [2019120107], [2019120108], [2019120109], [2019120110], [2019120111], [2019120112], [2019120113], [2019120114], [2019120115], [2019120116], [2019120117], [2019120118], [2019120119], [2019120120], [2019120121], [2019120122], [2019120123]]
                                    dteventtime := dteventtime:string:1:REGULAR
                        - LocalExchange[HASH][$hashvalue_74] (""expr_8"") => [thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer, expr_8:bigint, $hashvalue_74:bigint]
                                Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                            - RemoteExchange[REPARTITION][$hashvalue_75] => [thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer, expr_8:bigint, $hashvalue_75:bigint]
                                    Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                                - Project[] => [thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer, expr_8:bigint, $hashvalue_76:bigint]
                                        Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                        $hashvalue_76 := ""combine_hash""(bigint '0', COALESCE(""$operator$hash_code""(""expr_8""), 0))
                                    - ScanProject[table = hive:test:TableB] => [thedate_0:integer, dteventtime_1:varchar, dteventtimestamp_2:bigint, localtime_3:varchar, displayname_4:varchar, bk_biz_id_5:integer, query_num:bigint, dt_par_unit_6:integer, expr_8:bigint]
                                            Estimates: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                            expr_8 := CAST(""bk_biz_id_5"" AS bigint)
                                            bk_biz_id_5 := bk_biz_id:int:5:REGULAR
                                            thedate_0 := thedate:int:0:REGULAR
                                            localtime_3 := localtime:string:3:REGULAR
                                            displayname_4 := displayname:string:4:REGULAR
                                            dteventtime_1 := dteventtime:string:1:REGULAR
                                            dteventtimestamp_2 := dteventtimestamp:bigint:2:REGULAR
                                            query_num := query_num:bigint:6:REGULAR
                                            dt_par_unit_6 := dt_par_unit:int:-1:PARTITION_KEY
                                                :: [[2019120100], [2019120101], [2019120102], [2019120103], [2019120104], [2019120105], [2019120106], [2019120107], [2019120108], [2019120109], [2019120110], [2019120111], [2019120112], [2019120113], [2019120114], [2019120115], [2019120116], [2019120117], [2019120118], [2019120119], [2019120120], [2019120121], [2019120122], [2019120123]]
"

**Comment by Praveen2112** [comment]
Hi, I guess the generated plan is a proper one. When a filter is being applied on top of a Full join and if it the columns in that filter are from both the tables and are not a part of Join columns then it will translated to `INNER JOIN`

> the results are not as expected

Is this wrt to Hive or ?

**Comment by sopel39** [comment]
@groobyming Presto can normalize outer join to inner join in some cases (see `io.prestosql.sql.planner.optimizations.PredicatePushDown.Rewriter#tryNormalizeToOuterToInnerJoin`).
Particularly comment:
```
                        // If there is a single conjunct that returns FALSE or NULL given all NULL inputs for the inner side symbols of an outer join
                        // then this conjunct removes all effects of the outer join, and effectively turns this into an equivalent of an inner join.
                        // So, let's just rewrite this join as an INNER join
```

**Comment by Praveen2112** [comment]
I'll close this issue. As it is the expected behavior on transforming `OUTER JOIN` to a `INNER JOIN`. Please feel free to re-open this issue once again if you see any discrepancy in the results.
