### ISSUE TITLE
Kudu Connector delete rows that does not meet the conditions

### ISSUE THREAD

**Issue by owen-hh** [prestosql/presto#2252]
Hello. i'm presto newbie
i found Presto delete data that does not meet the conditions.

Environment
- PrestoSQL Version 326
- Kudu 1.6 ( CDH 5.14.2 )

**How to reproduce**

**Step 1 - Create Table**
```
CREATE TABLE pay_kudu.default.delete_issue_test (
   user_id integer WITH ( primary_key = true ),
   idx integer,
   first_name integer,
   last_name varchar
)
WITH (
   partition_by_hash_buckets = 2,
   partition_by_hash_columns = ARRAY['user_id']
);
```

**Step 2 - Insert Data**
```
insert into pay_kudu.default.delete_issue_test values (1, 1, 0, '1'), (2, 2, 1, '2'), (3, 3, 2, '3');
```

After Insert 
![image](https://user-images.githubusercontent.com/58797227/70676941-14260500-1cd1-11ea-97d7-a96a0df19956.png)

**Step 3 - Delete Data **

```
delete from pay_kudu.default.delete_issue_test 
where first_name = 1;
```

After Delete
- Delete 1 row ( idx = 1 )
![image](https://user-images.githubusercontent.com/58797227/70676982-2c961f80-1cd1-11ea-8f1b-0ae125ce65c1.png)

i think this issue is related to [link](https://github.com/prestosql/presto/issues/2025)
( ordinal position / index mapping )

Thank you :)

**Comment by lxynov** [comment]
It looks like the logic here is breaking this test case: https://github.com/prestosql/presto/blob/c74b775e103a7a239aafef1b7ca15fe6370495fe/presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduRecordSet.java#L68-L74

Could you explain a little bit about the logic here? @MartinWeindel

**Comment by MartinWeindel** [comment]
Sorry, I can't remember the exact reason, why this special handling was introduced. Maybe it is not relevant anymore. If you think it is non-sense, I suggest to remove it and run the tests to see if anythings breaks. As I'm not working with Presto and Kudu in my current job, I have no time to investigate it in detail.

**Comment by ebyhr** [comment]
I confirmed the following code passed all existing tests and an additional case for this issue. 
```java
            for (int i = 0; i < columns.size(); i++) {
                KuduColumnHandle handle = (KuduColumnHandle) columns.get(i);
                if (!handle.isVirtualRowId()) {
                    fieldMapping.put(i, handle.getOrdinalPosition());
                }
                else {
                    fieldMapping.put(i, -1);
                }
            }
```
