### ISSUE TITLE
Proposal: create a function/operator reference page in prestosql.io

### ISSUE THREAD

**Issue by lxynov** [prestosql/presto#2257]
Now we have categorized documentations for functions and operators. They are comprehensive and well-organized but not good for quick reference. I think we can create a one-page reference for functions and operators. With that one can quickly search the description of a specific function by its name.

**Comment by martint** [comment]
cc @mosabua

**Comment by mosabua** [comment]
That sounds reasonable ... just an A-Z list with function/operator name and a link to the documentation?
 We would have to figure out where to put that page and how to link to it from the navigation.

**Comment by lxynov** [comment]
> That sounds reasonable ... just an A-Z list with function/operator name and a link to the documentation?

I think either this or organizing them by categories is fine. Users can search by names using `ctrl+f`.

> We would have to figure out where to put that page and how to link to it from the navigation.

Do you think it's fine to just make it `7.1`?

**Comment by mosabua** [comment]
Maybe we should add a introduction to the chapter as a first section (or in the ToC page) and then the existing chapter but also link to the long list .. and have it as the last chapter in that section

**Comment by mosabua** [comment]
fyi @electrum

**Comment by electrum** [comment]
Sphinx can produce an index. If that’s too large, maybe we can write an extension to pull out just the functions and produce a function list.

**Comment by mosabua** [comment]
I am not sure if the functions and operators are already clearly defined so an index could be produced. I can take a look.

**Comment by findepi** [comment]
@mosabua obviously some percentage of functions isn't documented at all.
We should _test_ that index produced by Sphinx contains all the functions returned from `SHOW FUNCTIONS` (or actually `system....functions`).
For starters, we can just ignore overloads.

**Comment by mosabua** [comment]
https://github.com/prestosql/presto/pull/2288

**Comment by mosabua** [comment]
This is now live. We would love to get feedback about any error, missing functions and so on. Have a look at https://prestosql.io/docs/current/functions/list.html
