### ISSUE TITLE
Support aarch64 architecture

### ISSUE THREAD

**Issue by Lewuathe** [prestosql/presto#2262]
Presto currently requires amd64 or ppc64le on Linux and explicitly has the limitation about this requirement in [PrestoSystemRequirements](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/PrestoSystemRequirements.java#L74).

```
failRequirement("Presto requires amd64 or ppc64le on Linux (found %s)", osArch);
```

The error is thrown when I tried to use the A1 instance of AWS.

- Version: Presto 326
- Machine: A1 instance with Graviton Processor
- OS: Amazon Linux

We want to use Presto on the machine running with the aarch64 architecture machine.

**Comment by Lewuathe** [comment]
Is Arm architecture officially supported since 330?
https://github.com/prestosql/presto/pull/2809

**Comment by martint** [comment]
Yes, let's close this issue.

**Comment by Lewuathe** [comment]
🎉
