### ISSUE TITLE
Keep LF endings when checkout on windows

### ISSUE THREAD

**Issue by ssquan** [prestosql/presto#2272]
I checkout source code from Github on Windows than compile it in Gitbash.  Error message:
``` java
[ERROR] src\main\resources\io\prestosql\spi\type\zone-index.properties:[2233] (regexp) RegexpMultiline: Line contains carriage return
``` 

Git may convert LF to CRLF when checkout on windows. Some description from GitHub:[git-handle-line-ending](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) 

An old issues of prestodb:
[Build fails due to Checkstyle violations](https://github.com/prestodb/presto-jdbc-java6/issues/15)

I propose to add a git attribute: "text eol=lf", so git will always convert line endings to `LF` on checkout. 

Compile can accomplish by Gitbash on windows[/smile].

**Comment by findepi** [comment]
@ssquan we currently don't have capacity to support building Presto on windows.
I expect you will run into further problems (e.g. lack of native Windows libraries for hadoop) when going this path.
Currently, a workaround for building Presto on Windows that is known to work is to do this in a VirtualBox Linux.

Also, my (quite long) past experience of using Windows for work tells me that EOL conversion on check-out/check-in is not something I would recommend.
Instead, I would always ask my git on Windows not to mess with the files EOLs at all.  E.g. https://stackoverflow.com/questions/21822650/disable-git-eol-conversions
(Then I would tell my IDE / file editor to use the EOLs I want, which we already do -- https://github.com/prestosql/presto/blob/cd6c18a1a148f716587333dee24cb6e7ba29619b/.editorconfig#L6)

Does this address your needs?

(BTW I invite you to join the `#dev` channel of our slack https://prestosql.io/slack.html. See you there!)

**Comment by ssquan** [comment]
/ close
