### ISSUE TITLE
Support reading ACID/Transactional tables with "original files"

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2293]
See https://github.com/prestosql/presto/pull/1034#discussion_r349602696

Follow-up to: https://github.com/prestosql/presto/issues/576

**Comment by harmandeeps** [comment]
Regarding this support to read ACID table with original files, I have the changes ready. I am waiting on Full ACID PR to merge. Then, I will open the PR for review.

**Comment by harmandeeps** [comment]
@findepi : Assigning this issue to myself. I have raised PR for this. Please take a look. Thanks.
