### ISSUE TITLE
Support multiple EventListener plugin instances/types

### ISSUE THREAD

**Issue by jdintruff** [prestosql/presto#2299]
Right now users are able to configure a single EventListener plugin to handle tracking events. It would be nice to be able to have multiple instances of different types of EventListener plugins to have multiple destinations for this tracking data.

I've developed this patch internally and will publish a rebased PR shortly.

**Comment by raunaqmorarka** [comment]
In the past the recommendation was to propagate events to multiple listeners within your own implementation, but it would be nice to have this within presto
https://github.com/prestodb/presto/issues/9100

**Comment by kokosing** [comment]
Fixed with #3128
