### ISSUE TITLE
Document hidden columns in Hive connector

### ISSUE THREAD

**Issue by mosabua** [prestosql/presto#2344]
https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveColumnHandle.java#L40

They can be used in queries e.g. `$bucket`

Discussion came up in slack - https://prestosql.slack.com/archives/CFLB9AMBN/p1577092500086400

**Comment by tooptoop4** [comment]
$properties table from https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java#L397-L400 also not documented outside release notes (https://prestosql.io/docs/current/release/release-309.html)
