### ISSUE TITLE
feature request - Excel data source connector (xls/xlsx file reader)

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2351]
Apache Drill supports this: https://github.com/apache/drill/pull/1749/files
https://issues.apache.org/jira/browse/DRILL-7177
it makes use of:
https://poi.apache.org/index.html (org.apache.poi)

This is about the ability for Presto to run SQL that queries data living in xls/xlsx files (ie rather than querying parquet/orc/csv data). This is NOT about using excel to run queries against presto odbc

**Comment by tooptoop4** [comment]
maybe https://github.com/ebyhr/presto-flex solves some of this

**Comment by mohammadsrafiee** [comment]
You can see this GitHub project.
[https://github.com/mohammadsrafiee/trino-excel-plugin](url)
