### ISSUE TITLE
day_of_week to work with DATE and not only with TIMESTAMP

### ISSUE THREAD

**Issue by RosterIn** [prestosql/presto#2378]
`select day_of_week('2014-04-24')`
gives:

> Unexpected parameters (varchar(10)) for function day_of_week. Expected: day_of_week(timestamp) , day_of_week(timestamp with time zone) , day_of_week(date)

 `select day_of_week(TIMESTAMP '2014-04-24')`

Gives
`4`

Can the function also work with Date type? This will save the trouble of casting all the time...

**Comment by findepi** [comment]
`day_of_week` should work with `date` (technically: `date` should get coerced to `timestamp`).

@RosterIn Please try:

    select day_of_week(DATE '2014-04-24')

**Comment by RosterIn** [comment]
ok i stand corrected. I see it works with date.
Why can't it work with varchar?
The way I see it the function can handle the convert for the user or there is a specific reason why presto prefer not to do that?

**Comment by findepi** [comment]
@RosterIn thanks for checking.

This is a broader discussion, not really specific to `day_of_week`.
In database world, there are certain coercions which are mandated by SQL spec,
which should happen implicitly, without user requesting it explicitly (e.g. from `date` to `timestamp`).
Conversion from `varchar` to `date` is not one of them.

While I see how it could be useful for this specific case of `day_of_week` function,
such a coercions should be -- by consistency -- applied to e.g. comparison between
`varchar` and `date` values. Example: joining two tables where one side is `varchar`
and the other is `date`). However, in such an example, implicit coercion could be
harmful and it's really not obvious which direction types should be coerced to
(`date` to `varchar` or `varchar` to date`).

Let me close this, as I think it answers your question. Of course, you can continue 
discussion if you have any follow-ups.

I invite you to our slack https://prestosql.io/slack.html if you haven't joined it yet.
