### ISSUE TITLE
how to determine whether the PrepareStatement precompilation in Presto is actually executed？

### ISSUE THREAD

**Issue by wangwei216** [prestosql/presto#2498]
1. Hello, first of all, my purpose is to encapsulate a set of Client APIs that can support PHP, but Presto does not officially support the corresponding functions, so here we can only try to do it ourselves, I used https://github.com/360d-io-labs/PhpPrestoClient 

2. After I executed [PREPARE statementXXX select count (identify) as totalNum, real_region_name, provider from user where real_region_name =? And provider =? Group by real_region_name, provider order by totalNum asc], I put [`statementXXX = select count (identify) as totalNum, real_region_name, provider from user where real_region_name =? and provider =? group by real_region_name, provider order by totalNum asc`] Put it in `EXECUTE statementXXX USING 'Shanghai', 'China Mobile'` HTTP request field is [X-Presto-Prepared- Statement] in the request header     
```
               $this->headers = array(
                "X-Presto-User: " . $this->prestoUser,
                "X-Presto-Catalog: " . $this->prestoCatalog,
                "X-Presto-Schema: " . $this->prestoSchema,
                "X-Presto-Language: ".$this->prestoLanguage,
                "X-Presto-Time-Zone: ".$this->prestoTimeZone,
                "X-Presto-Added-Prepare: ".$this->prestoAddPrepare,
                "X-Presto-Prepared-Statement: ".$this->prestoPrepareStatement,
                "Content-Type: ".$this->contentType,
                "X-Presto-Source: ".$this->prestoSource,
                "Connection: ".$this->prestoConnection,
                "User-Agent: " . $this->userAgent);
```

3. But I found that as long as I put the statementName of the SQL I want to execute and the SQL of PREPARE into the "X-Presto-Prepared-Statement" request header, `EXECUTE statementXXX` will be executed eventually regardless of whether the first PREPARE HTTP request is executed `USING 'Shanghai', 'China Mobile'`, is this a PreStatement precompilation or not? Is this a bug? Hope to get your answer, thank you

**Comment by findepi** [comment]
Prepared statements should be prepared using `PREPARE`.

Since session state is kept on the client side, it's technically sufficient to put prepared statement in the HTTP header (without calling `PREPARE` first), but that's not guaranteed to work.

Does this answer your doubts?

**Comment by findepi** [comment]
BTW i recommend that you join https://prestosql.io/slack.html if you haven't yet done so.

**Comment by wangwei216** [comment]
1. then, if I want to query Presto through PHP, and I can support PrepateStatement, how can I do it? Can you give me some suggestions? Thank you

2. According to your opinion, even after I send the first HTTP request using PHP to execute prepare statementnamexx from xxxxx, the field value of "x-presto-prepared-statement" in the request header the second time does not need to get statementnamexx and original SQL from the first HTTP request, is not it The value of "x-presto-prepared-statement" in the request header is obtained from the session on the server side and placed in the request header by myself. It does not need me to manually

**Thank you very much**

**Comment by findepi** [comment]
i never used https://github.com/360d-io-labs/PhpPrestoClient. It looks pretty not maintained recently.
I guess it doesn't support Prepared statements, so you need to support them on your own.
The proper way to do it is (aka protocol description):

1. send `PREPARE ..` query 
2. save the value of `X-Presto-Added-Prepare` header (reference implementation https://github.com/prestosql/presto/blob/73e5738ade6c1b6ced334fb3aac3531b66a2a4de/presto-client/src/main/java/io/prestosql/client/StatementClientV1.java#L433-L442)
3. when sending `USING ..` query, send it along with `X-Presto-Prepared-Statement` header(s). (reference implementation https://github.com/prestosql/presto/blob/73e5738ade6c1b6ced334fb3aac3531b66a2a4de/presto-client/src/main/java/io/prestosql/client/StatementClientV1.java#L198-L201)

@wangwei216 let me close this issue as there is nothing that needs to be done by others.
We can continue discussion here, but I recommend that you join the `#dev` channel on our slack https://prestosql.io/slack.html
