### ISSUE TITLE
Table created in Hive2.3.6 can not list in Presto

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2500]
created a table from Hive and trying to access using show tables; in presto.
When using Hive 2.1.1 it is working but for Hive 2.3.6 not working.
With Hive 2.3.6 it does not list the tables in Presto;
Steps as below:
```
hive> create table test_hive(id integer);
hive> show tables;
table1
test_hive
presto:default> show tables;
     Table
---------------
 bigger_orders
 demo
 details
 details2
 details3
 details4
 details5
 details6
 orders1
 try1
 try3
(11 rows)
Query 20200114_081714_00009_c5gg4, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:00 [11 rows, 266B] [52 rows/s, 1.24KB/s]
presto:default>
root@BLR1000046663:/hadoop-2.7.7/bin# ./hadoop fs -ls /user/hive/warehouse
drwxrwxr-x   - root supergroup          0 2020-01-14 16:15 /user/hive/warehouse/test_hive
```

**Comment by ebyhr** [comment]
Did you remove unnecessary lines from the result? I'm asking this question because Hive SHOW TABLES count is fewer than Presto result. 

Also, could you share the SHOW CREATE TABLE result in Hive to confirm the entire table properties?

**Comment by AbhishekNew** [comment]
I already joined the community.

**Comment by ebyhr** [comment]
@AbhishekNew Could you post it on `#troubleshooting` channel so that we can talk interactively? I'm sorry, but I couldn't identify your account because there are some accounts that have the same name.

**Comment by AbhishekNew** [comment]
Already posted there and thread is going on.

**Comment by ebyhr** [comment]
Thanks, I found it. Let’s continue the discussion in the thread instead of here.

**Comment by ebyhr** [comment]
I'm going to close this issue because it's due to restarting of the embedded derby metastore. Please reopen or ping in Slack if you need further help.
