### ISSUE TITLE
Whats the process to include presto-oracle?

### ISSUE THREAD

**Issue by dprophet** [prestosql/presto#2504]
Whats the process to include
https://github.com/marcelopaesrech/presto-oracle

Within this org's standard presto? Oracle is a big use case for us and, IMO, its better to have upstream.

**Comment by findepi** [comment]
@dprophet Presto community is already working on Oracle connector.
Please follow https://github.com/prestosql/presto/pull/1959.
Let me close this issue in favor of that PR.

**Comment by electrum** [comment]
To directly answer your question, we’d need the author to submit the connector to the project as a pill request (with a signed CLA). 

The main reason we don’t have an Oracle connector yet is that until very recently, Oracle did not allow distribution of their driver under terms compatible with an open source project.
