### ISSUE TITLE
Metabase not recognise presto view name

### ISSUE THREAD

**Issue by MichaelZhao9824** [prestosql/presto#253]
Hi guys,

We are using metabase to connect to Presto but encounter an issue which not recognise view name 
There is an issue on -  https://github.com/prestodb/presto/issues/9173 but not fixed.

I am wondering you guys could help on this. Currently we fixed the issue manually built from scratch which is not convenient to upgrade. Thanks.

**Comment by electrum** [comment]
I believe this is fixed by the recently merged https://github.com/prestosql/presto/pull/250

Can you see if that resolves your issue? It will be in the 304 release.

**Comment by MichaelZhao9824** [comment]
@electrum Thanks a lot. that would be handy.

**Comment by dain** [comment]
If this is still an issue, please reopen.

**Comment by xueyibing** [comment]
[Code: 1, SQL State: ]  Query failed (#20190521_124812_00006_hn8ns): line 1:8: Column 'dw_presto.test_view.dt' cannot be resolved
