### ISSUE TITLE
Incorrect results for parse_datetime function

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#2533]
As far as I confirmed, the month of year always returns January. 
```
presto> SELECT parse_datetime('20180527', 'YYYYMMDD')
2018-01-27 00:00:00.000 Asia/Tokyo
```

If we remove the following `DD` or replace it with `dd`, it returns the right result.
```
presto> SELECT parse_datetime('201805', 'YYYYMM');
 2018-05-01 00:00:00.000 Asia/Tokyo 

presto> SELECT parse_datetime('20180527', 'YYYYMMdd');
 2018-05-27 00:00:00.000 Asia/Tokyo 
```

https://stackoverflow.com/a/59285577/4087465

**Comment by martint** [comment]
It seems to be picking up the month as minutes, no?

**Comment by ebyhr** [comment]
Sorry, I pasted the wrong result. Fixed.

**Comment by findepi** [comment]
thanks @ebyhr for catching me
