### ISSUE TITLE
Add Hive plugin support for assuming various AWS IAM roles depending on the target S3 path.

### ISSUE THREAD

**Issue by krishnadg** [prestosql/presto#2564]
When providing presto as a service/platform to other teams, organizations, etc., there may be a requirement for the cluster's IAM role to assume a role outside of the host cluster's AWS account when working through the Hive Plugin. 

One reason for this is that there may be object level restrictions for data stored in S3 which would prevent the presto cluster from being able to read/process the data. For example, let's say the presto cluster is running on resources in Account 'A' under an IAM role `'arn:iam:A:prestoRole'`. Then, I am allowing other users to access this presto cluster and write data (data in the form of hive tables with an s3 external location) back to their own destination S3 paths (in account 'B'). While they may create a proper bucket policy to allow for the objects to be read/written properly granting full control to the bucket owner, the underlying object owners of this data will still be account 'A', that of the presto cluster. This becomes an issue when there is a third party involved, account 'C' who desires to read/copy/use this generated data but is forbidden with access code 403 regardless of bucket permissions enabled (due to AWS S3 restrictions). 

Alternatively, there might be a requirement for presto users in account 'B' to maintain ownership of the data they are generating(for security reasons), which would not be possible since the presto cluster's IAM role in account 'A' is responsible for writing the data to S3 (in any account). 

The model that I proposed and implemented contains a new string property in the ".../prestosql/plugin/hive/s3/hiveS3Config.java" class:  @Config("hive.s3.s3-to-iam-role-mappings"), which consists of an unparsed HashMap of keys: 'S3:// locations' and values: 'IAM role arns'. 

This property gets initialized into a Map in the class ".../prestosql/plugin/hive/s3/PrestoS3FileSystem.java" and then checked during the initialization of a new presto filesystem (new s3 location) 

```
this.iamRole = this.iamRoleMappingsMap.containsKey(uri.toString()) ? this.iamRoleMappingsMap.get(uri.toString()) : conf.get(S3_IAM_ROLE, defaults.getS3IamRole());
``` 

I added a couple of test cases to validate the proper IAM roles were being assumed when initializing an S3:// location listed in the property; I will attach a snippet of those as well.

[TestPrestoS3FileSystem_snippet.txt](https://github.com/prestosql/presto/files/4088750/TestPrestoS3FileSystem_snippet.txt)

**Comment by electrum** [comment]
Thanks for raising this issue. We've also been working on this feature and will put it up for review soon. We'd actually started with a simple mapping like you propose, but ended up with a more fully featured JSON config file that allows overriding AWS credentials and specifying multiple allowed roles. I'd appreciate you taking a look at the design of this once the PR is ready.

**Comment by krishnadg** [comment]
Sure, would love to take a look at the PR when it's ready. I suppose one of the main features I was aiming for was not needing to manually select credentials when accessing specific S3 paths. Though I can definitely see the benefit of both features through something like "set hive.s3_iam_role=arn...."

Curious to see what your JSON config file might have in mind!

**Comment by electrum** [comment]
Apologies, I forgot to close this issue, as this use case is supported now: https://prestosql.io/docs/current/connector/hive.html#s3-security-mapping
