### ISSUE TITLE
Presto Connector for Tableau

### ISSUE THREAD

**Issue by mallika-singhi** [prestosql/presto#2592]
Timestamp conversion done incorrectly while connecting presto connector as data source in Tableau.

Database details as follows:
presto:default> select user_id,authorized_date from taxonomy.dim_users where user_id = 2325954;
 user_id |     authorized_date     
 **2325954 | 2018-07-01 00:19:36.000** 

hive> select user_id,authorized_date from taxonomy.dim_users where user_id = 2325954;
user_id	authorized_date
**2325954	2018-07-01 00:19:36
![Screenshot 2020-01-20 at 1 04 59 PM](https://user-images.githubusercontent.com/56252123/72957902-4b58fd00-3dcb-11ea-9796-4468257157a5.png)
![Screenshot 2020-01-20 at 1 05 07 PM](https://user-images.githubusercontent.com/56252123/72957903-4bf19380-3dcb-11ea-9f45-88d3ae46f406.png)

**

Tableau s/s as attached .

Please look into this and let me know if you need any more details from my end

Thanks,
Mallika Singhi

**Comment by findepi** [comment]
Timestamp is presented in session timezone-dependent form.
So the textual representation you see depends on where you run the client.
See more https://github.com/prestosql/presto/issues/37
You can configure the session timezone eg to UTC -- instructions depend on the library you use.

Are you using JDBC or ODBC with Tableau?
(AFAICT it supports both now)

**Comment by mallika-singhi** [comment]
thanks the the reply.

using presto connector directly to connect to Tableau ,s/s attached for the same.
![Screenshot 2020-01-23 at 6 31 20 PM](https://user-images.githubusercontent.com/56252123/72986608-97796100-3e0e-11ea-83fe-8438fe797f6e.png)

Any way i change the timezone ?

**Comment by findepi** [comment]
@mallika-singhi is it something called a "Web Connector" in Tableau?
(pardon my questions; as you see, i'm not Tableau expert)

**Comment by mallika-singhi** [comment]
no its not a web connector.
Its directly a presto driver connector.
Presto version i have used is SimbaPresto1.1-64-bit (1).msi

Links for reference:
https://www.tableau.com/support/drivers
https://help.tableau.com/current/pro/desktop/en-us/examples_presto.htm

**Comment by findepi** [comment]
@mallika-singhi please add `TimeZoneID=UTC` to the odbc connection string.

Also, please join our slack https://prestosql.io/slack.html, it has dedicated #troubleshooting channel.

let me close the issue as answered, you can still comment here, or move to slack
