### ISSUE TITLE
Query Failure while worker is in SHUTTING_DOWN state

### ISSUE THREAD

**Issue by ayushbilala** [prestosql/presto#2621]
Consider the below scenario,
User submits a query to Presto cluster. Same time a shutdown signal is sent to one of the Presto workers.
Query fails with a very generic error "No nodes available to run query".
Presto UI shows all the tasks are aborted.

I think below could be the possible cause,
Query received by Presto coordinator. Coordinator identifies a list of workers where the query can run. If a shutdown signal is sent to the worker just before the coordinator sends the task to the worker, coordinator fails communicating with the worker and the query fails.

**Is there a possibility to introduce a retry mechanism for running the query with the latest set of workers?**

**Comment by sopel39** [comment]
related slack discussion: https://prestosql.slack.com/archives/CFLB9AMBN/p1579853527036100

**Comment by ayushbilala** [comment]
Thanks for adding the fix @sopel39.
