### ISSUE TITLE
Document some jmx metrics

### ISSUE THREAD

**Issue by mosabua** [prestosql/presto#2623]
Question on slack: 

For jmx metrics such as numberofleakedqueries, querieskilledduetooutofmemory, blockednodes, and assignedqueries under clustermemorypool and clustermemorymanager, are they cumulative count since cluster start, or are they a running average of say 5m... not sure how to find documentation on these, so any help would be appreciated!

Answer from @martint :

NumberOfLeakedQueries: number of queries currently believed to be leaked. Generally, it goes up, but due to possible race conditions, it’s possible some suspected leaked queries will clear out later.

QueriesKilledDueToOutOfMemory: cumulative since restart.

BlockedNodes: number of currently blocked nodes. It can go up or down as the state of nodes changes.

AssignedQueries: current number of queries. It can go up or down as the state changes.

**Comment by mosabua** [comment]
Looking at this I am not sure where to document JMX more. The only JMX related info we have in the docs for now is the JMX connector. Should it be added there? Or do we need some other JMX section @martint ?

**Comment by raags** [comment]
Maybe the section in the wiki is a good start: https://github.com/prestosql/presto/wiki/Monitoring

**Comment by mosabua** [comment]
Yeah.. I think we might want to look at porting that info in the site .. do you agree @martint @electrum ?

**Comment by raags** [comment]
I stumbled on this issue while searching for presto monitoring. One thing that will be helpful is a list of key metrics that one should monitor. There are more than 5k JMX metrics out of the box. The list in the wiki is a start but doesn't seem to cover everything. It'll be useful if that is revised. A template grafana dashboard will be great.

**Comment by mosabua** [comment]
I started with porting the wiki content .. what do we want to add minimally to merge this @martint @electrum @dain and then delete the wiki page (or replace with link)

**Comment by mosabua** [comment]
@raags a grafana dashboard could be useful but would have to be a separate largish effort.

**Comment by mosabua** [comment]
I reopened and left assigned to me for now. Once the new docs are published I will remove the content on the wiki page and replace it with a link to the docs. Going forward we will expand that jmx page as well.

**Comment by mosabua** [comment]
This is all done.
