### ISSUE TITLE
Allow changing ownership of a scheme or GRANT/REVOKE on a schema (Hive connector)

### ISSUE THREAD

**Issue by lhofhansl** [prestosql/presto#2625]
Not sure this is covered anywhere else... Apologies if it is.

Currently in the hive connector when hive.security=sql-standard, only an admin user can create a schema and only an admin or the owner of a schema can create tables in it - by inference only users granted the "admin" role can ever create any tables.
EDIT: file based access control is too static for us.

We have a use case where we would like to use the SQL standard GRANT/REVOKE to have some users that can create tables (ideally in their schemas only), but not delete other tables.

It seems that could logically be done in two ways:
1. Allow GRANT/REVOKE on schemas, with the same perm we have (SELECT = see tables, INSERT = create/modify tables, DELETE = drop tables).
2. Allow ALTER SCHEMA SET OWNER|ROLE = ...

(1) is very flexible, but does not fit into the Hive model (as far as I can see.)
(2) Is actually support in Hive 0.13.0+. So perhaps we just have add syntax for that. Or are users expected to use Hive to set this up? (https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-AlterDatabase)

A related problem is that any user that can create any schemas can also drop any other schema. I can't see a "standard" way of handling, it would need to be some metadata or config per catalog.

I suppose one way is to setup different accesses via different catalogs, but it seems that would require actually running multiple metastores.

Comments? Other ideas?

**Comment by lhofhansl** [comment]
Postgres has this:
```
GRANT { { CREATE | USAGE } [,...] | ALL [ PRIVILEGES ] }
    ON SCHEMA schema_name [, ...]
    TO { [ GROUP ] role_name | PUBLIC } [, ...] [ WITH GRANT OPTION ]
```
(https://www.postgresql.org/docs/9.0/sql-grant.html)

**Comment by lhofhansl** [comment]
Some more info... Hive can grant access to schemas, but it does not behave as expected (IMHO) - it merely grant rights to all tables in the schema.

My main question here is: Can we deviate from Hive's security model in Presto?
I looked at Hive's Metastore DB schema and it seems expressive enough to do what I'm proposing in option (1) above. If so I'd try to provide a PR.

At the minimum I can do a PR that updates the current Hive security config documentation to describe the current behavior better.

**Comment by electrum** [comment]
The problem with deviating from the Hive security model is that it would cause problems with using both Hive and Presto (or other systems) against the same metastore. However, if the metastore API supports it, then it seems reasonable to implement, possibly with a config flag to disable it by default.

**Comment by lhofhansl** [comment]
What's really needed is a different admin per database/schema - with a separate set of users, roles, and database objects. That seems tricky.

In Presto I *could* get that by running multiple metastores. Maybe not as bad as I thought, since they're stateless anyway. (They can use the same database sever(s), just different databases/schemas and users)... And then use multiple catalogs in Presto as I hinted above.

Perhaps that's the safest bet anyway, since that way I can guarantee access isolation. That way I can even setup different access control methods - file-based in one, SQL based in another.

**Comment by dain** [comment]
Although there is no way to change owner in Presto, it does look like Presto correctly checks the Hive metastore for database ownership permissions for `create table` and `drop schema`, so if you have a Hive installation then you could run the commands there as a work around until Presto has a way to change ownership.

> A related problem is that any user that can create any schemas can also drop any other schema. I can't see a "standard" way of handling, it would need to be some metadata or config per catalog.

I didn't follow this.  In Hive with sql standard security enabled, you must be an owner of the schema (Hive database) or be an admin to drop it.

**Comment by lhofhansl** [comment]
> I didn't follow this. In Hive with sql standard security enabled, you must be an owner of the schema (Hive database) or be an admin to drop it.

Sorry I wasn't clear there. I specifically meant within Presto. As is, you have to be admin to create a schema, and an admin can drop any schema. By extension that means that any user that can create a schema can drop any other schema.

After some more reflection I think what we should add to Presto is just this:
ALTER SCHEMA <schema> SET OWNER {USER|ROLE} <principle>
(Hive has exactly this syntax and it does exactly what is expected.)

Only the current owner of the schema or a member of the admin role should be allowed to do this.

**Comment by martint** [comment]
The standard syntax for specifying an owner when creating a schema is 

```
CREATE SCHEMA <name> AUTHORIZATION <owner>
```

So, to be consistent with the specification I'd suggest:

```
ALTER SCHEMA <name> SET AUTORIZATION <owner>
```

**Comment by lhofhansl** [comment]
Let's add both, the CREATE and the ALTER syntax.
I'll work on the change file a PR (might take a bit, since it's my first Presto change.)

**Comment by lhofhansl** [comment]
Proposed schema change:

```
diff --git a/presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4 b/presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
index 65963da..ab59361 100644
--- a/presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
+++ b/presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
@@ -39,9 +39,10 @@ statement
     | USE schema=identifier                                            #use
     | USE catalog=identifier '.' schema=identifier                     #use
     | CREATE SCHEMA (IF NOT EXISTS)? qualifiedName
-        (WITH properties)?                                             #createSchema
+        (AUTHORIZATION principal)? (WITH properties)?                  #createSchema
     | DROP SCHEMA (IF EXISTS)? qualifiedName (CASCADE | RESTRICT)?     #dropSchema
     | ALTER SCHEMA qualifiedName RENAME TO identifier                  #renameSchema
+    | ALTER SCHEMA qualifiedName SET AUTHORIZATION principal           #setSchemaAuth
     | CREATE TABLE (IF NOT EXISTS)? qualifiedName columnAliases?
         (COMMENT string)?
         (WITH properties)? AS (query | '('query')')
```

**Comment by lhofhansl** [comment]
Do we need a way to show the owner of a schema? Looks like in Presto there's no way currently of doing that.

**Comment by martint** [comment]
We'd need to add support for `SHOW CREATE SCHEMA`

**Comment by lhofhansl** [comment]
I noticed that SHOW CREATE TABLE does not show the owner either.
Perhaps it's better in a separate PR - if that's what we decide to do.

**Comment by lhofhansl** [comment]
Coming back to Hive for a minute. As I said above Hive *can* grant INSERT | SELECT | UPDATE | DELETE to databases. But it doesn't behave as expected, CREATE TABLE still simply checks for ownership of the database.

We could deviate from this in Presto because Hive would be *more* restrictive, and arguably the new behavior would make more sense anyway. In the end I think this should be fixed in Hive as well, but I can't boil the ocean. :)

In any case #2673 takes the schema ownership route.
