### ISSUE TITLE
Support SSL/TLS for Hive Metastore

### ISSUE THREAD

**Issue by chu-salesforce** [prestosql/presto#2658]
It is a desired feature to support SSL connection to a custom hive metastore in the Hive connector. Some foundation work has already been done, but the feature is not yet complete:

https://github.com/prestosql/presto/commit/b46d506a062f487cc81348f00ebf681cfdc92693

A new flag will need to be added to ThriftMetastoreConfig, which turns on/off SSL:

https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java

If the flag is on, a new SSLContext should be constructed and passed into ThriftMetastoreClientFactory.

**Comment by dongwoo1005** [comment]
If nobody is working on it, I will look into the issue and start working on the feature

**Comment by electrum** [comment]
Please use the same config names  as https://github.com/airlift/drift/blob/master/drift-transport-netty/src/main/java/io/airlift/drift/transport/netty/client/DriftNettyClientConfig.java prefixed with `hive.metastore`. For example, `hive.metastore.thrift.client.ssl.trust-certificate`.

**Comment by electrum** [comment]
@dongwoo1005 please do. I’ve assigned this issue to you.

**Comment by ebyhr** [comment]
Covered by #3440
