### ISSUE TITLE
Doc requirement for glue config

### ISSUE THREAD

**Issue by mosabua** [prestosql/presto#2661]
User support on slack discivered the fact that 

```
hive.metastore=glue
```
is needed for glue usage so that the metastore.uri property is not required. Rest of params are used to get URI.

**Comment by mosabua** [comment]
We should just add an initial sentence about this need under the title at https://prestosql.io/docs/current/connector/hive.html#aws-glue-catalog-configuration-properties

It is actually documented in https://prestosql.io/docs/current/connector/hive.html#hive-configuration-properties but thats kinda hidden and making it explicitly in the glue section is probably a good idea

**Comment by pratikSethi** [comment]
I am going through the docs to run the project locally. I'll get back soon. Excited for my first contibution :)

**Comment by mosabua** [comment]
fyi @pratikSethi  .. I had some time and thought I knock this one out now ..

**Comment by pratikSethi** [comment]
@mosabua That is great! Sorry, I could not get to it!
Also, Thanks for helping me to setup my cluster with the configs.

**Comment by mosabua** [comment]
No worries.. next time @pratikSethi
