### ISSUE TITLE
Not able to bind MAP in parameterized query since 322 release version

### ISSUE THREAD

**Issue by parasupreti** [prestosql/presto#2675]
Binding MAP to parameterized query is not working from release version 322.
For Ex: if i run below queries,  
create table if not exists hive.default.maptable( a map(real, double) )
PREPARE stmt0 FROM insert into hive.default.maptable values (?)
EXECUTE stmt0 USING map(array[cast('2.3' as REAL),cast('1.2' as REAL)],array[cast(6.5 as DOUBLE),cast(4.9 as DOUBLE)])
Last query does not works and throws error, "Function call has not been resolved: map(ARRAY[CAST('2.3' AS REAL),CAST('1.2' AS REAL)], ARRAY[CAST(DECIMAL '6.5' AS DOUBLE),CAST(DECIMAL '4.9' AS DOUBLE)])".

If i just run insert into hive.default.maptable values (map(array[cast('2.3' as REAL),cast('1.2' as REAL)],array[cast(6.5 as DOUBLE),cast(4.9 as DOUBLE)])), then it works fine.

Above query used to work fine for the server version 321 and earlier.

**Comment by martint** [comment]
Thanks for the report! The fix is merged and will be available in the next release.
