### ISSUE TITLE
Failure Aware metastore client shoulnd not rotate metastores on expected Thrift exceptions

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#2694]
Currently `StaticMetastoreLocator` will rotate metastores on any thrift error (even expected ones like method not available).

FYI: @qqibrow

**Comment by kokosing** [comment]
> Currently StaticMetastoreLocator will rotate metastores on any thrift error (even expected ones like method not available).

What is the problem with this? Having several metastore configured, Presto rotate anyway. Why should we stick with certain metastore?

**Comment by sopel39** [comment]
> What is the problem with this?

So do we rotate for every request or only on failure? If the latter, then it's odd that we rotate for expected exceptions.

**Comment by kokosing** [comment]
As I understand we rotate every request. See`io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore#createMetastoreClient()`

**Comment by sopel39** [comment]
Closing as irrelevant. We can and should distribute request between metastores
