### ISSUE TITLE
Section 9. SQL Statement Syntax Document should be updated as Note mentioned in Section 8

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2695]
presto:_> alter schema ttt rename to t1; -- Does not work
Query 20200130_123113_00033_kmaa9 failed: Hive metastore does not support renaming schemas
But this works
presto:_> alter table ttt rename to t1;
RENAME TABLE
User can rename table but schema not
So this should be updated in document as Note: like Section 8 is updated.
Here use Hive connector so it is Hive Limitation.

**Comment by findepi** [comment]
@AbhishekNew you're correct. This works, but not for Hive metastore.
We should update docs to make it clear.

**Comment by mosabua** [comment]
I am not sure I understand where you want what documented. All SQL supports are subject to limitations from the connectors .. so I think in this case it would be correct to add this as a limitation to https://prestosql.io/docs/current/connector/hive.html#hive-connector-limitations

We could also have a general note about the fact that connectors influence scope of SQL support in https://prestosql.io/docs/current/language.html  

Could you clarify @findepi

**Comment by findepi** [comment]
Exactly.

> My personal preference is to add it as limitation to the Hive connector docs

Sounds reasonable.

Alternatively, we for given connector-dependent feature we could document for which connector it's said to work (a whitelist).

However, any approach we take, won't be easy to maintain. And i don't have personal strong preferences.
