### ISSUE TITLE
Allow ApplicationName and ClientTags as JDBC connector properties

### ISSUE THREAD

**Issue by mosabua** [prestosql/presto#2699]
Also allow `source` for compatibility with presto CLI.

Currently when connecting with the JDBC driver via DBeaver or SQuirreL SQL you can not set the property ApplicationName, source or client tags. 

ApplicationNamePrefix works since it is a custom property I think.

This means that resource group usage can not be use consistently for CLI and JDBC driver.

**Comment by mosabua** [comment]
Error message:

PrestoLocalhost: Unrecognized connection property 'ApplicationName'
class java.sql.SQLException: Unrecognized connection property 'ApplicationName'

**Comment by mosabua** [comment]
Standard properties should be preferred and work in my opinion.

https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#setClientInfo(java.lang.String,java.lang.String)

**Comment by findepi** [comment]
This can be worked upon once https://github.com/prestosql/presto/pull/2486 gets merged.
Also, if anyone wants to pick it up, that PR can server as a good starting point.

**Comment by mosabua** [comment]
Sounds. Imho we should ensure that CLI and JDBC driver are consistent and support the same properties.

**Comment by sajjoseph** [comment]
clientTags for JDBC is in progress here - #2468

**Comment by electrum** [comment]
We should name the connection parameter `source`, since that reflects the Presto naming, and matches the CLI. We only use `ApplicationName` for client info properties since that's the standard JDBC name

**Comment by mosabua** [comment]
Currently we support ApplicationNamePrefix in the JDBC driver, but we do not support the standard ApplicationName. In the CLI we support ClientTags but not in the JDBC driver.

Ideally we support a consistent set for both tools, any other driver or client tool and then also support those in the resource groups. I am not sure what the set should be however.

**Comment by electrum** [comment]
The driver now supports client tags.

There is a difference between client info and connections parameters. We support `ApplicationName` as a client info property and `ApplicationNamePrefix` as a connection parameter as a modifier for the client info property.

There is no such thing as a standard connection parameter, other than user and password.

**Comment by electrum** [comment]
Per our offline conversion, I created #3045 to summarize what needs to be done.
