### ISSUE TITLE
Views created in Hive is not supported in Presto

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2711]
hive> select * from t2;
OK
200
Time taken: 0.115 seconds, Fetched: 1 row(s)
hive> CREATE VIEW view1 AS SELECT id FROM t2;
OK
Time taken: 0.22 seconds
hive> show views;
OK
test
test_view
view1
Time taken: 0.012 seconds, Fetched: 3 row(s)
hive> select * from view1;
OK
200
Time taken: 0.155 seconds, Fetched: 1 row(s)

In Presto CLI when trying access the view it throws msg saying Hive Views are not supported.

presto:default> show create view view1;
Query 20200203_101149_00044_kmaa9 failed: Hive views are not supported: 'default.view1'

**Comment by tooptoop4** [comment]
that is known limitation, u need to create the view from presto cli/jdbc connection

**Comment by electrum** [comment]
We are working on adding support for this. First step is here: https://github.com/prestosql/presto/pull/2715

**Comment by findepi** [comment]
@AbhishekNew this is supported since https://github.com/prestosql/presto/pull/2715
of course, there are a lot of loose ends we will be tying up in coming releases, but this deserves individual issues, so let me close this.
