### ISSUE TITLE
JDBC PreparedStatement.setTimestamp is not implemented

### ISSUE THREAD

**Issue by edanayal** [prestosql/presto#2732]
I'm getting an error from Presto JDBC adapter ver 329: 
"Method PreparedStatement.setTimestamp is not yet implemented".

According to @kokosing , the unimplemented method is probably:
setTimestamp(int parameterIndex, Timestamp x, Calendar cal)

Using a different method instead is problematic when using a generic adapter interface. 
(like "public void setTimestamp(int parameterIndex, Timestamp x)")

Thank you

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/2733 should help. @edanayal do you have an option to build from source and try this out?

**Comment by edanayal** [comment]
I've just checked the new version 330 - works great! Thank you :-)
