### ISSUE TITLE
ARRAY comparison not supported for arrays with null elements

### ISSUE THREAD

**Issue by RosterIn** [prestosql/presto#2774]
`col_a` is of type `array(varchar)`
the column can contain nulls

consider following query:

```
SELECT id, 
        MIN(DISTINCT col_a)  FILTER (WHERE col_a is not null) AS col_a
FROM table
GROUP BY id
```

This query gives:

> ARRAY comparison not supported for arrays with null elements

This seems like a bug. The `FILTER` should be applied before `MIN()`

To mention :

```
SELECT id, 
        array_agg(DISTINCT col_a)  FILTER (WHERE col_a is not null) AS col_a
FROM table
GROUP BY id
```
Works but it converts `col_a` to be `array(array(varchar))` which is not desired.

**Comment by ebyhr** [comment]
The above filter isn't applied to each element. It makes sure whether  `col_a` is null (≒contains). 

You may want to use [filter](https://prestosql.io/docs/current/functions/array.html#filter) array function. 
> filter(array(T), function(T, boolean)) -> array(T)
> Constructs an array from those elements of array for which function returns true:

```sql
SELECT id, 
        MIN(DISTINCT filter(col_a, x -> x IS NOT NULL)) AS col_a
FROM table
GROUP BY id
```

**Comment by RosterIn** [comment]
I understand how you solution will work.
But I don't understand why my original solution doesn't work.
as you said it makes sure col_a doesn't have nulls then the values are distinct and then MIN() is added.

**Comment by findepi** [comment]
@RosterIn what is your actual query?

In your original query, you can replace `MIN(DISTINCT col_a) ` with `MIN(col_a)` to achieve the same result.
Does this help?

**Comment by ebyhr** [comment]
> count(col_a) FILTER (WHERE col_a >5)

The query won't work because the comparison is `array(integer)` vs `integer`. 

> Wouldn't the count consider only values where col_a> 5? what is the difference?

The type is difference.

**Comment by RosterIn** [comment]
> @RosterIn what is your actual query?
> 
> In your original query, you can replace `MIN(DISTINCT col_a) ` with `MIN(col_a)` to achieve the same result.
> Does this help?
@findepi 
No. It still gives the same error. This is my actual query with many more columns and complex FROM clause but at the end I group by id and all dimensions needs to be under aggregation function. 



> > count(col_a) FILTER (WHERE col_a >5)
> 
> The query won't work because the comparison is `array(integer)` vs `integer`.
> 
> > Wouldn't the count consider only values where col_a> 5? what is the difference?
> 
> The expected type and actual type are different. By the way, I would invite you to join the community Slack if you haven't yet joined. https://prestosql.io/slack.html

@ebyhr  I asked about count(col_a) FILTER (WHERE col_a >5) regardless of this type example. to better explain:
Why when x is integer and i do:  `count(x) FILTER (WHERE x >5)`  filter works but in my case it doesn't work.

I just don't understand what exactly happens when I use FILTER the way I did. obviously NULL values are being evaluated hence the error what I miss to fully understand this is why the NULL values weren't excluded in the FILTER.

**Comment by findepi** [comment]
@RosterIn consider:
```
SELECT ARRAY[42], ARRAY[NULL], CAST(NULL AS array(integer));
```

first constructs array with a number
second constructs array with NULL value
third constructs NULL array

When you do `MIN(DISTINCT col_a)  FILTER (WHERE col_a is not null)`, you filter out the third case, but not the second.

**Comment by RosterIn** [comment]
@findepi  thx now I understand. so I just missed condition in my query.

Thus
`MIN(DISTINCT col_a) FILTER (WHERE col_a is not null or col_a = ARRAY[NULL] )`
Should work and equivalent to:
` MIN(DISTINCT filter(col_a, x -> x IS NOT NULL)) AS col_a`

BTW is there a difference in terms of efficiency?

**Comment by ebyhr** [comment]
It's not equivalent in some cases because 
`MIN(DISTINCT col_a) FILTER (WHERE col_a is not null or col_a <> ARRAY[NULL] )` doesn't iterate all elements in an array.

**Comment by RosterIn** [comment]
OK I think I get it. In any case it needs to look into the elements with in the array
