### ISSUE TITLE
Auto-discover Cassandra protocol version

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#278]
Currently `io.prestosql.plugin.cassandra.CassandraClientConfig#protocolVersion` defaults to V3.
We should automatically select protocol version based on the Cassandra server we're connecting to.

**Comment by ebyhr** [comment]
fyi: We can get the protocol version using 
```sql
select native_protocol_version from system.local;
 native_protocol_version
-------------------------
                       4
```

**Comment by findepi** [comment]
cc @haaawk

**Comment by haaawk** [comment]
In general you don't have to set the protocol version. When unset, driver will negotiate the highest protocol version supported by both driver and the server.

See https://github.com/datastax/java-driver/blob/3.x/driver-core/src/main/java/com/datastax/driver/core/Cluster.java#L1648

You just need to make sure protocol options in configuration does not have initial protocol version set.

**Comment by ebyhr** [comment]
https://github.com/prestosql/presto/issues/587 is caused by default protocol version `V3`. It would be better to proceed this issue.

**Comment by ebyhr** [comment]
We can close this issue now.

**Comment by findepi** [comment]
Thanks @ebyhr 

Done in https://github.com/prestosql/presto/pull/596 (311).
