### ISSUE TITLE
Fail queries explicitly on ORC ACID tables before Hive 3

### ISSUE THREAD

**Issue by stagraqubole** [prestosql/presto#2790]
Queries fail today with 
```
Query 20200210_142822_00001_si8yh failed: Required field 'open_txns' is unset! Struct:GetOpenTxnsResponse(txn_high_water_mark:4, open_txns:null, min_open_txn:4, abortedBits:null)
```

**Comment by harmandeeps** [comment]
I am taking up this task, thanks.

**Comment by findepi** [comment]
Queries fail today (I updated the description with example failure). @harmandeeps what's your plan here?

**Comment by stagraqubole** [comment]
I had opened this looking at https://github.com/prestosql/presto/issues/2789. Query should have failed before reaching the point where the error was seen in that issue. We will identify that the table accessed is on Hive2 ACID and we will fail the query with clear message of Hive2 ACID tables not supported.

**Comment by harmandeeps** [comment]
@findepi : Hive 2.0 versioned transactional tables could only be bucketed tables with bucketing version 1.0. Therefore, the bucketing version can be used as a marker for Hive 2.0 versioned transactional table. As mentiond by @stagraqubole , we will fail the query with this message.

**Comment by findepi** [comment]
> Hive 2.0 versioned transactional tables could only be bucketed tables with bucketing version 1.0. Therefore, the bucketing version can be used as a marker for Hive 2.0 versioned transactional table

@harmandeeps 
Hive 3's code allows to have bucketed table without `bucketing_version` property (defaults to version 1).
Eg. Presto-created tables used to be this until I added support for bucketing versioned (or maybe they still default to no `bucketing_version` tbl property? idk)

(In fact, I expect that hive table created in Hive 2 will not have `bucketing_version` table property after env is upgraded to Hive 3.)

**Comment by harmandeeps** [comment]
@findepi : Yes, I checked that replying on bucketing_version is not a correct way.

One feasible solution is to check if base/delta directory has file '`_orc_acid_version`'. This file can be used a marker to check if Hive version is >= 3.0 (As mentioned at: https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java#L2555).

So, in Presto split loading logic, we can check if this file exists for an ACID table, if not, then throw an error.

**Comment by findepi** [comment]
@harmandeeps I drafted an alternative approach: https://github.com/prestosql/presto/pull/2826

**Comment by harmandeeps** [comment]
@findepi : Please correct me if I am wrong. I think your change fixes the case when Presto uses Hive Metastore < 3.0. 

But, in case, Presto uses HiveMetastore >= 3.0 (then all the checks added in your code will pass), a user queries an ACID table with version Hive 2.0, then it should fail the query saying that "ACID Hive 2.0 versioned tables are not supported, need to run compaction". That's what my fix will resolve.

**Comment by findepi** [comment]
> a user queries an ACID table with version Hive 2.0, then it should fail the query saying that "ACID Hive 2.0 versioned tables are not supported, need to run compaction"

That's the part i missed. Why is it so?

**Comment by harmandeeps** [comment]
@findepi : I checked manually by creating Hive 2 ACID table, then upgrading to Hive 3. In Hive 3, the delete deltas layout has been changed (link: https://jira.apache.org/jira/browse/HIVE-19598), so, AcidUtils doesn't return the delete deltas. Hive 2 ACID tables need to be major compacted to fix this.

**Comment by harmandeeps** [comment]
This should be fixed in Presto. I have created PR: https://github.com/prestosql/presto/pull/2989/commits/30266c0dc03f8a7c62bbcc76c76fd9fd2593cc41. Please review.
