### ISSUE TITLE
No sort icon but when use click column header it sorts the data

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2801]
When User move mouse over the Column header then cursor turns to hand and on clicking the data get sorted. Should be provided with sort icon and it should expand and collapse based on the user click operation. And sort icon should be provided across the pages in all tables where it is applicable.
![NoSortIconButSorting](https://user-images.githubusercontent.com/51321459/74307709-2503fd00-4d8c-11ea-98ad-f3707a72d02e.PNG)

**Comment by raghavsethi** [comment]
We should use icons from this library: https://getbootstrap.com/docs/3.3/components/#glyphicons

Specifically `glyphicon-triangle-bottom` and `glyphicon-triangle-top`
