### ISSUE TITLE
Query details search giving result for State Level text 

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2820]
User giving State: Text say 'Error' in Query details Search field,  is giving result. Which is not correct.
Because Search filed place holder says only:' User,source,query ID, resource group, or query text'
Attached are screen shot.
![QueryDetail_Search1](https://user-images.githubusercontent.com/51321459/74409495-d2dedc80-4e5c-11ea-9899-39e6fc0c2cd7.PNG)
![QueryDetails Search2](https://user-images.githubusercontent.com/51321459/74409508-da05ea80-4e5c-11ea-960f-da18c9e695bb.PNG)

**Comment by wendigo** [comment]
As I can see in the source-code it's intentional: https://github.com/prestosql/presto/blob/master/presto-main/src/main/resources/webapp/src/components/QueryList.jsx#L296

@martint should we fix "search input" placeholder text or remove filtering by query state?

**Comment by wendigo** [comment]
@findepi wdyt?

**Comment by martint** [comment]
We should fix the label. The idea of the search field is to look for anything in the query that might match

**Comment by wendigo** [comment]
Cool @martint - I'll make PR fixing label
