### ISSUE TITLE
Adding client tags to presto jdbc connection

### ISSUE THREAD

**Issue by palashgoel7** [prestosql/presto#2856]
From stackoverflow [https://stackoverflow.com/questions/60207690/adding-client-tags-to-presto-jdbc-connection](https://stackoverflow.com/questions/60207690/adding-client-tags-to-presto-jdbc-connection)

I am using jdbc to connect to presto server. 

From the documentation, I am able to connect to the server and run queries.
https://prestodb.io/docs/current/installation/jdbc.html

I am facing issues while sending ClientTags `(X-Presto-Client-Tags)` in the connection/statement.

Here's the function to build a connection and run a query.

    public void test() {
        java.util.Properties info = new java.util.Properties();

        if (PRESTO_USER != null) {
            info.put("user", PRESTO_USER);
        }
        if (PRESTO_PASSWORD != null) {
            info.put("password", PRESTO_PASSWORD);
        }
            info.put("ClientTags", "my,tag");

        try (Connection connection = DriverManager.getConnection(PRESTO_URL, info);
             Statement statement = connection.createStatement()) {
            testBody(connection, statement);
        } catch (Exception ex) {
            ex.printStackTrace();
            fail("Exception occured");
        }
    }

However, it fails with

    java.sql.SQLException: Unrecognized connection property 'ClientTags'
	    at com.facebook.presto.jdbc.PrestoDriverUri.validateConnectionProperties(PrestoDriverUri.java:316)

The workaround suggested by @findepi works very well. However, this should be handled by the driver itself.

**Comment by findepi** [comment]
@palashgoel7 thanks for raising the issue!

to anyone picking this up, you can e.g. follow example of "applicationNamePrefix"
https://github.com/prestosql/presto/blob/15fdd34d2f717eef81f599040936ba00b2128ff0/presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java#L194-L201

**Comment by electrum** [comment]
This is implemented in https://github.com/prestosql/presto/pull/2468

I’ll ping the author about addressing the comments so we can get it merged.
