### ISSUE TITLE
Elasticsearch Connector does not support username and password

### ISSUE THREAD

**Issue by hqisog** [prestosql/presto#2864]
example:

my es cluster config username is leno and password is leno.

when i  deploy Presto under the elastic user of Linux machine. it doesn't work.

[elastic@wh-8-148 bin]$ ./presto-cli --server localhost:8080 --user elastic --password elastic --catalog elasticsearch
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [elastic]
        at io.airlift.airline.SingleCommand.validate(SingleCommand.java:98)
        at io.airlift.airline.SingleCommand.parse(SingleCommand.java:65)
        at io.airlift.airline.SingleCommand.parse(SingleCommand.java:56)
        at io.prestosql.cli.Presto.main(Presto.java:24)

why?

**Comment by ebyhr** [comment]
The error message means the command line option is not correct. Could you try the following command and then input `elastic` to prompt? 
```
./presto-cli --server localhost:8080 --user elastic --password --catalog elasticsearch
```
Also, would you share the `elasticsearch.properties`?

I would recommend to join the community Slack https://prestosql.io/slack.html > #troubleshooting.

**Comment by hqisog** [comment]
elasticsearch.properties 

connector.name=elasticsearch
elasticsearch.host=11.2.8.10
elasticsearch.port=9200
elasticsearch.default-schema-name=es_test



 my Configurationis not right ? is it lack of  this.
elasticsearch.tls.enabled=true 
elasticsearch.tls.verify-hostnames=false
elasticsearch.tls.truststore-path=etc/elasticsearch/es_xpack.crt

**Comment by ebyhr** [comment]
If TLS isn't enabled in your Elasticsearch, you don't need to add the properties. 

Currently, password auth isn't supported in Elasticsearch connector for now, so please make sure the error message with the command I posted.  This is the related issue. https://github.com/prestosql/presto/issues/2127

**Comment by hqisog** [comment]
[elastic@wh-8-148 bin]$ ./presto-cli --server localhost:8080 --user elastic --password --catalog elasticsearch
Password: 
Exception in thread "main" java.lang.IllegalArgumentException: Authentication using username/password requires HTTPS to be enabled
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at io.prestosql.cli.QueryRunner.setupBasicAuth(QueryRunner.java:162)
        at io.prestosql.cli.QueryRunner.<init>(QueryRunner.java:93)
        at io.prestosql.cli.Console.run(Console.java:144)
        at io.prestosql.cli.Presto.main(Presto.java:31)


 i  use this command ,the result is error. so what should i do?

**Comment by hqisog** [comment]
ssl in es cluster is open  
xpack.security.transport.ssl.enabled: true

**Comment by ebyhr** [comment]
> i use this command ,the result is error. so what should i do?

Please try again without `--password` option.

**Comment by hqisog** [comment]
[elastic@wh-8-148 bin]$ ./presto-cli --server localhost:8080 --user elastic  --catalog elasticsearch
presto> show schemas;
       Schema       
--------------------
 es_test            
 information_schema 
 system             
(3 rows)

Query 20200218_054000_00006_6jpez, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:00 [3 rows, 46B] [13 rows/s, 208B/s]

presto> use es_test;
USE
presto:es_test> show tables;
Query 20200218_054012_00010_6jpez failed: method [GET], host [http://101.101.101.101:9200], URI [/_cat/indices?h=index&format=json&s=index:asc], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_cat/indices?h=index&format=json&s=index:asc]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/_cat/indices?h=index&format=json&s=index:asc]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

presto:es_test>

**Comment by hqisog** [comment]
there has Unauthorized error.

**Comment by ebyhr** [comment]
You need to disable authentication on Elastisearch or wait until https://github.com/prestosql/presto/pull/2311 will be merged. Let me close this issue because it's duplicated issue of #2127.

**Comment by hqisog** [comment]
thks you reply.

**Comment by hqisog** [comment]
@ebyhr How long can be support username and password  ？ can you give me an expectation. i need Make a plan.

**Comment by ebyhr** [comment]
@hqisog I'm asking the PR's author on Slack. Could you confirm (checkout, build & deploy) if the PR fixes your issue?

**Comment by hqisog** [comment]
i can try it.

**Comment by hqisog** [comment]
hi, this issue was solved? @ebyhr
