### ISSUE TITLE
Integer overflow when parsing dates beyond representable range

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2888]
Correct
```
presto:default> SELECT DATE '5881580-07-11';
     _col0
----------------
 +5881580-07-11
```

wrong:
```
presto:default> SELECT DATE '5881580-07-12';
     _col0
----------------
 -5877641-06-23
```

**Comment by wendigo** [comment]
Change to be made here: https://github.com/prestosql/presto/blob/ab0382cdd912bb1c8e5b5a0f7ac3733b13b51ab4/presto-main/src/main/java/io/prestosql/util/DateTimeUtils.java#L65 (toIntExact() will throw ArithmeticOverflowException so I guess it will be fine to wrap it in some presto exception)
