### ISSUE TITLE
can I use different memory config for different node?

### ISSUE THREAD

**Issue by magicsilence** [prestosql/presto#2893]
I have many  type machines, such as 8c16g, 16c32g...
Can i use diffenent config for them ?

**Comment by findepi** [comment]
@magicsilence 
it's complicated. In short -- yes, you can, but it's not recommended.
It will be hard to utilize hardware in 100%.

Let me close this. We can continue discussion here, but I'd recommend moving this on our slack https://prestosql.io/slack.html instead.
