### ISSUE TITLE
version: 330 ,  http://presto-server:8080/v1/cluster  404

### ISSUE THREAD

**Issue by Svti** [prestosql/presto#2895]
URI: | /v1/cluster
-- | --
404
Not Found
org.glassfish.jersey.servlet.ServletContainer-370c7cc5

**Comment by tchunwei** [comment]
I am facing this issue also, did you figure out what's wrong with this ?

**Comment by electrum** [comment]
@tchunwei can you file a new issue with more details?

**Comment by electrum** [comment]
Or ask on Slack: https://prestosql.io/slack.html

**Comment by tchunwei** [comment]
Just found out the changes in this commit.
https://github.com/prestosql/presto/commit/ff6d3e1e7343e7af1caac6ff352562d90277dfca#diff-0234c2f38498b581aa3eadc5f9302715
`/v1/cluster` has been moved to `/ui/api/stats`, after changing the url it does work properly now.
