### ISSUE TITLE
Prevent non-admins de-registering worker nodes or coordinator

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2911]
https://groups.google.com/forum/#!msg/presto-users/jK9gVmKKMk4/DBJCmbNdBQAJ mentions

curl -v -X PUT -d '"SHUTTING_DOWN"' -H "Content-type: application/json" http://presto-worker-1:8080/v1/info/state>>/tmp/prestonodeshutdown.log
OR
DELETE http request with url "/v1/announcement/". https://github.com/airlift/airlift/blob/5e77ec2c0d78d00525c97cdb025bcea814c59976/discovery/src/main/java/io/airlift/discovery/client/HttpDiscoveryAnnouncementClient.java#L128-L141 I'm guessing this turns off the coordinator.
This essentially means any authenticated user can cause a Denial-of-Service attack. This feature is about introducing a new config flag (deregisterEnabledForNonAdmin), that when set to false prevents any of the above unless user is an admin (as defined in authorisation Json).

**Comment by tooptoop4** [comment]
cc @dain

**Comment by dain** [comment]
This has been fixed since at least 337

**Comment by tooptoop4** [comment]
@dain how to define which users can trigger the shutdown? ie for graceful shutdown

**Comment by dain** [comment]
@tooptoop4 you need system information `write` permissions: https://prestosql.io/docs/current/security/built-in-system-access-control.html#system-information-rules
