### ISSUE TITLE
Java 13 support

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2914]
- [x] ensure code can be compiled with Java 13 (https://github.com/prestosql/presto/pull/3021)
- [ ] run tests with Java 13
- [ ] run product tests with Java 13 (ie with Presto containers running on Java 13)

**Comment by dain** [comment]
Can you be specific about what is not working for you?

**Comment by dain** [comment]
We are running some tests using Java 14 already (https://github.com/prestosql/presto/blob/master/.github/workflows/ci.yml#L21)  Is there more that you want?

**Comment by findepi** [comment]
To claim support for 14, we would need to run some product tests on Java 14 as well.
