### ISSUE TITLE
Build presto binaries JDK > 8

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2915]

**Comment by findepi** [comment]
What would be the benefit?

**Comment by tooptoop4** [comment]
Stepping stone to presto coordinator using HTTP 2
Eventual end-of-life of Java8, but still years away
Assumed performance benefits

**Comment by martint** [comment]
Presto can already run on newer versions of Java. In fact, we recommend running on Java 11 at a minimum.

The coordinator also supports HTTP/2 (both for the client protocol and for communicating to workers)

**Comment by tooptoop4** [comment]
i know java8 compiled binary can already run on java11.its low priority, just curious if compiling it on jdk11+ and running on java11 had perf benefit over the jdk8 compiled binary running on java11

**Comment by martint** [comment]
No, there are no performance benefits from that. The JVM does all its optimizations at runtime, and they work regardless of what version the code was compiled with.

The only benefit is that we can start using newer language features and JDK functions during development. We have a timeline for doing this switch, though. The latest version of Presto requires Java 11, but there’s a way to fall back to previous versions. In a few months, that requirement will be permanent and we’ll switch compilation to Java 11.

**Comment by tooptoop4** [comment]
https://github.com/prestosql/presto/issues/1169 suggests http2 has performance issue.

is there any reason below are not set to true by default?
	discovery.http-client.http2.enabled
	dynamic.http-client.http2.enabled
	event.http-client.http2.enabled
	failure-detector.http-client.http2.enabled
	memoryManager.http-client.http2.enabled
	node-manager.http-client.http2.enabled
	exchange.http-client.http2.enabled
	scheduler.http-client.http2.enabled
	workerInfo.http-client.http2.enabled

**Comment by martint** [comment]
> is there any reason below are not set to true by default?

Mostly because we haven't seen reports from people trying them out and indicating whether it works well for their uses cases. We've found some problems with the Jetty libraries over time and got them fixed. We'd like to see people try those settings, and if everything works as expected, we'll turn them on by default in a future release.
