### ISSUE TITLE
JXM typo instead of JMX on the website

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2936]
https://prestosql.io/docs/current/admin/properties.html

task.max-worker-threads
Type: integer
Default value: Node CPUs * 2
Sets the number of threads used by workers to process splits. Increasing this number can improve throughput, if worker CPU utilization is low and all the threads are in use, but it causes increased heap space usage. Setting the value too high may cause a drop in performance due to a context switching. The number of active threads is available via the RunningSplits property of the io.prestosql.execution.executor:name=TaskExecutor.RunningSplits **JXM** object.

**Comment by findepi** [comment]
@tooptoop4 do you want to do a PR?

**Comment by tooptoop4** [comment]
I would of but my first PR https://github.com/prestosql/presto/pull/2347 got discouraging nits

**Comment by findepi** [comment]
Would be good to outweigh that discouraging experience with a new PR.
