### ISSUE TITLE
Provide the project columns to ConnectorSplitManager.getSplits()

### ISSUE THREAD

**Issue by davidrabinowitz** [prestosql/presto#2943]
At the moment, the projected columns are provided just in the API of `ConnectorPageSourceProvider.createPageSource()`. For the BigQuery connector, the columns needs to be provided at the `ConnectorSplitManager` as at this point the `ReadSession` that contains the columns is created. 
This issues blocks Issue #2532 

This is per @findepi suggestion at https://github.com/prestosql/presto/pull/2532#discussion_r383209263

**Comment by electrum** [comment]
This should be possible today with `applyProjection()`. I ran `TpchQueryRunner` with a breakpoint in the default implementation in `ConnectorMetadata`, then ran `SELECT count(*) FROM tpch.tiny.region` and it's called as expected with an empty projection list.

**Comment by martint** [comment]
I don't think this is the direction we want to go. As David said above, the necessary information should be communicated to the connector via the `applyProjection` API. If that's not happening, we should figure out why.

**Comment by davidrabinowitz** [comment]
Ok, I'll check it out. Thanks

**Comment by davidrabinowitz** [comment]
Thanks for the tip, indeed I have managed with `applyProjection()`.
