### ISSUE TITLE
Refresh permissions from Hive file based authorization without restarting Presto

### ISSUE THREAD

**Issue by alrolorojas** [prestosql/presto#2954]
We'd like [Hive file based authorization](https://prestosql.io/docs/current/connector/hive-security.html#hive-file-based-authorization) file to be refreshed every X seconds/minutes similar to what we have for the [Built-in system access controls](https://prestosql.io/docs/current/security/built-in-system-access-control.html#refresh)

This would prevent us from having to restart Presto each time permissions are modified.

**Comment by kokosing** [comment]
It is already supported, please use:
```
security.refresh-period=5s
```
to refresh it every 5 seconds.
