### ISSUE TITLE
Provide --timezone CLI argument

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2961]
This is the most common reason people can't use CLI as a regular CLI and have to `java ... -jar presto-cli` instead.
Provide a direct support for this.

**Comment by dain** [comment]
You can use `TZ=UTC presto ...` for this today

**Comment by sanchitkashyap** [comment]
@findepi I would like to work on this, can this issue be assigned to me?

**Comment by martint** [comment]
@dain, yes, but that’s kind of “hidden”... it doesn’t show up in —help, it’s different than every other way to pass parameters to the CLI, etc

**Comment by electrum** [comment]
@sanchitkashyap please do! Let’s name the option `—timezone` as I can’t see a need for other types of time zones.
