### ISSUE TITLE
Showing access permissions for a Schema

### ISSUE THREAD

**Issue by lhofhansl** [prestosql/presto#2974]
When SQL Standard Authentication is enabled a schema is owned by its creator. 
The creator (and admin) have special rights on the schema.

When #2673 is merged the owner (or admin) can assign the schema to different user or role.

However, there's currently no way to tell who actually owns a schema.

This could be done in several ways:
- We could add SHOW CREATE SCHEMA schema, which would show some schema information as well as the current owner.
- Or we could add SHOW GRANTS ON SCHEMA schema, which would always show DELETE, INSERT and SELECT for the current owner. This is in anticipation that eventually we'll allow GRANTs to schemas.

In both cases it's not entirely clear who has the right to see this information. If only the owner can see that, it's kinda pointless, but if someone else could see this we'd leak some information.

Ideas? Comments?

**Comment by kokosing** [comment]
> We could add SHOW CREATE SCHEMA schema,

Yes we could. However, it won't solve your problem. Unless we would like to add syntax to create a schema and assign an owner in one statement, like `CREATE SCHEMA ... AUTHORIZATION owner`. Is there any DB that supports that? 

> Or we could add SHOW GRANTS ON SCHEMA schema

We could have `information_schema.schema_privileges` table like we do for table privileges.

> In both cases it's not entirely clear who has the right to see this information. If only the owner can see that, it's kinda pointless, but if someone else could see this we'd leak some information.

Correct. In regards to `information_schema.table_privileges` only an owner can see that he is an owner. Also, I guess that in Hive and sql-standard anyone with enabled `ROLE ADMIN` could also see it.

In general the best way would be to check what SQL standard defines for this.

**Comment by lhofhansl** [comment]
I was planning to add `CREATE SCHEMA ... AUTHORIZATION owner` soon.

**Comment by kokosing** [comment]
Yes, this sounds like the best idea here. Please do the research and see how other databases are doing this. Is this something specified in ANSI SQL? (cc: @martint )

**Comment by lhofhansl** [comment]
Here's the relavant part of the SQL (2003) standard:
```
<schema definition>    ::=   CREATE SCHEMA <schema name clause> [ <schema character set or path> ] [ <schema element> ... ]

...

<schema name clause>    ::=
         <schema name>
     |     AUTHORIZATION <schema authorization identifier>
     |     <schema name> AUTHORIZATION <schema authorization identifier>

<schema authorization identifier>    ::=   <authorization identifier> 
```
There's no standard for SHOW that I could find.

**Comment by lhofhansl** [comment]
This is what @martint suggested
```CREATE SCHEMA <name> AUTHORIZATION <owner>```

**Comment by kokosing** [comment]
👍

Are you going to the same for tables?
