### ISSUE TITLE
Multiple Presto catelogs with a single URI

### ISSUE THREAD

**Issue by rotivordep** [prestosql/presto#2982]
How can I add multiple catalogs on SQLAlchemy URI? I've tried presto://presto_address:port/catalog and it works, but I want to join cross databases with Presto DB. I already tried ";", ",", "/" to separate catalogs, but didn't work. I know the sintax is odbc://address:port/catalog/schema.

**Comment by ebyhr** [comment]
Are you using PyHive? 

By the way, thre is the good place to ask such kind of questions in Slack. 
https://prestosql.io/slack.html > `#troubleshooting`

**Comment by rotivordep** [comment]
> Are you using PyHive? Please share the current code if possible.
> 
> By the way, thre is a good place to ask such kind of questions in Slack.
> https://prestosql.io/slack.html > `#troubleshooting` channel

No. I'm using Presto only. How I join in the Slack channel? An adminstrator must invite me. If you can invite me, this is my email torivordep@gmail.com. Tks!

**Comment by ebyhr** [comment]
I sent an invitation.

**Comment by electrum** [comment]
The “sign up” link on https://prestosql.io/slack.html should allow you to sign up without an invite (it actually is the invite).

**Comment by ebyhr** [comment]
Going to close this issue because it depends on Superset implementation and we can use SQL Lab as alternative solution.
Related Slack thread: https://prestosql.slack.com/archives/CGB0QHWSW/p1583156913190800
