### ISSUE TITLE
Add support for MaxResults on Glue Hive Metastore

### ISSUE THREAD

**Issue by l1x** [prestosql/presto#2996]
I was tracing our Presto cluster with AWS CloudTrail and it issues a lot of GetPartitions (sometimes hundreds) for a table. We are using AWS Glue.

My first question is where is the MaxResults set to Presto?

https://docs.aws.amazon.com/glue/latest/webapi/API_GetPartitions.html

```
MaxResults
The maximum number of partitions to return in a single response.
Type: Integer
Valid Range: Minimum value of 1. Maximum value of 1000.
Required: No
```

**Comment by ebyhr** [comment]
Presto has `hive.max-partitions-per-scan` property (default: 100,000). Does this answer help you?

By the way, you can ask such kind of questions on our community Slack. 
https://prestosql.io/slack.html

**Comment by l1x** [comment]
> Presto has `hive.max-partitions-per-scan` property (default: 100,000). Does this answer help you?

No this is not the answer to my question. I think the MaxResults is not set (null) which results in defaulting to 1.

> By the way, you can ask such kind of questions on community Slack. I think you already joined there.
> https://prestosql.io/slack.html

Thanks.

**Comment by findepi** [comment]
@l1x i see you already did deep investigation. Do you think you know enough to propose a fix?

**Comment by l1x** [comment]
Sending the pull request soon.

**Comment by ebyhr** [comment]
As you already know, we haven't yet set `MaxResults` for Glue Hive metastore. (Sorry, I misunderstood your question)

**Comment by l1x** [comment]
> As you already know, we haven't yet set `MaxResults` for Glue Hive metastore. (Sorry, I misunderstood your question)

No worries at all. This is an important change form the performance point of view, I am not sure why AWS made it optional. We noticed it during a performance related investigation by accident.
