### ISSUE TITLE
Partition pruning seems to be not functioning for date type partitions with AWS Glue

### ISSUE THREAD

**Issue by l1x** [prestosql/presto#3002]
Having a table with date type partitioning key results in lack of partition pruning in the beginning of the select:

```SQL
SELECT *
FROM awsdatacatalog.db.table
WHERE
date_event_utc = CAST('2020-03-03' AS DATE)
AND hour_event_utc = '21';
```

From CloudTrail logs the correspoding GetPartitions request expression:

```
expression "(hour_event_utc='21')"
```

This results in reading way too much data when querying the table. The issue is gone if the partitioning key is string instead of date.

**Comment by findepi** [comment]
is `date_event_utc` a `date`, `timestamp` or `timestamp with time zone`?

**Comment by l1x** [comment]
> is `date_event_utc` a `date`, `timestamp` or `timestamp with time zone`?

date

**Comment by tooptoop4** [comment]
To enable this option, add hive.assume-canonical-partition-keys=true to the coordinator and worker config properties.

**Comment by l1x** [comment]
> To enable this option, add hive.assume-canonical-partition-keys=true to the coordinator and worker config properties.

Excellent thanks. Do you know more about what is _non-canonical_ about date partitioning keys?

I found the only reference to this in the Terradata documentations:

> Description: Disable optimized metastore partition fetching for non-string partition keys. Setting this property allows to avoid ignoring data with non-canonical partition values

https://teradata.github.io/presto/docs/141t/connector/hive.html

**Comment by findepi** [comment]
thanks @tooptoop4 .

**Comment by findepi** [comment]
@l1x the flag is because the search in metastore is done by string values and different string values can represent same part col value.
for example for date `2020-3-4` and `2020-03-04` are the same, yet the search "assuming canonical keys" would find only the second one

**Comment by l1x** [comment]
@findepi Alright, but how does this justify not using date partitioning keys by default? Wouldn't it make sense to at least warn the user about this?

**Comment by findepi** [comment]
Presto doesn't produce much warnings, because in practice no-one reads them.
More interesting would be if you could investigate, whether we needs this type of cautiousness for Glue at all.

**Comment by l1x** [comment]
The suggested fix did not solve our problems it still does not use the date field for partition pruning.

**Comment by l1x** [comment]
> Presto doesn't produce much warnings, because in practice no-one reads them.
> More interesting would be if you could investigate, whether we needs this type of cautiousness for Glue at all.

@findepi Good question. The problem is that worst case scenario (this is what we hit) there are many partitions in a table and partition pruning is essential for high performance. We only noticed this because we are facing continuous issues with Glue throwing exception of rate exceeded. I have seen this on the internet from more people who use Presto + Glue. This kicked out the investigation that resulted in the MaxResult pull request and this issue.
