### ISSUE TITLE
Inconsistent error reporting when schema does not exist

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3006]
```
presto> SELECT * FROM memory.xxx.yyy;
Query 20200305_113522_00005_kdbq9 failed: line 1:15: Schema xxx does not exist
```

```
presto> SHOW COLUMNS FROM memory.xxx.yyy;
Query 20200305_113603_00006_kdbq9 failed: line 1:1: Table 'memory.xxx.yyy' does not exist
```

```
presto> DESCRIBE memory.xxx.yyy;
Query 20200305_113620_00007_kdbq9 failed: line 1:1: Table 'memory.xxx.yyy' does not exist
```

Inconsistency:

* Error is about "Table does not exist" or "Schema does not exist"
* name is in apostrophes or not

**Comment by kokosing** [comment]
What should be our convention?

I prefer using quotes.

**Comment by findepi** [comment]
More importantly, error is about "Table does not exist" vs "Schema does not exist". I've updated description.

**Comment by agrawalreetika** [comment]
@findepi Is there anything pending as part of this task?

As per I checked all the above operations have consistent Error message -

presto> select * from memory.default.test;
Query 20200804_112041_00018_x7pvd failed: line 1:15: Table 'memory.default.test' does not exist
select * from memory.default.test

presto> SHOW COLUMNS FROM memory.default.test;
Query 20200804_112055_00019_x7pvd failed: line 1:1: Table 'memory.default.test' does not exist
SHOW COLUMNS FROM memory.default.test

presto> DESCRIBE memory.default.test;
Query 20200804_112102_00020_x7pvd failed: line 1:1: Table 'memory.default.test' does not exist
DESCRIBE memory.default.test

Please let me know if anything else has to be done in this open issue?

**Comment by ebyhr** [comment]
@agrawalreetika The pending part is Schema vs Table in the message. 
```bash
presto> SELECT * FROM memory.xxx.yyy;
Query 20200305_113522_00005_kdbq9 failed: line 1:15: Schema 'xxx' does not exist

presto> DESCRIBE memory.xxx.yyy;
Query 20200305_113620_00007_kdbq9 failed: line 1:1: Table 'memory.xxx.yyy' does not exist
```
While SELECT mentions Schema, DESCRIBE mentions Table.
