### ISSUE TITLE
Window and ORDER BY Spill To Disk

### ISSUE THREAD

**Issue by atris** [prestosql/presto#301]
Howdy!

Glad to see this effort. I wanted to check if we ported over the PRs myself and @sopel39 had worked on in the original repository for adding spill to disk for window aggregates and ORDER BY operator. Did those get committed yet?

**Comment by Praveen2112** [comment]
Hi,
I think it got committed (https://github.com/prestosql/presto/pull/228).

**Comment by atris** [comment]
Thanks.

Seeing the commits, I do not see the original PRs that I had raised, nor do the commits reflect anything about my co-authorship (
https://github.com/prestosql/presto/commit/d398d1c374a8d56e21a95ea3b6b84a4a5ff98268) and (
https://github.com/prestosql/presto/commit/24868b3481a974f3e068197d9c432788de9ddacb).

Was this intentional?

**Comment by atris** [comment]
cc: @sopel39 @findepi @mattsfuller

**Comment by dain** [comment]
Looking at the commits in two PRs, https://github.com/prestosql/presto/pull/228/commits and https://github.com/prestodb/presto/pull/11364/commits, I see your name attached to various commits in the both PRs, but unfortunately, it does look like we lost the author tag on one of the commits.

In the old PR, there are two commits with your name attached. The first one, https://github.com/prestodb/presto/pull/11364/commits/ee93b07629c2bc7b42d81f9cf9c02b0ea0e0a1f2 seems to match the https://github.com/prestosql/presto/pull/228/commits/8c5abca768bd9bf258be34b5ab0a5dd9d776ae41 which has you a the author.  The second commit https://github.com/prestodb/presto/pull/11364/commits/cc17ab5e785f2108567867d2345c1d09f73213e7 seems to match https://github.com/prestosql/presto/commit/d398d1c374a8d56e21a95ea3b6b84a4a5ff98268 no longer has you tagged as the author.

I apologize we messed this one up.  Please, don't attribute any malice to this, I am sure it was unintentional. Unfortunately, it is pretty easy for someone to accidentally lose the author tag when commits are reorganized (git only seems to allow one author per commit, so when squashing commits together, you always lose some of the authors). At this point, the code is already merged into master, and I am not aware of any way to fix this without rewriting the commit history, and force pushing over master branch.

I am sorry for any inconvenience this has caused you.

**Comment by atris** [comment]
Hi Dain,

Thanks for your reply.

I would like to mention two additional points here:

1) The commit which does not have my name is the actual main commit which introduces the real spill to disk functionality. It is very unfortunate that the feature on which I spent a couple of weeks was committed with no acknowledgement of my work in any form.

2) My name was omitted from not one, but two commits. Specifically, the actual commits which introduce spill to disk for window aggregates and spill to disk for order by aggregates totally gloss over the fact that I was the one who actually wrote those features:

Implement spill to disk for WindowOperator:
https://github.com/prestosql/presto/commit/d398d1c374a8d56e21a95ea3b6b84a4a5ff98268
Implement spil to disk for OrderBy operator:
https://github.com/prestosql/presto/commit/24868b3481a974f3e068197d9c432788de9ddacb

My original work on them:

https://github.com/prestodb/presto/pull/11364/commits
https://github.com/prestodb/presto/pull/11654

The second PR had a superseding version written by Piotr, but he
himself acknowledges that his PR is a curated version of my PR (please
see his comments).

I find it absurd that the two actual commits which introduced the
functionality I worked quite a bit for totally ignore any of my
efforts and do not acknowledge me. If Git history does not allow you
to mark my git handle as a co author, just a simple acknowledgement
which acknowledges me as the primary author would be good enough, as
is done by most ASF projects.
