### ISSUE TITLE
Cast first 64 bits of SHA1 to BIGINT?

### ISSUE THREAD

**Issue by marklit** [prestosql/presto#3011]
I'm able to produce SHA1 hashes from strings with the following:

```sql
SELECT SUBSTR(SHA1(CAST('test' AS VARBINARY)), 1, 8);
```

```
          _col0
-------------------------
 a9 4a 8f e5 cc b1 9b a6
```

Is there a way I could cast the above result to BIGINT? At the moment I'm getting the following:

```
SELECT CAST(SUBSTR(SHA1(CAST('test' AS VARBINARY)), 1, 8) AS BIGINT);
```

```
Query 20200305_143157_00105_hi6sc failed: line 1:8: Cannot cast varbinary to bigint
```

My application for the above is to shorten surrogate keys and ideally join two tables that contain billions and hundreds of millions of records respectively faster than they are currently with their long string surrogate keys.

**Comment by findepi** [comment]
> My application for the above is to shorten surrogate keys and ideally join two tables that contain billions and hundreds of millions of records respectively faster than they are currently with their long string surrogate keys.

The join is by hashed value (bigint) anyway, so it's can possibly be faster only if join by the short prefix _only_ (not two conditions: over prefix and full surrogate key).
Is this what you want?

**Comment by marklit** [comment]
If it is, then yes, that solves my problem. Thanks.
