### ISSUE TITLE
Presto queries involving partition column in hive scans the entire table

### ISSUE THREAD

**Issue by amalakar** [prestosql/presto#3014]
The performance difference is order of magnitude higher which is understandable. `$partition` query happens to be a metadata query only, while the other one ends up being full scan.

```
-- Query on $partitions take 250ms

presto> select max(ds) from hive.default."event_presto_query_logged$partitions";
   _col0
------------
 2020-03-04
(1 row)
Query 20200305_165426_03204_ua9r3, FINISHED, 2 nodes
Splits: 18 total, 18 done (100.00%)
0:00 [958 rows, 9.36KB] [2.04K rows/s, 19.9KB/s]

-- Query on the table takes 35s
presto> select max(ds) from hive.default.event_presto_query_logged where ds is NOT NULL;
   _col0
------------
 2020-03-04
(1 row)
Query 20200305_165512_03226_ua9r3, FINISHED, 110 nodes
Splits: 55,381 total, 55,381 done (100.00%)
0:35 [165M rows, 0B] [4.74M rows/s, 0B/s]
```

## Full Scan
<img width="1246" alt="scan-query" src="https://user-images.githubusercontent.com/65202/76011539-9d606880-5ec9-11ea-945a-e0b2ea8681b2.png">

## Metadata query only
<img width="1222" alt="metadata-query" src="https://user-images.githubusercontent.com/65202/76011572-a6e9d080-5ec9-11ea-8908-4c7bbb2faf89.png">

**Comment by raunaqmorarka** [comment]
You can enable `optimizer.optimize-metadata-queries` to make the second query into a metadata only query as well.
Without that flag also there is logic in `HivePageSource` to return pages with prefilled values for partition column keys without reading the values from file. However, we still open files and read the metadata and footer from them.

**Comment by amalakar** [comment]
Thank you @raunaqmorarka given `optimizer.optimize-metadata-queries=true` addresses the issue, I believe I can close this issue?
