### ISSUE TITLE
Unfair Behavior in PrestoSQL Community

### ISSUE THREAD

**Issue by atris** [prestosql/presto#302]
RE: https://github.com/prestosql/presto/issues/301

I had spent quite some time working on spill to disk for order by and spill to disk for window aggregates (both the PRs can be found in the issue mentioned above) but the commits that pushed those functionalities in PrestoSQL do not even mention my name, let alone associate my Github handle with the same.

This is a clear case of discrediting an author without informing him and forcefully taking credit of features by a specific set of committers from a single company.

I would like to raise this as a complaint to Presto Foundation and also would like to know the means to redressal since this is unfair behaviour and a clear case of harassement. I am sure there would be policies for addressing the same in the Presto Foundation and I would like to seek refuge in those.

**Comment by atris** [comment]
Also, please do not close this issue before we reach a resolution. Forcefully closing issues without giving a proper resolution is just another manifestation of high-handedness and dictatorial policies, which hopefully is not true with this community

**Comment by mattsfuller** [comment]
During the process of rebasing and preparing this PR to merge into master, some commits were squashed. This was a misunderstanding and unintentional. We took the following action and added a comment to the PR (https://github.com/prestosql/presto/pull/228#issuecomment-467424041). Based on our offline conversation and believe this is resolved.

**Comment by atris** [comment]
Yes, this is resolved now. Thank you

**Comment by atris** [comment]
As discussed offline, this has been resolved and no more discussion is required. PSF, please delete this issue
