### ISSUE TITLE
show functions like <pattern> not giving result as expected.

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#3039]
presto Version: 327
Hive show functions result:
hive> show functions like "a*";
OK
abs
acos
add_months
aes_decrypt
aes_encrypt
and
array
array_contains
ascii
asin
assert_true
atan
avg
presto show functions result
presto:default> show functions like 'a*';
 Function | Return Type | Argument Types | Function Type | Deterministic | Description
----------+-------------+----------------+---------------+---------------+-------------
(0 rows)

Query 20200309_090924_00016_ntks5, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0:02 [0 rows, 0B] [0 rows/s, 0B/s]
presto:default> show functions like 'abs';
 Function | Return Type  | Argument Types | Function Type | Deterministic |  Description
----------+--------------+----------------+---------------+---------------+----------------
 abs      | bigint       | bigint         | scalar        | true          | absolute value
 abs      | decimal(p,s) | decimal(p,s)   | scalar        | true          | absolute value
 abs      | double       | double         | scalar        | true          | absolute value
 abs      | integer      | integer        | scalar        | true          | absolute value
 abs      | real         | real           | scalar        | true          | absolute value
 abs      | smallint     | smallint       | scalar        | true          | absolute value
 abs      | tinyint      | tinyint        | scalar        | true          | absolute value
(7 rows)

**Comment by ebyhr** [comment]
The right pattern in Presto is `%` (≠`*`).

**Comment by AbhishekNew** [comment]
With % and _ it works fine.
