### ISSUE TITLE
current_date in docs is shown with braces

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3079]
https://prestosql.io/docs/current/functions/datetime.html#current_date:

> current_date()
>   Returns the current date as of the start of the query.

but in SQL this must be used without braces:

```
presto> SELECT current_date;
   _col0
------------
 2020-03-12

presto> SELECT current_date();
Query 20200312_100603_00004_kvt2r failed: line 1:20: mismatched input '('. Expecting: '%', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WHERE', '[', '||', <EOF>, <identifier>, <predicate>
```

Same applies to other `current_*` functions.

**Comment by ebyhr** [comment]
The page has this note ([session](https://prestosql.io/docs/current/functions/session.html) is also the same), but many people might miss it unless scrolling. 
<img width="1057" alt="Screen Shot 2020-03-14 at 14 41 42" src="https://user-images.githubusercontent.com/6237050/76675937-11a1b700-6602-11ea-8103-782091f244ca.png">
