### ISSUE TITLE
Deprecated checkCanSetUser is still required in implementing plugins

### ISSUE THREAD

**Issue by bolkedebruin** [prestosql/presto#3093]
While updating the Presto Ranger plugin I found that checkCanSetUser() is still required although it is mentioned as being deprecated and to use checkCanImpersonateUser(). I interpret deprecated as "don't use anymore"

```DEBUG	dispatcher-query-0	io.prestosql.security.AccessControl	Invocation of checkCanSetUser(principal=Optional.empty, userName='bolke') succeeded in 363.19us```

**Comment by findepi** [comment]
it's still called (to maintain backwards compatibility), but is not required.
https://github.com/prestosql/presto/blob/91d96a56447429f7b3c0e66116445a6be87ea17c/presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java#L77

**Comment by bolkedebruin** [comment]
If i dont implement it with a “just pass” it will always throw access denied

**Comment by electrum** [comment]
Yeah, you need to implement one of them to do the checks, and the other should do nothing.

**Comment by bolkedebruin** [comment]
But isnt that contrary to what deprecated means? “Only if present it will be executed and you should move away from it”

**Comment by dain** [comment]
Backwards compatibility is complex, and in this case this was the best decision we could come up with.

**Comment by dain** [comment]
I'm going to close this, but please reopen if you have more questions.
