### ISSUE TITLE
Phoenix  Date Time TIMESTAMP 

### ISSUE THREAD

**Issue by D-YuLin** [prestosql/presto#3108]
The date or time type is set in Phoenix. The complete timestamp is displayed in Phoenix, but only the year, month, day (hour), and minute (second) are displayed in presto, and the TIMESTAMP in Phoenix is not recognized in presto。

**Comment by ebyhr** [comment]
There are two issues in the description. 
1. Mapping DATE type between Phoenix and Presto
2. Support TIMESTAMP type

The 2nd issue is already filed as https://github.com/prestosql/presto/issues/2126. 

@vincentpoon I think you considered the mapping of DATE type when creating a connector. Do you have any opinion about this?

**Comment by D-YuLin** [comment]
Thank you for answering. At that time, timestamp was set in Phoenix, and it was not recognized in the presto column, and the column information was not visible. Later, the timestamp type in Phoenix was changed to bigint type. See the information recorded in the source code
`// TODO add support for TIMESTAMP after Phoenix adds support for LocalDateTime
            case TIMESTAMP:`
Used version 330,I don't know if this is the reason

**Comment by ebyhr** [comment]
I meant we haven't yet supported TIMESTAMP in Phoenix connector and it will be handled in the above issue. 

By the way, you may want to use `unsupported-type-handling` configuration properties (= unsupported_type_handling session properties) as the workaround.

**Comment by vincentpoon** [comment]
The `TIMESTAMP` type is not yet supported in the Phoenix connector.
I'm not sure I understand the `DATE` issue, if there is one.  It is supported.

**Comment by ebyhr** [comment]
@vincentpoon I guess he means Phoenix DATE's `hh:mm:ss` is trimmed by Presto.

**Comment by vincentpoon** [comment]
That is as expected, because Presto's `DATE` type does not include a time component.
Phoenix documentation explicitly states that it deviates from the SQL 92 standard in including a time component: https://phoenix.apache.org/language/datatypes.html#date_type

**Comment by electrum** [comment]
Maybe we should have an option to map Phoenix `date` to Presto `timestamp`?

**Comment by D-YuLin** [comment]
@ebyhr @vincentpoon 
Thank you for answering, as you said. 

Maybe my previous question description is ambiguous and embarrassing. 

 In our use case, the date type is used in Phoenix. Presto does not retain the time part. If the Time type is used, presto does not retain the date part. At that time, the timestamp type was used, and it was not recognized in presto. So, later I changed timestamp to bigint in Phoenix. Bypass this issue.
