### ISSUE TITLE
day_of_week add ability to retrun result by string

### ISSUE THREAD

**Issue by dephusluke** [prestosql/presto#3153]
The function returns number 1 for Monday etc..
This is good for calculations but I find myself many times need to add code to map it to strings for display.

Could there be something like `day_of_week(x, mode='num')`
num is the default where it will preserve the current behavior.
but it will also be possible to set `mode='string'`
In that case the func will return result as: `Sun,Mon, `etc..

**Comment by ebyhr** [comment]
We have `date_format` function supporting weekday name. Is it insufficient?
```sql
SELECT date_format(current_date, '%W');
```

**Comment by ebyhr** [comment]
Let me close this issue because we can achieve it using `date_format` function. Please reopen if you still need a new function.
