### ISSUE TITLE
Add SHOW PRINCIPALS for admin to see what roles were granted to users.

### ISSUE THREAD

**Issue by lhofhansl** [prestosql/presto#3167]
Apologies if I missed something.

A user can see all roles (s)he was granted, but there's no way I could find where an admin can see the membership of all roles or role assignments for all users. Neither through a SHOW command, nor via the information_schema.

An admin can create roles, assign roles to users, but has no way to see which roles were assigned to what user.

Is that intentional or simply missing?

**Comment by lhofhansl** [comment]
Hive has: `SHOW PRINCIPALS role;`

**Comment by kokosing** [comment]
I think it is missing. What ANSI SQL says about this? I guess there is some table defined in information_schema.

**Comment by lhofhansl** [comment]
The SQL standard does not have anything for SHOW, and each database does it differently. :(

In Postgres you issue \dg or \du in the shell. 

MySQL has SHOW GRANTS [FOR user [USING role]] and MySQL also lists which roles have been granted to a user, like this:
```
$ SHOW GRANTS FOR u1;

GRANT SELECT ON table TO us
GRANT r1,r2 TO u1
```
And even:
```
$ SHOW GRANTS FOR u1 USING r1;

GRANT SELECT ON table TO us
GRANT SELECT ON table2 TO u1
GRANT r1,r2 TO u1
```

So we could "just" add the "FOR" syntax and have SHOW GRANTS also show role assignments.
That part is only accessible to an admin.

**Comment by lhofhansl** [comment]
Snowflake has `SHOW GRANTS TO USER user`

Presto currently has: `SHOW ROLE GRANTS [ FROM catalog ]`, which shows the granted roles for the current user.

Perhaps the simplest (from the viewpoint of syntax at least) is to simply extend this to:
`SHOW ROLE GRANTS [ FROM catalog ] [ TO USER | ROLE principal ]`

That would align well with the CATALOG argument: If not specified the current catalog is used, otherwise the specified CATALOG. The TO argument would be same: Current user by default, otherwise the specified user or role.

Only an admin would be allowed to run this with `TO user` specified.

What do you folks think? Happy to do a PR if we agree.

**Comment by lhofhansl** [comment]
I verified that the Hive Metastore API has everything needed.
(can list roles for a principal, and can list principals for a role)

**Comment by lhofhansl** [comment]
Opinions? This seems to be an important gap.

What I'm looking is two abilities for an admin:
1. See all roles granted to a specific principal (role or user).
2. Given a role, show all principals that were granted that role.

(1) Could be `SHOW ROLE GRANTS [ FROM catalog ]` extended by ` [ TO USER | ROLE principal ]`
(2) Could be Hive's `SHOW PRINCIPALS role`

The meta point is: Most people defer these things to Hive still, I'd like to be able to do them straight through Presto.

I'm happy to start a PR. Maybe I'll start on with the proposed syntax changes so that we can have a look and try, and when that's OK fill is the access parts, tests, etc.

**Comment by lhofhansl** [comment]
Closing this.

This is now implemented via a new table `information_schema.role_authorization_descriptors`, which allows both the equivalent of `SHOW ROLE GRANTS TO` and `SHOW PRINCIPALS role`
See #3535
