### ISSUE TITLE
With SQLStandardAccessControl all users can see all schemas and all tables

### ISSUE THREAD

**Issue by lhofhansl** [prestosql/presto#3168]
Even listing schemas and tables can reveal information.

It would be better if users can only see:
- schemas they own (either directly or by role)
- tables they have any access permission to (any of SELECT, INSERT, DELETE)

The methods are already present in SQLBaseAccessControl, they just need to be implemented.

Catalog access is handled outside of the Hive connector (file based system access control)

It's not clear for Hive does.

**Comment by lhofhansl** [comment]
If people agree with the above, I'll do a PR.

**Comment by electrum** [comment]
This isn’t implemented because it’s very expensive, as the metastore has no bulk access for permission data. `SHOW TABLES` would have to do a fetch for each table.

Validating the schema is more doable as there are usually few schemas, plus users typically only access a single schema at a time.

**Comment by lhofhansl** [comment]
I see. We could simplify this such you can't any tables if you do not have access to the schema. Then it's a schema check only in both cases.

**Comment by lhofhansl** [comment]
Just this?

```
diff --git a/presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java b/presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
index ded7662a4a..7802eea038 100644
--- a/presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
+++ b/presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
@@ -83,9 +83,11 @@ import static io.prestosql.spi.security.AccessDeniedException.denyShowColumns;
 import static io.prestosql.spi.security.AccessDeniedException.denyShowCreateSchema;
 import static io.prestosql.spi.security.AccessDeniedException.denyShowCreateTable;
 import static io.prestosql.spi.security.AccessDeniedException.denyShowRoles;
+import static io.prestosql.spi.security.AccessDeniedException.denyShowTables;
 import static io.prestosql.spi.security.PrincipalType.ROLE;
 import static io.prestosql.spi.security.PrincipalType.USER;
 import static java.util.Objects.requireNonNull;
+import static java.util.stream.Collectors.groupingBy;
 import static java.util.stream.Collectors.toSet;
 
 public class SqlStandardAccessControl
@@ -202,12 +204,19 @@ public class SqlStandardAccessControl
     @Override
     public void checkCanShowTables(ConnectorSecurityContext context, String schemaName)
     {
+        if (!isDatabaseOwner(context, schemaName)) {
+            denyShowTables(schemaName);
+        }
     }
 
     @Override
     public Set<SchemaTableName> filterTables(ConnectorSecurityContext context, Set<SchemaTableName> tableNames)
     {
-        return tableNames;
+        return tableNames.stream()
+                .collect(groupingBy(SchemaTableName::getSchemaName, toSet())).entrySet().stream()
+                .filter(schema -> isDatabaseOwner(context, schema.getKey()))
+                .flatMap(schema -> schema.getValue().stream())
+                .collect(toSet());
     }
 
     @Override
```
Note: I haven't tried, this is for demonstration what I mean.

**Comment by lhofhansl** [comment]
Lemme just do a PR with tests, and then we can discuss there. It'll be quick.

**Comment by lhofhansl** [comment]
> Validating the schema is more doable as there are usually few schemas, plus users typically only access a single schema at a time.

In out case we'll have many schemas, and at least would want to hide tables in non-accessible schemas - see the PR, which does exactly that.

**Comment by kokosing** [comment]
How does SQL standard Hive behave when user has a SELECT privilege to a table? I would guess that then schema (database) that encloses this table, is visible for user?  If so, then for every schema that is not directly granted to user, we need to check all tables. Notice, that same story is for columns. Schema might be visible, whenever user has access to any column under this schema. That is so expensive to check.

**Comment by lhofhansl** [comment]
Hmmm... Interesting! `SELECT ... FROM TABLE s.t` still works even when a user has no access to schema `s`. (In Presto)

The problem is really twofolds:
1. There's no GRANT/REVOKE on schemas (the Hivemetastore seems to have it all, it's not implemented anywhere). So at the schema level it's all or nothing.
2. There's not bulk API to check permissions for HiveObjects.

I'll drop this line of development for now.
For our needs we'll likely either have a patched Hivemetastore that does not kind of filtering for us or that has a bulk api for access checks, along with a metastore proxy that tracks other things for us - such as usage, lineage, etc.

Closing this for now.

**Comment by kokosing** [comment]
Notice that it is quite easy to filter schemas with file based system access control. You could use it along with SQL standard. It is detached from HMS, but it is refreshable so you can write on your own something that could generate file with rules.
