### ISSUE TITLE
Result fields are misaligned when using subqueries with Kudu connector

### ISSUE THREAD

**Issue by fly0512** [prestosql/presto#3170]
--- this is a fact table
 CREATE TABLE kudu.test.test_fact (                       
    id varchar WITH ( primary_key = true ),    
    grade varchar WITH ( primary_key = true ),
    score varchar WITH ( nullable = true ),
    name varchar WITH ( nullable = true ),
    age varchar WITH ( nullable = true ),
    school varchar WITH ( nullable = true ),
	teacher varchar WITH ( nullable = true ),
	update_time varchar WITH ( nullable = true )
 )                                                       
 WITH (                                                  
    number_of_replicas = 3,                              
    partition_by_hash_buckets = 20,                      
    partition_by_hash_columns = ARRAY['grade','id']
 );
-- insert data
    insert into kudu.test.test_fact values('AA1','a1','99.0','stu1','12','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA2','a1','98.5','stu1','13','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA3','a2','96.5','stu1','14','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA4','a2','99.1','stu1','11','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA5','a4','88.5','stu1','12','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA6','a1','70.5','stu1','13','my school','hari','2018-01-18 14:00:53');
    insert into kudu.test.test_fact values('AA7','a4','90.5','stu1','10','my school','hari','2018-01-18 14:00:53');

-- The result is a field mismatch.Notice the teacher field in the query result,the value of the school field is displayed.
select t1.id as id ,t1.name as name,t1.score as score,t1.age as age,t1.teacher as teacher,t1.update_time as update_time
 from kudu.test.test_fact t1
  where (t1.grade = 'a1') and t1.age in (select age from kudu.test.test_fact) and t1.name is not null;

 -- When the school was checked out, the result showed normal, no dislocation. 
select t1.id as id ,t1.name as name,t1.score as score,t1.age as age,t1.school as school,t1.teacher as teacher,t1.update_time as update_time
 from kudu.test.test_fact t1
  where (t1.grade = 'a1') and t1.age in (select age from kudu.test.test_fact) and t1.name is not null;

![image](https://user-images.githubusercontent.com/50002522/77146305-b110ef00-6ac5-11ea-98b6-1b02c2d3104b.png)

**Comment by mozhou1991** [comment]
This is a problem at kudu

**Comment by fly0512** [comment]
Also in the kudu release, presto 324 does not have this problem.
