### ISSUE TITLE
Parsing Error: SQL Keyword Column Names Inside Hive `struct` and Presto `row` Types

### ISSUE THREAD

**Issue by jefflester** [prestosql/presto#3176]
A parsing exception is thrown when running a `SHOW CREATE TABLE` for a table that was created in Hive. The DDL contains column names that overlap with Presto's reserved SQL keywords (`end` and `by` in this case). The parser throws an exception similar to:

```
io.prestosql.sql.parser.ParsingException: line 1:1265: mismatched input 'end'. Expecting: <identifier>, <type>
```

To repro, create a table in Hive with the following DDL:

```
CREATE EXTERNAL TABLE `default.test`(
  `testCol0` struct<testStruct:string,stringCol:string>,
  `testCol1` struct<`end`:string,stringCol:string>,
  `testCol2` struct<`by`:string,stringCol2:string>
)
```

From Presto, you will get the error from `SHOW CREATE TABLE hive.default.test;` – you will also get the error if you create the same table in Presto with `row` types instead of the Hive `struct` type. This was tested against the latest versions of Presto and it appears to remain an issue. 

**EDIT**: I am sorely mistaken. My docker-compose.yml was pulling an older version than I realized. I tested against 331 (verified via `select * from system.runtime.nodes`). This appears to be fully compatible with Presto 331. If anything changes (I'll run a few more cases), I'll reopen. Thank you!

**Comment by jefflester** [comment]
My apologies for anyone who viewed this -- please see the update in the issue. My docker-compose.yml was pulling a stale image. I just re-tested on 331 (and made super-sure I was on 331), and it looks like the issue is resolved. 

**Hive**
```
CREATE EXTERNAL TABLE `default.test`(
  `testCol0` struct<testStruct:string,stringCol:string>,
  `testCol1` struct<`by`:string,stringCol:string>,
  `testCol2` struct<`end`:string,stringCol2:string>
  )
```

**Presto**
```
presto:default> show create table test;
                                 Create Table
------------------------------------------------------------------------------
 CREATE TABLE hive.default.test (
    testcol0 ROW(teststruct varchar, stringcol varchar),
    testcol1 ROW(end varchar, stringcol varchar),
    testcol2 ROW(by varchar, stringcol2 varchar)
 )
 WITH (
    external_location = 'hdfs://hadoop-master:9000/user/hive/warehouse/test',
    format = 'TEXTFILE'
 )
```

**Comment by electrum** [comment]
Thanks for confirmation. FYI, you can query `system.runtime.nodes` to see the server version.
