### ISSUE TITLE
Add system.jdbc.views table

### ISSUE THREAD

**Issue by dephusluke** [prestosql/presto#3194]
Presto has `system.jdbc.tables`
but there is no equivalent for views.

Say you want to count how many views you have.. there is no way.
Also even if you want just to verify view exist.. you must do select from the view there is no metadata table to use for that.

**Comment by ebyhr** [comment]
You may want to use `<catalog>.information_schema.views` table.

**Comment by findepi** [comment]
Would the following be helpful?
```
SELECT * FROM system.jdbc.tables WHERE table_type = 'VIEW'
```

**Comment by electrum** [comment]
The JDBC tables are intended for use by the JDBC driver. It’s recommended to use the `information_schema` tables instead.

**Comment by dephusluke** [comment]
> catalog.information_schema.views

awesome. wasn't aware of it.
