### ISSUE TITLE
Many test failures for TestFullParquetReader

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#323]
18 of 76 tests are currently failing, all with the same error:

```
java.lang.IllegalArgumentException: Encoding DELTA_BINARY_PACKED is only supported for type INT32
```

Hopefully, this is just a bug in the tests.

We should consider if it's worth moving `presto-parquet` module into a separate Travis job so that the tests can always be enabled. Running `TestFullParquetReader` in single thread took under 8 minutes on my laptop.

**Comment by electrum** [comment]
It turns out this was broken (by me) with the update to Hive `3.0.0` in 75828cf19e3a5ac5175227a92a29c683813ee1a2 which updated to Parquet `1.9.0`. I verified that the test passes on Parquet `1.6.0` and `1.8.1`.

@zhenxiao any ideas on this?

**Comment by zhenxiao** [comment]
whoops, did not see this. Let me take a look

**Comment by ryanrupp** [comment]
I remember I ran into this issue before when using `parquet-mr 1.9.0` or greater where `int64` delta encoding support was enabled, see [here](https://github.com/apache/parquet-mr/commit/8bcfe6c55e2588c1047368b4edbf733d1c1d5381) - specifically I was testing out writing timestamps as int64.

I think it should just be a matter of updating the check [here](https://github.com/prestosql/presto/blob/095ceaf9ef67ac1f42d2c9c9eb1bfb15ae27f86b/presto-parquet/src/main/java/io/prestosql/parquet/ParquetEncoding.java#L148) as int64 is now supported as well by the Parquet code base.

**Comment by electrum** [comment]
@ryanrupp Thanks for the info. Do you know the impact of incorrectly removing that check? Would the Parquet writer fail later (probably with a confusing error message), or would we write an invalid file?

**Comment by electrum** [comment]
@ryanrupp Thanks for the info. Do you want to put up a PR to remove the check?

**Comment by zhenxiao** [comment]
@ryanrupp is correct
Hi @electrum @ryanrupp I just posted a PR to fix it:
https://github.com/zhenxiao/prestosql/pull/1

**Comment by electrum** [comment]
Thanks @zhenxiao!

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/334 fixed the code, but we still can regress, as the tests are not enabled on Travis.
If we cannot add this long test to PR builds, let's run them on `master` builds only.
