### ISSUE TITLE
Phoenix Connector rowkeys spaces

### ISSUE THREAD

**Issue by bendemott** [prestosql/presto#3251]
@vincentpoon 
@electrum 

- HBase 1.5
- Phoenix 4.15

If spaces in the `rowkeys` argument are present, the Presto Phoenix Connector ignores all but the first rowkey value and creates the table anyway.

So this example query will succeed with a space in `recordkey, birthday` - but will create a rowkey with only `recordkey` in it.
```sql
CREATE TABLE myschema.scientists (
  recordkey VARCHAR,
  birthday DATE,
  name VARCHAR,
  age BIGINT
)
WITH (
  rowkeys = 'recordkey, birthday',
  salt_buckets = 10
);
```

The important bit here being: 
```
rowkeys = 'recordkey, birthday',
# -------------------^ (SPACE)
```
Spaces do not seem to matter in the native Phoenix client.

Can we at least fail with a syntax error? Thoughts?

**Comment by vincentpoon** [comment]
@bendemott The relevant code can be found here: [link](https://github.com/prestosql/presto/blob/master/presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixTableProperties.java#L151) 

Do you want to try adding a string trim there and see if it resolves your issue?

**Comment by bendemott** [comment]
@vincentpoon 

I experimented this afternoon, something akin to this resolved the issue, I'll get a PR tomorrow.
```
        List<String> names = Arrays.asList(StringUtils.split(rowkeysCsv, ','));
        List<String> names2 = names.stream().map(String::trim).collect(Collectors.toList());
```

**Comment by naveenmahadevuni** [comment]
hi, I would like to send a PR for this. I tested the fix. For the test case, I modified _TestPhoenixIntegrationSmokeTest#testCreateTableWithProperties_ test to have spaces in the rowkeys definition for the table and SHOW CREATE TABLE to verify that rowkeys are correctly created.

**Comment by losipiuk** [comment]
> hi, I would like to send a PR for this

Plase do :)

**Comment by naveenmahadevuni** [comment]
@losipiuk : Request to review PR #4384.

**Comment by naveenmahadevuni** [comment]
Closing. PR merged.
