### ISSUE TITLE
Error while accessing hive views when there is an empty string in the view definition

### ISSUE THREAD

**Issue by imjalpreet** [prestosql/presto#3266]
Issue Description: When trying to access a hive view which contains an empty string `''` (and this empty string isn't the last string with quotes `''` in the view definition) it throws an error in Presto.

For instance, let's assume we have two views,
**sample_hive_view_A**
```
CREATE VIEW `sample_hive_view_A` AS 
select cast(REGEXP_REPLACE(trim(`dual`.`dummy`), '^0+(?!$)', '') as varchar(40)) as `someCol` 
from `datadiscovery_db`.`dual`
```
and **sample_hive_view_B**
```
CREATE VIEW `sample_hive_view_B` AS 
select cast(REGEXP_REPLACE(trim(`dual`.`dummy`), '^0+(?!$)', '') as varchar(40)) as `someCol` 
from `datadiscovery_db`.`dual` where `dual`.`dummy` = '00031112'
```

When we try to access both the views from Presto, it works for **sample_hive_view_A** but throws an error for **sample_hive_view_B**
```
presto:datadiscovery_db> select * from sample_hive_view_A;
   somecol
-------------
 31112
 HA^G^FER$JY
(2 rows)

Query 20200328_121518_02767_pck3m, FINISHED, 2 nodes
Splits: 18 total, 18 done (100.00%)
0:02 [2 rows, 672B] [1 rows/s, 385B/s]
```
```
presto:datadiscovery_db> select * from sample_hive_view_B;
Query 20200328_121702_02768_pck3m failed: line 1:15: Failed parsing stored view 'hive.datadiscovery_db.sample_hive_view_b': line 1:151: mismatched input '00031112'. Expecting: ')', ',', 'ORDER'
select * from sample_hive_view_B
```

My RCA is as follow: The current REGEX pattern in the Class **HiveQlTranslation** considers the second successive `'` as the part of the quoted-string rather than the end of an empty string. I tried running the regex matcher on both the table definitions to make things a bit clearer.

<img width="1076" alt="Screenshot 2020-03-28 at 5 52 00 PM" src="https://user-images.githubusercontent.com/6432146/77822984-9f5ec580-711d-11ea-821a-a48139fcc12d.png">
<img width="1074" alt="Screenshot 2020-03-28 at 5 52 25 PM" src="https://user-images.githubusercontent.com/6432146/77822986-a8e82d80-711d-11ea-8ceb-ea3f15d6d494.png">

As can be seen, the current regex is not able to account for empty strings in the case when there is another quoted string present in the view definition later on.

**Comment by imjalpreet** [comment]
To solve this issue, a minor change in the regex would be sufficient. I can pick it up in that case.

**Comment by findepi** [comment]
While one can improve regex in `HiveQlTranslation`, in my opinion we shouldn't be using regex at all.
A state machine would be more future-friendly approach. 

@anusudarsan @kokosing  what do you think?

**Comment by kokosing** [comment]
yes, regex has short legs. However I am not sure if it is the moment to do this refactoring.

**Comment by electrum** [comment]
The current translation and is a placeholder and will be replaced with https://github.com/linkedin/coral so we shouldn’t spend time on substantial improvements.

**Comment by findepi** [comment]
@imjalpreet are you working on the fix?

**Comment by imjalpreet** [comment]
@findepi I can work on it. I wasn't sure about the priority of this so I did not proceed yet. Please let me know in case I should start working on the fix.
