### ISSUE TITLE
Incorrect pushdown in Kudu when value can be NULL

### ISSUE THREAD

**Issue by Crossoverrr** [prestosql/presto#3274]
Dear community, my friend @foxinmy found a problem we don't know if it has been Questioned@Answered.
When multiple conditions have the same column(and their logical relationship is or) then the 'is null' condition will be ignored, which lead to a problem that the data matches 'is null' condition will not be returned to the final ResultSet.
Sql is like :
`select * from profile where xwho='' or xwho is null;`
`select * from profile where distinct_id='xxx' and (xwho='a' or xwho is null)`
After debugging I think I might have found where the problem is:
in SortedRangeSet#union line 273:
![image](https://user-images.githubusercontent.com/33892550/77887161-b2e46a80-729c-11ea-80fa-dd9bc0df417f.png)
The code below will merge conditions that has same column into one SortedRangeSet according to their local attribute lowIndexedRanges. But 'is null' condition has a 0 size lowIndexedRanges, so this condition will not be unioned to the final SortedRangeSet, and also it will not be pushed-down to the TableScanNode.
`builder.addAll(checkCompatibility(valueSet).lowIndexedRanges.values());`

**Comment by Crossoverrr** [comment]
My prestosql version is 322.

**Comment by findepi** [comment]
@Crossoverrr `IS NULL` option is handled here:
https://github.com/prestosql/presto/blob/c683e77e53435416ada5db11e3187203cb2f7951/presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java#L225

did you try adding a repro test case to `TestDomain`?

**Comment by Crossoverrr** [comment]
Sorry I haven't add that test case about IS NULL option. I just debugging the sql.

**Comment by Crossoverrr** [comment]
So is that means when Domain#nullAllowed is true, it means IS NULL option, right?

**Comment by findepi** [comment]
> So is that means when Domain#nullAllowed is true, it means a NULL option, right?

Correct

**Comment by Crossoverrr** [comment]
Right! I've checked the final attribute constraintSummary in KuduClientSession#addConstraintPredicates, it's attribute nullAllowed is true definitely. So I have to push-down the IS NULL condition to KUDU right?
and this is a bug of kudu connector, not Presto, right?

**Comment by Crossoverrr** [comment]
![Screenshot from 2020-03-30 16-57-04](https://user-images.githubusercontent.com/33892550/77895047-c1d11a00-72a8-11ea-8836-183def5d3a91.png)

**Comment by findepi** [comment]
the Kudu pushdown code has other problems as well.

i did some quick cleanup (https://github.com/prestosql/presto/pull/3276). Please take a look.
I _did not_ fix this problem. 
Would be great to covert this with some kind of generic tests. 

@Crossoverrr if you are willing to work on this, can you first try adding a repro test case to
`io.prestosql.testing.AbstractTestDistributedQueries#testDataMappingSmokeTest`?

**Comment by Praveen2112** [comment]
@findepi For handling `io.prestosql.testing.AbstractTestDistributedQueries#testDataMappingSmokeTest` I guess we need to add support for creating a table with default partitions and support for inserting data for table with default partitions. A bit more cleanup is required I guess

**Comment by Crossoverrr** [comment]
OK, I will try :)

**Comment by Crossoverrr** [comment]
> the Kudu pushdown code has other problems as well.
> 
> i did some quick cleanup (#3276). Please take a look.
> I _did not_ fix this problem.
> Would be great to covert this with some kind of generic tests.
> 
> @Crossoverrr if you are willing to work on this, can you first try adding a repro test case to
> `io.prestosql.testing.AbstractTestDistributedQueries#testDataMappingSmokeTest`?

OK, I will try. :)
But please don't wait me, because I'm not very skillful. :)

**Comment by findepi** [comment]
@Praveen2112 does Kudu support only predicate pushdown on partition columns?

**Comment by Praveen2112** [comment]
I guess Kudu tries to apply the filter for non partition columns also. I will double check it.Though using the predicate that we apply on partition column he tries to skip certain tablets but for predicate on non partition column kudu performs a full data scan

**Comment by foxinmy** [comment]
![image](https://user-images.githubusercontent.com/1318274/77979287-cfcd7c00-7336-11ea-9a3c-9bafbcacee00.png)
