### ISSUE TITLE
Rest Api return  error  “/v1/resourceGroupState/global”

### ISSUE THREAD

**Issue by groobyming** [prestosql/presto#3299]
version：308
When I send a request to /v1/resourceGroupState/global, it returns as follows：
![image](https://user-images.githubusercontent.com/34335395/78109470-d4c02780-742b-11ea-94c0-bfaaae02962e.png)

But when I send the query, the api returns successfully. Why is the InternalResourceGroup initialized only after sending the query?
![image](https://user-images.githubusercontent.com/34335395/78109661-3bdddc00-742c-11ea-8761-0d385038c704.png)

**Comment by Praveen2112** [comment]
Name in resource group can be template (https://prestosql.io/docs/current/admin/resource-groups.html) in those cases we can't create a resource group when starting a server as we don't know the user upfront. So InternalResourceGroup is created on fly for each user when submitting a query. 

Special thanks for @findepi for enlightening me on this.

**Comment by groobyming** [comment]
Thanks for your help @Praveen2112
