### ISSUE TITLE
add function to validate uniqueidentifier 

### ISSUE THREAD

**Issue by RosterIn** [prestosql/presto#3303]
In [MsSQL](https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver15) there is support for `uniqueidentifier` which is used in many applications.

Basically I'm after a Presto function that will be able to verify if string is a valid `uniqueidentifier`

For example in `MsSQL`:
  ` SELECT CONVERT(uniqueidentifier,'0E984725-C51C-4BF4-9960-E1C80E27ABA0')`

Returns `0e984725-c51c-4bf4-9960-e1c80e27aba0` which means success.

However 

`SELECT CONVERT(uniqueidentifier,'0E984725-C51C-4BF4-9960-H1C80E27ABA0')` fails with 

`Conversion failed when converting from a character string to uniqueidentifier.`
as the string is not a valid `uniqueidentifier`/ `GUID` or [UUID](https://stackoverflow.com/questions/246930/is-there-any-difference-between-a-guid-and-a-uuid) if you wish 
Notice change of `E` to `H` in the first letter of the last substring

More info [here](https://www.sqlshack.com/understanding-the-guid-data-type-in-sql-server/)

This is very useful as `GUID` are used as primary keys in many system and Presto is analytical database so many ETLs want to verify that the data inserted into Presto is valid.

Feature Request: whether is convert or validate or anything you choose.. as long as there is a way to also support and verify the `GUID` type

Possible way to solve this is https://stackoverflow.com/questions/20041051/how-to-judge-a-string-is-uuid-type but I think that this data type is common enough to have it's own validation/conversion rather than ask users to do it themselves with regexp

**Comment by electrum** [comment]
Presto has a [UUID](https://prestosql.io/docs/current/language/types.html#uuid-type) type which should do what you want:
```
presto> select cast('0E984725-C51C-4BF4-9960-E1C80E27ABA0' as uuid);
                _col0                 
--------------------------------------
 0e984725-c51c-4bf4-9960-e1c80e27aba0 
(1 row)

presto> select cast('0E984725-C51C-4BF4-9960-H1C80E27ABA0' as uuid);
Query 20200401_153949_00001_chpq5 failed: Cannot cast value to UUID: 0E984725-C51C-4BF4-9960-H1C80E27ABA0
```

You can also use [`try_cast`](https://prestosql.io/docs/current/functions/conversion.html#try_cast) to convert invalid values to null:
```
presto> select try_cast('0E984725-C51C-4BF4-9960-H1C80E27ABA0' as uuid);
 _col0 
-------
 NULL  
(1 row)
```

**Comment by ebyhr** [comment]
Going to close this issue because we can achieve it easily using existing conversion function. Please feel free to reopen if needed.
