### ISSUE TITLE
Building prestosql (master branch) fails in presto-mysql: compilation failure

### ISSUE THREAD

**Issue by KentonParton** [prestosql/presto#3370]
When running `./mvnw clean install -DskipTests` against presto master branch, it fails in the presto-mysql directory with the following error trace:

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project presto-mysql: Compilation failure: Compilation failure: 
[ERROR] /Users/kentonparton/prestosql/presto/presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlJdbcConfig.java:[32,43] cannot find symbol
[ERROR]   symbol:   method parseURL(java.lang.String,<nulltype>)
[ERROR]   location: variable driver of type com.mysql.jdbc.Driver
[ERROR] /Users/kentonparton/prestosql/presto/presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlJdbcConfig.java:[45,43] cannot find symbol
[ERROR]   symbol:   method parseURL(java.lang.String,<nulltype>)
[ERROR]   location: variable driver of type com.mysql.jdbc.Driver
[ERROR] /Users/kentonparton/prestosql/presto/presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlJdbcConfig.java:[46,51] cannot find symbol
[ERROR]   symbol:   method database(java.util.Properties)
[ERROR]   location: variable driver of type com.mysql.jdbc.Driver
`

Does a mysql driver need to be added somewhere in the presto-sql directory?

**Comment by findepi** [comment]
ongoing discussion https://prestosql.slack.com/archives/CP1MUNEUX/p1586276767127200

**Comment by KentonParton** [comment]
Managed to resolve this issue by changing my JAVA_HOME path to point to version 11.
