### ISSUE TITLE
last_value() returns wrong results

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#339]
```select a, b, last_value(b) over (partition by a order by b) last_b from (values(1,1),(1,2),(1,3),(2,0)) as t(a,b) order by a,b```

results with:
```
a | b | last_b
--| --| --
1 | 1 | 1
1 | 2 | 2
1 | 3 | 3
2 | 0 | 0
```

while expected:
```
a | b | last_b
--| --| --
1 | 1 | 3
1 | 2 | 3
1 | 3 | 3
2 | 0 | 0
```

**Comment by martint** [comment]
That is actually how it's supposed to work. The default window frame is “range between unbounded preceding and current row”. You need to use “range between unbounded preceding and unbounded following” to get that behavior.
