### ISSUE TITLE
Reduce RPM size

### ISSUE THREAD

**Issue by martint** [prestosql/presto#3399]
The RPM is ~1015MB. This is close to the 1GB limit allowed by Sonatype, so we need to reduce it to avoid finding ourselves unable to release Presto.

Rehashing one idea from @electrum and @findepi, when building the RPM we could relocate libraries that are common across multiple plugins to a `/shared` folder and replace them with symlinks.

~We should also consider adding a check to the build to ensure no artifact crosses the 1GB limit. This will allow us to catch PRs that will get us over the edge before they get merged~ → covered by #3401

Note: there is also a discussion on #rpm-size channel.

**Comment by yuokada** [comment]
Duplicate: https://github.com/prestosql/presto/issues/2530 ?

**Comment by martint** [comment]
Indeed! I forgot I filed that one. I'll close the other one, since this one is more current and has a couple more details on possible things to do.

**Comment by findepi** [comment]
We need to fix this to be able to add a plugin (eg https://github.com/prestosql/presto/pull/3522) cc @samarthjain
@jvanzyl how hard would it be to do the symlinks trick?

**Comment by jvanzyl** [comment]
We would need to incorporate the hard-linked tar.gz into the RPM. I believe it would be possible to package up the tar.gz in the RPM and create an enumeration of the files as not to affect normal installation and updating mechanisms that rely on the explicit listing of files.

So this is blocking the next release?

**Comment by findepi** [comment]
> So this is blocking the next release?

No, this is blocking a PR: https://github.com/prestosql/presto/pull/3522
(Thanks to https://github.com/prestosql/presto/pull/3404 we didn't get into unreleasable state)

What about symlinks?
That sounds simpler and doesn't seem like RPM tools could complain?
(We could do symlinks for .targz for consistency too, if desired)

**Comment by bolkedebruin** [comment]
Just a suggestion: why not package the plugins in separate rpms? Cause this issue is bound to pop up rather sooner than later this way? It seems also the accepted pattern in rpm land. 

https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch10s04.html

**Comment by electrum** [comment]
@bolkedebruin This seems reasonable, but is a departure from the way it works today, and might be more difficult for some users, as they would need to download and manage multiple RPMs. I could see providing this in addition to an all-in-one RPM. @jvanzyl suggested we could provide a tool to convert the tarball into an RPM containing the user's choice of plugins.

The tarball is around 400MB after de-duplicating all of the JARs across plugins, and it grows slowly, as the size is the sum of unique library versions.

**Comment by bolkedebruin** [comment]
@electrum there are also things like "Uber" rpms that basically pull in a bunch of other as their dependencies. Or group rpms. You could leave those named the same and it would pull in everything.

**Comment by electrum** [comment]
That’s a good idea, though we’d need a way to add a repository so that users don’t have download it manually. I’m not sure what is involved or if that is compatible with Maven Central.
