### ISSUE TITLE
Allow mixed case partitions for Hive sync_partition_metadata

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#3431]
The Hive `system.sync_partition_metadata` procedure allows discovering partitions on the file system that match the Hive naming convention. For compatibility with Hive's `MSCK REPAIR TABLE`, partition names must be in lowercase by default. However, for users that wish to use it with mixed case names, we can add a new `case_insensitive` argument to allow this behavior.

**Comment by kkond** [comment]
Hello, I would like to work on this. Thanks!
