### ISSUE TITLE
Substring function does not support CHAR type

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3457]
While `substr` function accepts char type, `substring` function doesn't.
```sql
SELECT substr(cast('abcd1234' as char(8)), 1, 4);
→ OK
```

```sql
SELECT substring(cast('abcd1234' as char(8)), 1, 4);
→ Unexpected parameters (char(8), integer, integer) for function substring. Expected: substring(varchar(x), bigint, bigint) , substring(varchar(x), bigint)
```
https://prestosql.io/docs/current/functions/teradata.html

**Comment by findepi** [comment]
`substring` is part of teradata functions
(when we have function namespaces, this will be more clear to users as well).

@ebyhr did you check that `substring` in teradata works with `char` values  too?

**Comment by findepi** [comment]
Requires #3456 being resolved first.

**Comment by ebyhr** [comment]
Yes, I checked it before filing the issue.
