### ISSUE TITLE
Azure configuration is missing from Hive connector documentation

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3471]
https://prestosql.io/docs/current/connector/hive.html has no mention of Azure. But there is mention about 'Amazon' and 'Google Cloud'

a google search of 'azure site:prestosql.io'  does not show anything relevant either.

only the PR https://github.com/prestosql/presto/pull/2494/files shows some details like "hive.azure.abfs-access-key", "hive.azure.wasb-storage-account" etc

**Comment by mosabua** [comment]
I will take care of this in the linked PR.

**Comment by mosabua** [comment]
Done.

**Comment by tooptoop4** [comment]
@mosabua there is "Google Cloud Storage Configuration" section but  no section on configuring azure

**Comment by mosabua** [comment]
I thought you just meant the mention of Azure in the overview.

**Comment by mosabua** [comment]
Here is the change that now mentions Azure. https://github.com/prestosql/presto/commit/d91c816cd019e7e6d1a6d908caf055d79ca3cbe9
This will go live with 334 publishing .. probably later this week.

**Comment by mosabua** [comment]
We will have to look what to add with regards to specific properties.

**Comment by tooptoop4** [comment]
fixed by https://github.com/prestosql/presto/commit/53f876309a9264881ddddc768a02e35852e12ce2
