### ISSUE TITLE
Rubix initialization failure on coordinator renders Hive connector unusable

### ISSUE THREAD

**Issue by losipiuk** [prestosql/presto#3489]
Currently Presto process is not terminated if Rubix initialisation driven by `io.prestosql.plugin.hive.rubix.RubixInitializer` fails. The Presto continues to run even though Rubix services are not running. 
At this point any query touching Hive data will hang (and hopefully eventually fail) as worker nodes cannot connect to cache bookkeeper running on coordinator.

Possible fixes:
* Fail whole Presto process if Rubix caching is enabled but initialisation cannot be performed
* Improve/add failover mechanism, so non-cached access to data is performed, if Bookkeeper cannot be accessed.

**Comment by findepi** [comment]
Since caching is internal "service" of Presto, it should be treated as any other internal component. Initialization failure should fail fast.
This is a general rule. Are there any compelling reasons to make an exception in this case?

**Comment by losipiuk** [comment]
> Initialization failure should fail fast.

Product-wise, the only reason I can think of, why it got implemented this way, is that maybe we cannot distinguish a fatal error, which will not fix itself in the future (e.g. misconfiguration), from something transient.
But if that is the case, treating all errors as permanent is safer approach.

Not sure if that is easy to achieve above implemntation-wise (I did not investigate yet).

**Comment by sopel39** [comment]
PR: https://github.com/prestosql/presto/pull/3749
This PR will make Presto wait until Rubix initializes and fail-fast when Rubix fails to initialize for whatever reason.

**Comment by findepi** [comment]
> This PR will make Presto wait until Rubix initializes

how long can this be?

**Comment by sopel39** [comment]
> how long can this be?

Until coordinator starts-up really.
