### ISSUE TITLE
Remove "Blocked Time" from the web ui

### ISSUE THREAD

**Issue by dain** [prestosql/presto#3511]
Most users believe `Blocked Time` in the web ui is the amount of time the whole query was blocked.  Instead it is the sum of the time any individual, parallel, thread of the query is blocked. For example, the intermediate stages of a query spend most of their time blocked waiting for data from the table scan stages, and in that case the user would not expect blocked time to increase.   This value has no real use and should be removed from the UI.

**Comment by dhruvp-8** [comment]
@dain Can I take up this issue?

**Comment by findepi** [comment]
@dhruvp-8 sure, go for it!

**Comment by faridgt** [comment]
CPU Time | 18.62s
Blocked Time | 7.15m

in this case it should be a real block time
