### ISSUE TITLE
Presto does not support Chinese

### ISSUE THREAD

**Issue by chenjian2664** [prestosql/presto#3517]
Presto versions 330 to 332 do not support Chinese, but they are supported on version 310. Not sure which version is the earliest unsupported.

For example :
Select *  from table where col = '中文'. 
It will return empty from 330 to 332, but on 310 return correct data.

For Now I must write sql like this if field contains Chinese.
Select * from table where to_utf8(col) = to_utf8('中文')

**Comment by ebyhr** [comment]
Could you share the original table definition and the database version? (Hive DDL if you are using Hive connector)

**Comment by lxqfy** [comment]
@ebyhr  DDL is as follows. Hive version 1.2.2.
> CREATE EXTERNAL TABLE `test_table`(
  `cola` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://tl0/dataflow/salesforce/seller_index_tab/grass_date=2020-04-22/grass_region=TW'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='true',
  'numFiles'='0',
  'numRows'='0',
  'presto.numRows'='0',
  'presto_query_id'='20200423_035501_05988_budrp',
  'presto_version'='presto330',
  'rawDataSize'='0',
  'totalSize'='0',
  'transactional'='false',
  'transient_lastDdlTime'='1587614102')

**Comment by ebyhr** [comment]
Can you attach the parquet file?

**Comment by chenjian2664** [comment]
@lxqfy

**Comment by lxqfy** [comment]
@ebyhr  I can generate a parquet file to exclude the confidential info.  I happened to found that these 2 files with a 1-row difference(`S-life`), the one with fewer rows works. 
[part-00000-e8ba5864-1f98-4a23-8976-1f519ebe6700-c000.snappy.parquet.zip](https://github.com/prestosql/presto/files/4521299/part-00000-e8ba5864-1f98-4a23-8976-1f519ebe6700-c000.snappy.parquet.zip)
[part-00000-e8ba5864-1f98-4a23-8976-1f519ebe6700-c000.snappy.parquet.zip](https://github.com/prestosql/presto/files/4521301/part-00000-e8ba5864-1f98-4a23-8976-1f519ebe6700-c000.snappy.parquet.zip)

**Comment by ebyhr** [comment]
Thanks for providing the file! I could reproduce it. Let me investigate the details.

**Comment by lxqfy** [comment]
@findepi The parquet file is created with Spark.

**Comment by ebyhr** [comment]
@lxqfy Could you share more details with the script level (e.g. sql, pyspark)? Both parquet files are almost the same except for 1 row, so I would like to know how the difference was generated.

**Comment by lxqfy** [comment]
@ebyhr It is generated with pyspark.  The original file has many columns and around 120k rows.  I tried to exclude that confidential info. So I only selected 1 column to generate the new parquet file. Then I found that if I limit the number of rows selected, it works sometimes. After trial and error, I located the problematic row (88th row), which `S-life`.  As attached, 1 file has 87th and 88th selected, the other has only 87 selected.

**Comment by ebyhr** [comment]
@lxqfy I see, thanks for your explanation. I'm not sure, but the root cause might be the same as https://github.com/prestosql/presto/issues/1462

**Comment by lxqfy** [comment]
@ebyhr According parquet meta.
```
gp_account_name:  BINARY SNAPPY DO:0 FPO:4 SZ:125/123/0.98 VC:2 ENC:BIT_PACKED,PLAIN,RLE ST:[no stats for this column]
```
The parquet has no stats for this column. It should scan the details right?

**Comment by findepi** [comment]
> Select * from table where col = '中文'.
It will return empty from 330 to 332, but on 310 return correct data.

@lxqfy what happens if you add `OR rand() = 42` to your query? (this is a hack to disable any form of predicate pushdown)

**Comment by chenjian2664** [comment]
@findepi 
It works.

**Comment by tooptoop4** [comment]
"select * from external_table where from_utf8(to_utf8(cola))='科技有限公司';  this will work if converting to binary and converting back. "

**Comment by findepi** [comment]
@chenjian2664 thanks for checking. I understand that you mean that with `OR rand() = 42` you get correct results (and you don't get them without this `OR`).

@lxqfy you provided parquet metadata for `gp_account_name`.
Is this the column you're querying? (Double checking as in other places you call it `col`, for obvious reasons).

If this is the column, then this is not related to https://github.com/prestosql/presto/issues/1462 because that was about stats.

@lxqfy @chenjian2664 not sure how familiar you are with Presto development. Would you be able to bisect to narrow down 310-332 range, possibly to an individual commit?

**Comment by ebyhr** [comment]
I'm also narrowing down the version. 

Though parquet-tools exactly reports no-stats, I got the following error on 310. I could access it after changing fail-on-corrupted-statistics. 

```
Corrupted statistics for column "[gp_account_name] optional binary " in Parquet file "hdfs://hadoop-master:9000/tmp/chinese/part-00000-e8ba5864-1f98-4a23-8976-1f519ebe6700-c000.snappy.parquet": [min: 0xE4B887E88DA3E58EBFE8A7A3E5BA97E7BAA2E68F90E59D8AE69C8DE8A385E7BB8FE99480E5BA97, max: 0x532D6C696665, num_nulls: 1]
```

**Comment by findepi** [comment]
That's my fault.

**Comment by i95271116** [comment]
hi. I have also encountered this problem. Is there a solution yet?
