### ISSUE TITLE
Improve rubix initialisation phase

### ISSUE THREAD

**Issue by stagraqubole** [prestosql/presto#3525]
1. Inject HdfsConfigurationInitializer in RubixInitializer so that Configuration used by it can get configs from `hive.config.resources` files

2. Ensure RubixConfigurationInitializer is last entry in iteration of `configurationInitializers` in HdfsConfigurationInitializer as it needs to override `fs.impl` configs set by other configInitializers

3. If RubixInitializer takes time to set up, threadLocal `hadoopConfiguration` in HiveHdfsConfiguration can get configured without configs injected by RubixInitializer

**Comment by stagraqubole** [comment]
For (2): We are getting RubixConfigurationInitializer as last entry in iteration of `configurationInitializers` but there are not guarantees for this. [Multibinder doc](https://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/multibindings/Multibinder.html) says: `The set's iteration order is consistent with the binding order. This is convenient when multiple elements are contributed by the same module because that module can order its bindings appropriately. Avoid relying on the iteration order of elements contributed by different modules, since there is no equivalent mechanism to order modules.`

**Comment by stagraqubole** [comment]
For (3), options are:
i. Use `RubixConfigurationInitializer` as `DynamicConfigurationProvider`. `RubixConfigurationInitializer` holds back from applying any config changes until it is informed of rubix initialisation being completed. Using `DynamicConfigurationProvider` approach, it would start applying configs when it is ready to.

or

ii. Make rubix initialisation blocking. This will hold the server startup process until master node is discovered and rubix is initialised.

**Comment by sopel39** [comment]
Fixed via: https://github.com/prestosql/presto/pull/3729
