### ISSUE TITLE
Rename hive.cache.parallel-warmup-enabled

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3556]
the name `hive.cache.parallel-warmup-enabled` is not self-descriptive

property "description": https://github.com/prestosql/presto/issues/3494#issuecomment-619771104

cc @stagraqubole @losipiuk

**Comment by losipiuk** [comment]
maybe something like `hive.cache.warmup-mode` with possible values `read-through`, `async` would be better?
WDYT?

**Comment by losipiuk** [comment]
LGMT

**Comment by findepi** [comment]
@losipiuk can you please open a PR?

**Comment by losipiuk** [comment]
I will

**Comment by losipiuk** [comment]
@findepi: Can we drop support for `hive.cache.parallel-warmup-enabled`. Or do I need to implement logic which allows using both old and new property and only fail if both are explicitly set in uncompatible way?

**Comment by findepi** [comment]
i think we're early in the game, so we can drop
