### ISSUE TITLE
Add support for Authenticator plugins

### ISSUE THREAD

**Issue by knwg145** [prestosql/presto#3572]
We have an internal authenticator implementing the Authenticator interface. That authenticator will integrate with various internal libraries and currently uses various information from the HttpServletRequest. There is a PasswordAuthenticator but the interface only passes in a user and password, whereas we need other information from the HttpServletRequest. Specifically we are using:

-headers (AUTHORIZATION and X_FORWARDED_FOR)
-remote address

We want to move this internal authenticator out of the Presto code into its own plugin, so we want to see if we can create a mechanism to load Authenticators into Presto. What would be an appropriate interface for this?

**Comment by electrum** [comment]
Do you need the ability to send back a `WWW-Authenticate` header on failure?

**Comment by knwg145** [comment]
yes

**Comment by electrum** [comment]
Duplicate of #2117
