### ISSUE TITLE
Parquet predicate pushdown maps columns incorrectly

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3574]
https://github.com/prestosql/presto/blob/922f1712462421fb13ef59de894999cdf44c6afd/presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java#L326

- ~should match case-insensitively like in https://github.com/prestosql/presto/blob/237313b11f6e27356b48c014bb9ee53cb1e7af6c/presto-parquet/src/main/java/io/prestosql/parquet/ParquetTypeUtils.java#L171-L180~ (https://github.com/prestosql/presto/issues/4009)

- should match by index, when `!useParquetColumnNames`

**Comment by tooptoop4** [comment]
it's not clear on the impact or how to replicate this issue
