### ISSUE TITLE
MongoDB case sensitive support

### ISSUE THREAD

**Issue by d4rth-v4d3r** [prestosql/presto#3593]
I have a MongoDb database with collections that have camelCase naming convention, but I'm unable to query tables like: "userTags" or "customerTypes". Is there any way to make PrestoDb Mongo connector to work with this use case?

**Comment by ebyhr** [comment]
Going to close because this is a duplicate of https://github.com/prestosql/presto/issues/1102. 
It's not yet supported.

**Comment by d4rth-v4d3r** [comment]
Is there any plans to support it? @ebyhr

**Comment by ebyhr** [comment]
@d4rth-v4d3r Please take a look at the above issue. It has linked PR.

**Comment by d4rth-v4d3r** [comment]
Thanks @ebyhr I will check
