### ISSUE TITLE
Fix TestKuduDistributedQueries.testDataMappingSmokeTest failure

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3596]
All tests after https://github.com/prestosql/presto/commit/a380c5d1bdc40056860f4b06f4dacd2dd8bbdff8 are failing. 
```
[ERROR]   Run 13: TestKuduDistributedQueries>AbstractTestDistributedQueries.testDataMappingSmokeTest:1374->AbstractTestQueryFramework.assertQuery:130 For query: 
 SELECT id FROM test_data_mapping_smoke_char_3__nx9419y6pdtu WHERE rand() = 42 OR value = 'ab '
not equal
Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
    
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [sample value]
```

**Comment by findepi** [comment]
@ebyhr my fault. I merged @alexjo2144's https://github.com/prestosql/presto/pull/3588 when it was green, but I didn't notice CI job was not created at all for this PR.

We could revert, but I think we can as well fix/suppress kudu test.

**Comment by findepi** [comment]
BTW that's actually looks like a bug in Kudu connector

CHAR is mapped to Kudu string
https://github.com/prestosql/presto/blob/ec549ac8a1192b18c3667203974f453d5fe5a9fa/presto-kudu/src/main/java/io/prestosql/plugin/kudu/TypeHelper.java#L88-L89

but `char(3)` value `ab⎵` is not persisted as such, it's stored as `ab` instead.

**Comment by findepi** [comment]
i created https://github.com/prestosql/presto/issues/3597 for this
