### ISSUE TITLE
Express $file_modified_time as TIMESTAMP WITH TIME ZONE

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3611]
currently, the `$file_modified_time` hidden column in hive connector is of `bigint` type.
since it represents a point in time, `timestamp with time zone` would be the suitable type.

**Comment by findepi** [comment]
cc @MiguelWeezardo

**Comment by alexjo2144** [comment]
Hey @Praveen2112, didn't realize you had assigned yourself. I was in that part of the code base for something else and took a stab at this too. Mind taking a look at the linked PR and seeing if it's on the right track?

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3617
