### ISSUE TITLE
Document worker graceful shutdown

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3641]
from https://github.com/prestosql/presto/pull/3636#issuecomment-624506066

> Presto already has a graceful worker scaledown mechanism. To trigger it you need to send `SHUTTING_DOWN` via `PUT` request with `worker-address/v1/info/state`.
> 
> This can be achieved via curl call like this:
> 
> ```
> curl -v -X PUT -d '"SHUTTING_DOWN"' -H "Content-type: application/json" http://worker:8081/v1/info/state
> ```
> 
> At this point worker will wait for all task to complete and it will no longer accept new tasks. After that node will terminate. You can get exact logic from https://github.com/prestosql/presto/blob/915627ee733b59fe2c687af06888ef3870a60358/presto-main/src/main/java/io/prestosql/server/GracefulShutdownHandler.java.
>

**Comment by johnwhumphreys** [comment]
Found the code in master was enhanced to avoid a bunch of extra sleeps after this initial issue was made.  Current logic is here:  https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/server/GracefulShutdownHandler.java

Also, there is a brand new pending issue for optimizing the sleep time even more here: https://github.com/prestosql/presto/issues/5903.  That may modify the docs if it gets closed before this does.  If this goes in first then the optimization should update this doc.
