### ISSUE TITLE
Web UI prompts for a certificate to authenticate

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3649]
If i click cancel then i can enter user/pass in the login screen, but how to stop it prompting for 'certificate to authenticate' choice in first place?

![image](https://user-images.githubusercontent.com/33283496/81207303-478d6700-8fc5-11ea-92a8-8e901e03829f.png)

**Comment by tooptoop4** [comment]
cc @dain

**Comment by tooptoop4** [comment]
my guess is https://github.com/prestosql/presto/commit/4e2a0529ce8866addb4cd6a698cb64b1a3a50ed2 broke this.  perhaps commenting out https://github.com/prestosql/presto/blob/333/presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java#L51 could solve it

**Comment by tooptoop4** [comment]
commenting out https://github.com/prestosql/presto/blob/333/presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java#L51 did not solve it :(

**Comment by electrum** [comment]
We have a fix in progress for this.

**Comment by dain** [comment]
@tooptoop4 this has always been broken
