### ISSUE TITLE
Explicit bindings are required and io.prestosql.memory.LowMemoryKiller is not explicitly bound.

### ISSUE THREAD

**Issue by voycey** [prestosql/presto#367]
We have recently moved over to this repo from the prestodb one and are trying to get v304 working on our dataproc cluster. We have run into this message and so far can't figure out how to get past it, I have scoured the documentation for installation and cant find anything relating to this?

```
2019-03-04T03:05:13.525Z        ERROR   main    io.prestosql.server.PrestoServer        Unable to create injector, see the following errors:

1) Explicit bindings are required and io.prestosql.memory.LowMemoryKiller is not explicitly bound.
  while locating io.prestosql.memory.LowMemoryKiller
    for the 8th parameter of io.prestosql.memory.ClusterMemoryManager.<init>(ClusterMemoryManager.java:143)
  at io.prestosql.server.CoordinatorModule.setup(CoordinatorModule.java:223) (via modules: io.prestosql.server.ServerMainModule -> io.prestosql.server.CoordinatorModule)
```

I have attached our dataproc initialization action to this ticket which shows the full config of presto in this instance.
[presto-304.txt](https://github.com/prestosql/presto/files/2924188/presto-304.txt)

**Comment by martint** [comment]
The actual problem is this:

> 2) Error: Defunct property 'query.low-memory-killer.enabled' (class [class io.prestosql.memory.MemoryManagerConfig]) cannot be configured.

The `query.low-memory-killer.enabled` property is no longer supported. You should replace it with:

```
query.low-memory-killer.policy=none
```

**Comment by martint** [comment]
The PR where that change happened was https://github.com/prestosql/presto/pull/168 at it was included in release 302. Unfortunately, we didn't do a good job of documenting what options were removed. Sorry about that.

**Comment by voycey** [comment]
Thanks Martin, I went through a few iterations of that but had that left in - Presto now starts!
