### ISSUE TITLE
Reading parquet file generate by Nifi

### ISSUE THREAD

**Issue by kishoreduraisam** [prestosql/presto#3683]
I have parquet files in my s3 bucket that I am trying to query using presto. These parquet files are generated using the Nifi Processor ParquetRecordSetWriter. I am using AWS EMR. I setup the hive metastore and was able to query the table in hive with no issues. But when I try to query this data using presto I am running into datatype issues. This is happening in many of my fields. For example, I have a string column which stores a name. If I try to query the name I get the message saying the column is declared as type string but the parquet file declares as type INT64. If I change the type to INT, I get a message saying the parquet file declares as type BINARY. 

Hadoop distribution:Amazon 2.8.5
Applications:Hive 2.3.6, Pig 0.17.0, Hue 4.4.0, Presto 0.227

**Comment by tooptoop4** [comment]
try prestosql 333 ?

**Comment by kishoreduraisam** [comment]
> try prestosql 333 ?

I am not sure I am following. I am very new to presto. I looked up presto 333 and it comes up with some documentation. Just to add some more info. I stream data to s3 bucket in parquet format. I use nifi processor to convert the data into parquet. Then I am setting up a hive metastore. Querying in hive is not a problem. But when I try to query using presto I run into issues.

Additional info. I have 50 records in s3. If I try to query for all the records most of the time it fails. But sometimes it pull half of the record or some random number of records and then fail. sometimes it fails without returning any records. It makes me believe there could be bad data?

**Comment by findepi** [comment]
@kishoreduraisam 
you can get Presto 333 from https://prestosql.io/download.html
for managed deployment on AWS (like EMR), you can use https://www.starburstdata.com/presto-aws-cloud/

For Parquet problems, please add `hive.parquet.use-column-names=true` to your hive.properties and restart Presto.

**Comment by kishoreduraisam** [comment]
I am currently on managed deployment on AWS with EMR. Not using starburstdata.

**Comment by tnatssb** [comment]
hive.parquet.use-column-names=true isn't particular to Starburst distribution. Give that a try. 

Most likely your DDL column name order isn't matching up with your parquet file.

**Comment by kishoreduraisam** [comment]
This doesnt seem to help with my problem. I added the attribute to my instance configuration which ended up putting this value in /etc/hive/conf/hive-site.xml. But that doesnt seem to help. Still running into the same issue.  There are some columns that I always get back if I am just querying for that. 

Below you will find some of the errors I have seen. 
presto:default> select name from shopperlists;

Query 20200510_090212_00007_j3niy, FAILED, 2 nodes
Splits: 66 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200510_090212_00007_j3niy failed: The column name is declared as type string, but the Parquet file declares the column as type INT64

presto:default> select name from shopperlists;

Query 20200510_090216_00008_j3niy, FAILED, 2 nodes
Splits: 66 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200510_090216_00008_j3niy failed: The column name is declared as type string, but the Parquet file declares the column as type INT64

**Comment by kishoreduraisam** [comment]
I realized that I did not change the hive.properties file under presto. But I have added the property in /etc/presto/conf/catalog/hive.properties. But I am still running into the same issue. Can you help?

**Comment by tnatssb** [comment]
Can you paste the full error along with your hive.properties file?

**Comment by kishoreduraisam** [comment]
hive.properties:
hive.metastore-refresh-interval=1m
connector.name=hive-hadoop2
hive.metastore-cache-ttl=20m
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.non-managed-table-writes-enabled = true
hive.s3-file-system-type = EMRFS
hive.hdfs.impersonation.enabled = true
hive.metastore = glue
hive.parquet.use-column-names = true

Table:
presto:default> desc shopperlists;
       Column       |  Type   | Extra | Comment
--------------------+---------+-------+---------
 id                 | bigint  |       |
 productadded       | bigint  |       |
 productmodified    | bigint  |       |
 prodid             | bigint  |       |
 prodoptionsvalues  | varchar |       |
 name               | varchar |       |
 storeid            | bigint  |       |
 storename          | varchar |       |
 onsale             | boolean |       |
 opcontainerid      | bigint  |       |
 productlifecycle   | varchar |       |
 vendorproductidsku | varchar |       |
 qty                | bigint  |       |
 categoryid         | bigint  |       |
 producttypeid      | bigint  |       |
 category           | varchar |       |
 producttype        | varchar |       |
 siteid             | bigint  |       |
 options_0__name    | varchar |       |
 options_0__value   | varchar |       |
 options_1__name    | varchar |       |
 options_1__value   | varchar |       |
 options_2__name    | varchar |       |
 options_2__value   | varchar |       |
(24 rows)

query 1 : 
select * from shopperlists;

Error 1:
Query 20200510_110520_00004_ae9st, FAILED, 2 nodes
Splits: 66 total, 3 done (4.55%)
0:01 [3 rows, 5.3KB] [2 rows/s, 4.05KB/s]

Query 20200510_110520_00004_ae9st failed: The column id is declared as type bigint, but the Parquet file declares the column as type BINARY

Query 2:(As you can see below this query returned one result and then the failed with error for rest)
presto:default> select storename from shopperlists;
   storename
----------------
 store1
(1 row)

Query 20200510_110734_00006_ae9st, FAILED, 2 nodes
Splits: 66 total, 7 done (10.61%)
0:01 [6 rows, 589B] [7 rows/s, 749B/s]

Query 20200510_110734_00006_ae9st failed: The column storename is declared as type string, but the Parquet file declares the column as type INT64

**Comment by kishoreduraisam** [comment]
I got it working. It was infact the  property hive.parquet.use-column-names=true that helped with this. My update in the file didnt seem to work. But Setting it session made it stick and I was able to query without issues.  set session hive.parquet_use_column_names = true; 

Thanks for the help.

**Comment by tnatssb** [comment]
That is great. A handy tool is parquet-tools so you can see the schema of the parquet file. I've used this a few times and it reduced my troubleshooting time. Here is a handy link to keep: https://drive.google.com/file/d/17sARmItzlBNepajUjZfdfhGPWgQyBr0e/view?usp=sharing and and example:  java -jar parquet-tools-1.8.2.jar schema part-00000-tid-1696245914157549903-af02faf7-7a79-4308-b52f-4d94ed8475a0-1484.c000.snappy.parquet   Git page: https://github.com/apache/parquet-mr/tree/master/parquet-tools

**Comment by kishoreduraisam** [comment]
One follow up question. Do I need to have a hadoop distribution in order to query s3 using hive connector? I am currently trying this on Amazon EMR with Amazon's hadoop distribution. Starting to wonder if I need hadoop distribution at all or just install presto on EC2 directly.

**Comment by tooptoop4** [comment]
u dont need hadoop

**Comment by tnatssb** [comment]
You are correct in your thinking that that is why it was suggested to use https://www.starburstdata.com/presto-aws-cloud/ as it's just Presto on EC2 without anything else plus you get added features. (HA, additional connectors, security,etc..)

**Comment by findepi** [comment]
> I got it working.

thanks for feedback

**Comment by kishoreduraisam** [comment]
I know this issue is closed. I am not sure if I should open a new one or just continue on this one. I am running into the same problem again.

This is what parquet-tool brings up as schema for my document.
  optional binary listId (UTF8);

When I created the hive table I tried to stick to the schema of my parquet and declared listId as BINARY data type. When I run the query on presto, I am getting the below error
Query 20200512_193251_00068_ssbf4 failed: The column listid is declared as type binary, but the Parquet file declares the column as type INT64

This worked when I 'set session hive.parquet_use_column_names = true' yesterday but doesnt work anymore. 

Also my attempt to follow what athena does when creating table by passing serdeproperties is not going well with syntax issues
CREATE EXTERNAL TABLE IF NOT EXISTS MYLISTS_TEST(
listId BINARY,
...
)STORED AS PARQUET
WITH SERDEPROPERTIES('parquet.column.index.access'='false')
LOCATION 's3a://.....';

FAILED: ParseException line 38:0 missing EOF at 'WITH' near 'PARQUET'

**Comment by findepi** [comment]
> Also my attempt to follow what athena does when creating table by passing serdeproperties is not going well with syntax issues

Athena uses its own syntax (borrow from Hive) for DDL.
Also, if i am not mistaken, `parquet.column.index.access` is Athena-specific. (@pettyjamesm will know better though)

> This worked when I 'set session hive.parquet_use_column_names = true' yesterday but doesnt work anymore.

What's full stacktrace (run CLI with `--debug`)?

Also, I suggest to move this to `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).

**Comment by kishoreduraisam** [comment]
Ok. I think I figured out the problem. My problem was inconsistency between multiple records in the schema. Once I was able to figure that out and get that corrected and I am back up and running. Appreciate all the help.

**Comment by kishoreduraisam** [comment]
Last couple of recommendations:
1. Recommendations for web based query execution tool on presto? - I have seen https://airbnb.io/airpal/. Any other recommendations?
2. Open source BI tool integration for visualization

**Comment by findepi** [comment]
@kishoreduraisam this is unrelated to the issue discussed here.
Please ask on #general channel on [our slack](https://prestosql.io/slack.html), but check https://prestosql.io/resources.html first.
