### ISSUE TITLE
Invalid format from_iso8601_date() function

### ISSUE THREAD

**Issue by o3LL** [prestosql/presto#3695]
Hello everyone!

I think there is an issue with from_iso8601_date() function :

```
presto> select from_iso8601_date(to_iso8601(now()));

Query 20200511_120826_00002_q3wh7 failed: Invalid format: 
"2020-05-11T12:08:26.132Z" is malformed at "T12:08:26.132Z"
```

Actually, it seems that the function from_iso8601_date only support YYYY-MM-dd format and not iso8601 format!

**Comment by martint** [comment]
That function only parses ISO dates (https://en.wikipedia.org/wiki/ISO_8601#Dates) into SQL dates:

```
presto> WITH t(d) AS (VALUES '2020-W10', '2020-05-11', '2020-123')
     -> SELECT from_iso8601_date(d) FROM t;
   _col0
------------
 2020-03-02
 2020-05-11
 2020-05-02
(3 rows)
```

If you want a full timestamp, you have to use `from_iso8601_timestamp`:

```
presto> select from_iso8601_timestamp(to_iso8601(now()));
             _col0
--------------------------------
 2020-05-11 09:11:05.045 -07:00
(1 row)
```

cc @mosabua -- something to clarify in the docs.
