### ISSUE TITLE
Custom Principal is replaced with BasicPrincipal

### ISSUE THREAD

**Issue by Ennosigaeon** [prestosql/presto#3696]
I have implemented a custom _io.prestosql.spi.security.PasswordAuthenticator_ that creates my own _java.security.Principal.Principal_ instances (_PrincipalWithRoles_). Furthermore I have added a custom _io.prestosql.spi.security.SystemAccessControl_ that evaluates the roles in my principal objects to grant permissions.

On executing a `show catalogs;` everything works as intended and I can see _PrincipalWithRoles_ instances being available in the provided _SystemSecurityContext_. However, if I execute a _show schemas from kudu;_, my SystemAccessControl is called multiple times with the correct _PrincipalWithRoles_ but ultimately the principal is replaced by a _io.prestosql.spi.security.BasicPrincipal_. I tracked the issue back to _io.prestosql.SessionRepresentation#toSession_ called from _io.prestosql.server.TaskResource#createOrUpdateTask_ where always a _BasicPrincipal_ is created. I assume the principal is replaced when work is handed over from the coordinator to the worker, but that is only a guess.

I think I can solve this issue using the _GroupProvider_ but the silent replacement of the principal caused quite some headache for me.

Tested with prestosql-332 with a single worker/coordinator.

**Comment by dain** [comment]
We added `GroupProvider` for exactly this case.  Relying on `Principal` is not a good idea, since is can not be serialized, and in the future as we support more complex deployment architectures, the principal will be be replaced as the engine needs.  For this exact reason, we have been considering removing the Principal from the security context for a long time now.

**Comment by Ennosigaeon** [comment]
Thanks for your feedback. I was able to replace everything with the `GroupProvider` and everything works as intended. Shall I close the issue?
