### ISSUE TITLE
Thread.currentThread().getContextClassLoader() changed after upgrading to 333

### ISSUE THREAD

**Issue by pangyifish** [prestosql/presto#3704]
I upgraded Presto from version 331 -> 333, and Thread.currentThread().getContextClassLoader() changed from io.prestosql.server.PluginClassLoader to a different one when i used it eventListener constructor and break my code:(

i found this which is possibly the reason, may i know the reason for this change? 
--> Use platform classloader in Java 8 and 11 for plugins
https://github.com/prestosql/presto/commit/3195d8a3bb6b1b87b63d7df010a7312e8b960c28

**Comment by kokosing** [comment]
Hi,

For reference, please see:
 - https://github.com/prestosql/presto/pull/3342
 - https://github.com/prestosql/presto/pull/3340

Regards,
Grzegorz
https://www.starburstdata.com/
https://prestosql.io/

**Comment by electrum** [comment]
Can you provide details on how it broke?

**Comment by pangyifish** [comment]
> Can you provide details on how it broke?

I imported some code (let's say package A) which will 
1. find a loader with ServiceLoader.load(ConfigLoader.class), which will implicitly call Thread.currentThread().getContextClassLoader(); 
2. use the loader to find some resources from the package A i imported

what Thread.currentThread().getContextClassLoader() get is different:
in 331, it will get io.prestosql.server.PluginClassLoader, it can find the resources well; 
in 333, it will get jdk.internal.loader.ClassLoaders$AppClassLoader, it cannot find the resources.

**Comment by electrum** [comment]
Thanks, this is a bug. The intent of that change was to allow extension classes for JDK 8, not to change it the context class loader. We’ll fix this in a future release (hopefully the next one).

**Comment by pangyifish** [comment]
> Thanks, this is a bug. The intent of that change was to allow extension classes for JDK 8, not to change it the context class loader. We’ll fix this in a future release (hopefully the next one).

Cool, thx!

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3736 should fix it.
