### ISSUE TITLE
Support serving presto with a context path

### ISSUE THREAD

**Issue by Ennosigaeon** [prestosql/presto#3706]
I want to deploy Presto in a Kubernetes cluster and access presto using a context path, e.g. `https://server.com/presto`. However, using the _presto-cli_ the context path is dropped in the `StatementClientV1#buildQueryRequest` leading to request for `https://server.com/v1/statement`.

It would be great to be able to use Presto in combination with a context path. For now I am going to use a subdomain.

**Comment by electrum** [comment]
I don't think this is something we are ever going to support. It would be a large amount of work, not just in Presto itself, but also in all the various client libraries. Even if someone was willing to do the work, it's doubtful we would accept it, as it introduces complexity and testing burden. We'd rather spend our "complexity budget" in other areas.

I'm going to close this issue for now, but I'm happy to discuss your specific use case and needs on Slack: https://prestosql.io/slack.html

**Comment by utf7** [comment]
we have same problem， do you have a solution?
@Ennosigaeon

**Comment by Ennosigaeon** [comment]
No, we have given up on this issue and used a dedicated subdomain, i.e. `https://presto.server.com/`
