### ISSUE TITLE
IcebergConnector: Handle `null` partition value 

### ISSUE THREAD

**Issue by manishmalhotrawork** [prestosql/presto#3716]
If the partition value is null. 
here if partition column value is null. it fails with exception.

```File hdfs://abc.parquet has no partition data for partitioning column event_dt\```

Place from where this condition is checked:

```
private static Map<Integer, String> getPartitionKeys(FileScanTask scanTask)
```

```
            if (value == null) {
                throw new PrestoException(ICEBERG_INVALID_PARTITION_VALUE, format(
                        "File %s has no partition data for partitioning column %s",
                        scanTask.file().path().toString(),
                        field.name()));
            }
```

If the similar data read from Spark, then its returning proper data, even though there is partition which has `null` value .

**Comment by Parth-Brahmbhatt** [comment]
PR posted https://github.com/prestosql/presto/pull/3725
