### ISSUE TITLE
Add Schema level access control to FileBasedSystemAccessControl

### ISSUE THREAD

**Issue by haldes** [prestosql/presto#3733]
Currently FileBasedSystemAccessControl control has catalogRules, queryAccessRules, impersonationRules and principalUserMatchRules. The proposal here is to add schema access rules to it. This will give more granular access controls over the datasets.
	
	At high level idea is to implement/enhance the below methods of FileBasedSystemAccessControl
	
	- checkCanDropSchema - Allow if user has access to catalog and is SchemaOwner
	- checkCanRenameSchema - Allow if user has access to catalog and is SchemaOwner
	- checkCanSetSchemaAuthorization - Allow if user has access to catalog and is SchemaOwner
	- checkCanShowCreateSchema - Allow if user has access to catalog and is SchemaOwner

**Comment by haldes** [comment]
@findepi Thanks. Will send a PR soon. Can you assign this issue to me.

**Comment by findepi** [comment]
@haldes  thanks!
cc @kokosing

**Comment by haldes** [comment]
@findepi @kokosing 
PR raised. : https://github.com/prestosql/presto/pull/3766/

**Comment by ebyhr** [comment]
Going to close this issue as #3766
