### ISSUE TITLE
Fix timestamp mapping in Elasticsearch for non-legacy timestamp

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3742]
https://github.com/prestosql/presto/blob/13a3c523f2739a2373c251697f6826daaf193266/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/TimestampDecoder.java#L82

should use UTC for non-legacy timestamp semantics.

Relates to https://github.com/prestosql/presto/issues/3741

**Comment by combineads** [comment]
I use Phoenix and Elasticsearch connector, but there is a difference in the value of the timestamp column. Until the TIMESTAMP behavior of presto is decided, I try to solve this problem with the following code. Thank you for your efforts.
```
            if (value instanceof String) {
                timestamp = LocalDateTime.from(Instant.from(ISO_DATE_TIME.parse((String) value)).atZone(zoneId));
            }
            else if (value instanceof Number) {
                timestamp = LocalDateTime.ofInstant(Instant.ofEpochMilli(((Number) value).longValue()), zoneId);
            }
```
