### ISSUE TITLE
Document compatible hive metastore/hadoop versions

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3764]
Current docs mention: "The Hive connector supports Apache Hadoop 2.x and derivative distributions including Cloudera CDH 5 and Hortonworks Data Platform (HDP)." and also some limitations for Hive 3.

They don't mention if following versions are supported:
Hive 1.x
Hive 2.x
Hadoop 3.x
Hive 0.14.0
.etc

**Comment by findepi** [comment]
Hive 1.x -- We test eg with CDH 5.15, which includes Hive 1.1 (+ Cloudera patches).
Hive 2.x -- supported 
Hadoop 3.x -- supported
Hive 0.14.0 -- i think not supported (i dont think it's in use anyway, is it?)

**Comment by mosabua** [comment]
https://github.com/prestosql/presto/pull/3790

**Comment by mosabua** [comment]
PR merged.
