### ISSUE TITLE
Flaky TestOracleIntegrationSmokeTest.testSelectInformationSchemaColumns

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3781]
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

Similar failure: https://github.com/prestosql/presto/actions/runs/108922785

**Comment by eskabetxe** [comment]
@ebyhr in the past when this happened, increasing the number of processes it is usually solved the problem.. 
now it has 500 processes, maybe we should raise that to a high value like 1000 or 5000
