### ISSUE TITLE
prestosql slack community

### ISSUE THREAD

**Issue by nishantambastha** [prestosql/presto#3782]
Hi, 
How do I get an invite for prestosql slack community. Thanks.

**Comment by ebyhr** [comment]
You can join from [sign up](https://join.slack.com/t/prestosql/shared_invite/enQtNTMyNzU2NzQ1NzQ4LWUyMjY4NTA0NWU0ZDlkMjM4Y2JhODdiZWZiZWQ2NDNhZDVhOGY5ZTk4NDY0OGIzOTE2YzI3YjhlMmUyNDJiNGM) in this page. https://prestosql.io/slack.html

**Comment by ebyhr** [comment]
Let me close this issue since I found you on Slack. Welcome!

**Comment by nishantambastha** [comment]
Thanks!

**Comment by monicavalluri** [comment]
@ebyhr I am trying to join the presto slack community and the [link](https://join.slack.com/t/prestosql/shared_invite/enQtNTMyNzU2NzQ1NzQ4LWUyMjY4NTA0NWU0ZDlkMjM4Y2JhODdiZWZiZWQ2NDNhZDVhOGY5ZTk4NDY0OGIzOTE2YzI3YjhlMmUyNDJiNGM) when visited says it is no longer active. Could you please help me join? Thanks.

**Comment by martint** [comment]
@monicavalluri, it appears the invite link became invalid. I just generated a new one and updated the website. Can you please give it another try?

**Comment by monicavalluri** [comment]
@martint It worked. Thanks!
