### ISSUE TITLE
Support prepared statement parameters in LIMIT and OFFSET

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3800]
`LIMIT` and `OFFSET` currently expect an integer literal.

They could be updated to allow for `?`, a prepared statement parameter. This may be especially useful for JDBC users.

**Comment by Lewuathe** [comment]
We parse the parameter for the prepared statement as a type of expression. Do we need to support all types of expressions in `LIMIT` and `OFFSET` in general? Or just supporting parameter (`?`) is sufficient?

```
primaryExpression
    : ...
    | '?'                                                                                 #parameter
```

**Comment by findepi** [comment]
Only constant number (as it is today) or `?` is sufficient.

**Comment by ebyhr** [comment]
Going to close this issue since it was added in version 340.
