### ISSUE TITLE
Remove testcontainers ryuk image override

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3816]
Revert https://github.com/prestosql/presto/pull/3787 when the official image is published to Docker Hub and we upgrade to testcontainers release using it

See @bsideup's https://github.com/prestosql/presto/issues/2598#issuecomment-631098613
> [...] Yes, the image will eventually (ETA: this week) be moved to Docker Hub.

**Comment by electrum** [comment]
This seems to be addressed in https://github.com/testcontainers/testcontainers-java/commit/fe2102a99ce323a1fa00913104954264bda44a86

We will need to wait for the next testcontainers release.
