### ISSUE TITLE
Objects in hidden schema appear on information_schema in JDBC based connector

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3831]
After filtering `sys` in MySqlClient.listSchemas.
```sql
presto> show schemas in mysql;
       Schema
--------------------
 information_schema
 performance_schema
 tpch
(3 rows)
```

```
presto> select * from mysql.information_schema.tables where table_schema = 'sys';
 table_catalog | table_schema |                  table_name                   | table_type
---------------+--------------+-----------------------------------------------+------------
 mysql         | sys          | sys_config                                    | BASE TABLE
 mysql         | sys          | host_summary                                  | BASE TABLE
...
```

Even after filtering Oracle internal schemas in #3784, the TestOracleIntegrationSmokeTest.testSelectInformationSchemaColumns will take about 10min due to many system tables.

**Comment by findepi** [comment]
> Even after filtering Oracle internal schemas in #3784, the TestOracleIntegrationSmokeTest.testSelectInformationSchemaColumns will take about 10min due to many system tables.

This is insufficiency in that PR, not engine thing. I will comment there.
