### ISSUE TITLE
View owner 'hive' cannot create view that selects from

### ISSUE THREAD

**Issue by DerekRen** [prestosql/presto#3841]
tags：333

hive.properties ：

hive.security=file
security.config-file=/opt/cloudera/parcels/presto/etc/catalog/hive_auth

hive_auth:
{"tables": [{"privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP"], "user": "hive"}, {"privileges": ["SELECT", "INSERT", "DELETE","VIEW", "OWNERSHIP"], "user": "derek"}]}

use hive,support  hive view;
use derek,not support hive view;

**Comment by archongum** [comment]
You need to grant ""
