### ISSUE TITLE
Incorrect value returned by localtime

### ISSUE THREAD

**Issue by martint** [prestosql/presto#3846]
```
presto> select localtime, localtimestamp;
    _col0     |          _col1
--------------+-------------------------
 13:33:37.711 | 2020-05-25 14:33:37.711
(1 row)
```

It appears that the value of `localtime` is being affected by daylight savings offset.

**Comment by findepi** [comment]
Same for `current_time` -- https://github.com/prestosql/presto/issues/3850

See
https://github.com/prestosql/presto/blob/7ff3ace9e84848943e4dbc232a9162fa14998d72/presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java#L112-L118

even though `time with time zone` is "the same" for both semantics, we were consciouly not fixing function result for legacy semantics (to avoid breaking changes, anticipating the cut over to new semantocs will follow  up soon)
I am not saying it was the right thing to do, but there may be some more problems like that.
