### ISSUE TITLE
prestosql support IPv6？

### ISSUE THREAD

**Issue by Boomxiakalakaka** [prestosql/presto#3915]
Does prestosql support IPv6？

**Comment by dain** [comment]
Yep.  Presto has been run in pure v6 data centers, but it is possible some of the stuff Presto connects to doesn't fully support v6.  Please, let us know if you find any issues.

**Comment by Boomxiakalakaka** [comment]
Thank you very much, when prestosql version of IPv6 is supported from？
we use the prestosql 316

**Comment by dain** [comment]
It was several years ago... long before 316

**Comment by dain** [comment]
If you find any issues, please open a new issue.  Thanks.
