### ISSUE TITLE
Add reverse function for varbinary

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#3917]
This should work like the varchar version, but for binary strings. The code goes in `VarbinaryFunctions` and the documentation in `binary.rst`.

**Comment by vasantteja** [comment]
I'm happy to help. Can I get a detailed description please.

**Comment by electrum** [comment]
The function should return the binary string with the bytes in the reverse order. So if the input bytes are `abcdef` then the function should return `fedcba`.

**Comment by vasantteja** [comment]
Sure sounds good. Can I assign this to me.

**Comment by aayush27894** [comment]
Thank you for working on this. I just wanted to make sure what the function is doing. 
The function should return the binary string with the bytes in the reverse order. So if the input bytes are ab cd ef then the function should return ef cd ab, right?

Also, could you tell when will this function be available to users?

**Comment by vasantteja** [comment]
@aayush27894 I am working on this. But you example appears to be different from the example given by @electrum. Can you please clarify?

**Comment by aayush27894** [comment]
I had a discussion with @electrum on the slack channel about this.
https://prestosql.slack.com/archives/CFLB9AMBN/p1590780859115600

We are talking about converting hex string into little endian, which requires us to reverse in a way that I showed. @electrum could you please confirm this?

**Comment by vasantteja** [comment]
@aayush27894 gotcha. If we are going to reverse the binary string we are going to arrive at your output. There is a sliceutf8.reverse implementation from string functions which I can use to achieve the reverse functionality. @electrum is this the right approach or do you anything else to add?

**Comment by electrum** [comment]
@vasantteja No, this is for binary strings, not UTF-8, so it should be reversing the raw bytes.  `SliceUtf8` is for UTF-8 strings and works on Unicode characters (which can be multiple bytes).

@aayush27894 was talking about hex strings, which is unrelated to this new binary reverse function. I originally suggested that reverse on hex could solve his problem (but that's clearly wrong as you'd need to reverse each hex pair), which caused this confusion.

**Comment by vasantteja** [comment]
Okay. I got it. I will do a reversal in the hex pair instead of whole hex reversal.

**Comment by aayush27894** [comment]
Hi, think I have figured the code for the reverse logic, could you please tell me how I could contribute?

**Comment by electrum** [comment]
GitHub has guides to help you get started: https://guides.github.com/

The basic flow is to fork the repository, clone it to your computer, create a branch for your change, make the change, commit it, push the branch to your fork, then submit a pull request.

The guides should help you learn this process. Try following “Hello World” first.

**Comment by vasantteja** [comment]
@aayush27894 Can you please discuss the logic you have in mind.

**Comment by mohdarif8299** [comment]
I would to like to contribute to this.
