### ISSUE TITLE
add human readable representation of duration

### ISSUE THREAD

**Issue by JeffryMAC** [prestosql/presto#3948]
The problem:
many times for reporting you want to convert duration number (integer) into readable human string. The problem is that this can not be easily obtain in SQL.

I have the following Python code that handles it:
https://gist.github.com/borgstrom/936ca741e885a1438c374824efb038b3
```
TIME_DURATION_UNITS = (
    ('week', 60*60*24*7),
    ('day', 60*60*24),
    ('hour', 60*60),
    ('min', 60),
    ('sec', 1)
)


def human_time_duration(seconds):
    if seconds == 0:
        return 'inf'
    parts = []
    for unit, div in TIME_DURATION_UNITS:
        amount, seconds = divmod(int(seconds), div)
        if amount > 0:
            parts.append('{} {}{}'.format(amount, unit, "" if amount == 1 else "s"))
    return ', '.join(parts)


items = [535333.9513888889, 61, 56363463, 1, 8003]
for val in items:
    print(human_time_duration(val))

```
Output is:
```
6 days, 4 hours, 42 mins, 13 secs
1 min, 1 sec
93 weeks, 1 day, 8 hours, 31 mins, 3 secs
1 sec
2 hours, 13 mins, 23 secs
```

Could something like this be provided by Presto as build in function?
I think that human readable convert options are really important it save a lot of trouble when you have the data but there is no easy way to convert it to something that you can actually read.

**Comment by findepi** [comment]
We have `parse_duration` https://prestosql.io/docs/current/functions/datetime.html#parse_duration 
We could also add `format_duration`, as a reverse. This, however, for "1 minute 5 second" duration would produce output like
```
65000.00ms OR
1.08m
```
-- so probably not want you want.

For the really human-readable formatting there are lots of (subjective) preferences. For example, if the duration is longer than a day I personally
would want the minutes and seconds be omitted, as not relevant. Someone else would want minutes/seconds/millis to be always included
so that the output is a faithful representation of the value being formatted.

For these reasons, I think the best place for this king of logic is in the application displaying data processed by Presto, not in the Presto itself.

**Comment by findepi** [comment]
Note also that Presto already has a better representation for durations than a number -- the `interval` type:
```
presto> SELECT INTERVAL '127' SECOND;
     _col0
----------------
 0 00:02:07.000

presto> SELECT CAST(parse_duration('123s') AS varchar);
     _col0
----------------
 0 00:02:03.000
```

Would that satisfy your needs?

**Comment by JeffryMAC** [comment]
> For the really human-readable formatting there are lots of (subjective) preferences
In this request I don't really care about the specifics. I think everyone can agree that the solution won't satisfy everyone. I'm looking for a solution. Whatever you guys think best.
But I do need it in human readable string.

Your 2nd reply isn't very human readable. Managers and people who are not programmers won't understand what is `0 00:02:03.000`. Think for example on a case where all values are smaller than 24 hours than all you will see are representation of something that could look like time. for example: 23:45 - You might think it's 11:45 PM but it actually just a duration of 23 hours and 45 minutes. Only if you have combination of time that is longer than 24 hours for example 27:45 then you might understand that it's duration but even then it's confusing.

To represent durations to business suit people its prefer to use strings.

Googling for a bit you can see that this is a question raised by many people in many mediums.

**Comment by haldes** [comment]
@findepi - I want to pick this up. Can you please assign this to me.

**Comment by findepi** [comment]
@haldes thank you!

before you do, however, we should come to agreement on the syntax.

@electrum @martint

**Comment by haldes** [comment]
Thanks @findepi

**Comment by JeffryMAC** [comment]
thanks @haldes 
so what exactly is the status here? how the syntax review works?

**Comment by martint** [comment]
If this is for human consumption - and we can make that explicit in the docs - we could start with any format and improve it over time. It doesn’t need to be stable, IMO

**Comment by haldes** [comment]
Thanks @martint . Let me then start working on this and come back with an PR. Also any special considerations/edge case we need to take care of?

**Comment by JeffryMAC** [comment]
@haldes I think it would be good to stick to the code example I provided it handled all edge cases then the questions left are only on "how do you want to represent it as string".
You can run the provided code in any python online IDE like https://www.onlinegdb.com/online_python_compiler

**Comment by haldes** [comment]
@JeffryMAC Thanks.

@findepi @martint Can any one suggest any good name for this function e,g to_readbleFmt(), to_humanReadbleFmt() etc.

**Comment by electrum** [comment]
How about `human_readable()`

**Comment by haldes** [comment]
@electrum - Thanks. Sounds good to me.

**Comment by haldes** [comment]
PR raised
https://github.com/prestosql/presto/pull/4344
