### ISSUE TITLE
testDistributesSpillOverPathsBadDisk fails when running as Root

### ISSUE THREAD

**Issue by csunwold** [prestosql/presto#3969]
When attempting to build Presto running as root [TestFileSingleStreamSpillerFactory#testDistributesSpillOverPathsBadDisk](https://github.com/prestosql/presto/blob/900fb60e11b6df455271221c817cb61b3f6fa1c6/presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpillerFactory.java#L112) fails. Since the process is running as root, it ignores the file permissions that the test depends on and writes to the directory that is set as read-only.

**Comment by findepi** [comment]
Thanks for reporting this, and with a good explanation!

Unfortunately, I don't know off hand how this can be fixed and at the same time, it seems an easy workaround exists (do not run tests as root user).

Do you have any suggestions?

**Comment by csunwold** [comment]
No obviously solution sticks out to me either.

@shrijeet @dfinninger Looking through Github history it looks like you contributed these changes originally. I'm curious if you have any ideas?

**Comment by findepi** [comment]
@csunwold are you running tests in a docker container?

**Comment by csunwold** [comment]
@findepi Yes.

**Comment by findepi** [comment]
@csunwold would it help if you add `-u a_user` to your `docker run` command?
(picking `a_user` depending on the base image you use, eg `ubuntu` user in `ubuntu` image)

**Comment by shrijeet** [comment]
@csunwold few options other than the workaround @findepi suggested

* Find a more deterministic way to simulate disk failure, I looked into changing the mutability of the file object but didn't find any java api in my quick search

* Use mocking, my recollection is that presto doesn't have dependency on a mock library yet. Also its not clear if its straightforward to inject a mock instance in this code path

**Comment by findepi** [comment]
@csunwold i think the conclusion for now would be: let's not run the test as root

I am going to close the issue, as we do not plan to change this limitation, so keeping it open doesn't help.
We can continue discussion here and -- specially if we find a good proposed solution -- we can reopen if needed.
