### ISSUE TITLE
MySQL case-sensitive table names not working

### ISSUE THREAD

**Issue by dekelev** [prestosql/presto#3974]
MySQL supports case-sensitive table names, but I'm getting the following error when querying a table named `camelCase` with PrestoSQL v334 and MySQL 8.x:
```
Table 'mysql.test.camelcase' does not exist
```

I've tried wrapping the table name with double-quotes, but I'm still getting the same error.

**Comment by Praveen2112** [comment]
Hi !! Can you try by setting the property in your connector.properties file 
```
case-insensitive-name-matching=true
```
Presto currently converts name as lower case (whether it is quoted or not). 

Feel free to join our slack channel - https://prestosql.io/slack.html

**Comment by Praveen2112** [comment]
If you still face this issue, please re-open this issue.

**Comment by dekelev** [comment]
@Praveen2112 thanks, the display of table and column names is still in lower-case, which makes them hard to read, but at least it works.

**Comment by findepi** [comment]
@dekelev correct. this will be addressed with https://github.com/prestosql/presto/issues/17.
You can follow that issue.
