### ISSUE TITLE
Error on selecting tinyint column from Cassandra table

### ISSUE THREAD

**Issue by dekelev** [prestosql/presto#3985]
I'm getting an error when trying to query Cassandra table with `tinyint` column using the following simple query:
```
SELECT tinyint_column FROM cassandra.default.test;
```

`DESCRIBE cassandra.default.test` shows the column type as `tinyint`.

The error is:
```
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: ['org.apache.cassandra.db.marshal.ByteType' <-> java.lang.Byte]
```

Presto v334

**Comment by findepi** [comment]
This would probably require a change here:
https://github.com/prestosql/presto/blob/6d9d47e0909b3fe9367584ba8450827dbbb8e1d7/presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java#L284

The test should go `TestCassandraIntegrationSmokeTest`

(Normally, this would be covered by `TestCassandraDistributedQueries.testDataMappingSmokeTest`, but this test is disabled for Cassandra)

**Comment by findepi** [comment]
@dekelev please provide steps to reproduce.
In particular, it's not possible to create such table via Presto:
```
presto:tpch> create table t(a tinyint);
Query 20200610_230950_00015_wvxjf failed: Unknown type tpch.tinyint
com.datastax.driver.core.exceptions.InvalidQueryException: Unknown type tpch.tinyint
```

so steps to reproduce will be useful to whoever picks this up.

**Comment by ebyhr** [comment]
@dekelev Additionally, could you share Cassandra version and cassandra.proerrties? I also couldn't reproduce the issue.

**Comment by dekelev** [comment]
In Cassandra (CQL):
```
Use some_keyspace;

create table test
(
    id uuid primary key,
    tiny tinyint
);

INSERT INTO test (id, tiny) VALUES ('0e9a0923-e9f7-48f0-83d5-a18256adb08c', 1);
```

In Presto:
```
select tiny from cassandra.some_keyspace.test;
```

cassandra.properties:
```
connector.name=cassandra
cassandra.contact-points=localhost
cassandra.protocol-version=V3
```

Cassandra v3.11.3

**Comment by ebyhr** [comment]
@dekelev Do you have special reason specifying `cassandra.protocol-version`? This issue won't happen if you remove `cassandra.protocol-version` property or use `V4`.

**Comment by dekelev** [comment]
@ebyhr I was under the assumption that I need V3 since I'm using Cassandra v3.x cluster, not because an actual error that I got. The query does work now!

**Comment by findepi** [comment]
@dekelev thanks for confirming!
