### ISSUE TITLE
Enable testDataMappingSmokeTest for Cassandra

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3993]
See TODO

https://github.com/prestosql/presto/blob/fdbeea304bcf3252e7cd1be718dcd148340cf764/presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java#L153-L160

1. enable the test
2. for any test cases that fail, create exclusions as here: https://github.com/prestosql/presto/blob/329a48592ecb6c628712ef3648f2e8da7eb33d38/presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java#L123-L145
3. Create follow up issues for them

**Comment by stonewallstan** [comment]
Is anybody on this yet?

**Comment by findepi** [comment]
Not that i know of. @ebyhr  please confirm.

**Comment by ebyhr** [comment]
@stonewallstan Please feel free to pick up this issue. Thanks in advance!
