### ISSUE TITLE
Presto mongo connector version 334 is null query returning incorrect output

### ISSUE THREAD

**Issue by abhisheksahani** [prestosql/presto#4003]
Presto version:334

### Steps to reproduce

A.) Add 4 documents in mongo having state information of users.

1. {
  "_id": ObjectId("5ee1d46f6c09d6b54e5c4c71"),
  "state1": "TELANGANA1"
}

2.{
  "_id": ObjectId("5ee1d4746c09d6b54e5c4c72"),
  "state1": "TELANGANA1",
  "state": "TELANGANA1"
}

3. {
  "_id": ObjectId("5ee1d4796c09d6b54e5c4c73"),
  "state1": "TELANGANA1",
  "state": null
}

4.{
  "_id": ObjectId("5ee1dbdd6c09d6b54e5c4c74"),
  "state1": "TELANGANA1"
}

In the above 4 documents, one document have **"state"** as **"TELANGANA1"** other document have **"state"** as NULL  and rest two doesn't have state key inside the document.

B.) Run a query via presto Mongo connector for collection having above 4 records:
      
    SELECT count(*) FROM your_table WHERE state IS NULL;  -- 1

The output of the above query is 1 which is **incorrect** and  correct output is 3.

C.) Run the following query 
      
    SELECT count(*) FROM your_table WHERE state IS NULL OR rand() = 42; -- 3
      
What I understand from this query is that it fetches  all the data from collection without 
filtering inside Mongo and then in-memory perform the null check and **returns correct output 3**

**Comment by nikitasherman** [comment]
I would be glad to take it.

Basically as I see it today the issue is here:

`private static Document isNullPredicate()
    {
        return documentOf(EXISTS_OP, true).append(EQ_OP, null);
    }`

It is producing the following mongo query which is enforcing the existence of field and it's equality to `null` 

The query is like that:
`{"state": { $exists: true, eq: null }}`
