### ISSUE TITLE
Add dynamic partition pruning integration test with dummy connector

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#4032]
We currently lack a test where we ensure that dynamic partition pruning works end-to-end with connector.

**Comment by findepi** [comment]
@sopel39 can we get this impl'd for tpch connector (when partitions are enabled), or is it too few partitions there?

**Comment by sopel39** [comment]
> can we get this impl'd for tpch connector (when partitions are enabled), or is it too few partitions there?

I don't think you can assert that partitions were skipped with tpch connector (can you?). In dummy connector you can actually wait for dynamic filter to materialize.
