### ISSUE TITLE
hive connector cache does not support multiple locations

### ISSUE THREAD

**Issue by on99** [prestosql/presto#4057]
https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java#L90

Is it possible to support multiple locations cache? We have multiple ssd devices attached to one machine.

**Comment by sopel39** [comment]
Hi @on99. You can specify multiple locations via properties like: 
```
hive.cache.location=/var/lib/presto/cache1,/var/lib/presto/cache2
```

@mosabua Maybe we should put that information in documentation?

**Comment by mosabua** [comment]
Done.
