### ISSUE TITLE
Incorrect non revocable memory usage calculation in QueryStatistics

### ISSUE THREAD

**Issue by Lewuathe** [prestosql/presto#4060]
`getPeakTotalNonRevocableMemoryBytes` in QueryStatistics is obtained from the `getPeakTotalMemoryReservation` in QueryStats. But peak total memory reservation is the sum of the user, system, and revocable memory reservation. Hence, nonrecoverable memory should come from the total of user and system, not total memory reservation. 

See: https://github.com/prestosql/presto/pull/3996#discussion_r440061567

**Comment by Lewuathe** [comment]
@sopel39 Thanks for merging https://github.com/prestosql/presto/pull/4096. Can we close this issue?

**Comment by sopel39** [comment]
Yes. It is fixed.
