### ISSUE TITLE
Enforcement of NOT NULL column constraints

### ISSUE THREAD

**Issue by djsstarburst** [prestosql/presto#4070]
This issue is created to decide how enforcement of NOT NULL column constraints should be supported, and implement that support.   Discussion of this issue was triggered by the desire to support NOT NULL constraints for the Iceberg connector.  But we wondered if it should be handled in the Presto engine in a generic way, independent of connector type.

I asked for opinions in the #dev Slack channel, and @martint commented:

> Aspirationally, yes. But we have to think about a few things:
>
> When and how does the NOT NULL constraint get exposed to Presto. Specifically, how does it interact with features supported by databases, such as DEFAULT. For instance, given this table in postgres, the constraint shouldn’t be enforced by Presto:
>
> `create table t (a bigint, b timestamp default localtimestamp not null);`
>
> If a table exposes a NOT NULL constraint to the engine. Will it do validation on read — if necessary, to ensure the engine doesn’t get bad data. For instance, let’s say another engine inserts data into iceberg without verifying that constraint and the iceberg connector tells the engine that that column doesn’t contain any nulls, is the iceberg connector going to reject data on read?

Relates to https://github.com/prestosql/presto/issues/2923

**Comment by djsstarburst** [comment]
So it seems to me that we have these options:

- Implement enforcement of the NOT NULL constraint only in the Iceberg connector, being careful to also validate data read, since as @martint points out, Presto might not be the only writer of the data.
- Implement enforcement of the NOT NULL constraint generically in core Presto, both for reading and writing, but use of it only for connectors that don't have the concept of default value.

**Comment by findepi** [comment]
> Implement enforcement of the NOT NULL constraint generically in core Presto, both for reading and writing, but use of it only for connectors that don't have the concept of default value.

Currently, in JDBC connectors the DEFAULT value is utilized only when we _do not_ write any data (we insert specifying a subset of columns).
This is probably also the correct behavior. So, we could enforce NOT NULL when writing also there.

**Comment by djsstarburst** [comment]
@electrum and I talked about enforcement of NOT NULL constraints, and plan to begin by adding enforcement on writes in the Presto engine, so enforcement will apply to all connectors.  The plan is to do enforcement in TableWriterOperator.addPage(), based on a set of non-null column channels prepared by LocalExecutionPlanner and passed through TableWriterOperatorFactory.

**Comment by findepi** [comment]
done in https://github.com/prestosql/presto/pull/4144?

**Comment by djsstarburst** [comment]
Yes, it was done when writing in the engine for all connectors, in part as
a result of your counsel :)

David

**Comment by findepi** [comment]
Thanks for confirming.
