### ISSUE TITLE
Views don't expose Hive special columns

### ISSUE THREAD

**Issue by awishnick** [prestosql/presto#4105]
If I create a view of a hive table (e.g. `CREATE VIEW hive.default.myview AS SELECT * from hive.default.mytable`) then the Hive special columns like `$path` can't be accessed through the view (for example, `SELECT "$path" from hive.default.myview LIMIT 1`). The error I get is `io.prestosql.spi.PrestoException: line 1:8: Column '$path' cannot be resolved`

**Comment by dain** [comment]
The "special" columns are marked as `hidden` which means they are not included with `*`.  Otherwise, they would always show up for simple queries like `SELECT * FROM t LIMIT 1`

**Comment by findepi** [comment]
There are some problems with views containing `SELECT * ...`. 
View declares its own schema and it needs to match the schema produced by the underlying query.
In your example, If the schema of `mytable` changes (e.g. a new column is added), the view schema will
become out of sync and the view will be considered stale.

https://github.com/prestosql/presto/blob/6d9d47e0909b3fe9367584ba8450827dbbb8e1d7/presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java#L1177

I'd recommend that you mention all the required columns explicitly when defining a view.

**Comment by findepi** [comment]
Anyway, your question is answered, let me close the issue. We can still continue the discussion here if needed.
