### ISSUE TITLE
ERROR [HY000] [Simba][Presto] (1070) Unknown Presto data type: timestamp(3) in version 336

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#4106]
In 336 still get error in PowerBI when clicking on Schema Preview (ie clicking on table name in PowerBI, typing a direct query SQL is ok though):

DataSource.Error: ERROR [HY000] [Simba][Presto] (1070) Unknown Presto data type: timestamp(3)

PowerBI sent this query
select * from "hive"."information_schema"."columns" WHERE table_schema LIKE 'sales' AND table_name LIKE 'mytable'

which shows successful on the presto server side, but i guess PowerBI sees timestamp(3) value within data_type column and then doesn't know how to handle it

Can you suggest any code to disable parametric timestamp type?

Is that a failure in the Simba driver or at the PowerBI level?
Unfortunately, I can’t think of a good way around that other than the client fixing their logic. We made the protocol backward compatible, but those types are not part of the protocol. They are in the contents of the table being queried. It looks like something in the client is trying to interpret those contents and failing.

Issue in the SIMBA driver, which class controls what values appear in information_schema.columns table? I'm thinking of replacing timestamp(* with timestamp

I see a few options to fix this on the Presto side:
1. Change TypeSignature to render timestamp(3) as timestamp.
2. Change TimestampType similarly for getDisplayName().
3. Change InformationSchemaPageSource to do the transformation just for timestamp.
None of these are particularly appealing.

JDBC metadata in ColumnJdbcTable has the same issue.

In addition to getting Simba to fix the ODBC driver, there is also the potential issue for any application that queries information_schema, JDBC DatabaseMetaData, any similar ODBC facility, etc.

**Comment by dain** [comment]
I think this was fixed in 339

**Comment by adautobezerra** [comment]
@tooptoop4 managed to solve? I'm having the same problem.

**Comment by tooptoop4** [comment]
@adautobezerra we using ApacheRanger so put a column mask policy to replace timestamp(3) with timestamp on these information_schema/system tables
