### ISSUE TITLE
Implement all full AbstractTestIntegrationSmokeTest for Druid

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4116]
Currently `TestDruidIntegrationSmokeTest` runs a subset of `AbstractTestIntegrationSmokeTest` tests because only `orders` table is provided.

**Comment by findepi** [comment]
cc @samarthjain

**Comment by samarthjain** [comment]
PR submitted - https://github.com/prestosql/presto/pull/4271

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/4271
