### ISSUE TITLE
Exception in presto using Qubole.

### ISSUE THREAD

**Issue by spachari** [prestosql/presto#4136]
I have a sql that takes data from a table, does some ETL and loads the output to s3. I am getting this error. But if i remove the insert into statement, the sql works fine. Can anyone tell me what this error means?

`[2020-06-22T07:57:56.330075 #10246] ERROR -- : Command execution failed with exception: Query 20200622_2kaye failed: com.google.common.base.VerifyException
nullsCount must be less than or equal to rowCount. nullsCount:12349898. rowCount: 0.
com.google.common.base.Verify.verify(Verify.java:353)
com.facebook.presto.hive.statistics.MetastoreHiveStatisticsProvider.calculateNullsFraction(MetastoreHiveStatisticsProvider.java:288)
com.facebook.presto.hive.statistics.MetastoreHiveStatisticsProvider.setTableColumnStatistics(MetastoreHiveStatisticsProvider.java:161)
com.facebook.presto.hive.statistics.MetastoreHiveStatisticsProvider.getTableStatistics(MetastoreHiveStatisticsProvider.java:119)
com.facebook.presto.hive.statistics.QuboleMetastoreHiveStatisticsProvider.fetchTableStatistics(QuboleMetastoreHiveStatisticsProvider.java:169)
com.facebook.presto.hive.statistics.QuboleMetastoreHiveStatisticsProvider.getTableStatistics(QuboleMetastoreHiveStatisticsProvider.java:126)
com.facebook.presto.hive.HiveMetadata.getTableStatistics(HiveMetadata.java:554)
com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:234)
com.facebook.presto.metadata.MetadataManager.getTableStatistics(MetadataManager.java:465)
com.facebook.presto.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:66)
com.facebook.presto.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:41)
com.facebook.presto.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:80)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
com.facebook.presto.cost.SelectingStatsCalculator.calculateStats(SelectingStatsCalculator.java:50)
com.facebook.presto.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:85)
com.facebook.presto.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:62)
com.facebook.presto.cost.FilterStatsRule.calculate(FilterStatsRule.java:48)
com.facebook.presto.cost.FilterStatsRule.calculate(FilterStatsRule.java:27)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:80)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
com.facebook.presto.cost.SelectingStatsCalculator.calculateStats(SelectingStatsCalculator.java:50)
com.facebook.presto.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:85)
com.facebook.presto.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:62)
com.facebook.presto.cost.ProjectStatsRule.doCalculate(ProjectStatsRule.java:52)
com.facebook.presto.cost.ProjectStatsRule.doCalculate(ProjectStatsRule.java:30)
com.facebook.presto.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:80)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
com.facebook.presto.cost.SelectingStatsCalculator.calculateStats(SelectingStatsCalculator.java:50)
com.facebook.presto.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:85)
com.facebook.presto.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:62)
com.facebook.presto.cost.AggregationStatsRule.doCalculate(AggregationStatsRule.java:57)
com.facebook.presto.cost.AggregationStatsRule.doCalculate(AggregationStatsRule.java:33)
com.facebook.presto.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:80)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
com.facebook.presto.cost.SelectingStatsCalculator.calculateStats(SelectingStatsCalculator.java:50)
com.facebook.presto.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:85)
com.facebook.presto.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:62)
com.facebook.presto.cost.ProjectStatsRule.doCalculate(ProjectStatsRule.java:52)
com.facebook.presto.cost.ProjectStatsRule.doCalculate(ProjectStatsRule.java:30)
com.facebook.presto.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:80)
com.facebook.presto.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
com.facebook.presto.cost.SelectingStatsCalculator.calculateStats(SelectingStatsCalculator.java:50)
com.facebook.presto.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:85)
com.facebook.presto.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:62)
com.facebook.presto.sql.planner.iterative.rule.DetermineJoinDistributionType.canReplicate(DetermineJoinDistributionType.java:98)
com.facebook.presto.sql.planner.iterative.rule.DetermineJoinDistributionType.addJoinsWithDifferentDistributions(DetermineJoinDistributionType.java:121)
com.facebook.presto.sql.planner.iterative.rule.DetermineJoinDistributionType.getCostBasedJoin(DetermineJoinDistributionType.java:107)
com.facebook.presto.sql.planner.iterative.rule.DetermineJoinDistributionType.apply(DetermineJoinDistributionType.java:78)
com.facebook.presto.sql.planner.iterative.rule.DetermineJoinDistributionType.apply(DetermineJoinDistributionType.java:52)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:166)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:139)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:104)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:95)
com.facebook.presto.sql.planner.LogicalPlanner.runOptimizers(LogicalPlanner.java:173)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:159)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:148)
com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:585)
com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:459)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)`

**Comment by raunaqmorarka** [comment]
@spachari that seems to be an issue with one of older versions of Presto available on Qubole. You can upgrade to the most recent version based on Presto sql repo where this issue should be fixed.
Please raise tickets related to Presto on Qubole with Qubole support.
