### ISSUE TITLE
Aggregation pushdown in SQL Server connector

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4139]
Follow-up to https://github.com/prestosql/presto/pull/3881

Relates to: https://github.com/prestosql/presto/issues/4138

**Comment by mr-big-spency** [comment]
I would like to work on this story.  Please assign to me.

**Comment by kokosing** [comment]
Please go for it!

**Comment by mr-big-spency** [comment]
I did sign the CLA - but getting "2020-09-16T21:36:40.541Z INFO The contributors @dleach001 have not signed the CLA, adding error status to the pull request".  Think I listed mr-big-spency on the CLA.  Not sure why my company userid is showing up as the contributor name as my fork is at: https://github.com/mr-big-spency/presto/tree/agg-pushdown-sqlserver

**Comment by findepi** [comment]
Let's move the CLA-related discussion to `#dev` on [our slack](https://prestosql.io/slack.html). Someone will assist you with this.

**Comment by martint** [comment]
@cla-bot check
