### ISSUE TITLE
Support unsigned int in MySQL connector

### ISSUE THREAD

**Issue by dekelev** [prestosql/presto#4146]
MySQL unsigned integer field with value above the signed int range will fail a simple SELECT query with error like the following:
```
'2.193620399E9' in column '1' is outside valid range for the datatype INTEGER.
```

Presto v336
MySQL v8.x
Mac OS Catalina v10.15.5

**Comment by findepi** [comment]
Implementation plan

* determine unsigned types in `io.prestosql.plugin.mysql.MySqlClient#toPrestoType`  based on `jdbcTypeName` (eg. `BIGINT UNSIGNED` for `create table t(a unsigned bigint);` in mysql)
* map them to a wider type
* tests go into `TestMySqlTypeMapping`

**Comment by fornaix** [comment]
I would like to work on it.

**Comment by findepi** [comment]
@fornaix go for it!
ask on [#dev](https://prestosql.io/slack.html) if you have any questions.

**Comment by chhsiao90** [comment]
Sorry, @fornaix I just saw your comment, and I already have a pull request for this issue.

**Comment by dekelev** [comment]
Works great, thanks!
