### ISSUE TITLE
Unable to connect to a elasticsearch cluster with user/password authentication

### ISSUE THREAD

**Issue by JMNDev** [prestosql/presto#4163]
Hi all I have tried all type of configs and until now I couldn't be able to connect to a elasticsearch cluster that i need to use as source, this elasticsearch was authentication based on user/password only.

Can some one please help me with this topic, with suggestion of configurations or specific fields to add in the configuration to support the user and password.

Thank you very much.

**Comment by martint** [comment]
This is currently not supported. There was some effort to implement this a while ago, but the author appears to have abandoned it: https://github.com/prestosql/presto/pull/2311

The change is fairly straightforward, so it shouldn’t be hard to add. Let me look into it.

**Comment by JMNDev** [comment]
Thank you very much @martint , for the effort.

I would be very thankfull if you find/develop a solution.

**Comment by dekelev** [comment]
@JMNDev in v337, you can now add the following properties to the `elasticsearch.properties` file:

```
elasticsearch.security=PASSWORD
elasticsearch.auth.user=elastic
elasticsearch.auth.password=changeme
```

**Comment by dekelev** [comment]
Found the `elasticsearch.ignore-publish-address` property.

**Comment by JMNDev** [comment]
Thank you very much @dekelev I will test and give some feedback soon.

**Comment by JMNDev** [comment]
@dekelev  I have tested and worked fine. Thank you very much.
