### ISSUE TITLE
Hive connector cache files locality enquiry

### ISSUE THREAD

**Issue by on99** [prestosql/presto#4186]
Is it possible for hive connector to enquire cache layer(rubix/alluxio) for cache files locality on initialization and periodically so scheduler can do better job?

I don't know if hash helps, what if more presto workers are added to the cluster?

**Comment by sopel39** [comment]
> Is it possible for hive connector to enquire cache layer(rubix/alluxio) for cache files locality on initialization and periodically so scheduler can do better job?

For Rubix (and probably Alluxio) scheduler will try to assign splits to nodes where the cached data should be located. This works even if files are not cached yet.

cached file -> node assignment is computed using consistent hashing (in Rubix), therefore adding a new node shouldn't cause full reshuffle.

Does that answer your question?

**Comment by on99** [comment]
Great, thank you! @sopel39
