### ISSUE TITLE
Incorrect return value for ROUND_N with negative N for types other than DECIMAL

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#42]
`ROUND(SMALLINT '99', -1)` should return 100, now it returns 99.

Ref https://github.com/prestodb/presto/issues/10025

**Comment by findepi** [comment]
@ebyhr would you like to rebase & apply comments from https://github.com/prestodb/presto/pull/10349 ?

**Comment by ebyhr** [comment]
@findepi Yes, let me try once again.
