### ISSUE TITLE
presto-hive wrong results with pushed down predicate (version 334) 

### ISSUE THREAD

**Issue by kabunchi** [prestosql/presto#4200]
bottom line:
```
select count(ss_store_sk)  from singleflatstoresales where ss_store_sk = 340;
 _col0 

    0 
(1 row)

select count(ss_store_sk)  from singleflatstoresales where (ss_store_sk - 340) = 0;
 _col0 

  2065 
(1 row)

```

table:
`CREATE TABLE hive.default.singleflatstoresales (         
  ss_sold_date_sk integer,                       
  ss_sold_time_sk integer,                       
  ss_item_sk integer,                          
  ss_customer_sk integer,                        
  ss_cdemo_sk integer,                         
  ss_hdemo_sk integer,                         
  ss_addr_sk integer,                          
  ss_store_sk integer,                         
  ss_promo_sk integer,                         
  ss_ticket_number bigint,                       
  ss_quantity integer,                         
  ss_wholesale_cost double,                       
  ss_list_price double,                         
  ss_sales_price double,                        
  ss_ext_discount_amt double,                      
  ss_ext_sales_price double,                      
  ss_ext_wholesale_cost double,                     
  ss_ext_list_price double,                       
  ss_ext_tax double,                          
  ss_coupon_amt double,                         
  ss_net_paid double,                          
  ss_net_paid_inc_tax double,                      
  ss_net_profit double,                         
  d_date date,                             
  d_year integer,                            
  d_quater integer,                           
  t_am_pm char(2),                           
  c_description100 varchar(100),                    
  c_string_num varchar(4),                       
  c_town varchar(15),                          
  c_description200 varchar(300),                    
  c_jibrish30 varchar(30),                       
  c_description60 varchar(60)                      
 )                                    
 WITH (                                  
  external_location = '***', 
  format = 'PARQUET'                          
 )
`

data - single file (public):
`wget https://varadaio-us-east1-singleflatstoresales.s3.amazonaws.com/part-00008-73b15f45-4d37-45bc-895f-8b04ac80c1e8-c000.snappy.parquet`

initial findings/notes:
- parquet version is relatively old `parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)`
- the relevant column in the file has no stats 
- when rewriting the file to a newer parquet version (and stats) issue solved.
- used to work (95% certainty)

**Comment by findepi** [comment]
@kabunchi thanks for a bug report with full details!

is the problem reproducible with latest master?
we made some fixes around Parquet recently.

**Comment by kabunchi** [comment]
reproduced. 
proposed fix in https://github.com/prestosql/presto/pull/4255
