### ISSUE TITLE
Failed to return the minimum value of BIGINT

### ISSUE THREAD

**Issue by mchades** [prestosql/presto#4210]
> BIGINT
> A 64-bit signed two’s complement integer with a minimum value of -2^63 and a maximum value of 2^63 - 1.

when I try to get a minimum value of -2^63(-9223372036854775808), I got this error:
```
presto> select -9223372036854775808;
Query 20200625_075330_00004_36zfm failed: line 1:1: Invalid numeric literal: 9223372036854775808
select -9223372036854775808
```

**Comment by findepi** [comment]
@mchades thanks for your report.
We fixed this a couple versions ago.

```
presto:test> select -9223372036854775808;
        _col0
----------------------
 -9223372036854775808
(1 row)
```

Please make sure to upgrade to Presto 336.
https://prestosql.io/download.html

Let me close as answered, but we can continue discussion here,
or on our [slack](https://prestosql.io/slack.html).
