### ISSUE TITLE
docker run causes env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by MohammedRashidKP** [prestosql/presto#4215]
With the latest presto-server-336 tarball, on doing docker run, getting

+ [[ ! -d /usr/lib/presto/etc ]]
+ [[ -d /etc/presto ]]
+ ln -s /usr/lib/presto/default/etc /usr/lib/presto/etc
+ set +e
+ grep -s -q node.id /usr/lib/presto/etc/node.properties
+ NODE_ID_EXISTS=1
+ set -e
+ NODE_ID=
+ [[ 1 != 0 ]]
+ NODE_ID=-Dnode.id=d30d44f455d9
+ exec /usr/lib/presto/bin/launcher run -Dnode.id=d30d44f455d9
env: ‘python’: No such file or directory

The Dockerfile does not include RUN command for python installation and setting environment variable.

**Comment by ebyhr** [comment]
@MohammedRashidKP The docker image in https://hub.docker.com/r/prestosql/presto contains Python. Could you share the steps to reproduce?

**Comment by MohammedRashidKP** [comment]
Right. But the Docker file at 'presto/docker/Dockerfile' does not contain the step to install python. I had to customise the Dockerfile to have base image rhel-ubi instead of the CentOs that comes in the file.
And I believe CentOs doesn't come with python and we need to install it, like jdk-11 is installed.

I added the following lines and it worked:
yum install -y python36 python3-pip && \
    ln -s /usr/bin/python3.6 /usr/local/sbin/python && \
    python -V && \

**Comment by findepi** [comment]
Centos docker image comes with Python preinstalled.
Of course, you can create your own Dockerfile, just the way you did, changing the base image or the installed components.
It's reasonable to expect that such a change may imply some other changes. For example, changing the base image may require adding more packages, using different names of packages, or changing the way packages are installed.

I happy you were succesful creating your own image!

btw please make sure you're on the `#dev` channel of our [slack](https://prestosql.io/slack.html).
