### ISSUE TITLE
Wrong answer of coalesce function

### ISSUE THREAD

**Issue by mchades** [prestosql/presto#4219]
the result of expression `coalesce(1234,'56')` should be `1234`，but presto got `12`:

```
presto> select coalesce(1234,'56');
 _col0
-------
 12
(1 row)
```

**Comment by tooptoop4** [comment]
works fine for me

what version u on? in 336 i get All COALESCE operands must be the same type: integer

select coalesce('1234','56'); gives 1234

**Comment by mchades** [comment]
@tooptoop4 I base the presto version of 0.215

when I run on Hive:
```
hive> select coalesce(1234,'56');
OK
_c0
1234
Time taken: 0.035 seconds, Fetched: 1 row(s)
```

**Comment by findepi** [comment]
@mchades can you please check with Presto 336 https://prestosql.io/download.html?

**Comment by mchades** [comment]
@findepi thanks a lot, i rerun the sql on version of 336, and got the same result as @tooptoop4 showed.

**Comment by findepi** [comment]
thanks for confirming. let me close this then.
