### ISSUE TITLE
Elasticsearch Connector some properties need to be documented

### ISSUE THREAD

**Issue by BruceKellan** [prestosql/presto#4256]
hi, when i using es connector in my presto, I found property named 'elasticsearch.ignore-publish-address' in source code.
It work for me, but I can't find it in document.
I think it need to be documented, isn't it ?

**Comment by dekelev** [comment]
Thank you for that!!! I was going crazy about this connector and only now I see that it uses the `_nodes/http` endpoint to get the `publish_address` of all nodes.

There is zero documentation about this functionality and the `elasticsearch.ignore-publish-address` property.

In addition, PrestoSQL just released the user & password auth in v337, again without updating the docs about the new functionality and properties:
```
elasticsearch.security=PASSWORD
elasticsearch.auth.user=elastic
elasticsearch.auth.password=changeme
```

It's expected from an open-source this size to update docs along with code at the same release version.

**Comment by martint** [comment]
cc @mosabua

**Comment by mosabua** [comment]
I am going to assign this to myself for now. If anybody wants to get to it before me link a PR to here... otherwise I hope to get to it next week

**Comment by mosabua** [comment]
Doc PR merged. Will be published with next release
