### ISSUE TITLE
Is there a memory leak?

### ISSUE THREAD

**Issue by manbuyun** [prestosql/presto#4257]
There are 100 woker nodes in our cluster, and the OOM of worker nodes occasionally occurs. The picture is as follows(version 310):
![image](https://user-images.githubusercontent.com/29940618/85977402-20747400-ba0f-11ea-8c4f-0480260a3e75.png)
![image](https://user-images.githubusercontent.com/29940618/85977454-3a15bb80-ba0f-11ea-9759-fef9e22e4430.png)
![image](https://user-images.githubusercontent.com/29940618/85977491-4863d780-ba0f-11ea-8092-7012aebdd3fb.png)

**Comment by sopel39** [comment]
Hi @manbuyun ,

Thanks for reporting. It seems to be coming from `io.prestosql.execution.SqlTaskExecution#drivers`. Could it be possible to try with newest Presto?
Is there some way of reproducing it? Was it for particular query? What connectors were used? Did you used caching?

**Comment by manbuyun** [comment]
Thanks for replying @sopel39 ,
Hive connector was used in our cluster. No cache.
There is no way to reproduce it. Several worker machines may hang up in about 3 days. The stack is all in issue.
It seems to be coming from io.prestosql.parquet.reader.BinaryColumnReader

**Comment by manbuyun** [comment]
![image](https://user-images.githubusercontent.com/29940618/85998353-40229100-ba3d-11ea-98af-d65a5c952083.png)
Is there anything to do to avoid?

**Comment by sopel39** [comment]
CC @martint. I recommend using newest Presto version. There have been fixes to Parquet reader.

**Comment by manbuyun** [comment]
@sopel39 
Can you tell me which PR or key code fixed this problem? I want to merge into version 310.

**Comment by manbuyun** [comment]
@martint Sorry. Can you tell me which PR or key code fixed this problem? I want to merge into version 310.

**Comment by tooptoop4** [comment]
did u solve @manbuyun ? I also face particular older worker processing splits much slower than other workers

**Comment by duhanmin** [comment]
@tooptoop4 @manbuyun https://github.com/trinodb/trino/pull/10632
