### ISSUE TITLE
recommended support "offset ... limit ..." statement?

### ISSUE THREAD

**Issue by caleben** [prestosql/presto#4281]
wether to consider support "offset ... limit ..." statement? paging query?

**Comment by findepi** [comment]
@caleben  Presto does support `OFFSET .. LIMIT` syntax:

```
presto> SELECT nationkey, name FROM tpch.tiny.nation ORDER BY nationkey OFFSET 5 LIMIT 5;
 nationkey |   name
-----------+-----------
         5 | ETHIOPIA
         6 | FRANCE
         7 | GERMANY
         8 | INDIA
         9 | INDONESIA
(5 rows)
```

is this what you are asking about?
which Presto version are you currently using?

**Comment by caleben** [comment]
yes! tks.
I used the version 310, now presto has supported OFFSET .. LIMIT? which version begin

**Comment by findepi** [comment]
OFFSET support was dded in 311, but there were some fixes later as well.
Please upgrade to 337.

BTW make sure you join our [slack](https://prestosql.io/slack.html).

**Comment by caleben** [comment]
ok.

I`m now  in slack
