### ISSUE TITLE
Upgrade druid avatica jdbc version for CJK issue

### ISSUE THREAD

**Issue by hey-jude** [prestosql/presto#4312]
Current druid avatica jdbc driver (version 1.16.0) has non-latin character issue, this was fixed on 1.17.0 .

https://issues.apache.org/jira/browse/CALCITE-2704
https://calcite.apache.org/avatica/docs/history.html#v1-17-0

So, I wish upgrade this version.

**Comment by findepi** [comment]
@hey-jude good idea. Do you plan doing a PR?
hopefully https://github.com/prestosql/presto/blob/03aa1b6f9d9ced2807a33d578384c6e05a6f939a/presto-druid/pom.xml#L45 is the only place to change

cc @samarthjain

**Comment by hey-jude** [comment]
@findepi 
https://github.com/prestosql/presto/pull/4326
