### ISSUE TITLE
Support GRANT/REVOKE <privileges> ON <schema> to <principal>

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#4327]
Currently it is possible to grant/revoke access to tables (and views). This ticket is about adding similar functionality for schemas.

For example when SELECT is granted on schema then user can select any from any table in that schema.

**Comment by lhofhansl** [comment]
When we discussed this in the past the concern was that Hive does not support this and thus we'd diverge from what can be supported with Hive.

I agree that this would be very helpful and useful.

**Comment by kokosing** [comment]
> When we discussed this in the past the concern was that Hive does not support

Correct. However this issue is generic it is about adding this syntax to the engine in general, then we could discuss if we should support that with `hive.security=sql-standard`

**Comment by lhofhansl** [comment]
When I checked the Hive-Metastore it seems to have the parts in place to implement this - but I only took a quick look.

**Comment by kokosing** [comment]
Good to know. Thanks.

**Comment by lukasz-walkiewicz** [comment]
I've submitted a PR (#4396) with syntax proposition and changes to the appropriate interfaces in the engine. I would appreciate your comments.

**Comment by kokosing** [comment]
I extracted Hive sql-standard support for this as https://github.com/prestosql/presto/issues/5784. Closing this one as engine changes are already merged.
