### ISSUE TITLE
Add function to extract all table names from a query string

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#4331]
For example:

imagine below sample data (4 rows) -->
select query from system.runtime.queries gives:

```
select abc,xyz from schema4.tableB join schema3.tableA on 1=1
with x as (select * from catalogG.schema7.tableY union all catalogR.schema9.tableA) select * from x where j not in (select id from tableH) and not exists (select 1 from catalogR.schema9.tableA where d='a')
select count(1) from tableU
select 1
```

select get_table_names(query) from system.runtime.queries would give:

expected result (4 rows ie an array showing all tables involved in each query):
```
['schema4.tableB','schema3.tableA']
['catalogG.schema7.tableY','catalogR.schema9.tableA','tableH']
['tableU']
[]
```

ie new function get_table_names() would parse all table names from given sql

use case is to get metrics on table usage. ie how many times each table was queried

**Comment by kokosing** [comment]
What is the use case here? Extracting table is not that simple as it requires semantic analysis to happen and also it requires a session configuration that was present during the query execution.

For reference, all referenced tables in the query are mentioned in the query event. Maybe using eventlistener is a better fit for you?

**Comment by tooptoop4** [comment]
I want to show a bar chart in Superset with count of how many times each table was queried

**Comment by kokosing** [comment]
So using eventlistener sounds like the way to go. You capture tables from event then you can store them in relation database (postgres?) and you can query that in the way you like.

Let me close this issue.
