### ISSUE TITLE
Presto not showing microseconds for table created via spark-sql

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#4334]
Use spark-submit (v2.4.6) to write parquet to s3://redact/fol/part_filename=ju.txt/ (parquet is https://github.com/tooptoop4/presto-1/blob/master/part-00000-e35ff4f1-5a4b-4b5e-afde-fe00fcc1a7b2-c000.snappy.parquet?raw=true)

Use spark-sql to run:
CREATE EXTERNAL TABLE s.t (opr_date TIMESTAMP,city STRING,hour DOUBLE,temp DOUBLE,temp_diff DOUBLE,temp_normal DOUBLE,dew DOUBLE,cloud_cover DOUBLE,feels_like DOUBLE,feels_like_diff DOUBLE,precip DOUBLE,wind_dir DOUBLE,wind_speed DOUBLE,hdd DOUBLE,cdd DOUBLE ) PARTITIONED BY (part_filename STRING) STORED AS PARQUET LOCATION 's3a://redact/fol/';

Use spark-sql to run:
MSCK REPAIR TABLE s.t;

Query in HiveServer2 (v2.3.4):
select * from s.t;

![image](https://user-images.githubusercontent.com/33283496/86470828-1ebeef00-bd34-11ea-82fa-e88437c82733.png)

Query in PrestoSQL (336 and JDBC driver is 336):
select *,date_format(opr_date,'%f') from s.t;

![image](https://user-images.githubusercontent.com/33283496/86470912-4910ac80-bd34-11ea-92cc-537c156f8f27.png)

show create table s.t;

CREATE TABLE s.t (
   opr_date timestamp(3),
   city varchar,
   hour double,
   temp double,
   temp_diff double,
   temp_normal double,
   dew double,
   cloud_cover double,
   feels_like double,
   feels_like_diff double,
   precip double,
   wind_dir double,
   wind_speed double,
   hdd double,
   cdd double,
   part_filename varchar
)
WITH (
   external_location = 's3a://redact/fol',
   format = 'PARQUET',
   partitioned_by = ARRAY['part_filename']
)

cc @martint

**Comment by findepi** [comment]
This is covered by https://github.com/prestosql/presto/issues/3977
