### ISSUE TITLE
support for auto_increment column in mysql connecter

### ISSUE THREAD

**Issue by liyubin117** [prestosql/presto#4352]
Now I have to build a temporary table like my destination table but exclude auto_increment column, 
at first, insert value into temporary table  in presto, then insert into destination table from temporay table in mysql-cli,
It will be great if mysql connector support for auto_increment column

**Comment by Praveen2112** [comment]
Can you check with the latest Presto version. I guess this was added in 330(#2265) where Presto respects the columns with `DEFAULT` when inserting data for JDBC based connector. So when inserting into your table we don't have to specify the `auto_increment column` in our INSERT query. 

Feel free to join the #dev channel on our [slack](https://prestosql.io/slack.html).

**Comment by liyubin117** [comment]
@Praveen2112 excellent improvement! thanks very much
