### ISSUE TITLE
Hive connector silently ignores extra buckets

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#4378]
`BackgroundHiveSplitLoader.getBucketedSplits()` should verify that every bucket number is less than `partitionBucketNumber`. For example, create a table with a bucket count of `4` and then create these files:
```
0000_0
0001_0
0003_0
0004_0
0009_0
```
The files for buckets 4 and 9 are silently skipped. The query should instead fail with `HIVE_INVALID_BUCKET_FILES`.

**Comment by ArvinZheng** [comment]
So basically we should catch this case - the highest bucket number that detected from data file should be less than `(table bucket number)` and then fail the query? But would it impact the data correctness in current implementation as anyway we skip those 2 invalid buckets?
