### ISSUE TITLE
Presto: Not able to connect External Hive using presto hive connector.

### ISSUE THREAD

**Issue by SonuSingh200190** [prestosql/presto#4405]
In Presto, I was trying to connect external hive source using Presto Hive connector. I added the below configuration in hive.properties but its not working. Please help.

connector.name=hive-hadoop2
connection-url=jdbc:hive2://x.x.x.x:10000
connection-user=hive
connection-password=hive

**Comment by phd3** [comment]
Presto uses Hive Metastore for accessing hive table metadata (it doesn't use hive's execution engine).  You can find the configuration for setting up `hive.properties` here: https://prestosql.io/docs/current/connector/hive.html#configuration

**Comment by phd3** [comment]
@SonuSingh200190 I hope this helped. Closing this. We can continue discussion here
or on [our Slack](https://prestosql.io/slack.html). See you there!

**Comment by SonuSingh200190** [comment]
Thanks, Pratham.
