### ISSUE TITLE
single TupleDomain constraint for multiple splits

### ISSUE THREAD

**Issue by kabunchi** [prestosql/presto#442]
In case the constraint is large sending the constraint (TupleDomain) per split is wasteful (for the case the constraint is the same per split).
In our connector we have relatively large number of small splits and we've stumbled upon the use case of querying for 10K string keywords in a single query we hacked/fixed it by adding the constraint to TaskSource and then infest it to all its splits. 
Does it makes sense? Is this approach acceptable? Would it be more clean to add another kind of connectorHandle per taskSource?

**Comment by martint** [comment]
The information is contained in the TableHandle associated with the TableScanNode. What we might need to do is change the PageSourceProvider API to take the TableHandle in addition to the Split. That way, anything that's common for the whole query doesn't need to be included in every split (only what's relevant to a split). 

This is going to be important to support pushdown of complex operations and whole subplans into connectors. We certainly don't want connectors to have to embed a copy of the subplan in every split! (relates to https://github.com/prestosql/presto/wiki/Pushdown-of-complex-operations)
