### ISSUE TITLE
Not able to system.register_partition with a default location if the location is not provided (hive connector)

### ISSUE THREAD

**Issue by pangyifish** [prestosql/presto#4443]
I am wondering if we can have a default location just like system.create_empty_partition does.

**Comment by findepi** [comment]
For registering partitions that conform to hive's partition directory naming convention
I would recommend using `sync_partition_metadata` procedure.

**Comment by sandeshh** [comment]
> For registering partitions that conform to hive's partition directory naming convention
> I would recommend using `sync_partition_metadata` procedure.

That would be very expensive operation. Use case here is we are adding a new dt partition everyday, so just register_partition is sufficient.

**Comment by wendigo** [comment]
I was thinking about that case and one more - when one of the partitions is broken we can unregister all and then add one at the time to find the broken one.

**Comment by findepi** [comment]
> Use case here is we are adding a new dt partition everyday

@sandeshh how do you write the data? (eg who _names_ the output directory?)

**Comment by sandeshh** [comment]
Legacy writers, writes the data to S3 and Spark adds the partition. Spark uses default location. Having this option would make it easy for us to just replace Spark with Presto.

**Comment by electrum** [comment]
Making location optional seems reasonable.
