### ISSUE TITLE
URI generation with TLS-terminating proxies

### ISSUE THREAD

**Issue by mh-amount** [prestosql/presto#4453]
This is similar to https://github.com/prestosql/presto/issues/2908. In a scenario where we have Presto running plain http behind a reverse proxy which has SSL enabled (an AWS ALB, in this case), Presto doesn't take the original protocol header into consideration when creating the nextUri/infoUri/cancelUri elements of the response object from POST /v1/statement. As a result, clients end up attempting to connect to the reverse proxy via http instead of https.

I assume fixing the protocol/port on uri generation will be a reasonable approach in the short term. It's a larger effort, but if the uris were relative instead of fully resolved by presto, that would reduce a lot of this complexity in the long run. It might make presto a little less opinionated about how things like credentials, tls, and proxies should be used with the application, but that separation of concerns is really nice when users have deployment strategies that may differ from the author's expectations.

Are there any concerns about implementing the short-term/simple fix as described?

**Comment by mh-amount** [comment]
After poking around to see what would be required, I noticed the proxy-server directory in the repo that might handle what I'm trying to do (though it's odd having a proxy made by presto rather than just making presto work well with proxies). Is that the recommended approach for this type of problem, and if so, is anyone aware of any documentation on how to use it? The readme is pretty sparse and I'm having trouble finding docs via googling.

**Comment by electrum** [comment]
Presto should handle this correctly as of 336 (?). What version are you running?

Can you show the request headers sent from the load balancer to Presto?

`presto-proxy` solves a very specific problem of being a secure front end for Presto. It only supports TLS client certificates for authentication, so it’s usefulness may be limited.

As of 337, everything in Presto should be fully authenticated and authorized, so there is less need for the proxy. Though the proxy still adds a layer of security since it only exposes exactly what is needs for the client protocol, which can be important in some environments.

**Comment by mh-amount** [comment]
The ALB provides X-forwarded-for, X-forwarded-proto, and X-forwarded-port: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

Without sharing the specific values for this, I can confirm that they are correct. We're running Presto 338.

**Comment by dain** [comment]
@mh-amount with `http-server.process-forwarded=true` in 338, the amazon ELBs work fine with Presto.

If you are still having issues. Please post the headers, the request url and the response url you are getting.  You can also test this with curl on the command line to make things simpler.

**Comment by findepi** [comment]
We definitely need `http-server.process-forwarded` documented. 
Currently it's only mentioned in release notes.
cc @mosabua 

@dain can we at least log warning, when X-Forwarded are used and `http-server.process-forwarded` is not set at all?
Previously most of the provided behavior was available without any configuration.

**Comment by mosabua** [comment]
I will try to get a PR going for this soon.

**Comment by mh-amount** [comment]
It's working with the new setting. Thanks.
