### ISSUE TITLE
Provide a FileBasedGroupProvider

### ISSUE THREAD

**Issue by lhofhansl** [prestosql/presto#4493]
Now that we have GroupProviders we should add a default implementation.

**Comment by lhofhansl** [comment]
A rules files could be structured like this:
```
{
   "users": [
      {
         "user": <pattern>,
         "groups": [group1, group2, ...]
      },
      {...}
   ]
}
```

If a user matches multiple pattern the set of groups would be the superset of all matching rules.

**Comment by kokosing** [comment]
> If a user matches multiple pattern the set of groups would be the superset of all matching rules.

This is something contrary to what we do in other places. Typically we traverse rules from top to bottom and first one applies, when no one applies then we raise an error.

**Comment by lhofhansl** [comment]
@kokosing I agree that's easier to reason about.

**Comment by electrum** [comment]
This was done in #4493
