### ISSUE TITLE
CLI should not print `field0`, `field1` for anonymous ROW

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4587]
Currently

```
presto> SELECT ROW(42, true, 'abc');
                _col0
--------------------------------------
 {field0=42, field1=true, field2=abc}
(1 row)
```

But 

```
presto> SELECT ROW(42, true, 'abc').field0;
Query 20200726_092259_00004_fz6ey failed: line 1:8: Column 'null' cannot be resolved
```

We should not print those field names.

**Comment by electrum** [comment]
Is this a bug in the CLI or client protocol? It sounds like the names are in the type name or signature returned from the server.

**Comment by findepi** [comment]
@electrum this is here:
https://github.com/prestosql/presto/blob/838048343f6868f65f574bc00edf612a1b5ee77e/presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java#L117
