### ISSUE TITLE
Investigate possible incorrect query results related to ORC decimal min/max statistics

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4637]
https://issues.apache.org/jira/browse/ORC-517 doesn't say this causes correctness problem
But   https://github.com/apache/orc/pull/405/files#diff-a0861c5ad0775baf23793ac86da5fbb6R502-R507
ignores stats written by older writers, suggesting there was a correctness problem.

**Comment by alexjo2144** [comment]
I took a look at this yesterday, and was able to reproduce the incorrect stats issue. I don't think we need to explicitly skip stats for that generation of the writer though. The stats are always more inclusive than they need to be, so I don't think this will cause incorrect results from predicate pushdown.

**Comment by findepi** [comment]
Thanks for checking @alexjo2144
