### ISSUE TITLE
Presto GUI prompts for Client certificate after enabling HTTPS

### ISSUE THREAD

**Issue by DRavikanth** [prestosql/presto#4644]
After enabling HTTPS for Presto on trying to access the GUI on HTTPS link the browser prompts for a client certificate. Can this be addressed ?

Thanks,
Ravi

**Comment by tooptoop4** [comment]
duplicate of https://github.com/prestosql/presto/issues/3649

**Comment by findepi** [comment]
@tooptoop4 thanks, my fault

@DRavikanth thanks for reporting the issue, let's continue under https://github.com/prestosql/presto/issues/3649
