### ISSUE TITLE
document for hive.metastore-timeout config

### ISSUE THREAD

**Issue by ArvinZheng** [prestosql/presto#4663]
I can't see this config in the documentation, this config is somehow useful when people use thrift metastore, I think we should add it to the doc.

**Comment by yuokada** [comment]
FYI: This one.

- https://github.com/prestodb/presto/blob/ba8627aa260c96fefdc9e5f6069f4b86d0b3d45b/presto-hive/src/main/java/com/facebook/presto/hive/HiveClientConfig.java#L398-L409
- https://github.com/prestosql/presto/blob/master/presto-docs/src/main/sphinx/connector/hive.rst

**Comment by agrawalreetika** [comment]
This is documented as a part of this #4986
