### ISSUE TITLE
Support aggregation pushdown for functions with coercions

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#4689]
We can't pushdown `sum(integer)` today because Presto only has `sum(bigint)` and thus the implicit coercion prevents the pushdown rule from matching. However, the fact that Presto doesn't `sum()` implement for all the integer types is an implementation detail. We should instead be pushing down the original `sum(integer)` operation, without the coercion applied.

**Comment by findepi** [comment]
Duplicate https://github.com/prestosql/presto/issues/4170
