### ISSUE TITLE
Pushdown filter with expression

### ISSUE THREAD

**Issue by infearOnTheWay** [prestosql/presto#4708]
Hi all，

I wonder presto support ‘pushdown filter with expression’ to connector or not. Consider such case:
`select * from table where func(a) > b`
My question is whether the _func(a)_ could be pushdown to the connector while this caculation could get better performance from the data source.

**Comment by sopel39** [comment]
Currently, it's not supported. However, Presto will use lazy materialization technique. It will first read column `a` and `b`, evaluate filter and only fetch other columns when there are rows in page that evaluate to `true`. This only works for connectors, that support lazy column reads (e.g Hive, Iceberg).

**Comment by martint** [comment]
We have a plan to support that. Last year we added a new connector API (`applyFilter`) for that purpose. The part that's missing is a way to communicate to connectors the identity of functions and for connectors to be able to look up and resolve functions. That's currently in progress and we expect to have it in the near future. The overall effort is being tracked here: https://github.com/prestosql/presto/issues/18

**Comment by infearOnTheWay** [comment]
@sopel39 @martint 
Thanks for your replys. I would follow the #18 .
