### ISSUE TITLE
Hive CLUSTERED BY SORTED BY sort files should utilize a configurable temporary location

### ISSUE THREAD

**Issue by ddrinka** [prestosql/presto#471]
See https://github.com/prestodb/presto/issues/11664 for previous discussion.

HivePageSinkProvider should support a configurable temporary location for Sort Files.  Currently these Sort Files are stored beside the table, which may be far away, such as in S3.  This leads to poor performance and stalled/failed queries due to common S3 timeouts when working with larger amounts of data.

**Comment by ddrinka** [comment]
@electrum is this still your realm?

**Comment by electrum** [comment]
@ddrinka I don't think adding a config for this will be difficult. Are you interested in working on this yourself?

**Comment by ddrinka** [comment]
@electrum I'm not a Java developer and don't have an environment set up to work well within the ecosystem.  If this is a quick fix for you or someone else, it would save me many hours of setup time to be able to contribute a PR.  However if I accumulate enough pending simple fix requests here I'll eventually do the work.  :)

**Comment by raunaqmorarka** [comment]
@electrum could you please take a look at https://github.com/prestosql/presto/pull/3434 which is trying to address this ?
