### ISSUE TITLE
Document logging configuration options

### ISSUE THREAD

**Issue by martint** [prestosql/presto#477]
We don't have documentation for logging-related configuration such as:

* log.max-history
* log.max-size
* http-server.log.max-history
* http-server.log.max-size

**Comment by mosabua** [comment]
Prepared a doc PR but there doesnt seem to be any of this config in the presto code base .. is this part of the airlift config basically so I can look it up there?

**Comment by mosabua** [comment]
There is lots more e.g. https://github.com/airlift/airlift/blob/418b0adea11560b81330bf750f4b42a173848d97/http-server/src/main/java/io/airlift/http/server/HttpServerConfig.java 

Maybe we should see what sort of docs we create for airlift as well.. and then just refer to it.

**Comment by findepi** [comment]
> Maybe we should see what sort of docs we create for airlift as well.. and then just refer to it.

@mosabua see https://github.com/airlift/airlift/issues/753, https://github.com/airlift/airlift/issues/417, and https://prestosql.slack.com/archives/CFLB9AMBN/p1567834707126800?thread_ts=1567726032.112300&cid=CFLB9AMBN.

Quoting @electrum 
> For user facing config like HTTP server, that should be part of Presto documentation. Users shouldn't have to look elsewhere.

**Comment by mosabua** [comment]
Also l looked at https://github.com/airlift/airlift/blob/ca3cb480e1d052c960bf969dd0e90623d7ad0be0/log-manager/src/main/java/io/airlift/log/LoggingConfiguration.java
