### ISSUE TITLE
Possibility to do `container.withReuse(true)`

### ISSUE THREAD

**Issue by iirekm** [prestosql/presto#4806]
I'm adding support for `container.withReuse(true)` to our project, to make local development faster (see `GenericContainer.withReuse`). It works very well with containers provided by TestContainers, but doesn't work so well with containers provided by Presto, for example: 
- `TestingPostgreSqlServer`: it starts `container.start()` in constructor - doing I/O in constructor is generally considered as an antipattern, for example it prevents customizations (like `withReuse(true)`, `withEnv(...)` etc)
- `TestMySqlIntegrationSmokeTest` - method `destroy()` is final, I can't do anything with it in subclasses - for `withReuse(true)` functionality, `container.close()` or `container.stop()` should be replaced with something like:
```java
if (!container.isShouldBeReused() || !TestcontainersConfiguration.getInstance().environmentSupportsReuse()) {    
    container.stop();
}
```
- and many, many more things that call `start()` or `close()`

**Comment by ebyhr** [comment]
I think you already filed similar issue (https://github.com/prestosql/presto/issues/4514). What is the difference from the previous one?

**Comment by iirekm** [comment]
ahh, sorry, some time passed, I forgot about that issue

so I'm closing this one as duplicate, and adding more comments there
