### ISSUE TITLE
[PrestoSQL316] Select query with alias as mentioned below fails in presto cli but works properly in spark-sql. 

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4809]
Environment - PrestoSQL316 version. Spark 2.4.5 version. Carbondata 2.0.1 version.

Steps-
From spark-sql execute the below create carbondata table and load data to table.
create table all_datatypes_2048 (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) stored as carbondata TBLPROPERTIES('table_blocksize'='2048','flat_folder'='true');
LOAD DATA INPATH 'hdfs://hacluster/chetan/100_olap_C20.csv' INTO table all_datatypes_2048 options ('DELIMITER'=',', 'QUOTECHAR'='\', 'BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription');

Issue -
From prestosql  cli execute the select query. The select query fails with error as shown below.
select AMSize,sum(gamePointId+contractNumber) as total from all_datatypes_2048 where  CUPAudit='0CPU Audit' group by AMSize having total > 10 order by total desc;
**Query 20200803_062409_00044_etxj6 failed: line 1:132: Column 'total' cannot be resolved**
select AMSize,sum(gamePointId+contractNumber) as total from all_datatypes_2048 where  CUPAudit='0CPU Audit' group by AMSize having total > 10 order by total desc

**Comment by martint** [comment]
This is expected behavior in standard SQL. The column names in the SELECT clause are not visible to the HAVING clause (from a logical point of view, HAVING evaluates before the SELECT clause).

You need to rewrite your query as:

```sql
SELECT AMSize, sum(gamePointId+contractNumber) as total 
FROM all_datatypes_2048
WHERE CUPAudit='0CPU Audit'
GROUP BY AMSize 
HAVING sum(gamePointId+contractNumber) > 10 
ORDER BY total DESC
```

or use a subquery:

```sql
SELECT * FROM (
    SELECT AMSize, sum(gamePointId+contractNumber) as total 
    FROM all_datatypes_2048
    WHERE CUPAudit='0CPU Audit'
    GROUP BY AMSize 
)
WHERE total > 10 
ORDER BY total DESC
```

**Comment by martint** [comment]
cc @mosabua, we should probably document this.

**Comment by mosabua** [comment]
What specifically? That Presto adheres to ANSI SQL? Maybe some note visibility out from the Having clause docs about https://prestosql.io/docs/current/sql/select.html#having-clause ? cc @Ordinant @rosewms

**Comment by martint** [comment]
I was thinking something about how SELECT / WHERE / GROUP BY / HAVING work in sql, visibility scopes, etc. Yes, Presto follows ANSI SQL semantics, but people don't read the SQL spec, and many databases deviate from the spec so you can't rely on their documentation or tutorials built around them.

**Comment by mosabua** [comment]
Maybe should add a section about visibility scopes into https://prestosql.io/docs/current/sql/select.html after description?
