### ISSUE TITLE
[PrestoSQL 316] After alter table add column on Carbondata table select query on newly added column throws error in prestocli

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4821]
Environment - PrestoSQL 316, Spark 2.4.5, Carbondata 2.0.1

Steps - 
From SparkSQL create carbondata table and load data to table.
spark-sql> create table brinjal (imei string,AMSize string,channelsId string,ActiveCountry string, Activecity string,gamePointId double,deviceInformationId double,productionDate Timestamp,deliveryDate timestamp,deliverycharge double) stored as carbondata TBLPROPERTIES('table_blocksize'='1','COLUMN_META_CACHE'='AMSize','carbon.column.compressor'='gzip');
Time taken: 0.264 seconds
spark-sql> LOAD DATA INPATH 'hdfs://hacluster/chetan/vardhandaterestruct.csv' INTO TABLE brinjal OPTIONS('sort_scope'='global_sort','DELIMITER'=',', 'QUOTECHAR'= '"','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'= 'imei,deviceInformationId,AMSize,channelsId,ActiveCountry,Activecity,game                                                                                                              PointId,productionDate,deliveryDate,deliverycharge');

alter table add column on Carbondata table

spark-sql> alter table brinjal add columns(age int);

Issue - After alter table add column on Carbondata table select query on newly added column throws error in prestocli.

presto:priyesh> select * from brinjal where age is NULL and gamePointId =1341.0;
Query 20200805_154611_00563_ed34h failed: line 1:29: Column 'age' cannot be resolved
select * from brinjal where age is NULL and gamePointId =1341.0

**Comment by martint** [comment]
Can you show the output of `describe` for your table?

**Comment by chetandb** [comment]
spark-sql> desc brinjal;
imei    string  NULL
amsize  string  NULL
channelsid      string  NULL
activecountry   string  NULL
activecity      string  NULL
gamepointid     double  NULL
deviceinformationid     double  NULL
productiondate  timestamp       NULL
deliverydate    timestamp       NULL
deliverycharge  double  NULL
Time taken: 0.076 seconds, Fetched 10 row(s)
spark-sql>  alter table brinjal add columns(age int);
OK
Time taken: 0.426 seconds
spark-sql> desc brinjal;
imei    string  NULL
amsize  string  NULL
channelsid      string  NULL
activecountry   string  NULL
activecity      string  NULL
gamepointid     double  NULL
deviceinformationid     double  NULL
productiondate  timestamp       NULL
deliverydate    timestamp       NULL
deliverycharge  double  NULL
age     int
Time taken: 0.044 seconds, Fetched 11 row(s)

**Comment by dain** [comment]
Can you describe the table in Presto?  

Also, this could be related to #4820.  The carbondata code you are using could be caching the schema somehow.  You could verify by restarting your Presto cluster to see if the issue is resolved.  If that works, I would dig into the carbondata code to figure out what it is doing.

**Comment by chetandb** [comment]
presto:chetan> desc brinjal;
       Column        |   Type    | Extra | Comment
---------------------+-----------+-------+---------
 imei                | varchar   |       |
 amsize              | varchar   |       |
 channelsid          | varchar   |       |
 activecountry       | varchar   |       |
 activecity          | varchar   |       |
 gamepointid         | double    |       |
 deviceinformationid | double    |       |
 productiondate      | timestamp |       |
 deliverydate        | timestamp |       |
 deliverycharge      | double    |       |
 age                 | integer   |       |
(11 rows)

Query 20200813_180407_01349_8k3vm, FINISHED, 3 nodes
Splits: 53 total, 53 done (100.00%)
0:00 [11 rows, 766B] [104 rows/s, 7.12KB/s]

**Comment by dain** [comment]
Does the query still fail?  If not, I expect there was some caching the carbondata connector you are using.

**Comment by chetandb** [comment]
yes the query fails.

**Comment by dain** [comment]
Can you post the stacktrace?

**Comment by chetandb** [comment]
Issues to be discussed and tracked in relevant community. Its closed here.
