### ISSUE TITLE
Optimize join ordering in query execution

### ISSUE THREAD

**Issue by isanuk** [prestosql/presto#483]
[First Post, submitting as a SQL user, not a developer]

**tl;dr** feature request: optimize table ordering before executing joins

As an analyst, we often need to remember optimization tricks to get queries to run faster. One specific optimization is the ordering of tables in a Join. We find that with Presto SQL, it is important to always put the "large table on the left" (e.g. first in code order) to improve performance.

Feature request: could we solve for the optimal table ordering in the query execution process? e.g. optimize ordering by table size?

**Comment by billonahill** [comment]
This functionality already exists. It requires enable stats collection in Hive, which the Presto CBO cost based optimized can then leverage.
https://www.starburstdata.com/technical-blog/introduction-to-presto-cost-based-optimizer/

**Comment by findepi** [comment]
@isanuk, as @billonahill explained join reordering functionality exists and is part of Cost-Based Optimizer in Presto.
This is a functionality we (the Starburst team, previously Teradata) developed back in 2017 and improved in 2018.
We've finally merged all the pieces into `master`, including documentation just recently (https://github.com/prestosql/presto/pull/127).

Last but not least, this functionality is not enabled by default yet.
See https://docs.starburstdata.com/latest/optimizer/cost_based_optimizations.html for docs & how to enable it.
(Docs will be published @ https://prestosql.io/docs/current/ with the next release).

@kbajda @martint, we enable CBO by default in Starburst Presto.

(@isanuk let me close the issue, you can still comment here if you have any feedback or questions)
