### ISSUE TITLE
Document Hive `INSERT OVERWRITE` behavior

### ISSUE THREAD

**Issue by dain** [prestosql/presto#485]
Document the Hive connector `insert_existing_partitions_behavior` session property, which can be used to to get Hive's `INSERT OVERWRITE` behavior.  This property has three values: ERROR, APPEND, and OVERWRITE.

**Comment by wpf375516041** [comment]
Hi, is this a new grammar ready to support? If I want to do an overwrite operation now, can I delete it first?
