### ISSUE TITLE
Unable to retrieve mongodb nested field value when field name has uppercase letter

### ISSUE THREAD

**Issue by hustneed4speed** [prestosql/presto#4881]
SQL 
"_select nested_fields.field_D from mongodb.db_test.presto_schema_test_" 
will not return the value of nested_fields.field_D

**reproduce environment and steps**
presto server version: 340
client: presto-cli-340-executable.jar

**1. prepare test data**
create a test mongodb collection named "presto_schema_test" with 1 document below
```json
{ 
    "field_a" : "a_val", 
    "field_B" : "b_val", 
    "nested_fields" : {
        "field_c" : "c_val", 
        "field_D" : "d_val"
    }
}
```

define schema in collection "_schema" as
```json
{ 
    "table" : "presto_schema_test", 
    "fields" : [
        {
            "name" : "_id", 
            "type" : "ObjectId", 
            "hidden" : true
        }, 
        {
            "name" : "field_a", 
            "type" : "varchar", 
            "hidden" : false
        }, 
        {
            "name" : "field_B", 
            "type" : "varchar", 
            "hidden" : false
        }, 
        {
            "name" : "nested_fields", 
            "type" : "row(field_c varchar, field_D varchar)", 
            "hidden" : false
        }
    ]
}
```

**2. run test sql**
```
presto>select field_a, field_B, nested_fields.field_c, nested_fields.field_D from mongodb.db_test.presto_schema_test;
 field_a | field_B | field_c | field_D 
---------+---------+---------+---------
 a_val   | b_val   | c_val   | NULL    
(1 row)

Query 20200819_045211_00000_uer4a, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
3.34 [1 rows, 1B] [0 rows/s, 0B/s]
```

**Test result**
Value of field_D is NULL while "d_val" is expected.
This test passed successfully in presto-server version 317, while failed in version 340

**Comment by ebyhr** [comment]
Did you create _schema manually? If so, you need to surround the field name by double-quote >`"field_D" varchar`

**Comment by hustneed4speed** [comment]
> It seems the behavior was changed >= 323. You need to surround the field name by double-quote >`"field_D" varchar` now.

Thank you, ebyhr.
Your solution works.

Here is what I found after I checked the code of presto.

In my test case, field_D is an Identifier, defined by class `io.prestosql.sql.tree.Identifier`
Identifier is checked against a name pattern to tell if it is delimited.
```
    private static final Pattern NAME_PATTERN = Pattern.compile("[a-zA-Z_]([a-zA-Z0-9_:@])*");

    public Identifier(NodeLocation location, String value, boolean delimited)
    {
        this(Optional.of(location), value, delimited);
    }
    
    public Identifier(String value)
    {
        this(Optional.empty(), value, !NAME_PATTERN.matcher(value).matches());
    }
```
And Identifier that is not delimited, will be lowercased, in `io.prestosql.sql.analyzer.TypeSignatureTranslator.canonicalize`
```   
    private static String canonicalize(Identifier identifier)
    {
        if (identifier.isDelimited()) {
            return identifier.getValue();
        }

        return identifier.getValue().toLowerCase(Locale.ENGLISH); // TODO: make this toUpperCase to match standard SQL semantics
    }
```
