### ISSUE TITLE
Support for tdigest_agg?

### ISSUE THREAD

**Issue by pb-stripe** [prestosql/presto#4975]
Hi, we've found `approx_percentile` to be unreliable for higher percentiles (p99.9 for example), even when setting an `accuracy` value closer to 0 than the default of `0.01`. There's some indication in [this paper](https://arxiv.org/abs/1902.04023) that t-digests would be more accurate than the q-digests used by `approx_percentile`.

To this end, the prestodb/presto project added `tdigest_agg` recently: https://github.com/prestodb/presto/pull/13940

Are any active plans to add this function to this project as well?

**Comment by martint** [comment]
Yes, we plan to add support for that data type and change the underlying implementation of approx_percentile to use t-digest. We've already replaced some of the internal server metrics data structures to use it, so the building blocks are in good shape.

cc @kasiafi
