### ISSUE TITLE
io.prestosql.sql.parser.SqlBaseParser The source code This class cannot be found

### ISSUE THREAD

**Issue by wangfeigithub** [prestosql/presto#5029]
hello  , in the  source code .i don't have find 'io.prestosql.sql.parser.SqlBaseParser' ,This class cannot be found. 
please tell me how to find and why. thinks！

**Comment by sopel39** [comment]
This is generated class, please compile Presto project. Then the class should be generated.

**Comment by findepi** [comment]
you need to 
```
mvn clean install -DskipTests
```
(once)

before you can run things from IDE

Reach out on `#dev` on [our slack](https://prestosql.io/slack.html) if you need more help with development.

**Comment by xianjuntang** [comment]
> you need to
> 
> ```
> mvn clean install -DskipTests
> ```
> 
> (once)
> 
> before you can run things from IDE
> 
> Reach out on `#dev` on [our slack](https://prestosql.io/slack.html) if you need more help with development.

I succeeded in executing git bash. But there are still no classes

**Comment by ebyhr** [comment]
@xianjuntang The latest package was changed to `io.trino.sql.parser` and the path is `core/trino-parser/target/generated-sources/antlr4/io/trino/sql/parser/SqlBaseParser.java`

**Comment by xianjuntang** [comment]
> @xianjuntang The latest package was changed to `io.trino.sql.parser` and the path is `core/trino-parser/target/generated-sources/antlr4/io/trino/sql/parser/SqlBaseParser.java`

Thank you. I found it according to your hint. Next, I just need to copy the class generated under the target to the address of the guide package. Is that ok.

**Comment by xianjuntang** [comment]
> @xianjuntang The latest package was changed to `io.trino.sql.parser` and the path is `core/trino-parser/target/generated-sources/antlr4/io/trino/sql/parser/SqlBaseParser.java`

Thank you very much. I found it according to your hint.
