### ISSUE TITLE
Support insert and delete for Hive ACID

### ISSUE THREAD

**Issue by djsstarburst** [prestosql/presto#5049]
This issue is opened to track work to support Hive ACID insert and row-by-row delete, and document the metastore messages used by Hive for the insert and delete operations we wish to support in Presto.

**Relates to https://github.com/prestosql/presto/issues/5035**

**Comment by djsstarburst** [comment]
Some facts about how Hive performs deletions:

- Hive ACID DELETEs always cause row-by-row deletion, using the delete_delta mechanism, whether or not the table is partitioned, even if all rows are deleted.
- Partition dropping in Hive only happens as a result of ALTER TABLE DROP PARTITION requests.

**Hive drop partition**

These are the important metastore modifications performed when Hive drops a partition:

With this table definition:
`CREATE TABLE test_delete_all_failure (column2 BIGINT) PARTITIONED BY (column1 INT) STORED AS ORC TBLPROPERTIES('transactional'='true')"`

Here are the important calls captured by tcpdump during the partition drop, done with:
`ALTER TABLE test_delete_all_failure DROP PARTITION(column1 = 1)`

- Call to get_partitions_by_expr, passing PartitionsByExprRequest.  The partition corresponding to column1 = 1 is identified an "expr" ByteBuffer with two escaped characters: "\001\001". Another arg is defaultPartitionName, whose value is "HIVE_DEFAULT_PARTITION".
- Call to lock, with lockTYpe = 3, meaning EXCLUSIVE, and lockLevel = 3, meaning PARTITION.  The partitionName is the string "column1=1", and the DataOperationType = 6, meaning NO_TXN.  A comment explains that this kind of locking is non-transactional.
- Call to drop_partitions_req, passing a parition spec containing a list of partitions that in this case contains a ByteBuffer with two escaped characters: "\001\001".
- Calls to commit_txn() to commit the transaction.

I captured the delta files before and after the delete, and it really did rm the files when the partition was dropped.  No new writeIds were generated, so it can't in principle be transactional.  Here is the zipped-up tcpdump .pcap file:

[hive-drop-partition.pcap.gz](https://github.com/prestosql/presto/files/5157966/hive-drop-partition.pcap.gz)

**Comment by djsstarburst** [comment]
**Hive insert into a partitioned table**

With this table definition:
`CREATE TABLE test_delete_all_failure (column2 BIGINT) PARTITIONED BY (column1 INT) STORED AS ORC TBLPROPERTIES('transactional'='true')`

I ran a single Hive insert that added 20 rows for column1=1 and 20 rows for column2=2.

Hive ran an absolute blizzard of get requests intermixed with the important update operations:

- A call to allocate_table_write_ids, passing a list containing the transactionId, getting back a new writeId.
- A call to lock_req, acquiring two locks: a shared read table lock on db "_dummy_database", table "_dummy_table"; and a shared read table lock on table "test_delete_all_failure".  We determined that the _dummy_database/_dummy_table was a goofy artifact of how the Hive engine marshals results, and Presto won't need to acquire that lock.
- A call to alter_partitions_req, passing a list of Partition objects and the new writeId for the partitions.
- A call to alter_table_req, updating the table with the new writeId.
- A second call to alter_table_req, with the same new writeId, but updating the totalSize, the numRows and numFiles attributes of the table.
- A call to commit_txn, passing the transactionId.

Here is the zipped-up .pcap file:
[hive-insert-2-partitions-20-rows.pcap.gz](https://github.com/prestosql/presto/files/5158014/hive-insert-2-partitions-20-rows.pcap.gz)

**Comment by findepi** [comment]
@djsstarburst nice writeup, thanks!

> We determined that the _dummy_database/_dummy_table was a goofy artifact of how the Hive engine marshals results, and Presto won't need to acquire that lock.

Can you elaborate on this?
Also, even if we do not have today, hive code may change, leveraging the assumption that a lock is present. So maybe it is better to acquire the lock still?



> A single call to add_dynamic_partitions, passing the txnId, the writeId, the schema and table name, a list of partition names, and an operationType of DELETE

Does INSERT trigger a kind of delete operation?

What does this operation do?

> A call to alter_table_req, updating the table with the new writeId.

Can this be called if we do not acquire a lock on the table first?

**Comment by djsstarburst** [comment]
> Can you elaborate on this?
> Also, even if we do not have today, hive code may change, leveraging the assumption that a lock is present. So maybe it is better to acquire the lock still?

@electrum  is the guy who knows most about this, and he should chime in.  I think that the lock on the `_dummy_table` is acquired because for transactions that perform updates, Hive ACID actually writes the updates to the dummy table first, and then copies them user-specified table.

> Does INSERT trigger a kind of delete operation?

No - - it's a typo.  I've fixed it to be:

> A single call to add_dynamic_partitions, passing the txnId, the writeId, the schema and table name, a list of partition names, and an operationType of INSERT.


> > A call to alter_table_req, updating the table with the new writeId.

> Can this be called if we do not acquire a lock on the table first?

No, the lock is always acquired first.  The sequence is always:

- Open a transaaction
- Allocate a new writeId
- Lock the table
- Write new data files containing inserts or deletes, or both in the case of updates.
- Update partition and table writeIds, but don't commit them.
- Commit the transaction.  It's only after this point that any new transaction will see the updates.

**Comment by djsstarburst** [comment]
The work for this ticket, in PR #5402, which has been merged.

Closing this ticket.

**Comment by divyanshidm** [comment]
Is this available in Trino? (I am using Trino CLI 376, Hive Metastore 3.1.2, Both on dataproc gcp.)
But it still complains on update/delete - **Invalid method name: 'alter_table_req'**
Can somebody help?
