### ISSUE TITLE
Can not clear temporary table in JDBC connector while executing 'EXPLAIN CREATE TABLE ... AS SELECT' or 'EXPLAIN INSERT INTO ... SELECT'

### ISSUE THREAD

**Issue by allenfudunhui** [prestosql/presto#5089]
While executing 'explain create table ... as select' or 'explain insert into ... select', and the target table in SQL is Jdbc table. Temporary tables will be created in BaseJdbcClient.beginInsertTable() and BaseJdbcClient.beginCreateTable(), but the temporary tables can not be cleared when the SQL was finished.

**Comment by findepi** [comment]
@allenfudunhui thanks for your issue.
This is already tracked by https://github.com/prestosql/presto/issues/130.
Let me close this one.
