### ISSUE TITLE
Support insert overwrite unpartitioned table

### ISSUE THREAD

**Issue by xumingming** [prestosql/presto#510]
Currently we support insert overwrite partition table but not unpartitioned table.

**Comment by dain** [comment]
I believe this will require modifications near https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriterFactory.java#L296.  The code for overwrite of partitioned tables is just below that section.

**Comment by findepi** [comment]
This was implemented in https://github.com/prestosql/presto/pull/648.
Before we close the ticket though, we should fix the case when running with Glue -- https://github.com/prestosql/presto/issues/1243
