### ISSUE TITLE
Error running query: class java.sql.Timestamp cannot be cast to class java.lang.Number (java.sql.Timestamp is in module java.sql of loader 'platform'; java.sql.Number is in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by JhonJohnatan** [prestosql/presto#5121]
Hello guys,

I was using presto 336, today I updated to presto 341, and now some of the select queries stopped working.

The error logged: "Error running query: class java.sql.Timestamp cannot be cast to class java.lang.Number (java.sql.Timestamp is in module java.sql of loader 'platform'; java.sql.Number is in module java.base of loader 'bootstrap')"

The select query is very simple, 
```SQL
SELECT timestampfield
FROM sometable
```

Did anyone experience the same thing?

**Comment by findepi** [comment]
@JhonJohnatan thanks for reporting this. 
Do you have a full stacktrace?

**Comment by JhonJohnatan** [comment]
I'm sorry, I'm not able to share the full stacktrace, Technically issues.

**Comment by findepi** [comment]
Do you have any other hint how could I reproduce the problem?

**Comment by electrum** [comment]
What connector are you using? If it’s Hive, what file format is the table? If it’s partitioned, please check if the table schema matches the partition schema — this might be a schema evolution issue.

**Comment by electrum** [comment]
It might be to discuss this on [Slack](https://prestosql.io/slack.html).

**Comment by findepi** [comment]
Let's continue discussion on Slack.
