### ISSUE TITLE
Incorrect predicate pushdown processing for Parquet files containing NaN 

### ISSUE THREAD

**Issue by aalbu** [prestosql/presto#5127]
https://issues.apache.org/jira/browse/PARQUET-1246 has changed the way statistics are created for columns containing `NaN` values.  As a result, stats in this scenario have both min and max equal to 0 and the flag for non-null values set to `false`.  See https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/statistics/Statistics.java#L90-L92.

This causes Presto to incorrectly skip data.  To reproduce, create the table in Hive:
```
create table test_nan as select 1 as id, cast('nan' as double) as val;
```

Then query in Presto:
```
select * from test_nan where value is not null;

 id | val
----+-----
(0 rows)
```

Note that the issue does not manifest itself when inserting the data through Presto.

**Comment by tooptoop4** [comment]
not a bug? @aalbu

**Comment by aalbu** [comment]
Yeah, I meant to add a note.  It turns out  I had a typo in my Hive DDL.  `cast('nan' as double)` returns `null`, which explains the result of my query.  That was supposed to read `cast('NaN' as double)` and once I've fixed that, the issue went away.
