### ISSUE TITLE
presto-benchmark tpcds q04.sql about 10 times slower than impala 

### ISSUE THREAD

**Issue by gaojun2048** [prestosql/presto#5155]
Hi ,
I run benchmark tpcds on presto and impala. And I found that Presto is 10 times slower than impala in the q04.sql case.
**this is my session params:**
- join_distribution_type=AUTOMATIC
- join_reordering_strategy=AUTOMATIC
- enable_intermediate_aggregations=true
- enable_dynamic_filtering=false

**the cluster config:**
16c 32G * 3

Impala and presto run on the same data 'tpcds_sf10_orc' and same sql q04.sql.
Impala cost 10s finish, and presto cost 1.3m.
From the presto ui I found the `Physical Input Data = 1.20GB` ,but the `Internal Network Data = 18.6GB`. I think the `Internal Network Data` cause the problem.

Has anyone done the benchmark tpcds test of impala and presto? And is the performance of presto normal in the q04.sql scenario?

![image](https://user-images.githubusercontent.com/32193458/93084796-29e4b280-f6c7-11ea-883f-fd90bc18bb7e.png)

**Comment by findepi** [comment]
Thanks for sharing session properties you use in your benchmark

Can you also share the following?

- where is your data set located (eg HDFS? S3?)
- what is your metastore (eg HMS? AWS Glue?)
- what are the machines being used
- presto version and configuration, hive connector configuration
- Impala version and configuration
- whether the data set is partitioned 
- whether you run ANALYZE in Presto
- how do you run queries: number of queries run, concurrency, number of warmup queries if any, how do you aggregate results into single number that you provided (avg, min, max or something else)

**Comment by gaojun2048** [comment]
> Thanks for sharing session properties you use in your benchmark
> 
> Can you also share the following?
> 
> * where is your data set located (eg HDFS? S3?)
> * what is your metastore (eg HMS? AWS Glue?)
> * what are the machines being used
> * presto version and configuration, hive connector configuration
> * Impala version and configuration
> * whether the data set is partitioned
> * whether you run ANALYZE in Presto
> * how do you run queries: number of queries run, concurrency, number of warmup queries if any, how do you aggregate results into single number that you provided (avg, min, max or something else)

* data set located is HDFS
* hive version is 3.1.3000.7.1.3.0-100 (CDP)
* 16c 32G machines * 3
* presto version is 341 .
```
jvm.config:
-server
-Xmx16G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+UseGCOverheadLimit
-XX:+HeapDumpOnOutOfMemoryError
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
```
```
config.properties:
query.max-memory-per-node=8192MB
query.max-total-memory-per-node=8192MB
colocated-joins-enabled=True
optimizer.optimize-hash-generation=true
concurrent-lifespans-per-task=30
#experimental.spiller-threads=4
#node-scheduler.network-topology=flat
join-distribution-type=BROADCAST
task.concurrency=16
grouped-execution-enabled=True
#experimental.work-processor-pipelines=true
node-scheduler.max-pending-splits-per-task=10
#single node install config
web-ui.authentication.type=fixed
web-ui.user=admin
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8285
http-server.log.path=/var/log/presto/http-request.log
discovery-server.enabled=true
discovery.uri=http://localhost:8285
```
```
catalog/hive.properties:
connector.name=hive-hadoop2
hive.metastore-cache-ttl=0s
hive.metastore-refresh-interval=1s
hive.allow-drop-table=true
hive.metastore.uri=thrift://test.node.host1:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
```

* impala version is 3.2.0.7.1.3.0-100 (CDP)，impala configuration is default.
* the data set is create by presto tpcds. and all table is not partitioned.
* ANALYZE is run.
* I run the sql use presto-cli and only one query run at the same time.
* The sql is tpcds query q04.sql. the sql file location is presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q04.sql.

**Comment by findepi** [comment]
Can you issue in Presto the following?

```sql
SHOW STATS FOR hive.tpcds_sf10_orc.customer;
SHOW STATS FOR hive.tpcds_sf10_orc.store_sales;
SHOW STATS FOR hive.tpcds_sf10_orc.catalog_sales;
SHOW STATS FOR hive.tpcds_sf10_orc.web_sales;
SHOW STATS FOR hive.tpcds_sf10_orc.date_dim;
```

and also
```
SHOW CREATE TABLE hive.tpcds_sf10_orc.store_sales;
```

(assuming `tpcds_sf10_orc` is your schema with the tables)

**Comment by gaojun2048** [comment]
> Can you issue in Presto the following?
> 
> ```sql
> SHOW STATS FOR hive.tpcds_sf10_orc.customer;
> SHOW STATS FOR hive.tpcds_sf10_orc.store_sales;
> SHOW STATS FOR hive.tpcds_sf10_orc.catalog_sales;
> SHOW STATS FOR hive.tpcds_sf10_orc.web_sales;
> SHOW STATS FOR hive.tpcds_sf10_orc.date_dim;
> ```
> 
> and also
> 
> ```
> SHOW CREATE TABLE hive.tpcds_sf10_orc.store_sales;
> ```
> 
> (assuming `tpcds_sf10_orc` is your schema with the tables)

I run `analyze hive.tpcds_sf10_orc.customer;` but all the stats of this table is null.
![image](https://user-images.githubusercontent.com/32193458/93156698-3efb2900-f73b-11ea-8a5f-934668d0bc60.png)

It is same to all tables.

***SHOW CREATE TABLE hive.tpcds_sf10_orc.store_sales;***
```
                  Create Table                  
------------------------------------------------
 CREATE TABLE hive.tpcds_sf10_orc.store_sales ( 
    ss_sold_date_sk bigint,                     
    ss_sold_time_sk bigint,                     
    ss_item_sk bigint,                          
    ss_customer_sk bigint,                      
    ss_cdemo_sk bigint,                         
    ss_hdemo_sk bigint,                         
    ss_addr_sk bigint,                          
    ss_store_sk bigint,                         
    ss_promo_sk bigint,                         
    ss_ticket_number bigint,                    
    ss_quantity integer,                        
    ss_wholesale_cost decimal(7, 2),            
    ss_list_price decimal(7, 2),                
    ss_sales_price decimal(7, 2),               
    ss_ext_discount_amt decimal(7, 2),          
    ss_ext_sales_price decimal(7, 2),           
    ss_ext_wholesale_cost decimal(7, 2),        
    ss_ext_list_price decimal(7, 2),            
    ss_ext_tax decimal(7, 2),                   
    ss_coupon_amt decimal(7, 2),                
    ss_net_paid decimal(7, 2),                  
    ss_net_paid_inc_tax decimal(7, 2),          
    ss_net_profit decimal(7, 2)                 
 )                                              
 WITH (                                         
    format = 'ORC'                              
 )    
```

**Comment by gaojun2048** [comment]
I change the hive version to 1.2, It is ok. So, I think this issue is caused by hive version. It seems the support of hive in presto 341 is not yet complete.

**Comment by jiangzhx** [comment]
presto 339
hive 1.2

stats work fine.
![image](https://user-images.githubusercontent.com/494507/93158981-db272f00-f73f-11ea-81ff-8b90709d69f8.png)

**Comment by findepi** [comment]
> I change the hive version to 1.2, It is ok.

Thanks for checking.



> Impala and presto run on the same data 'tpcds_sf10_orc' and same sql q04.sql.
Impala cost 10s finish, and presto cost 1.3m.

Can you please re-test the original problem with Hive 1.2?
What are the numbers now?

**Comment by gaojun2048** [comment]
> > I change the hive version to 1.2, It is ok.
> 
> Thanks for checking.
> 
> > Impala and presto run on the same data 'tpcds_sf10_orc' and same sql q04.sql.
> > Impala cost 10s finish, and presto cost 1.3m.
> 
> Can you please re-test the original problem with Hive 1.2?
> What are the numbers now?

Yes, I re-test the case with hive1.2 , Presto cost about the same time as impala.
But our online hive is the hive3, from the test results, we cannot use presto with hive3.

**Comment by findepi** [comment]
> Yes, I re-test the case with hive1.2 , Presto cost about the same time as impala.


Thanks for confirming. Let me close the issue as solved then.

> But our online hive is the hive3, from the test results, we cannot use presto with hive3.


I guess you're aware that Hive 3 is supported (at least the HDP variant) -- https://github.com/prestosql/presto/issues/1218
you may wan to create a new issue if your case isn't covered yet

**Comment by jiangzhx** [comment]
i find some diff between hive3 and hive1.2
hive's metastore in mysql.
hive3.0 add new  column "ENGINE"  in table TAB_COL_STATS
![image](https://user-images.githubusercontent.com/494507/93182002-c1034600-f76b-11ea-9508-c785e246b37a.png)


so when analyze table in presto got error.

**Comment by jiangzhx** [comment]
FYI：Differentiate among column stats computed by different engines
https://issues.apache.org/jira/plugins/servlet/mobile#issue/HIVE-22046

**Comment by aakashnand** [comment]
@jiangzhx Were you able to find the solution to this problem?
https://github.com/trinodb/trino/issues/5155#issuecomment-692540048

**Comment by Mionsz** [comment]
@tooptoop4 @jiangzhx @jiangzhx We experienced the same problem at some point. In our case the problem behind Metastore on Hive 3.1.3 with java.net.socketTimeout, running on Kubernetes cluster, was due to database backend service. We were using self-hosted instance of Apache Derby and migrated to self-hosted PostgreSQL. Problem occurred no more.
