### ISSUE TITLE
Jdbc throws Exception while using getDouble method on DECIMAL value

### ISSUE THREAD

**Issue by groobyming** [prestosql/presto#5165]
I am using prestosql-jdbc-308, when I call getDouble method on double column, an exception occurs

sql:
select ceil(1.5) from test_tb

exception:
Value is not a number: java.lang.String

connector:
hive-hadoop2

**Comment by findepi** [comment]
Note that the result is actually `decimal`:
```
presto> SELECT typeof(ceil(1.5));
    _col0
--------------
 decimal(2,0)
```

I've updated the issue description accordingly.

To get double number you need to cast `1.5` as `double`, or use scientific notation for a literal: `1.5e0`.

**Comment by findepi** [comment]
If anyone wants to pick this up,

the test should go here: https://github.com/prestosql/presto/blob/bb460c0b3a3b7857e0484a0960eee28b29680534/presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java#L88-L96

and should use extended version of `checkRepresentation`, like here: https://github.com/prestosql/presto/blob/bb460c0b3a3b7857e0484a0960eee28b29680534/presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java#L103-L109

**Comment by groobyming** [comment]
@findepi  Thanks for your reply
I found that the problem is that I use the getDouble method on the decimal column, if I use the getDecimal method on this column, there will be no exception

**Comment by vatsalmevada** [comment]
@findepi I would like to work on this.

**Comment by jetsasank** [comment]
I tried fixing this issue in https://github.com/prestosql/presto/pull/5312.
