### ISSUE TITLE
Error Setting scheduler.http-client.connect-timeout in config.properties (Ver 305)

### ISSUE THREAD

**Issue by PabloInnocenti** [prestosql/presto#518]
Dear Prestosql Team,

We are using version 305 and we some errors and warning like:

`WARN	TaskInfoFetcher-20190321_142603_00152_59y9e.1.2-1684	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20190321_142603_00152_59y9e.1.2: Server refused connection`

`2019-03-21T14:35:53.669Z	ERROR	remote-task-callback-567	io.prestosql.execution.StageStateMachine	Stage 20190321_143053_00265_59y9e.1 failed
io.prestosql.spi.PrestoTransportException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes.`

We try to set the properties like in [config.properties](https://github.com/prestosql/presto/blob/master/presto-main/etc/config.properties) to increase timeout tolerance.

```
scheduler.http-client.max-connections=1000
scheduler.http-client.max-connections-per-server=1000
scheduler.http-client.connect-timeout=5m
scheduler.http-client.idle-timeout=5m
```

The following error occurs starting server:

```
2019-03-21T14:33:21.046Z	ERROR	main	io.prestosql.server.PrestoServer	Unable to create injector, see the following errors:

1) Configuration property 'optimizer.optimize-single-distinct' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

2) Configuration property 'scheduler.http-client.connect-timeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

3) Configuration property 'scheduler.http-client.idle-timeout' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

4) Configuration property 'scheduler.http-client.max-connections' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

5) Configuration property 'scheduler.http-client.max-connections-per-server' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)
```

Do we need to setup something else?

Thanks,
Pablo.

**Comment by findepi** [comment]
> 1) Configuration property 'optimizer.optimize-single-distinct' was not used

This configuration property was removed (apparently around 0.198 release).
We missed to update documentation though -- https://github.com/prestosql/presto/pull/520

thanks for reporting this!

> 2) Configuration property 'scheduler.http-client.connect-timeout' was not used

Is this error being reported on coordinator or on the scheduler?
`scheduler.*` configuration is applicable on coordinator node only.

**Comment by findepi** [comment]
BTW, this kind of troubleshooting questions are best served by the `#troubleshooting` channel on Presto Slack. Get an invite from https://prestosql.io/community.html.

I will close this issue, but you still can comment here. Or we can move this to Slack.
