### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct ,when i run presto338 with ranger2.0

### ISSUE THREAD

**Issue by wangfeigithub** [prestosql/presto#5180]
I followed the following documentation : https://cwiki.apache.org/confluence/display/RANGER/Presto+Plugin

Then run the bin/launcher run, a Java lang. NoClassDefFoundError: / PostConstruct javax.mail/an annotation

**Comment by wangfeigithub** [comment]
![image](https://user-images.githubusercontent.com/29723968/93288774-3e33c700-f80f-11ea-8d78-5b2b87ee57ab.png)
this is error ,How did this happen?

**Comment by kokosing** [comment]
I think you wanted to open an issue to Ranger project: https://issues.apache.org/jira/projects/RANGER/issues

**Comment by findepi** [comment]
I will close this as not-an-issue in Presto.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).
See you there!
