### ISSUE TITLE
Why `Given correlated subquery is not supported` when `limit 1` added in a corelated subquery

### ISSUE THREAD

**Issue by hustneed4speed** [prestosql/presto#5209]
presto server version: 341

test data:
```
table A
c1 | c2
----+----
k1 | v1
k2 | v2
```

```
table B
c1 | c2
----+----
k2 | v3
k3 | v4
```

failed query:
```
select
  a.c1,
  a.c2,
  coalesce(
    (select b.c2 from B b where a.c1 = b.c1 limit 1),
    'NA'
  )
from
  A a
;
```

The query will failed with error: `Given correlated subquery is not supported`, and it may executed successfully if  `limit 1` is removed. 
**My question is: why `limit 1` matters?**

Below is the query to reproduce it
```
with A as
(
  select * from (values ('k1', 'v1'), ('k2', 'v2')) as v1 (c1, c2)
),
B as
(
  select * from (values ('k2', 'v3'), ('k3', 'v4')) as v2 (c1, c2)
)
select
  a.c1,
  a.c2,
  coalesce(
    (select b.c2 from B b where a.c1 = b.c1 limit 1),
    'NA'
  )
from
  A a
;
```

**Comment by losipiuk** [comment]
`select b.c2 from B b where a.c1 = b.c1 limit 1` subquery is used in context which requires that result of subquery returns single value (the result is passed as first argument to `coalesce`).
This constraint verified by Presto in query analysis phase, before table data is read. Without `limit 1` it would be possible that more than one value is retuned from the subquery if there were multiple rows in `B` matching current row from `A`.
E.g for B contents like below:
```
table B
c1 | c2
----+----
k2 | v3
k2 | v4
```

In case you have more questions regarding this, please reach out to me at https://prestosql.slack.com/.

**Comment by findepi** [comment]
Related: https://github.com/prestosql/presto/issues/4673

**Comment by losipiuk** [comment]
@hustneed4speed please disregard my previous comment. It is very wrong. 
Actually we can enforce single-value constraint at runtime - which I forgot. And the reason why it does not work for `limit 1` is more prosaic. We simply did not implement rule to decorrelate subquery where there is `limit 1` in it.

As a temporary measure you can rewrite the inner query to use `arbitrary` global aggregation instead of limit 1.

```sql
with A as
(
  select * from (values ('k1', 'v1'), ('k2', 'v2')) as v1 (c1, c2)
),
B as
(
  select * from (values ('k2', 'v3'), ('k3', 'v4')) as v2 (c1, c2)
)
select
  a.c1,
  a.c2,
  coalesce(
    (select arbitrary(b.c2) from B b where a.c1 = b.c1),
    'NA'
  )
from
  A a
;
```

**Comment by hustneed4speed** [comment]
> @hustneed4speed please disregard my previous comment. It is very wrong.
> Actually we can enforce single-value constraint at runtime - which I forgot. And the reason why it does not work for `limit 1` is more prosaic. We simply did not implement rule to decorrelate subquery where there is `limit 1` in it.
> 
> As a temporary measure you can rewrite the inner query to use `arbitrary` global aggregation instead of limit 1.
> 
> ```sql
> with A as
> (
>   select * from (values ('k1', 'v1'), ('k2', 'v2')) as v1 (c1, c2)
> ),
> B as
> (
>   select * from (values ('k2', 'v3'), ('k3', 'v4')) as v2 (c1, c2)
> )
> select
>   a.c1,
>   a.c2,
>   coalesce(
>     (select arbitrary(b.c2) from B b where a.c1 = b.c1),
>     'NA'
>   )
> from
>   A a
> ;
> ```

Thank you,  @losipiuk 
I am just curious why it failed, so I post an issue here, and you have given me an answer for that.

I used `max(b.c2)` as a work around in my project, and it looks like `arbitrary` is a better choice.

**Comment by sopel39** [comment]
> We simply did not implement rule to decorrelate subquery where there is limit 1 in it.

We actually can decorrelated subqueries with limit. However, it would have to be in simpler form:
```
(select b.c1 from B b where a.c1 = b.c1 limit 1),
```
which is less useful. @kasiafi what are our current correlated `limit` correlated subquery limitations?

**Comment by kasiafi** [comment]
@hustneed4speed @sopel39 We can decorrelate subqueries with `LIMIT`. However, we've got different implementations for LIMIT 1 and LIMIT greater than 1. The implementation for `LIMIT 1` is less powerful. Specifically, it does not succeed if the subquery returns non-constant output (`b.c2`) in your example.
The implementation for LIMIT greater than 1 can handle it.

Theoretically, we could use the more powerful decorrelation strategy for `LIMIT 1` as well. However, it would affect the way certain queries are processed (e.g. queries containing `EXISTS` clause). We'd have to run benchmarks and make sure we don't trade off efficiency.

**Comment by sopel39** [comment]
> We'd have to run benchmarks and make sure we don't trade off efficiency.

The current support for LIMIT 1 was introduced specifically to improve performance of `EXISTS` clause.
Could we use other method when we cannot decorrelate `LIMIT` with more performant method? Do I understand correctly, that the other method requires aggregation on top of join?

**Comment by kasiafi** [comment]
> Could we use other method when we cannot decorrelate LIMIT with more performant method? Do I understand correctly, that the other method requires aggregation on top of join?

I'm not sure if the method we currently use for `LIMIT 1` is more performant than the other.
- the method for `LIMIT 1` replaces `LimitNode` with `AggregationNode` with a single grouping set.
- the method for `LIMIT` greater than `1`replaces `LimitNode` with `RowNumberNode` partitioned on constants.

In neither case there is an aggregation on top of `JoinNode`

You can follow the difference using the following examples:
```
EXPLAIN SELECT * FROM region r, LATERAL (SELECT n.regionkey FROM nation n WHERE r.regionkey = n.regionkey LIMIT 1);
```
```
EXPLAIN SELECT * FROM region r, LATERAL (SELECT n.regionkey FROM nation n WHERE r.regionkey = n.regionkey LIMIT 2);
```

**Comment by sopel39** [comment]
> I'm not sure if the method we currently use for LIMIT 1 is more performant than the other.

That needs to be verified. It looks like `io.prestosql.operator.RowNumberOperator` might consume more memory due to requirement to count partitions (that shouldn't be much more). Also it seems to materialize `rowNumberChannel`.
However, it looks like we could use `RowNumberOperator` where `AggregationNode` cannot be used. I think it's the condition here (`io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java:212`):
```
            if (constantSymbols.isEmpty() || !constantSymbols.containsAll(decorrelatedChildNode.getOutputSymbols())) {
                return Optional.empty();
            }
```
