### ISSUE TITLE
Update usages of deprecated isCharType, isVarcharType

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5212]
We deprecated the functions in https://github.com/prestosql/presto/pull/5200, https://github.com/prestosql/presto/pull/5213

Rationale:

> There is no way of preventing `instanceof VarcharType` and we do no try
> to discourage that. For consistency of the code base, let's standardize
> on (unavoidable) `instanceof` and depart from using a method to check
> that.
> 
> Note also we do not have such methods for some other parametric types,
> e.g.  timestamps, decimals, arrays.
 

* remove usages of `io.prestosql.spi.type.Varchars#isVarcharType`
* remove usages of `io.prestosql.spi.type.Chars#isCharType`
* remove usages of `io.prestosql.spi.type.VarbinaryType#isVarbinaryType`

**Comment by amommendes** [comment]
@findepi I would like to work on this!

**Comment by findepi** [comment]
@amommendes thanks, go for it!

**Comment by findepi** [comment]
Thanks @amommendes!
