### ISSUE TITLE
Error in .jcall(rp, "I", "fetch", stride, block) :    java.sql.SQLException: Value is not a number: java.lang.String

### ISSUE THREAD

**Issue by yanqingfu** [prestosql/presto#5228]
Connect Prestosql database in R

library(RJDBC)
library(DBI)
library(rJava)

drv <-  JDBC("io.prestosql.jdbc.PrestoDriver",classPath="presto-jdbc-341.jar")

>  driver download from https://prestosql.io/docs/current/installation/jdbc.html

con <- dbConnect(drv,
                 user = 'user',
                 password = 'passwd',
                 url = 'jdbc:presto://address:port/database',
                 SSLKeyStorePath = 'keystore.jks',
                 SSLKeyStorePassword = 'pw',
                 SSL = 'true'
)

table1 <- dbGetQuery(con,'SELECT decimal(38,12) column FROM table')

>  **error Error in .jcall(rp, "I", "fetch", stride, block) : 
>  java.sql.SQLException: Value is not a number: java.lang.String**
>  also error in table1 <- dbGetQuery(con,'SELECT * FROM table')

table2<- dbGetQuery(con,'SELECT CAST(decimal(38,12) column as double) FROM table')

> no error

1. DBeaver same query no issue
2. Oracle datbase has the same data using `drv = JDBC("oracle.jdbc.OracleDriver",classPath="ojdbc6.jar") ` no issue
3. Using RPresto package with correct setting no issue

**Comment by findepi** [comment]
This seems to be the same issue as https://github.com/prestosql/presto/issues/5165.
Can we close this one and continue there?
Note that https://github.com/prestosql/presto/issues/5165 contains pointers if someone wants to add support for this.
