### ISSUE TITLE
support tencent cloud cos filesystem in hive connector

### ISSUE THREAD

**Issue by allendang001** [prestosql/presto#5234]
Prestosql can support tencent cos filesystem in hive connector only through hive.config.resources=core-site.xml, it is not gracefully. Tencent COS as a famous object storge system has been integrated into Hadoop 3.0. For a certain idea 'SQL on everything', prestosql need have a ability to process data in tentcent cos.

**Comment by ebyhr** [comment]
@allendang001 It's ongoing in this PR https://github.com/prestosql/presto/pull/4978.

**Comment by allendang001** [comment]
it reuse AWS S3‘s configuration parameters. Is these properties can turn into universal in name？

**Comment by ebyhr** [comment]
Maybe, I misunderstood your requirement. What you want is something like [HiveAzureConfig.java](https://github.com/prestosql/presto/blob/cc30d16a7fd7604b758ee554b59a13f9c26b4cf8/presto-hive/src/main/java/io/prestosql/plugin/hive/azure/HiveAzureConfig.java), right?

**Comment by findepi** [comment]
Support for Tencent COS filesystem is already tracked by https://github.com/prestosql/presto/issues/4519.

**Comment by allendang001** [comment]
> Sorry, I misunderstood your requirement. What you want is dedicated configuration like [HiveAzureConfig.java](https://github.com/prestosql/presto/blob/cc30d16a7fd7604b758ee554b59a13f9c26b4cf8/presto-hive/src/main/java/io/prestosql/plugin/hive/azure/HiveAzureConfig.java), right?
> https://prestosql.io/docs/current/connector/hive-azure.html
> 
> By the way, I would invite you to community Slack: https://prestosql.io/slack.html

yes，specific configuration parameters are good. Why not consider making the parameter items universal？
