### ISSUE TITLE
Add SSLVerification parameter to JDBC driver

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#5246]
The new `SSLVerification` parameter should have three modes:

* `FULL` -- default, normal TLS verification
* `CA` -- verifies CA only, but allows hostname mismatch
* `NONE` -- no verification of CA or hostname

If `CA`, we should call `OkHttpUtil.setupSsl()`, but afterwards set a custom hostname verifier that does nothing, like we do in `setupInsecureSsl()`.

If `NONE`, we should call `OkHttpUtil.setupInsecureSsl()` in the same way that we do for `--insecure` in the CLI. We should also disallow any of the following (which would not be used in this mode):

* `SSLKeyStorePath`
* `SSLKeyStorePassword`
* `SSLKeyStoreType`
* `SSLTrustStorePath`
* `SSLTrustStorePassword`
* `SSLTrustStoreType`

**Comment by alexku7** [comment]
This is exactly what we requested here https://github.com/prestosql/presto/issues/5230 :)

So just for reference

**Comment by electrum** [comment]
@alexku7 no, it's the same feature request but a completely unrelated component, so they will require separate implementations.

**Comment by mohammedtabish** [comment]
Hey, can i start working on this?
