### ISSUE TITLE
trademark usage disabled?

### ISSUE THREAD

**Issue by ringtail** [prestosql/presto#5252]
![image](https://user-images.githubusercontent.com/3116693/93842070-31f4b180-fcc8-11ea-961e-c41ca2b886ad.png)
Hi man. Does prestosql deny other opensource projects to use presto in name?

**Comment by ringtail** [comment]
We want to opensource an opensource project called `presto-on-k8s-operator`. Could we use presto in project name?

**Comment by ringtail** [comment]
CC @electrum

**Comment by electrum** [comment]
This is a general summary of the Apache License by GitHub (that you'll find on every project using it), based on this text from the license:

> Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.

You'll need to consult an attorney for any specific questions about trademarks or licenses.
