### ISSUE TITLE
Wrong exception message when ResultSet.getDate called on a TIMESTAMP or TIME value

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5313]
```
java.sql.SQLException: Invalid date from server: 09:39:05.000
	at io.prestosql.jdbc.AbstractPrestoResultSet.getDate(AbstractPrestoResultSet.java:282)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getDate(AbstractPrestoResultSet.java:251)
	at io.prestosql.jdbc.PrestoResultSet.getDate(PrestoResultSet.java:44)
```

~should be something like "Expected column to be a date type but is time"~

**Comment by findepi** [comment]
> should be something like "Expected column to be a date type but is time"



@jetsasank found out that PostgreSQL JDBC behavior is dependent on actual value, not the type
i checked same applies to Oracle JDBC

so the message should be different, see https://github.com/prestosql/presto/pull/5335/files#r497450122

**Comment by rafatmunshi** [comment]
@findepi so it should be like- "Expected value to be a date but is" + value ?

**Comment by findepi** [comment]
@rafatmunshi @jetsasank yes

**Comment by findepi** [comment]
@rafatmunshi see WIP PR https://github.com/prestosql/presto/pull/5335
