### ISSUE TITLE
Remove usages of assertThrows

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5320]
`org.testng.Assert#assertThrows` encourages very relaxed testing for expected exceptions, which may lead (and has lead) to masking real problems.

Expected exceptions should be tested using `org.assertj.core.api.Assertions#assertThatThrownBy`:
```
assertThatThrownBy(() -> ....)
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessage("Foo is invalid");
```

**Comment by findepi** [comment]
Note:
in case of **one-liners** it's OK to use `@Test(expectedExceptions = IllegalArgumentException.class, expectedExceptionsMessageRegExp = "Foo is invalid")`
but it's **not recommended** -- the patter works correctly for one-liners only and needs to be converted to `assertThatThrownBy` as soon as any preparatory code needs to be added to the test, so it's recommended to write using  `assertThatThrownBy`  from the start.

**Comment by j4ckofalltrades** [comment]
@findepi Can you assign this issue to me? I'd like to pick this up.

**Comment by findepi** [comment]
@j4ckofalltrades thanks, go for it!
