### ISSUE TITLE
Can Spark read data using Presto JDBC?

### ISSUE THREAD

**Issue by STTianXiang** [prestosql/presto#5328]
I'm a rookie.

At present, I use Presto to complete the processing through Java program using JDBC..

Can I use spark.read().format(" JDBC ")?

How do I define Kerberos authentication in Option?

Like this.

SparkSession spark = SparkSession
                .builder()
                .appName("test_spark_jdbc_presto")
                .getOrCreate();
        
        Dataset<Row> dataset = spark.read()
                .format("jdbc")
                .option("driver", "io.prestosql.jdbc.PrestoDriver")
                .option("url", "jdbc:presto://127.0.0.1:8080/catalogs/schemas")
                .option("user", "root")
                .option("dbtable", "table_name")
                .load();
        
        dataset.show(10);

Thank you very much for your answer.

**Comment by ebyhr** [comment]
Yes, you can connect to Presto via JDBC format. Please try appending `url` connection string as `jdbc:presto://127.0.0.1:8080/catalogs/schemas?KerberosRemoteServiceName=...`. 

It's troubleshooting than issue. Could you please join https://prestosql.io/slack.html and ask in `#troubleshooting` channel?
