### ISSUE TITLE
Cluster memory configuration question

### ISSUE THREAD

**Issue by pysenic** [prestosql/presto#5343]
I have a Presto cluster(version 332)

**coordinator*1** :
* 16c32g
* JVM -Xmx20g
* node-scheduler.include-coordinator=false
* query.max-memory-per-node=5GB   _// jvm*0.25_
* memory.heap-headroom-per-node=4G   _//j vm*0.2_
* query.max-total-memory-per-node=8GB  _// jvm*0.4_
* query.max-memory=32GB _// works number * query.max-memory-per-node * 0.8_

**works*2**:
* 32c128g
* JVM -Xmx80g
* query.max-memory-per-node=20GB   _// jvm*0.25_
* memory.heap-headroom-per-node=16G   _//j vm*0.2_
* query.max-total-memory-per-node=32GB  _// jvm*0.4_
* query.max-memory=32GB _// works number * query.max-memory-per-node * 0.8_

I have some questions, please help me：

Q1. Will the query.max-memory-per-node=5GB configured by the coordinator cause the workers to use only the 5GB

Q2. The coordinator checks to see if the memory used per query exceeds its limit. According to which configuration is the limit taken? Is it the configuration of the Coordinator or of each worker node

Q3. If the configuration of workers is different, can different configurations be performed for each worker node, such as query.max-memory-per-node, memory.heap-headroom-per-node and query.max-total-memory-per-node? In other words, is the per-node configuration only effective for the current node? and the query.max-memory on each node include coordinator must be same？

Q4.how resources.reserved-system-memory works? the default value is jvm*0.4 and the memory.heap-headroom-per-node default value is jvm*0.3,so only jvm*0.3 can be use in query???

**Comment by findepi** [comment]
This isn't really an issue but a question.
Let's move this to `#general` channel on [our slack](https://prestosql.io/slack.html).
See you there!
