### ISSUE TITLE
PluginManager should build classpath from workspace

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#535]
Currently, when using `pom.xml` as a plugin bundle:
https://github.com/prestosql/presto/blob/ea2d4214fbed38e3c84e9820ca6c014674d9d4b5/presto-main/etc/config.properties#L29-L43

`io.prestosql.server.PluginManager#buildClassLoaderFromPom` builds classpath using artifacts from `~/.m2/repository`
For plugin code, this isn't practical -- one has to `./mvnw install` changed plugins each time before starting `PrestoServer`

It would be best if we could use the classes compiled by the IDE.

**Comment by electrum** [comment]
This is only a problem for Hive, since the actual plugin is in a different module than the main code. But it’s something I’ve wanted to fix for years.

**Comment by findepi** [comment]
@electrum right, this works as expected for the most part.
(Note that this is not limited to Hive, e.g. applicable to JDBC connectors when you change base-jdbc.)

**Comment by findepi** [comment]
Hopefully https://github.com/airlift/resolver/pull/15 fixes this.
