### ISSUE TITLE
Presto 332 coordinator has non heap memory leak 

### ISSUE THREAD

**Issue by photogamerun** [prestosql/presto#5400]
![image](https://user-images.githubusercontent.com/16651123/94986911-17a6b780-0595-11eb-9bbe-235d320644b3.png)
hello every one

when I open native memory tracing

I run jcmd baseline to tracing the memory usage ,I found reserved memory is larger than heap memory, and Internal type become larger and larger when I compare the diff with baseline.

I have no I idea how to found what in presto coordinator cause the non heap memory leak. is there any can help! 

![image](https://user-images.githubusercontent.com/16651123/94987003-db278b80-0595-11eb-8afb-6db4429fc28d.png)

**Comment by photogamerun** [comment]
is anyone help?

**Comment by findepi** [comment]
what is your `jvm.config`?

**Comment by photogamerun** [comment]
> what is your `jvm.config`?

![image](https://user-images.githubusercontent.com/16651123/96663173-c06d5900-1382-11eb-8cc3-7000d185805f.png)

**Comment by findepi** [comment]
Can you please make sure to include all the recommended properties from https://prestosql.io/docs/current/installation/deployment.html#jvm-config
in particular `-Djdk.nio.maxCachedBufferSize=...`

it it does not help, please try to reproduce the problem with 344 & reopen.

**Comment by hackeryang** [comment]
New `jvm.config` template: https://trino.io/docs/current/installation/deployment.html#jvm-config
