### ISSUE TITLE
Query semantic analysis time should not be reported as queued time

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#545]
In case queries that communicates a lot with Hive metastore (retrieving information about tables or checking privileges) analysis time could be noticable. 
Notice that Query State Machine is created in initial state QUEUED and so semantic analysis time is included in QUEUED time.

**Comment by dain** [comment]
With the dispatcher this gets messy.  The analysis will happen twice. Once asynchronously while queued, so we can kill queries early in the queueing process (we don't want to wait for start to show a that the query is referencing a column that doesn't exist).  The second time will occur when the query is started on an actual coordinator.  The first analysis can't be reused because there is no way to transport an analysis, and we don't want to restrict coordinator selection to where the analysis occurred.  I suggest you simply record the analysis as separate item, and not try to make is a phase.

**Comment by kokosing** [comment]
I will work on this.

**Comment by sopel39** [comment]
>  The analysis will happen twice. 

Does it mean that we will call metastore at least twice for metadata heavyweight queries?

> The first analysis can't be reused because there is no way to transport an analysis

Maybe there should be a way to serialize analysis

**Comment by dain** [comment]
> > The analysis will happen twice.
> 
> Does it mean that we will call metastore at least twice for metadata heavyweight queries?

Yes.

> > The first analysis can't be reused because there is no way to transport an analysis
> 
> Maybe there should be a way to serialize analysis

I doubt this optimization is worth the work.

**Comment by findepi** [comment]
The analysis itself usually is fast. The communication with external metastore (or RDBMS or other connectors' data sources) is what usually takes time, easily going into seconds. This is becomes significant for tactical queries which don't spend much time doing actual work. E.g. simple aggregate range queries over tables with large number of partitions.

**Comment by kokosing** [comment]
What is more, connector access control also may communicate with external services. See hive sql-standard, for example when given user has many roles we might ask Hive metastore several times to check if user has access to a table.

**Comment by kokosing** [comment]
>> Does it mean that we will call metastore at least twice for metadata heavyweight queries?
>
> Yes.

By analysis I mean semantic analysis, the one that happens in `SqlQueryExecution` constructor and produces `Analisis` object. Currently we also collect a duration (query statistic) which is called `analysisTime` (see `SqlQueryExecution#doAnalyzeQuery`), however there we measure the time spent in logical planner. No semantic semantic analysis is done there.

@dain Can you please tell me where there is second semantic analysis is done? Is `SqlQueryExecution` twice in single query?

**Comment by sopel39** [comment]
@dain does the analysis happens twice in the current code base? If so, where does it happen?

**Comment by dain** [comment]
> @dain does the analysis happens twice in the current code base? If so, where does it happen?

No, today it happens once.  If someone runs a separate dispatcher, we will perform ansync analysis on a random worker to ensure the query is valid.  If the queueing the analysis will be canceled.  

BTW we are only talking about analysis and not full planning, which means table schema and not partitions.
