### ISSUE TITLE
support dynamic connector configuration

### ISSUE THREAD

**Issue by allendang001** [prestosql/presto#5534]
Prestosql does not support adding a new catalog when presto cluster is running, this leads to no way to support the join operation of an existing catalog and a new catalog without restarting. 
Is there any solution at present?

**Comment by ebyhr** [comment]
Going to close as duplicate of #2110. It's not possible now.

**Comment by allendang001** [comment]
what is the reason?

**Comment by allendang001** [comment]
> Going to close as duplicate of #2110. It's not possible now.

what is the reason?

**Comment by findepi** [comment]
Let's keep the discussion under #2110 issue.
if you have more questions you can also reach out on #dev on [our slack](https://prestosql.io/slack.html).
