### ISSUE TITLE
Regression with pushing down timestamp functions to PostgreSQL for timestamp with precision higher than 3

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#5543]
```
SELECT ts_col
FROM postgresql.public.tab 
WHERE ts_col >= now() - interval '1' day
```

In `341`  filter on ts_col is pushed down to Postgresql and index on `ts_col` is used 
In `342+`  full table scan

**Comment by findepi** [comment]
`344` brought some improvements around timestamps and PostgreSQL.
@guyco33 can you please re-verify with that version the bug still exists?

**Comment by findepi** [comment]
What is the type of `ts_col` from PostgreSQL perspective?
Can you share `DESCRIBE tab` from Presto, as well as `EXPLAIN ...` of that query?

Does the query sent to PostgreSQL have a `ts_col >= ?` condition, or no condition at all?

**Comment by guyco33** [comment]
`ts_col` is a Postgres `timestamp`

```
create table if not exists tab
(
	id serial not null constraint tab_pkey primary key,
	ref_id integer not null,
	data jsonb,
	created_at timestamp not null,
	updated_at timestamp not null
)
```

In `342`  The query in Postgres looks like this: 
```
SELECT "created_at" AS "created_at" FROM "public"."tab"
```
without the condition at all

**Comment by guyco33** [comment]
`DESCRIBE bookkeeping.public.odrs`

`341`:
```
Column	Type
id	integer
ref_id	integer
data	json
created_at	timestamp(3)
updated_at	timestamp(3)
```

`342`:
```
Column	Type
id	integer
ref_id	integer
data	json
created_at	timestamp(6)
updated_at	timestamp(6)
```

It might be that `342` doesn't pass the filter, since the value of `now() - interval '1' day` is not `timestamp(6)`

**Comment by findepi** [comment]
@guyco33 
we hit some roadblock with a fix for this (see https://github.com/prestosql/presto/pull/5673, https://github.com/prestosql/presto/pull/5675, https://github.com/prestosql/presto/issues/5685).

As a **workaround**, try replacing `now()` function in your query with `localtimestamp`,
or explicitly casting RHS of the comparison to `timestamp(p) [without time zone]`.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/5692
