### ISSUE TITLE
Row keys are forced into lower case

### ISSUE THREAD

**Issue by jvlasblom** [prestosql/presto#5546]
Presto lower cases row keys: 
```
SELECT CAST(array[row('foo', 'bar')] as row(rowEntry1 varchar, rowEntry2 varchar) array) as mixedCaseThing;
          mixedCaseThing
----------------------------------
 [{rowentry1=foo, rowentry2=bar}]
(1 row)
```
...rowEntry1 and rowEntry2 above are transformed to lower case in the result.  Tested on Presto v339

**Comment by findepi** [comment]
Per the spec, the names without " quotes (non-delimited) are case insensitive, and Presto lowercases them (per spec we should probably uppercase, but that's separate).
To get your case preserved, put `rowEntry1` in quotes: `"rowEntry1"`.

**Comment by ebyhr** [comment]
> SELECT MAP(ARRAY['myFirstRow', 'mySecondRow'], ARRAY[cast(row('row1FieldValue1', 'row1FieldValue2') as row("firstField" varchar, "secondField" varchar)), cast(row('row2FieldValue1', 'row2FieldValue2') as row("firstField" varchar, "secondField" varchar))]) as mapField;

@jvlasblom This query works without error on upstream. What Presto version are you using?

**Comment by jvlasblom** [comment]
@ebyhr - it works for me now too in Presto v346.   It failed with Presto v339.    I will close the issue as it seems it is resolved now.
