### ISSUE TITLE
Regression in Hive metastore performance

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#5567]
For some queries `341+` uses  `getPartitionNames` while `340` uses `getPartitionNamesByParts` that is much faster.

For example:
Table `t` is partitioned by `[tdate, key]`  (`tdate` has 3 years with about 1500 `key` values per day)
```
SELECT key, count(*) FROM t WHERE tdate >= date'2020-01-14' AND key LIKE 'val%' GROUP BY 1
```
`340` uses `getPartitionNamesByParts` and it takes 1952.1124 miliseconds
`341` uses `getPartitionNames` and it takes 20349.98233 miliseconds (10 times slower) 

I used `jmx` catalog to track the numbers with the following query:
```
SELECT node,
"getpartitionnames.time.alltime.avg","getpartitionnames.time.alltime.count","getpartitionnames.time.alltime.max","getpartitionnames.time.alltime.min","getpartitionnames.time.alltime.unit",
"getpartitionnamesbyparts.time.alltime.avg","getpartitionnamesbyparts.time.alltime.count","getpartitionnamesbyparts.time.alltime.max","getpartitionnamesbyparts.time.alltime.min","getpartitionnamesbyparts.time.alltime.unit",
"getpartitionsbynames.time.alltime.avg","getpartitionsbynames.time.alltime.count","getpartitionsbynames.time.alltime.max","getpartitionsbynames.time.alltime.min","getpartitionsbynames.time.alltime.unit",
"gettable.time.alltime.avg","gettable.time.alltime.count","gettable.time.alltime.max","gettable.time.alltime.min","gettable.time.alltime.unit",
"listtableprivileges.time.alltime.avg","listtableprivileges.time.alltime.count","listtableprivileges.time.alltime.max","listtableprivileges.time.alltime.min","listtableprivileges.time.alltime.unit" 

FROM jmx.current."presto.plugin.hive.metastore.thrift:name=hive,type=thrifthivemetastore" 
JOIN system.runtime.nodes on node=node_id WHERE coordinator
```

Probably relates to  PR https://github.com/prestosql/presto/pull/4748

**Comment by findepi** [comment]
cc @electrum @rash67

**Comment by guyco33** [comment]
IMHO, issue happens here:
https://github.com/prestosql/presto/blob/7711b445b5069b9763a0c2e1e6bb063dd9077554/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreUtil.java#L440-L442
Both partition filters are not single value domain:  filter `tdate >= date'2020-01-14'` is  `[?, <max>)` and filter `key LIKE 'val%'` is `[?, ?)` 
Therefore `partitionKeysFilter` is set to `TupleDomain.all()` in https://github.com/prestosql/presto/blob/7711b445b5069b9763a0c2e1e6bb063dd9077554/presto-spi/src/main/java/io/prestosql/spi/predicate/TupleDomain.java#L84-L85 
and finally the execution is delegated to `getPartitionNames` function while it would be much efficient with `getPartitionNamesByParts` https://github.com/prestosql/presto/blob/7711b445b5069b9763a0c2e1e6bb063dd9077554/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java#L1166-L1183

@electrum @rash67

**Comment by findepi** [comment]
> and finally the execution is delegated to `getPartitionNames` function while it would be much efficient with `getPartitionNamesByParts`

Are you saying that `getPartitionNames` (`get_partition_names`) is slower than `getPartitionNamesByParts` (`get_partition_names_ps`) even when there is no "parts" filter?

Both methods return the same information (list of partition names).

**Comment by guyco33** [comment]
>Are you saying that getPartitionNames (get_partition_names) is slower than getPartitionNamesByParts (get_partition_names_ps) even when there is no "parts" filter?

I don't see any advantage to use `getPartitionNamesByParts` when there is no parts filter, but for sure it will respond much faster for any filter that results with few partition list (high selectivity), especially when the total number of table partitions is huge (thousands of them).
When the total number of partitions in table is low, we won't see much difference.

**Comment by findepi** [comment]
In your query there is no equality filter and i think `getPartitionNamesByParts` (`get_partition_names_ps`) supports only equality filters.
Thus I would expect both methods (`get_partition_names` and `get_partition_names_ps`) to do exactly same job (again: in this case),
and -- hopefully -- have same performance characteristic.

**Comment by guyco33** [comment]
>In your query there is no equality filter and i think getPartitionNamesByParts (get_partition_names_ps) supports only equality filters.

That's right. `getPartitionNamesByParts` requires at least one equality filter, so also for this simple query it won't be used:
```
SELECT key, count(*) from t WHERE tdate in (date'2020-01-14', date'2020-01-15') AND key in ('val1', 'val2') GROUP BY 1
```
