### ISSUE TITLE
Add debug query log for MongoDB

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#5600]
Related to https://stackoverflow.com/questions/64432527/how-to-intercept-mondodb-query-from-presto-connector

https://github.com/prestosql/presto/blob/80d88f9cd66125cf9ba8db06cd6e73d61104ef3a/presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java#L274-L303

**Comment by shandhanumohan** [comment]
Hi, I like to help. Are you expecting a simple debug log before the return statement?

**Comment by ebyhr** [comment]
@shandhanumohan Thanks for your help. Yes, I'm expecting simple debug log. I hope you will log both collection name and query (above `query` holds only filter for the collection).

**Comment by findepi** [comment]
`buildQuery(tableHandle.getConstraint())` returns a `Document`. Is there any recommended way to turn this into a string representation? Is `Document#toString` sufficient here?

**Comment by shandhanumohan** [comment]
How about using `Document#toJson` instead of `Document#toString`
