### ISSUE TITLE
Method `ConnectorNodePartitioningProvider#getSplitBucketFunction` cannot fetch session properties. As follow:

### ISSUE THREAD

**Issue by Crossoverrr** [prestosql/presto#5622]
Method `ConnectorNodePartitioningProvider#getSplitBucketFunction` cannot fetch session properties. As follow:
![1](https://user-images.githubusercontent.com/33892550/96679207-c32d7580-13a5-11eb-8771-16c94c57fb97.png)
I think this is because we use this api below:
![2](https://user-images.githubusercontent.com/33892550/96679311-02f45d00-13a6-11eb-9a87-ef4e0385ce64.png)
![Screenshot from 2020-10-21 11-26-08](https://user-images.githubusercontent.com/33892550/96679357-14d60000-13a6-11eb-91e1-11a13b5dde10.png)
After I change this api to `Session#toConnectorSession(CatalogName)` the problem is fixed.

**Comment by Crossoverrr** [comment]
I have changed the code to `    private ToIntFunction<Split> getSplitToBucket(Session session, PartitioningHandle partitioningHandle)
    {
        ConnectorNodePartitioningProvider partitioningProvider = partitioningProviders.get(partitioningHandle.getConnectorId().get());
        checkArgument(partitioningProvider != null, "No partitioning provider for connector %s", partitioningHandle.getConnectorId().get());

        ToIntFunction<ConnectorSplit> splitBucketFunction = partitioningProvider.getSplitBucketFunction(
                partitioningHandle.getTransactionHandle().orElse(null),
                session.toConnectorSession(partitioningHandle.getConnectorId().get()),
                partitioningHandle.getConnectorHandle());
        ... ...
`

**Comment by sopel39** [comment]
Could you make a PR?

**Comment by Crossoverrr** [comment]
OK, I will do it.  :)

**Comment by Crossoverrr** [comment]
@sopel39 Hi, I have raised a PR about this issue, please help me review the code. https://github.com/prestosql/presto/pull/5690
