### ISSUE TITLE
select count(*) from BigQuery views always return 0

### ISSUE THREAD

**Issue by chilang** [prestosql/presto#5635]
Is this a bug or a (unimplemented) feature ? 

Steps to reproduce:

In BQ console: `create view ds.test_view as select * from ds.my_table`

In presto cli: 
`select * from bq.ds.test_view limit 10` 
returns non-empty results, 

but 
`select count(*) from bq.ds.test_view` 
always return 0.

Presto version:343
bq.properties has `bigquery.views-enabled=true`

**Comment by findepi** [comment]
cc @davidrabinowitz

**Comment by davidrabinowitz** [comment]
views query results are materialized to a temporary table on BigQuery, but in this case since count(*) yields an empty schema I think it is taken from the table metadata. Can you please add a where clause ? Even `where 1=1` ?

**Comment by chilang** [comment]
`select count(*) from bq.ds.test_view where 1=1` also returns 0 rows

**Comment by findepi** [comment]
can this be related to https://github.com/prestosql/presto/issues/5618? cc @losipiuk

**Comment by ebyhr** [comment]
I could reproduce this issue. Exactly, `TableInfo#getNumRows` returns 0 at
https://github.com/prestosql/presto/blob/f4bca505a7d8dce4d7bd5a3d551dc4a9803cadad/presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java#L128
