### ISSUE TITLE
Why the length of year must greater than 4?

### ISSUE THREAD

**Issue by qfrtrt** [prestosql/presto#5646]
https://github.com/prestosql/presto/blob/46aa52f5f6f15b314a9b7ace11ac525e18b17eac/presto-main/src/main/java/io/prestosql/type/DateTimes.java#L52-L55
Why here is `(?<year>[-+]?\\d{4,})` instead of `(?<year>[-+]?\\d{1,})`

**Comment by phd3** [comment]
@qfrtrt This is to avoid ambiguity. For all the fields (year, month, date), the number of digits enforced by the pattern end up enforcing a unique interpretation. Does that answer your question?

**Comment by qfrtrt** [comment]
what ambiguity? Can you make an example? please

**Comment by findepi** [comment]
@qfrtrt what is the context of your question?

**Comment by qfrtrt** [comment]
I think '20-01-01' should be a valid timestamp value, and in a previous version(0.214) it is valid. But in 344 version, it is invalid. I just want to know what is the reason of this change.

**Comment by findepi** [comment]
> I think '20-01-01' should be a valid timestamp value

you mean that Presto should accept `CAST('20-01-01' AS date)` or `DATE '20-01-01'`, or something else?

**Comment by qfrtrt** [comment]
`CAST('20-01-01' AS timestamp)` or `TIMESTAMP '20-01-01'`

**Comment by martint** [comment]
> I think '20-01-01' should be a valid timestamp value, and in a previous version(0.214) it is valid. But in 344 version, it is invalid. I just want to know what is the reason of this change.

Mostly to be closer to standard SQL semantics, which defines date and timestamp literals as:

```
31) Within a <datetime literal>, the <years value> shall contain four digits. 
```

But, to elaborate on the potential ambiguity, `20-01-01` could be interpreted as `2020-01-01`, `1920-01-01`, or simply as an omission of the first two digits of the year, which would result in `0020-01-01`.

**Comment by qfrtrt** [comment]
Got it. Thanks for answer.

**Comment by findepi** [comment]
Let me close this as answered.
We can continue conversation here, or on [our slack](https://prestosql.io/slack.html).
