### ISSUE TITLE
Queries involving Kudu do not evaluate all predicates correctly

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5670]
@losipiuk found out that https://github.com/prestosql/presto/issues/5618 is caused by a piece of code that is similar in BQ and Kudu connectors.

**Comment by findepi** [comment]
cc @Crossoverrr @lzeiming

**Comment by Crossoverrr** [comment]
So, have this issue been fixed?

**Comment by losipiuk** [comment]
I did not deeper into Kudu implementation. Just notices that implementation of `applyProjection` in Kudu is the same as it was in BQ (see https://github.com/prestosql/presto/pull/5666/files)
In BQ it resulted in query correctness issues. But it does not necessarily need to be true for Kudu. 

Yet for sure the behavior of projection in Kudu is suboptimal, as effectively only first call to `applyProjection` is taken into consideration. While the method may be called multiple times as the predicated is refined through optimization process.

**Comment by Crossoverrr** [comment]
![Screenshot from 2020-11-18 11-13-19](https://user-images.githubusercontent.com/33892550/99478618-af1e6900-298f-11eb-8504-825828ee2fce.png)
I have checked version 346_SNAPSHOT, it's OK.
Maybe we could close this issue now  :)

**Comment by Crossoverrr** [comment]
Well, in version 322, I've  got error below:
![Screenshot from 2020-11-18 11-22-30](https://user-images.githubusercontent.com/33892550/99479048-73d06a00-2990-11eb-9700-9cf095d32f17.png)

**Comment by losipiuk** [comment]
@Crossoverrr If this code does not imply query correctness issues feel free to close this one.

You can open another "improvement" issue to address this part:
>Yet for sure the behavior of projection in Kudu is suboptimal, as effectively only first call to applyProjection is taken into consideration. While the method may be called multiple times as the predicated is refined through optimization process.
