### ISSUE TITLE
Incorrect LIKE result in PostgreSQL connector

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#5684]
Steps to reproduce:
```sql
create table test (c1 varchar)
insert into test values ('test.123.test')
select * from test where c1 like 'test.%.test';
→ empty
```

The above SELECT query generates the following query. While `"c1" >= 'test.'` returns true, `"c1" < 'test/'` returns false in PostgreSQL.
```sql
SELECT "c1" AS "c1" FROM "tpch"."test" WHERE (("c1" >= 'test.' AND "c1" < 'test/'))
```

Related to https://stackoverflow.com/questions/64510558/how-to-use-like-operator-in-presto-whit-string-that-contain-dot
MySQL connector generates the same query except for the quotation, but it returns correct result.

**Comment by findepi** [comment]
See https://github.com/prestosql/presto/issues/3645

**Comment by ebyhr** [comment]
@findepi Thanks, I was missing that. Let me close this.
