### ISSUE TITLE
jmx.base-name is no longer applied to QueryManager metrics

### ISSUE THREAD

**Issue by andrewdryder** [prestosql/presto#5697]
After upgrading from 336 -> 338, our dashboards suddenly were missing some QueryManager metrics. After a bit of investigating, it seems like this was due to this [PR](https://github.com/prestosql/presto/pull/4129) - specifically [this line](https://github.com/prestosql/presto/pull/4129/files#diff-cfc279e7ec98b2e797d73425a9d01e29f096d1e9b1580b29296cc531a09333c4R243) - Not applying `jmx.base-name` to these specific metrics.

cc: @martint

**Comment by kokosing** [comment]
@aalbu Maybe we could expose these stats under two names? Is this possible?

**Comment by aalbu** [comment]
It's possible, but probably not necessary.  My intent was to make the change completely transparent, I just messed up by hard-coding the prefix.
