### ISSUE TITLE
Drop Hive min/max statistics writing for timestamp columns

### ISSUE THREAD

**Issue by losipiuk** [prestosql/presto#5857]
Presto is currently setting min/max statistics for `TIMESTAMP` columns when data in Hive is written or analyzed. As min/max statistics for TIMESTAMP are not currently used by Presto, and we are lacking test coverage for write flow, we should stop writing those.

**Comment by findepi** [comment]
I agree we should remove writing for now -- not used, not tested, "doesn't exist."
As a follow up we may want to do this properly though.

**Comment by losipiuk** [comment]
Readding with proper testing is tracked by https://github.com/prestosql/presto/issues/5859
