### ISSUE TITLE
Support INSERT statement using arbitrary/out of order column names

### ISSUE THREAD

**Issue by reugn** [prestosql/presto#5868]

**Comment by kokosing** [comment]
Can you please share more details? As far I know it is already supported by the engine, see: https://prestosql.io/docs/current/sql/insert.html

However there might be some issues in certain connectors.

**Comment by reugn** [comment]
@kokosing According to the documentation, you need to provide the column names in the order they appear in the table. There is no option to skip one of them, and you can drop only the tail columns to be set to null. The `Page` from the `public CompletableFuture<?> appendPage(Page page)` of the `ConnectorPageSink` has only the positions of the values.

**Comment by kokosing** [comment]
Please see: io.prestosql.testing.AbstractTestDistributedQueries#testInsert

![image](https://user-images.githubusercontent.com/7569403/98462105-cf8d3d00-21b1-11eb-9ca9-e8290f160504.png)

That proves that you can use arbitrary subset of columns. Depending on connector null values will be inserted to missing columns or default values.

**Comment by reugn** [comment]
Figured out the root cause for faulty INSERT behavior. It was a misuse of the `supportsMissingColumnsOnInsert` flag on my side.

**Comment by ebyhr** [comment]
@reugn By the way, you can ask a question on community Slack's `#dev` channel when you faced development issues. 
https://prestosql.io/slack.html
