### ISSUE TITLE
How to query kudu table created by impala

### ISSUE THREAD

**Issue by lordk911** [prestosql/presto#5916]
When impala created a kudu table ,the table name will be with prefix: "impala::" , how to use presto to query this ?

**Comment by findepi** [comment]
If this is only about table name, you can put the name in double quotes:
```
SELECT * FROM "impala::my_table"
```

I will close this as hopefully answered.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).
See you there!

**Comment by lordk911** [comment]
no , should use kudu.schema-emulation.enabled=true and kudu.schema-emulation.prefix=impala::
