### ISSUE TITLE
Support boolean type in MySql

### ISSUE THREAD

**Issue by zaz968m** [prestosql/presto#5938]
MySQL does not have built-in Boolean type. However, it uses TINYINT(1) instead. To make it more convenient, MySQL provides BOOLEAN or BOOL as the synonym of TINYINT(1).
https://www.mysqltutorial.org/mysql-boolean/

MySQL encodes presto `boolean` to `TINYINT(1)`, however presto is not able to decode `TINYINT(1)` to `boolean` back.

https://github.com/prestosql/presto/pull/5900#discussion_r521962546

**Comment by shandeep00** [comment]
@zaz968m @findepi  anyone working on this? If not, I would like to work on this.

**Comment by findepi** [comment]
> however presto is not able to decode TINYINT(1) to boolean back


Once the columns end up being TINYINT(1) on MySQL side, it is a numeric column and is presented as such in Presto.
I think there is nothing we could improve actually

> https://github.com/prestosql/presto/pull/5900#discussion_r521962546

i improved the comment in that place to indicte _why_ the exclusion.
