### ISSUE TITLE
‘cast as bigint’ should add pre check

### ISSUE THREAD

**Issue by Chaos-Ju** [prestosql/presto#6011]
query context:  

`             select room_id as room_number  from test.db_statistics.live_user_info A 
                inner join test.clazz_lesson B on A.room_id  = cast(B.room_number as bigint)
                group by room_id
`
error message：
Query 20201119_052128_00045_stauq failed: Cannot cast '' to BIGINT

correct query context:

`         select room_id as room_number  from test.db_statistics.live_user_info A 
                inner join test.clazz_lesson B on A.room_id  = cast(B.room_number as bigint)  and B.room_number != ''
                group by room_id `

**Comment by martint** [comment]
That’s expected behavior. An empty string cannot be cast to bigint, only strings containing numeric sequences.

As you pointed out in your second query, you need to filter out those values. Alternatively, you can use try_cast, which will produce null instead of failing with an error.

**Comment by Chaos-Ju** [comment]
> That’s expected behavior. An empty string cannot be cast to bigint, only strings containing numeric sequences.
> 
> As you pointed out in your second query, you need to filter out those values. Alternatively, you can use try_cast, which will produce null instead of failing with an error.

Thanks
