### ISSUE TITLE
Do have  a plan to support Clickhouse ?

### ISSUE THREAD

**Issue by vkingnew** [prestosql/presto#6037]
Clickhouse have a high speed,but the SQL is not stand sql,do you have a plan to support it?
https://clickhouse.tech/
refer project:
https://github.com/zeeshanabid94/presto/tree/presto-clickhouse/presto-clickhouse

**Comment by ebyhr** [comment]
Support for Clickhouse is ongoing in #4500 & #4909. Please take a look at the issue & PR.
