### ISSUE TITLE
Give Prometheus test classes meaningful names

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#6059]
`TestPrometheusIntegrationTests1`, `TestPrometheusIntegrationTests2`, `TestPrometheusIntegrationTests3`  are not the best names possible.

**Comment by GeorgePanaretos** [comment]
How about IntegrationTestOne etc. ? Because Test is mentioned twice and prometheus is the name of the file so you can skip that part and better for the numbers to represented as whole words.

**Comment by findepi** [comment]
Thanks for your comment @GeorgePanaretos 

within Presto we have these conventions:

- test classes start with `Test...` (i know it's not a common convention in general, but it's also something that we grow very used to)
- test classes are "meaningful" without looking at the package name. it simply helps communicate and work in the IDE
  - consider example of all subclasses of `AbstractTestIntegrationSmokeTest` class. They all would look very much the same if we removed "PostgreSql", "Hive" or "MySql" from their name

thus, the new names here should start with `TestPrometheus...`. The rest is to be determined. 
Since the classes are named as they are, i do not know what they are supposed to test.
Someone needs to look at them, guess their intended meaning and propose some new names.

**Comment by CoachLuck** [comment]
`Test...1` -> `TestPrometheusIntegrationMetrics` / `TestPrometheusIntegrationURI`
- startup and basic test functions being ran
- metrics checked
- URI checked

`Test...2` -> `TestPrometheusIntegrationSchema` / `TestPrometheusIntegrationSplit`
- Table values types checked
- Tests correct number of splits that were created.

`Test...3` -> `TestPrometheusIntegrationHealth` / `TestPrometheusIntegrationStatus`
- Runs a re-check on metrics
- Checks to see that Prometheus is up and running

**Comment by findepi** [comment]
Sounds good to me.
