### ISSUE TITLE
Preserve NOT IN when pushing down to JDBC source

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#6075]
For a query against eg a PostgreSQL connector
```
SELECT * FROM nation WHERE nationkey NOT IN (1, 2, 3, 4);
```

we sent the following to the remote system:

```
SELECT "nationkey" AS "nationkey", "name" AS "name", "regionkey" AS "regionkey", "comment" AS "comment" FROM "tpch"."nation" WHERE (("nationkey" < ?) OR ("nationkey" > ? AND "nationkey" < ?) OR ("nationkey" > ? AND "nationkey" < ?) OR ("nationkey" > ? AND "nationkey" < ?) OR ("nationkey" > ?))
```

we should reconstruct original `NOT IN` from the domain

Relates to https://github.com/prestosql/presto/issues/6076

**Comment by sopel39** [comment]
There is `io.prestosql.spi.predicate.Domain#complement`. Is it not used in JDBC connectors?

**Comment by findepi** [comment]
Yes, the Domain is complemented. I think we could reconstruct the original domain (un-complement, unless `Domain#complement` will just do that) within `io.prestosql.plugin.jdbc.QueryBuilder#buildSql`.
