### ISSUE TITLE
Use assertThatThrownBy in TestSetSessionTask

### ISSUE THREAD

**Issue by phd3** [prestosql/presto#6082]
Make tests in `TestSetSessionTask` more readable by using `assertThatThrownBy`.

e.g. https://github.com/prestosql/presto/blob/master/presto-main/src/test/java/io/prestosql/execution/TestSetSessionTask.java#L155

**Comment by somayaj** [comment]
Hi, can this be worked?

**Comment by phd3** [comment]
@somayaj Welcome! Feel free to take this up.

**Comment by somayaj** [comment]
Thanks
