### ISSUE TITLE
CachingJdbcClient invalidation is too coarse

### ISSUE THREAD

**Issue by ssheikin** [prestosql/presto#6106]
For example 
`io.prestosql.plugin.jdbc.CachingJdbcClient#dropTable` invokes 
`io.prestosql.plugin.jdbc.CachingJdbcClient#invalidateTablesCaches` which purges all caches despite the key.

**Comment by zaz968m** [comment]
relates to https://github.com/prestosql/presto/pull/5871

**Comment by kokosing** [comment]
It is a bit complicated. Notice that when user drop a table, the table is dropped for all users. So we need to invalidate all entries that are about that table. Same goes to other caches.

**Comment by kokosing** [comment]
The thinking here was, that `DDL` queries are not that frequent and populating the cache again is not that expensive.

**Comment by zaz968m** [comment]
relates to https://github.com/prestosql/presto/pull/6160
