### ISSUE TITLE
what's the lastest version when java in JDK8

### ISSUE THREAD

**Issue by vkingnew** [prestosql/presto#6171]
+======================================================================+
|      Error: Required Java version could not be found                 |
+----------------------------------------------------------------------+
| Please install JDK 11. On RHEL/CentOS, use java-11-openjdk-devel.    |

Most time ,I used java 8 in productions, i don't want to have more risk on productions, so what's latest version of prestosql fit for java 8.
And I think prestosql.io  index page should provide a RPM package fit for java 8.After all Java 8 is used more at present.

**Comment by electrum** [comment]
You can install a private JDK just for Presto -- there is no risk to anything else. Simply download the [Zulu JDK](https://www.azul.com/downloads/zulu-community/?version=java-11-lts&package=jdk) tarball and unpack it, then put the `bin` directory from that JDK first in your `PATH` when running Presto.

Another option is to use the [Presto Docker image](https://hub.docker.com/r/prestosql/presto), which is fully self contained and includes its own JDK.

If you have any questions, please [join us on Slack](https://prestosql.io/slack.html).

**Comment by zloss** [comment]
Release 330 (18 Feb 2020) requires running on Java 11 or above. 
https://prestosql.io/docs/current/release/release-330.html
