### ISSUE TITLE
JMX MBeans are not accessible 

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#62]
When JMX MBean is created via:
```
newExporter(binder).export(GlueHiveMetastore.class);
```
it doesn't list, but when created via:
```
newExporter(binder).export(GlueHiveMetastore.class)
  .as(generator -> generator.generatedNameOf(GlueHiveMetastore.class));
```
it does list in `presto.plugin.hive.metastore.glue`.

FYI: @electrum

**Comment by electrum** [comment]
I'm guessing this is unavoidable given how the Guice binding DSL works. cc @dain

**Comment by sopel39** [comment]
This is to be closed then?

**Comment by dain** [comment]
The JMX utils should really report an error if the binding is not finalized, but that is an issue for that project.
