### ISSUE TITLE
Memory connector's view is not visible in system.jdbc.tables

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#6239]
Similar to https://github.com/prestosql/presto/issues/3195 but different ;)

Reproduction:

```
presto:tpch> use memory.default;
USE
presto:default> create view x as select 1 col;
CREATE VIEW
presto:default> select * from system.jdbc.tables where table_cat = 'memory' and table_schem = 'default';
 table_cat | table_schem | table_name | table_type | remarks | type_cat | type_schem | type_name | self_referencing_col_name | ref_generation
-----------+-------------+------------+------------+---------+----------+------------+-----------+---------------------------+----------------
 memory    | default     | x          | VIEW       | NULL    | NULL     | NULL       | NULL      | NULL                      | NULL
(1 row)

presto:default> select * from system.jdbc.tables where table_cat = 'memory' and table_schem = 'default' and table_name = 'x';
 table_cat | table_schem | table_name | table_type | remarks | type_cat | type_schem | type_name | self_referencing_col_name | ref_generation
-----------+-------------+------------+------------+---------+----------+------------+-----------+---------------------------+----------------
(0 rows)
```

In hive:

```
presto:tpch> use hive.tpch;
USE
presto:tpch> create view testview as select 1 x;
CREATE VIEW
presto:tpch> select * from system.jdbc.tables where table_cat = 'hive' and table_schem = 'tpch' and table_name = 'testview';
 table_cat | table_schem | table_name | table_type | remarks | type_cat | type_schem | type_name | self_referencing_col_name | ref_generation
-----------+-------------+------------+------------+---------+----------+------------+-----------+---------------------------+----------------
 hive      | tpch        | testview   | VIEW       | NULL    | NULL     | NULL       | NULL      | NULL                      | NULL
(1 row)

presto:tpch> select * from system.jdbc.tables where table_cat = 'hive' and table_schem = 'tpch' and table_name = 'testview';
 table_cat | table_schem | table_name | table_type | remarks | type_cat | type_schem | type_name | self_referencing_col_name | ref_generation
-----------+-------------+------------+------------+---------+----------+------------+-----------+---------------------------+----------------
 hive      | tpch        | testview   | VIEW       | NULL    | NULL     | NULL       | NULL      | NULL                      | NULL
(1 row)
```

I've debugged that and the cause of that behavior is `MetadataManager.listTables`: https://github.com/prestosql/presto/blob/41a777bd529be737e3d4394f45cfede1d25c806e/presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java#L555-L560 which delegates to `MetadataManager.getTableHandle` when the table name is fully qualified. This in turn delegates to `MemoryMetadata`: https://github.com/prestosql/presto/blob/7aeea3a7b7a295428a20c643ea1b954ea3265daa/presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java#L137-L145 which returns a handle for tables only.

So my question is whether the memory connector is wrong or `MetadataManager.listTables` should check if the fully qualified name exists as view also (I've checked and that does the trick).

I've included Hive testcase as well as it calls `getTableHandle` for view as well (which returns non-null value).

**Comment by losipiuk** [comment]
> So my question is whether the memory connector is wrong or MetadataManager.listTables should check if the fully qualified name exists as view also (I've checked and that does the trick).

I would expect the latter. That `listTables` should check for a view. The other option is not feasible as a view is not an entity connector can read directly from, so you cannot create a TableHandle for it.
cc: @findepi, @martint

**Comment by wendigo** [comment]
Then why `HiveMetadata.getTableHandle` returns non-null value for Hive view?

**Comment by losipiuk** [comment]
> Then why `HiveMetadata.getTableHandle` returns non-null value for Hive view?

Accidentally? I am not sure, but it would be my guess.

**Comment by wendigo** [comment]
@losipiuk I've seen a couple of places where we don't check for view existence but rely on Hive's getTableHandle returning non-null value for views (i.e. GrantTask). These places should be fixed as well.
