### ISSUE TITLE
PrestoS3ClientFactory should use the AWS Java SDK default credential provider

### ISSUE THREAD

**Issue by ddrinka** [prestosql/presto#625]
The Glue Hive Metastore provider uses the default [AWSGlueAsyncClientBuilder](https://github.com/prestosql/presto/blob/d8131337f69a58852ac2596b8b5dda6a48efd4c1/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java) provided by the AWS SDK for Java to locate AWS credentials.  This is good.  There are [numerous ways](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) to provide the credentials to the plugin, and these are the ways we're used to providing credentials to services that run on AWS.  These configuration mechanisms are also container-friendly.

On the other hand, the [S3 client](https://github.com/prestosql/presto/blob/5dda1b7d59d4fd73f2cc6fe6f5d26b55251ca77e/presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ClientFactory.java) handles this process its own way, with only two included options for configuration, hardcoded credentials in the configuration files, and utilizing the InstanceProfileCredentialsProvider.

#### The S3 client should be able to retrieve credentials from AWS using the default provider, as Glue does.

Here are a couple other folks struggling with this over the years:
https://stackoverflow.com/questions/51527973/configure-presto-connector-options-by-environment-variables
https://stackoverflow.com/questions/41554020/presto-fails-to-recognize-aws-credentials-both-iam-and-keys
https://prestodb.slack.com/archives/C07JH9WMQ/p1556085524072500

**Comment by electrum** [comment]
This seems reasonable. We could add a new config, `hive.s3.use-default-credentials`, that when true, would return `null` as the credential provider rather than throwing an exception when no other credentials are available. This should be done for both `PrestoS3ClientFactory` and `PrestoS3FileSystem`. This config could default to true, but be set to false if someone wants to assure they don't pick up credentials automatically.

**Comment by ddrinka** [comment]
@anoopj thanks for #741, that should close this issue.

**Comment by anoopj** [comment]
@ddrinka, Yep, I'm fixing PrestoS3FileSystem and PrestoS3ClientFactory as part of #741
