### ISSUE TITLE
Unable to Update NULL columns after Schema Evolution with Column Addition/Rename in Hive Transactional tables

### ISSUE THREAD

**Issue by abhishekkhanna1** [prestosql/presto#6280]
Once the table schema is evolved by adding new columns or by renaming columns. The resulting added/modified column values for existing rows is NULL. Subsequent update query is unable to update the NULL values .

```
PTs to reproduce:

withTemporaryTable("schema_evolution_column_addition", true, false, NONE, tableName -> {
            onPresto().executeQuery(format("CREATE TABLE %s (column1 INT, column2 BIGINT) WITH (transactional = true)", tableName));

            onPresto().executeQuery(format("INSERT INTO %s VALUES (11, 100), (12, 200), (13, 300)", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L), row(12, 200L), row(13, 300L));

            onPresto().executeQuery(format("ALTER TABLE %s ADD COLUMN column3 VARCHAR", tableName));

            onPresto().executeQuery(format("INSERT INTO %s VALUES (14, 400, 'fourHundred'), (15, 500, 'fiveHundred'), (16, 600, 'sixHundred')", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L, null), row(12, 200L, null), row(13, 300L, null), row(14, 400L, "fourHundred"), row(15, 500L, "fiveHundred"), row(16, 600L, "sixHundred"));

            onPresto().executeQuery(format("UPDATE %s SET column3 = 'default' WHERE column3 is not NULL", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L, null), row(12, 200L, null), row(13, 300L, null), row(14, 400L, "default"), row(15, 500L, "default"), row(16, 600L, "default"));

            onPresto().executeQuery(format("UPDATE %s SET column3 = 'default1' WHERE column3 is NULL", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L, "default1"), row(12, 200L, "default1"), row(13, 300L, "default1"), row(14, 400L, "default"), row(15, 500L, "default"), row(16, 600L, "default"));
        });

```

```
withTemporaryTable("schema_evolution_column_rename", true, false, NONE, tableName -> {
            onPresto().executeQuery(format("CREATE TABLE %s (column1 INT, column2 BIGINT) WITH (transactional = true)", tableName));

            onPresto().executeQuery(format("INSERT INTO %s VALUES (11, 100), (12, 200), (13, 300)", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L), row(12, 200L), row(13, 300L));

            onPresto().executeQuery(format("ALTER TABLE %s RENAME COLUMN column1 to column3", tableName));

            onPresto().executeQuery(format("INSERT INTO %s VALUES (14, 400), (15, 500), (16, 600)", tableName));

            verifySelectForPrestoAndHive("SELECT column3 FROM " + tableName, "true", row(null), row(null), row(null), row(14), row(15), row(16));

            onPresto().executeQuery(format("UPDATE %s SET column3 = 1 WHERE column3 is NULL", tableName));

            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(1, 100L), row(1, 200L), row(1, 300L), row(14, 400L), row(15, 500L), row(16, 600L));
        });
```

The last verifySelect fails.

**Comment by findepi** [comment]
@abhishekkhanna1 the UPDATE support does not exist in Presto yet
It seems you running into problems with the code that is your custom patch applied on top of project's code, therefore I will close this issue.

If you re testing out this PR: https://github.com/prestosql/presto/pull/5861, please post your findings there, this will be highly appreciated!
Thanks!

cc @djsstarburst 

relates to https://github.com/prestosql/presto/issues/6281

**Comment by djsstarburst** [comment]
Thanks very much for finding this bug, @abhishekkhanna1.  I'm looking at it now.

**Comment by djsstarburst** [comment]
@abhishekkhanna1, for the second example you listed, with ALTER TABLE RENAME COLUMN, I get an NPE due to calling `row(null)`.  There are two overloadings of `row`.  `row(null)` is getting the overloading in which the arg is supposed to be a collection, causing the NPE.

When I fix that by substituting `new QueryAssert.Row((Object) null)`, the subsequent `SELECT column3 FROM table...` returns different results for Presto and for Hive.  On Presto, I see the three nulls followed by row(14), row(15), row(16).  When the SELECT is run on Hive, I see row(11), row(12), row(13), row(14), row(15), row(16), which is I think the right answer.

So the ALTER TABLE RENAME COLUMN bug is (unsurprisingly) in Presto, and it's not related to UPDATE.

**Comment by abhishekkhanna1** [comment]
> @abhishekkhanna1, for the second example you listed, with `ALTER TABLE RENAME COLUMN`, I get an NPE due to calling `row(null)`. There are two overloadings of `row`. `row(null)` is getting the overloading in which the arg is supposed to be a collection, causing the NPE.
> 
> When I fix that by substituting `new QueryAssert.Row((Object) null)`, the subsequent `SELECT column3 FROM table...` returns different results for Presto and for Hive. On Presto, I see the three nulls followed by row(14), row(15), row(16). When the SELECT is run on Hive, I see row(11), row(12), row(13), row(14), row(15), row(16), which is I think the right answer.
> 
> So the `ALTER TABLE RENAME COLUMN` bug is (unsurprisingly) in Presto. The subsequent Presto UPDATE fails with `Index 4 out of bounds for length 4` while trying to assemble the `HivePageSource` page, more evidence that Presto is confused about the schema.

I had not run this one using the PT but instead ran it on the server running locally on my mac. I had also run on an EMR Hive cluster for the hive part. If I remember correctly, I was getting 3 nulls followed by 14,15,16 in both cases but yeah the subsequent update passed in hive but failed in presto. I can double check again

**Comment by djsstarburst** [comment]
`If I remember correctly, I was getting 3 nulls followed by 14,15,16 in both cases but yeah the subsequent update passed in hive but failed in presto. I can double check again`

The fact that by default it verifies against both Hive and Presto sometimes makes things confusing :(

BTW, I just verified that if the table isn't transactional, Presto correctly follows the schema change, and returns `row(11), row(12), row(13), row(14), row(15), row(16)` from `SELECT column3 FROM table...`, matching Hive.  so transactional tables don't correctly follow schema changes, but non-transactional table do.

**Comment by djsstarburst** [comment]
I've boiled down the test case to this, which fails saying that the final SELECT returns row(null) instead of row(11) as it should:

```
    public void testAcidSelectAfterRenamingColumn()
    {
        withTemporaryTable("schema_evolution_column_rename", true, false, NONE, tableName -> {
            onPresto().executeQuery(format("CREATE TABLE %s (column1 INT, column2 BIGINT) WITH (transactional = true)", tableName));
            onPresto().executeQuery(format("INSERT INTO %s VALUES (11, 100)", tableName));
            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L));
            onPresto().executeQuery(format("ALTER TABLE %s RENAME COLUMN column1 to column3", tableName));
            verifySelect(onPresto(), "SELECT column3 FROM " + tableName, "true", row(11));
        });
    }
```

Adding a major compaction causes the test to pass, as you would expect:

```
    public void testAcidSelectAfterRenamingColumn()
    {
        withTemporaryTable("schema_evolution_column_rename", true, false, NONE, tableName -> {
            onPresto().executeQuery(format("CREATE TABLE %s (column1 INT, column2 BIGINT) WITH (transactional = true)", tableName));
            onPresto().executeQuery(format("INSERT INTO %s VALUES (11, 100)", tableName));
            verifySelectForPrestoAndHive("SELECT * FROM " + tableName, "true", row(11, 100L));
            onPresto().executeQuery(format("ALTER TABLE %s RENAME COLUMN column1 to column3", tableName));
            compactTableAndWait(MAJOR, tableName, "", Duration.valueOf("6m"));
            verifySelect(onPresto(), "SELECT column3 FROM " + tableName, "true", row(11));
        });
    }
```
