### ISSUE TITLE
Elasticsearch connection properties file 

### ISSUE THREAD

**Issue by rstuartVT** [prestosql/presto#6308]
By creating an elasticsearch.properties file it breaks the presto server. I specify just the following four properties 

connector.name=elasticsearch
elasticsearch.host=vpc-cdp-master-prod-jbe4wu5bjxjv3i2nnp3alpvhcu.eu-west-1.es.amazonaws.com
elasticsearch.port=443
elasticsearch.default-schema-name=default

But I get the following errors in the server.log

`1) Configuration property 'elasticsearch.host' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:238)

2) Configuration property 'elasticsearch.port' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:238)`

This is an EMR Cluster and I've reprovistioned a new cluster, without the elasticsearch.properties file presto works as expected, but with the file it fails to start.

**Comment by martint** [comment]
I don't think that functionality is available in older versions of Presto provided by EMR. It should would with Presto 338 that's shipped with the latest version of EMR.

**Comment by rstuartVT** [comment]
thank you! I didn't realize that much had changed with one minor version.
