### ISSUE TITLE
How can I get PreparedStatement of Execute Query in event listener?

### ISSUE THREAD

**Issue by pan3793** [prestosql/presto#6360]
I'm trying to write a plugin (event listener) to send query logs to kafka, but I found there are some queries are `EXECUTE statement1 USING ...` and I don't found how to get the `PreparedStatement` of Execute Query from spi, could you please give me some advices?

**Comment by findepi** [comment]
Did you check the
```
QueryCompletedEvent -> getMetadata() -> getPreparedQuery()
```
?

Anyway, this is a question, so I will close this as not-an-issue in Presto.
We can continue conversation here still, or on `#dev` channel on [our slack](https://prestosql.io/slack.html).
See you there!

**Comment by pan3793** [comment]
Got it! Thanks for your kind tips, and sorry for asking question on GitHub Issue page.

**Comment by findepi** [comment]
You're welcome. Also, no problem about asking in an issue. Just slack is more convenient for that.
