### ISSUE TITLE
Add main method to DruidQueryRunner

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#6361]
Example: 
https://github.com/prestosql/presto/blob/46e0e4cec494dc279cfa9b83af4449f1be091419/presto-mysql/src/test/java/io/prestosql/plugin/mysql/MySqlQueryRunner.java#L87-L101

**Comment by shandeep00** [comment]
@ebyhr I would like to take up this.

**Comment by ebyhr** [comment]
@shandeep00 Thanks! Please go ahead.
