### ISSUE TITLE
Make Presto cluster information available to plugins

### ISSUE THREAD

**Issue by reugn** [prestosql/presto#6397]
We have the System connector, which provides information and metrics about the currently running Presto cluster. But there is no way to get cluster nodes info from within a plugin. The `ConnectorSession` object may be a suitable place to keep it.

**Comment by sopel39** [comment]
`io.prestosql.spi.connector.ConnectorFactory#create` has `io.prestosql.spi.connector.ConnectorContext` as an argument. There you can get `io.prestosql.spi.NodeManager` which provides information about cluster nodes.
