### ISSUE TITLE
Schema and database mapping in SQLServer

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#643]
Currently presto maps sqlserver's schema to presto's schema, but I think it should be sqlserver  database → presto schema. Is it intentional design? I guess general sqlserver users expect `sys.sysdatabases` result as presto schema.

```sh
sqlcmd> create database test;
sqlcmd> select name from sys.sysdatabases;
sqlcmd> go
name                                                                                                                            
--------------------------------------------------------------------------------------------------------------------------------
master                                                                                                                          
tempdb                                                                                                                          
model                                                                                                                           
msdb
test
```

```sh
presto> show schemas in sqlserver;
       Schema       
--------------------
 db_accessadmin     
 db_backupoperator  
 db_datareader      
 db_datawriter      
 db_ddladmin        
 db_denydatareader  
 db_denydatawriter  
 db_owner           
 db_securityadmin   
 dbo                
 guest              
 information_schema 
 sys 
```

https://prestosql.io/docs/current/connector/sqlserver.html
> Multiple SQL Server Databases or Servers
The SQL Server connector can only access a single database within a SQL Server server. Thus, if you have multiple SQL Server databases, or want to connect to multiple instances of the SQL Server, you must configure multiple catalogs, one for each instance.

Related to https://github.com/prestodb/presto/issues/12561

**Comment by findepi** [comment]
@ebyhr good question!
If you use databases and only `dbo` schema in each database, then it makes sense.
if however you use schemas other than `dbo`, how would you expect Presto to make them available for querying?

**Comment by ebyhr** [comment]
Oh I see, understood...! Exactly, presto can't handle such case. Let me close this issue.
