### ISSUE TITLE
ML plugin documentation (and its future)

### ISSUE THREAD

**Issue by kokes** [prestosql/presto#662]
Hi, there is quite a bit of ML code [here](https://github.com/prestosql/presto/tree/master/presto-ml/src/main/java/io/prestosql/plugin/ml) (~2K SLOC), but apart from the original pull request https://github.com/prestodb/presto/pull/1275 and [release notes from May 2014](https://prestosql.io/docs/current/release/release-0.69.html), I can't find anything on this.

What are the plans for this? Has it gotten any closer to production grade code? If so, should it be documented?

Thanks!

**Comment by dain** [comment]
We are not actively working on it, and we are not aware of anyone using it.  If you want to document it, we would be more than willing to merge the changes.

**Comment by findepi** [comment]
@ebyhr recently wrote a quick tutorial about the ML plugin: https://www.ebyhr.org/2019/04/machine-learning-connector-in-presto.html

**Comment by liuguiyangnwpu** [comment]
hi, I want to use presto as a SQL engine to run the kubeflow to train the model and load the models to inference the data on-line.
If i have some question about presto-ml, i will ask for your help.

thx.
