### ISSUE TITLE
Query timing in the cli depends on time spent in the pager

### ISSUE THREAD

**Issue by kokes** [prestosql/presto#663]
When I run a query that forces a pager to be invoked, the timing of such query includes time spent in the pager.

If I run a query with `PRESTO_PAGER=cat`, I get

```
$ PRESTO_PAGER=cat presto
presto> with t as (select sequence(1,100) as s) select 1 from t cross join unnest(s);
 _col0 
-------
     1 
 [...]
     1 
(100 rows)

Query 20190424_102908_00047_cxygj, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]
```

If instead I don't supply a `PRESTO_PAGER` and use the default (`less`), then if I spend some time paging the results (or doing nothing), then this time spent is reflected in the query timing.

```
Query 20190424_103044_00048_cxygj, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:16 [0 rows, 0B] [0 rows/s, 0B/s]
```

So you see the exact same query, the same execution time (judging by the Presto UI), but the cli reports two wildly different numbers.

**Comment by findepi** [comment]
@kokes there might be some reporting friction here that can be improved.
However in general, when you use pager your query can actually take longer to complete.
This is because coordinator is streaming query results to the client. When you start a pager,
query results are loaded lazily and so they query can become blocked on the client, as
coordinator's buffers fill up.

**Comment by Praveen2112** [comment]
@kokes If the `PRESTO_PAGER` is set to use default (`less`) the timer continues to run till we press `q` to stop it.(Typical behavior of `less` command in Linux)

**Comment by kokes** [comment]
I know, that's what I reported above.

The issue is not only that time is misrepresented, but also the performance characteristics (rows/s, MB/s), since they appear to be computed on the client side.

So this way of reporting may give the user an impression that their query is slow and not performant. It also doesn't match the UI, so that adds further confusion.

**Comment by Praveen2112** [comment]
Okay. So in that case we can modify the `StatusPrinter` to use the elapsed time which is obtained from the `StatementStats` rather the timer from the cli. 
So we can modify 
`Duration wallTime = nanosSince(start);`
to 
`Duration wallTime = succinctNanos(stats.getElapsedTimeMillis());`
and the final stats line would be running on the actual counter.

@findepi Your insights on this ?

**Comment by findepi** [comment]
@Praveen2112 
yes, i think we should improve. CLI-reported stats ideally should match UI-reported stats.
I don't know the CLI code that well, so can't say of this is the right fix.
@electrum ?

@kokes,
please be aware that even after this change, query stats with page and query stats without pager will be different.
if you have large query results and you're using a pager -- pager will prevent CLI from reading all results,
and this in turn will prevent the query from completing. (In such a case, query will ultimately complete when user
scrolls to the tail of the pager (eg `G`) or quits it.)
