### ISSUE TITLE
Presto Identifies S3 Writes using EmrFs as a regular File System

### ISSUE THREAD

**Issue by cdw9bf** [prestosql/presto#699]
When using EmrFs to write to S3, Presto identifies the writes as going to a regular file system instead of S3. This has the consequence of two things, writing temporary files to the base directory on a S3 bucket and not allowing writes to a S3 path if the path doesn't exist. 

The problematic code is located [here](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriteUtils.java#L458) in HiveWriteUtils.java. Presto checks to see if the file system is `instanceof PrestoS3FileSystem`. This by itself would not be problematic if Presto was checking to see if it was using the native Presto S3 FileSystem but this function is later used to [write the data to a temporary location](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java#L87) and [rejecting the write if the directory is not present](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriteUtils.java#L431).

EmrFs has the filesystem classpath `com.amazon.ws.emr.hadoop.fs.EmrFileSystem`. However I'm unsure how you'd check to see if it is an instance of EmrFileSystem without specifying a dependency on the Amazon package or if this specific behavior was already known.

**Comment by electrum** [comment]
This can be done by calling `getClass().getName()` and comparing to the string rather than an `instanceof` check. Are you interested in working on this yourself? Otherwise I can mark this as a *good first issue* since it is only a couple of lines.

**Comment by cdw9bf** [comment]
Yeah I'd be happy to take this up, does it matter if the PR is to the prestosql or prestodb project?

**Comment by dain** [comment]
Yes, it does matter. prestosql and prestodb are two different projects (https://github.com/prestosql/presto/issues/380).  Also, the code has different packaging, names and often different changes, so a PR is specific to one project.

**Comment by electrum** [comment]
Please submit the PR to this repository.

**Comment by martint** [comment]
This is fixed and will be available in version 315.
