### ISSUE TITLE
feature request: function which returns array pairs(permutations/combinations)

### ISSUE THREAD

**Issue by neilkod** [prestosql/presto#714]
It's useful to aggregate on combinations of items in in an array. 

A toy example:

User 1 bought `[eggs, potatoes, milk, grapefruit]`

We want to aggregate all of the pairs(or triplets, etc) of items bought together.

so ideally, given this input, it would return

`[(eggs, potatoes), (eggs, milk), (eggs, grapefruit), (potatoes, milk), (potatoes, grapefruit)...(milk, grapefruit)]`

Ideally a flag for ordered vs unordered pairs would also be useful.

A workaround is to `UNNEST` the items and then self-join the unnested data on a join key(in this case user id), and filter out the cases `where item_left = item_right`

**Comment by findepi** [comment]
@neilkod is `ngrams` (https://prestosql.io/docs/current/functions/array.html#ngrams) something similar to what you want?

**Comment by martint** [comment]
@findepi, no, ngrams produces sequences of adjacent n elements. This issue is about adding something to produce permutations or k-combinations (i.e., n choose k)

**Comment by findepi** [comment]
@neilkod please see https://github.com/prestosql/presto/pull/718

**Comment by neilkod** [comment]
@findepi  thanks for jumping on this so quickly!

re: ngrams - @martint said it best-ngrams is useful for sequences of adjacent n elements - this is most useful when analyzing text. Many people frequently and incorrectly assume that ngrams will return combinations. This might be a function of the lack of descriptive documentation for `ngrams()`

**Comment by neilkod** [comment]
@findepi i submitted https://github.com/prestosql/presto/pull/719 to briefly explain what an ngram is(in the docs) - based on @martint's comments above. I need to go through the CLA process though. Feel free to take this over.
