### ISSUE TITLE
Add support for bitwise shift functions

### ISSUE THREAD

**Issue by martint** [prestosql/presto#722]
Presto currently supports bitwise functions and/or/xor/not. We should add support for bitwise left and right shift.

We need to consider how the function may or may not be sensitive to the length of the data type. From the original issue (https://github.com/prestodb/presto/issues/4028):

> 
> Function that has tricky overflow issue:
> 
> ```
> BITWISE_LSH(7, 2, 4) = 12 -- treat 7 as a 4-bit signed number and left shift by 2,
>                           -- truncate overflow
> ```
> 
> Function that are inherently sensitive to width of numbers:
> 
> ```
> BITWISE_LRSH(-8, 2, 5) = 6 -- treat -8 as a 5-bit signed number and lsh by 2
> ```
>

**Comment by martint** [comment]
Specifically, we need to think about the following scenarios:
* How does it behave for different types: TINYINT, SMALLINT, INTEGER, BIGINT?
* How does it behave with respect to implicit casts?

Naming-wise, we may want to call them `bitwise_left_shift` and `bitwise_right_shift`

**Comment by martint** [comment]
I think what we want are the following functions for each `t` in [`TINYINT`, `SMALLINT`, `INTEGER`, `BIGINT`]

```
bitwise_left_shift(value::t, bits::integer) :: t
bitwise_right_shift(value::t, bits::integer) :: t
bitwise_right_shift_signed(value::t, bits::integer) :: t
```

That would make the functions consistent with the implementations of shift operators for various types in traditional programming languages and databases that support shift operators. For each of the types in the list above, the values are interpreted as 2s complement signed 8-bit, 16-bit, 32-bit and 64-bit numbers, respectively. The `_signed` variant of right shift preserves the sign of the number (similar to `>>` in Java).

**Comment by Lewuathe** [comment]
@martint 
I think having multiple dedicated functions for each type is a good idea. That would make the interface clearer.

But `_shift_arithmetic` seems to be straightforward instead of `_shift_signed` so that we can make it explicit that the function is for the arithmetic right shift. 

```
bitwise_left_shift(value::t, bits::integer) :: t
bitwise_right_shift(value::t, bits::integer) :: t
bitwise_right_shift_arithmetic(value::t, bits::integer) :: t
```

**Comment by martint** [comment]
The issue I have with `arithmetic` is that it's not immediately obvious to me that it means "extend sign". But it may be clear to others.

**Comment by martint** [comment]
In any case, let's go with this plan. We can finalize the name later.
