### ISSUE TITLE
Accessing AWS Glue Catalog in different account using presto

### ISSUE THREAD

**Issue by niraj8241** [prestosql/presto#726]
Well, this is not an issue but I am trying to access aws glue catalog using presto which is situated in a different account. I can access the Glue catalog in the account where the presto instance is running using the below configuration:

connector.name=hive-hadoop2
hive.metastore = glue

While looking at the properties list. I don't seem to find any option to provide access/secret key to access Glue in a different account. Is this a limitation?

**Comment by electrum** [comment]
This is a current limitation, but should be easy to add. If you're interested in working on this yourself, it should be just adding them to `GlueHiveMetastoreConfig` and using them in `GlueHiveMetastore` to create the AWS client (creating a `BasicAWSCredentials`).

In the latest `310` release, we did add `hive.metastore.glue.iam-role` which allows you to choose the IAM role to assume for connecting to Glue. I'm not sure if this helps in your situation.
