### ISSUE TITLE
Resource Group should take ${NumberOfWorkers} and simple arithmetic as template argument

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#762]
For example one could define:
```
        {
          "name": "adjustable_running_queries",
          "maxQueued": ${NumberOfWorkers} * 10,
          ...
        },
```
This would be useful in cloud environments where one could scale number of workers dynamically. One could also autoscale number of workers based on number of queued queries.

**Comment by sopel39** [comment]
It's too simplistic with current resource group semantics

**Comment by electrum** [comment]
Max queued is mainly a safety valve for the coordinator, since there is a cost for each queued query (clients are actively connected and waiting, so there are sockets, memory, etc).
