### ISSUE TITLE
[Need information] About Version difference and UT.

### ISSUE THREAD

**Issue by ajantha-bhat** [prestosql/presto#771]
Hi, I have 2 questions related to project process as I am new here.

a) how do we differentiate the major and minor version in presto ?
Example Hive has 1.X.X, 3.X.X, so first digit indicates major version. What naming convention is followed here ?

b) When we raise PR, where do compilation and UT runs for changes. for merged PR, I don't see any task for compilation and UT. so, how quality is ensured ?

Please let me know, these might be dumb questions. But I am new. So, want to understand.

**Comment by Praveen2112** [comment]
Hi, 
> how do we differentiate the major and minor version in presto ?
My understanding is that in Presto we do a release every once a week or 2 so we don't have anything like a major and minor version. The version is just an incremental number which starts 300. 

 > When we raise PR, where do compilation and UT runs for changes
Presto uses Travis for running the compilation and testing. You can see the status of the tests in the `checks` tab of the raised PR. (https://github.com/prestosql/presto/pull/{pr_id}/checks)

**Comment by findepi** [comment]
@ajantha-bhat 

> how do we differentiate the major and minor version in presto ?

In Presto, there is no concept of major and minor releases.
We strive to maintain backwards compatibility between releases
and whenever we cannot do so, we document that in release notes.
If you are just using Presto and using connectors that are provided
with it (as opposed to e.g. developing your own connectors),
you can think of each release as minor incremental improvement 
over the previous one.

For so complex a system as Presto, distinguishing between major
and minor releases would not be that practical, as it all depends how
deeply you integrate with Presto.

Of course, with a rapid development & release cycle, it's possible that
a bug sneaks in between the releases. So, if you are looking for something
like "long term supported" versions, take a look at Starburst Presto
releases (https://docs.starburstdata.com/latest/release.html).

b) ... for merged PR, I don't see any task for compilation and UT. so, how quality is ensured ?

Expanding on @Praveen2112 's answer --
once a PR is merged, tests are run on `master` branch.
You can see the results at https://travis-ci.com/prestosql/presto/branches

Hope that helps. I will close this question.
Feel free to comment here, if you want to learn more.

**Comment by ebyhr** [comment]
@ajantha-bhat By the way, you can join Presto Slack channel in this page https://prestosql.io/community.html or post to the mailing list to ask the question :)

**Comment by ajantha-bhat** [comment]
@Praveen2112  @findepi : Thanks for the detailed info.

@ebyhr : I have joined slack and google group. 

Thanks.
