### ISSUE TITLE
Use dockerized Accumulo in tests

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#782]
We can replace all of the code in `AccumuloQueryRunner` that starts Accumulo in the same JVM with a Docker instance using `DockerContainer`. See `TestingSqlServer` or `DockerizedMySqlServer` for an example.

**Comment by kokosing** [comment]
Isn't a better developer experience having everything in single JVM? Are you concern about `MiniAccumuloCluster` that is mocking to much?

**Comment by electrum** [comment]
I think the developer experience is the same, assuming you have Docker installed. The only usefulness of having it in the same JVM is if you want to debug or otherwise interact with the code. But we treat it as a black box external service, so I don't think there is any value there.

The advantages of this are

* Possibly more realistic test environment
* Allows testing against multiple versions
* Removes some dependencies and simplifies the code

To me, this approach seems a lot cleaner.

**Comment by findepi** [comment]
We should dockerize Cassandra and test with multiple versions too, especially now that we have version discovery (https://github.com/prestosql/presto/pull/596)

**Comment by findepi** [comment]
@adamjshook is there a recommendable dockerized Accumulo we could use here?

**Comment by adamjshook** [comment]
@findepi I made one at https://github.com/prestosql/docker-images/pull/74 and we have an open PR to use it https://github.com/prestosql/presto/pull/5598 (currently using a different image but will update once docker-images is published).  That should take care of this issue.

**Comment by adamjshook** [comment]
Closed by #5598
