### ISSUE TITLE
SSL Handshake Error after enabling HTTPS

### ISSUE THREAD

**Issue by niraj8241** [prestosql/presto#783]
I am trying to configure HTTPS and LDAP Authentication. Below is my config:

/etc/presto/config.properties
```
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://xx.xx.xx.xx:8080
query.max-memory=1PB
query.max-memory-per-node=1433MB
query.max-total-memory-per-node=1433MB
http-server.allow-external-connection-on-http=true

http-server.https.keystore.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/lib/security/cacerts
http-server.https.keystore.key=xxxxxxxx

http-server.authentication.type=PASSWORD

http-server.https.enabled=true
http-server.https.port=8443
http-server.https.secure-random-algorithm=SHA1PRNG
```

/etc/presto/password-authenticator.properties
```
password-authenticator.name=ldap
ldap.url=ldaps://example.com:636
ldap.user-bind-pattern=uid=${USER},ou=PrestoUsers,ou=Groups,dexamplec=hp8,dc=com
ldap.user-base-dn=dc=example,dc=com
```

**I have tested my LDAPS connection from an external client and it works fine. Example.com is a valid DNS host with a genuine certificate.**

Running Presto CLI in Debug Mode:
```
java -Djavax.net.debug=ssl:handshake:verbose -jar presto --server https://example.com:8443 --keystore-path /usr/lib/jvm/jjava-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/lib/security/cacerts --keystore-password xxxxxx --catalog glue --user presto --password
```

Output:
```
 TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension extended_master_secret
Extension server_name, server_name: [type=host_name (0), value=example.com]
Extension renegotiation_info, renegotiated_connection: <empty>
***
main, WRITE: TLSv1.2 Handshake, length = 164
main, READ: TLSv1.2 Alert, length = 2
main, RECV TLSv1.2 ALERT:  fatal, handshake_failure
main, called closeSocket()
main, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
main, called close()
main, called closeInternal(true)
**Error running command: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure**
```

Java Version:

openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

I have applied Unlimited Strength as of now.

Can anyone please help.

**Comment by dain** [comment]
In your config you are pointing the server at this key store:
```
http-server.https.keystore.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/lib/security/cacerts
```
The name `cacerts` is normally used to signify the trusted key signers.  Does that file contain the private keys for your server?

In the CLI invocation, you are setting ` --keystore-path`.  This is used to specify the private key of the client when using TLS client certificate authentication.  The store of trusted keys is specified with `--truststore-path`

**Comment by dain** [comment]
Also, for Java versions > 1.8.0_161, unlimited strength encryption is on by default.

**Comment by niraj8241** [comment]
@dain Thanks for the response. So, what i did, is purchase a server certificate by generating private keys using openssl command and then just importing that public cert along with CA ( DigiCert ) in the cacerts truststore. Is that enough. 

Or do i need to import private keys too along with certificate while importing?

Also, can i just point to cacerts with --truststore-path instead of --keystore-path ?

**Comment by niraj8241** [comment]
We can close this thread as i managed to fix the issue. The issue was indeed with certificate not being imported along with key. Re-importing cert along with key in cacerts fixed the problem.
