### ISSUE TITLE
OrcCorruptionException only in recent versions of Presto

### ISSUE THREAD

**Issue by ddrinka** [prestosql/presto#794]
Let me start by saying this may actually be ORC corruption, as I'm using my own ORC serialization.  But older versions of Presto, Athena, and Apache ORC's tools read the data fine.

I'm receiving the following exception:
```
Caused by: io.prestosql.orc.OrcCorruptionException: Malformed ORC file. Read past end of RLE integer [s3://s3Location]
        at io.prestosql.orc.stream.LongInputStreamV2.readValues(LongInputStreamV2.java:66)
        at io.prestosql.orc.stream.LongInputStreamV2.skip(LongInputStreamV2.java:444)
        at io.prestosql.orc.stream.LongInputStreamV2.seekToCheckpoint(LongInputStreamV2.java:432)
        at io.prestosql.orc.stream.LongInputStreamV2.seekToCheckpoint(LongInputStreamV2.java:29)
        at io.prestosql.orc.stream.CheckpointInputStreamSource.openStream(CheckpointInputStreamSource.java:57)
        at io.prestosql.orc.reader.DecimalStreamReader.openRowGroup(DecimalStreamReader.java:284)
        at io.prestosql.orc.reader.DecimalStreamReader.readBlock(DecimalStreamReader.java:113)
        at io.prestosql.orc.OrcRecordReader.readBlock(OrcRecordReader.java:410)
        at io.prestosql.plugin.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:231)
```

The table definition:
```
CREATE EXTERNAL TABLE intraday.symbolEvent (
  date DATE,
  source STRING,
  sequenceNumber BIGINT,
  messageNumInPacket INT,
  time DECIMAL(14,9),
  receivedTime DECIMAL(14,9),
  symbol STRING,
  eventType STRING,
  details1 STRING,
  details2 STRING
)
STORED AS ORC
LOCATION 's3://s3Location';
```

An example query:
```
select receivedtime from symbolEvent where "$PATH"='s3://s3Location' limit 10000; --works
select receivedtime from symbolEvent where "$PATH"='s3://s3Location' limit 10001; --throws
```

And data that replicates the issue:
[bad_decimal.zip](https://github.com/prestosql/presto/files/3199523/bad_decimal.zip)

I'm running 311.

**Comment by ddrinka** [comment]
@dain I know you were doing a bunch of ORC work over the last few weeks.  I'm going to keep digging on my side for issues with the serialization code, but if you have an easy way to drop this data into some test cases and make sure it's not an issue with your new code, I figured I'd get the conversation started rather than waiting until I was sure it wasn't on my side.

**Comment by dain** [comment]
The exception is happening at the ORC checkpoint boundary, so the checkpoint is likely malformed.

**Comment by ddrinka** [comment]
I'm suspicious that this is an issue with the PRESENT data stream.  It looks like every value is present so the PRESENT stream isn't written, but the index positions still include an entry for the PRESENT stream:

```
    Stream: column 6 section DATA start: 4657 length 9107
    Stream: column 6 section SECONDARY start: 13764 length 19
    Row group indices for column 6:
      Entry 0: count: 10000 hasNull: false min: 37770085893996 max: 38310688060365 sum: 380388235229664715 positions: 0,0,0,0,0,0,0,0,0
      Entry 1: count: 5902 hasNull: false min: 38310688060365 max: 38661469698719 sum: 227160364752782238 positions: 0,20,0,0,70000,0,0,80,0
```

**Comment by ddrinka** [comment]
This ended up being an issue with bad index positions, as I mentioned above.  @dain any idea why the bugged data files worked for so long on older versions?  Are you using indexes in a different way as of late?  Anyhow, closing this issue.

**Comment by ddrinka** [comment]
@dain, I'm reopening this.  It looks to me like we each had a bug.  I fixed the issue with the PRESENT stream as I mentioned above, which fixed decimals for me.  But now I'm having a problem with Dictionary strings.

Here's an example column:
```

**Comment by ddrinka** [comment]
Nope. It's just my bug again.  https://github.com/apache/orc/blob/d81131b9d608779f48d7de6a3c11ece03a3bc0a0/java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java#L227 :
`// bit streams use 3 positions if uncompressed, 4 if compressed`

**Comment by dain** [comment]
The problem is the index (restart checkpoints) is not really documented.  The way they are encoded is a side effect of how the original ORC writer code was laid out, so if the present stream happened to be written first the data for it was first in the long array, and if it wasn't written, then there was no entry in the array.  I had to reverse engineer their system.
