### ISSUE TITLE
Convert column names read from ORC files to lower case

### ISSUE THREAD

**Issue by linxingyuan1102** [prestosql/presto#802]
We have a use case that data producers include camel-case column names in a ORC file, which causes a problem when `hive.orc.use-column-names` is set to be true. In this case, the ORC page reader reads column names from both ORC files and Hive Metastore. It treats columns `fooBar` from ORC and `foobar` from HMS as different columns, and causes the results of `select * from table` to be all `NULL`s.
Since column names in Hive are all lower case, it makes sense to convert those read from ORC files to lower case in the Hive Connector.

**Comment by findepi** [comment]
@linxingyuan1102 how does Hive handles that? Do they do e.g. case-insensitive column name matching by default?
