### ISSUE TITLE
Ignore order by in a from subquery

### ISSUE THREAD

**Issue by hustnn** [prestosql/presto#807]
I noted some systems ignore order by in a from subquery or at least when it is not used with limit. 
https://mariadb.com/kb/en/library/why-is-order-by-in-a-from-subquery-ignored/

Some more cases can benefit from it in addition to https://github.com/prestosql/presto/issues/759 mentioned by @Praveen2112

When outer query and inner query are both aggregation, it is hard to parallel outer query if we want to keep the ordering of inner query.

**Comment by kokosing** [comment]
Sounds good, would like to work on this?

**Comment by hustnn** [comment]
@kokosing I'd like to work on it !

**Comment by ankitdixit** [comment]
@kokosing @hustnn I already have implemented a solution for other issue, which fixes this. Let me share it

**Comment by hustnn** [comment]
cool. go ahead.

**Comment by ankitdixit** [comment]
Thanks, this is the PR https://github.com/prestosql/presto/pull/810

**Comment by hustnn** [comment]
Solved in Presto 312. Quite fast !
