### ISSUE TITLE
Insecure mode for presto-cli

### ISSUE THREAD

**Issue by Lewuathe** [prestosql/presto#815]
As [`curl`](https://stackoverflow.com/questions/8520147/curl-insecure-option) does, it is beneficial if presto-cli provides an insecure mode not to check the SSL certificates. 

https://prestosql.io/docs/current/installation/cli.html

```bash
$ ./presto --server localhost:8080 --catalog hive --schema default --insecure
```

In our use cases, we sometimes want to submit queries to our presto cluster via internal ALB in AWS. The ALB accepts 443 port but the certificate is not available publicly. To make the test of the internal presto easy, we may want to submit queries without checking SSL certificate via 443 ports.

**Comment by electrum** [comment]
I dislike this from a security perspective, but I understand your use case, and it is useful for debugging. Do you want to send a PR to implement this?

**Comment by Lewuathe** [comment]
@electrum Thanks for the feedback. Sure I can do that.

**Comment by findepi** [comment]
Done in https://github.com/prestosql/presto/pull/1484
