### ISSUE TITLE
Constraint and tupleDomain

### ISSUE THREAD

**Issue by l0yu** [prestosql/presto#826]
how to provide tuple doman when make api call to data source, any suggestion ?
Seems like connectorLayout/handler is going to be deprecated ... 

https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorTableLayout.java#L31

https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorSplitManager.java#L19
^^ and further, no layout when provide split in the future ?

**Comment by Praveen2112** [comment]
hi, we can provide the `TupleDomain` to the datasource using the `ConnectorTableHandle` and now any filter expression will be passed to the connector using `ConnectorMetadata#applyFilter` which will be invoked from `PushPredicateIntoTableScan`

**Comment by l0yu** [comment]
Thanks @Praveen2112 . 
That would be great if we have a sample connector which use
` ConnectorMetadata#applyFilter ` instead of ` layout ` for us app developer
Look through existing connectors in repo, still relies on table layout for predicate purpose

**Comment by Praveen2112** [comment]
@l0yu It is currently implemented in JDBC connector and TPCH connector (For Hive it is not yet merged). You can check the implementation from there. For other connectors we are migrating to this model. #781 keeps track of connectors which have migrated to the new model.

**Comment by l0yu** [comment]
@Praveen2112 That's awesome !
