### ISSUE TITLE
Add field/line delimiter property in create hive table 

### ISSUE THREAD

**Issue by aeoles** [prestosql/presto#828]
There is an closed but not PRed  issue [prestodb issue 6387](https://github.com/prestodb/presto/pull/6387), and a related [issue 572](https://github.com/prestosql/presto/issues/572). Hope this feature would be enhanced.

**Comment by findepi** [comment]
@aeoles do you have any needs beyond what's described in https://github.com/prestosql/presto/issues/572 ?

**Comment by aeoles** [comment]
> @aeoles do you have any needs beyond what's described in #572 ?

Currently No
