### ISSUE TITLE
Support Hive bucketed tables with any number of files per bucket

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#852]
This is available in Presto `312`. See blog post for details: https://prestosql.io/blog/2019/05/29/improved-hive-bucketing.html

**Comment by kokosing** [comment]
Fixes https://github.com/prestodb/presto/issues/8557, fixes https://github.com/prestodb/presto/issues/10301, and fixes https://github.com/prestodb/presto/issues/7693
