### ISSUE TITLE
Positional access to fields in anonymous Row 

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#860]
It's very easy to construct an unnamed/anonymous `Row`:

    row(value1, value2, value3)
    (value1, value2, value3)

Also, some connectors return rows with unnamed fields (e.g. https://github.com/prestosql/presto/pull/416)

Currently, accessing an individual value in such a row is not convenient: it requires casting to a named row, so user needs to name all the fields _and_ their types. This verbosity brings no additional benefit.

Let's provide a way to access fields in anonymous `Row` in a convenient fashion.

See previous discussion: https://github.com/prestosql/presto/pull/416#issuecomment-472294245

**Comment by findepi** [comment]
@martint proposed in https://github.com/prestosql/presto/pull/416#issuecomment-472294245 that we use subscript operator

> For a long time I've been thinking we might want to add support for positional access for row types (as an extension to standard SQL). This could easily be done by allowing row types to support the subscript operator: e.g., `x[1]`.

I like this idea.
For this, we should allow only integer literals in the subscript, so that we can analyze the types correctly.

**Comment by martint** [comment]
I think it's the cleanest way to implement this. It doesn't require additional syntax or non-standard language constructs, and it's semantically consistent with arrays and maps. The only weird aspect is the requirement that the subscript be a constant, so it's not completely seamless vs subscript for other types.
