### ISSUE TITLE
Customized DiscoveryService

### ISSUE THREAD

**Issue by l0yu** [prestosql/presto#896]
Is it possible to customize discovery service for coordinator to find worker nodes
(ex: zookeeper) instead of the embedded one ?
then later I could factor out discovery function just by change
discoveryUri in config ?

Scale worker nodes is straightforward, unique worker node id and config worker node with discoveryUri. What if I want to scale coordinator nodes (i.e #coordinators schedule query on the same set of worker nodes)? How to make sure coordinators share consistent states of shared workers ?

**Comment by Praveen2112** [comment]
Actually I think there is an approach which enables us to switch to a different discoveryUri without restart the PrestoServer. We have `ServiceInventory` in airlift which is a bootstrap mechanism for finding the discovery services.  So we could expose the new discovery uri's using this feature and the discovery client will update its disovery URI to a new one. We have expose these information via http or file and discovery client will poll it and looks for any changes.

**Comment by l0yu** [comment]
I see, then what's the pojo to represent node healthy state (when client poll, should return a corresponding json blob). Would you point me to the code ? 
Thank you @Praveen2112

**Comment by dain** [comment]
@l0yu The discover service today already support syncing state between multiple instances.  Supporting multiple coordinator requires a number of changes to work as expected.  The project is being tracked here https://github.com/prestosql/presto/issues/391

**Comment by l0yu** [comment]
That's awesome ! Thanks @dain

**Comment by electrum** [comment]
@l0yu This explains the format of the service inventory JSON: https://groups.google.com/forum/#!topic/presto-users/vUirVCZqaok

The Java code for this is `io.airlift.discovery.client.ServiceDescriptorsRepresentation`

**Comment by l0yu** [comment]
@electrum That's really helpful !
