### ISSUE TITLE
Presto UI high network usage

### ISSUE THREAD

**Issue by igorcalabria** [prestosql/presto#907]
Since deploying presto to more users, we saw a decent increase on its load balancer that did not fit with results downloaded or queries ran. Upon further investigation, we found out that the the UI was downloading a ~ 5mb gzipped json payload every second. 

The refresh loop on `QueryList.jsx` https://github.com/prestosql/presto/blob/master/presto-main/src/main/resources/webapp/src/components/QueryList.jsx#L329  hits `/v1/query` endpoint which returns all queries including its source code.  In our case, the raw payload was 19mb. 

This does not seem like a sustainable design choice and I'd like to start a discussion on how to solve this. Some suggestions 

-  Without a big refactor, we could simply add a timestamp filter to this endpoint and request updates only from the highest mark possible.
- If a bigger refactor is desired, we could split the endpoint in two and request query status separately from the query metadata. Metadata could be pooled at a lower interval than query status and status could only be requested for non finished queries.

**Comment by dain** [comment]
Theses seem like reasonable ideas.  If possible, can you join Slack (https://prestosql.io/community.html) and start a design discussion there?

**Comment by igorcalabria** [comment]
Sure.

**Comment by dain** [comment]
I believe this was resolved by fixing a leak in the query history.   Is this fixed for you?

**Comment by igorcalabria** [comment]
@dain Yes. The root cause was the query history leak. The payload is still kinda big for a polling endpoint, but it's not harming us any more. Thanks for the quick fix.

**Comment by tooptoop4** [comment]
@dain  which PR has the fix?

**Comment by dain** [comment]
@tooptoop4 there were several fixes in [314](https://prestosql.io/docs/current/release/release-314.html), but there may be others I forgot about.  I would just upgrade.
