### ISSUE TITLE
presto-cli should acquire password using stdin&stderr when stdout is a pipe

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#916]
This should be possible:
```
presto-cli --user me --password --execute 'select 1' > /dev/null
```

Currently, this fails with
```
Exception in thread "main" java.lang.RuntimeException: No console from which to read password
	at io.prestosql.cli.Console.getPassword(Console.java:173)
	at io.prestosql.cli.Console.run(Console.java:136)
	at io.prestosql.cli.Presto.main(Presto.java:31)
```

It should work just the same way as `sudo echo x > /tmp/x` does.

**Comment by findepi** [comment]
#### Workaround

One can specify the password with the `PRESTO_PASSWORD` environment variable.

**Comment by jagan985** [comment]
Dear All,
Could someone help me with the issue I'm facing currently, Im connecting to presto using Presto CLI by constructing presto string including user and password and trigger it in bash. 
When I grep the process in unix, the whole presto string is being shown including the password.
Help me to overcome this issue.

String ptr_sec = presto_cli_path + "/presto --server " + presto_https_server + " --keystore-path " + keystore_path+ " --keystore-password " + keystore_password+ " --catalog " +presto_catalog + " --schema " + presto_schema+ " --user " + presto_user + " -f " + queryFile+ " --output-format " + outputFromat + " --password " + Password ;

Process p_sec = Runtime.getRuntime().exec(new String[] { "bash", "-c", ptr_sec });
