### ISSUE TITLE
Fix ORC Bloom Filter

### ISSUE THREAD

**Issue by dilipkasana** [prestosql/presto#921]
This is same issue refers to : https://github.com/prestodb/presto/issues/12900
The same is reproduces in community version of presto.
All releases of community presto from 300 to 313 will not get advantage of ORC Bloom filter due to this.
Below is the description : 
After changes of `StreamId` in `readBloomFilterIndexes` method of `StripeReader` class the Bloom filter does not skip unsatisfied Row Group of ORC due to coding bug as the below line return always `null`.

StripeReader.java
`List<HiveBloomFilter> bloomFilters = bloomFilterIndexes.get(entry.getKey()); `
 This have an impact on Presto ORC performance.

@martint I have created the same issue here too and submit the PR for this.

**Comment by Praveen2112** [comment]
hi.. But would this PR solves (https://github.com/prestosql/presto/pull/914) the issue ?

**Comment by dilipkasana** [comment]
@Praveen2112  Yes, The PR will resolve this.

This is the snapshot of the query run on the current presto community version that should skip all the Splits and should read 0 Rows instead.

```
presto:default> select count(*) from msc_cdr_orc where called_calling_no='0091889' AND date_of_call=190508 AND call_type='SMT';
 _col0
-------
     0
(1 row)

Query 20190605_123713_00008_qxskm, FINISHED, 1 node
Splits: 67 total, 67 done (100.00%)
0:05 [26.3M rows, 91.1MB] [5.35M rows/s, 18.5MB/s]
```

This is the snapshot after the fix.

```
select count(*) from msc_cdr_orc where called_calling_no='00919811680000' AND date_of_call=190508 AND call_type='SMT';
 _col0
-------
     0
(1 row)

Query 20190605_124920_00001_ieepp, FINISHED, 1 node
Splits: 67 total, 67 done (100.00%)
0:02 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by martint** [comment]
Fixed
