### ISSUE TITLE
Different Stats computed for OR and IN expression

### ISSUE THREAD

**Issue by Praveen2112** [prestosql/presto#980]
Presto currently computes different stats for these expression

`columnA = 'abc' or columnA = 'def'`
and for 
`columnA IN ('abc', 'def')`

But these expressions are equivalent. 

Since these columns are of `VARCHAR` type and `andEstimate` which we compute when processing `OR` expression should ideally be 0. 

As a workaround/solution for this can we start maintaining the `lowValue` and `highValue` as a single `Domain` instead of `double` ?

**Comment by findepi** [comment]
> As a workaround/solution for this can we start maintaining the `lowValue` and `highValue` as a single `Domain` instead of `double` ?

In my opinion, converting (normalizing) `columnA = 'abc' or columnA = 'def'` to `columnA IN ('abc', 'def')` might be simpler solution.
As I understand we already do this when pushing down TupleDomain to a connector, but I see no reason not to do this kind of normalization in general.

**Comment by sopel39** [comment]
I've created explicit issue for normalizing `ORs` to `INs`: https://github.com/prestosql/presto/issues/1118
