### ISSUE TITLE
Add limit pushdown to the Information Schema Connector

### ISSUE THREAD

**Issue by linxingyuan1102** [prestosql/presto#998]
This can be helpful to queries like `select * from hive.information_schema.columns limit 1`.
Without the limit pushdown, the Connector will fetch metadata of all columns from Hive firstly, which is very expensive.

**Comment by findepi** [comment]
@linxingyuan1102 thanks for working on this.
One approach is to do limit pushdown (as you do in your PR #999)
Did you consider a different approach, where `InternalTable` is based on an Iterator or Stream, and loads metadata lazily?
Such approach is not as good as explicit limit pushdown, but should be advantageous also in case of queries without a limit, as it should decrease latency of the first query result.

While we can implement both approaches, I am not sure both are needed.
@linxingyuan1102  What do you think?
@electrum and you?

**Comment by electrum** [comment]
@findepi Making the tables lazy is a good approach, but will be more work. Are there plan shapes where removing the limit is advantageous? When we move to the lazy model, it should be easy to move the limit code there, so I'm fine with merging this for now.

@linxingyuan1102 Do you want to make the tables lazy as a follow up task?

**Comment by linxingyuan1102** [comment]
@findepi @electrum 
Thanks for the review. I'll update #999 first and then work on to make `InternalTable` lazy.

**Comment by linxingyuan1102** [comment]
@findepi @electrum 
I'm thinking about the implementation of lazy data loading in the information schema connector. So the current implementation preloads all the data and builds a `FixedPageSource` instance as a `ConnectorPageSource`. I think what we want is to implement a specific `ConnnectorPageSource` which build `Page`s lazily. Is this correct?

**Comment by electrum** [comment]
Yes, that sounds correct. I think a good solution is to add a new constructor to `FixedPageSource` that takes an `Iterator<Page>`. It would be similar to the existing constructor except it won't calculate the memory usage up front (it would set that to zero).
